Antipatrea::ProximityBruteForce< Key, DistFnData > Class Template Reference
Antipatrea::ProximityBruteForce< Key, DistFnData > Class Template Reference
#include <ProximityBruteForce.hpp>
Public Member Functions
ProximityBruteForce (void)
virtual ~ProximityBruteForce (void)
virtual void Neighbors (ProximityQuery< Key > &query, ProximityResults< Key > &results)
Public Member Functions inherited from Antipatrea::Proximity< Key, DistFnData >
Proximity (void)
virtual ~Proximity (void)
bool IsDataStructureConstructed (void) const
const std::vector< Key > * GetKeys (void) const
virtual void AddKey (const Key key)
virtual void ConstructDataStructure (void)
virtual void ClearDataStructure (void)
virtual void Clear (void)
virtual Key Neighbor (ProximityQuery< Key > &query, double *const d=NULL)
Additional Inherited Members
Public Types inherited from Antipatrea::Proximity< Key, DistFnData >
typedef double(* DistFn) (const Key, const Key, DistFnData)
Public Attributes inherited from Antipatrea::Proximity< Key, DistFnData >
DistFn m_distFn
DistFnData m_distFnData
Protected Attributes inherited from Antipatrea::Proximity< Key, DistFnData >
bool m_construct
std::vector< Key > m_keys
Constructor & Destructor Documentation
template<typename Key , typename DistFnData > Antipatrea::ProximityBruteForce< Key, DistFnData >::ProximityBruteForce (void) inline
template<typename Key , typename DistFnData > virtual Antipatrea::ProximityBruteForce< Key, DistFnData >::~ProximityBruteForce (void) inline virtual
Member Function Documentation
template<typename Key , typename DistFnData > virtual void Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors (ProximityQuery< Key > & query, ProximityResults< Key > & results) inline virtual
Implements Antipatrea::Proximity< Key, DistFnData >.
References Antipatrea::ProximityResults< Key >::Clear(), Antipatrea::Proximity< Key, DistFnData >::ConstructDataStructure(), Antipatrea::ProximityQuery< Key >::GetKey(), Antipatrea::ProximityQuery< Key >::GetNrNeighbors(), Antipatrea::ProximityQuery< Key >::GetRange(), Antipatrea::ProximityResults< Key >::Insert(), Antipatrea::Proximity< Key, DistFnData >::IsDataStructureConstructed(), Antipatrea::Proximity< Key, DistFnData >::m_distFn, Antipatrea::Proximity< Key, DistFnData >::m_distFnData, Antipatrea::Proximity< Key, DistFnData >::m_keys, and Antipatrea::ProximityResults< Key >::SetNrNeighborsAndRange().
The documentation for this class was generated from the following file:
ProximityBruteForce.hpp