Antipatrea::Scene2D Class Reference
Antipatrea::Scene2D Class Reference
Scene2D is defined by its bounding box and the 2D obstacles it contains.
#include <Scene2D.hpp>
Public Member Functions
Scene2D (void)
virtual ~Scene2D (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual int GetNrObstacles (void) const
Get the number of the obstacles.
virtual double GetObstacleCenterX (const int i) const
Get the x-coordinate of the center of the ith obstacle.
virtual double GetObstacleCenterY (const int i) const
Get the y-coordinate of the center of the ith obstacle.
virtual double GetObstacleRadius (const int i) const
Get the radius of the ith obstacle.
virtual void SetObstacleCenterX (const int i, const double x)
Set the x-coordinate of the center of the ith obstacle.
virtual void SetObstacleCenterY (const int i, const double y)
Set the y-coordinate of the center of the ith obstacle.
virtual void SetObstacleRadius (const int i, const double r)
Set the radius of the ith obstacle.
virtual void SetObstacle (const int i, const double cx, const double cy, const double r)
Set the center and radius of the ith obstacle.
virtual void AddObstacle (const double cx, const double cy, const double r)
Add a disk obstacle with radius r centered at (cx, cy).
virtual void RemoveObstacle (const int i)
Remove the ith obstacle.
virtual bool IsPointInCollision (const double p[]) const
Return true iff the point p is inside an obstacle.
virtual bool IsSegmentInCollision (const double p1[], const double p2[]) const
Return true iff the segment (p1, p2) is inside or intersects an obstacle.
virtual int NearestObstacleToPoint (const double p[], double &d) const
Find the obstacle closest to the point p.
virtual const double * GetBoundingBox (void) const
Get a pointer to the bounding box.
virtual double * GetBoundingBox (void)
Get a pointer to the bounding box.
virtual std::ostream & Print (std::ostream &out) const
Print the bounding box and the obstacles to the output stream.
virtual std::istream & Read (std::istream &in)
Read the bounding box and the obstacles from the input stream.
virtual void Draw (void)
Draw the bounding box and the obstacles.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Attributes
std::vector< double > m_obstacles
Disk obstacles.
double m_bbox [4]
Bounding box of the scene.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Detailed Description
Scene2D is defined by its bounding box and the 2D obstacles it contains.
Author
Erion Plaku, Amarda Shehu
Remarks
The obstacles in the scene are disks (defined by their center and radius).
Constructor & Destructor Documentation
Scene2D()
Antipatrea::Scene2D::Scene2D (void) inline
References m_bbox.
~Scene2D()
virtual Antipatrea::Scene2D::~Scene2D (void) inline virtual
Member Function Documentation
Info()
virtual void Antipatrea::Scene2D::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, Print(), and SetupFromParams().
SetupFromParams()
virtual void Antipatrea::Scene2D::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Reads the scene from the specified file (keywords Constants::KW_ReadFromFile).
It uses the parameter group associated with the keyword Constants::KW_Scene2D.
The parameter values can be specified in a text file as, for example, Chain2D { NrLinks 8 LinkLength 1.0 }
Reimplemented from Antipatrea::Component.
Referenced by Info().
GetNrObstacles()
virtual int Antipatrea::Scene2D::GetNrObstacles (void) const inline virtual
Get the number of the obstacles.
Author
Erion Plaku, Amarda Shehu
References m_obstacles.
Referenced by RemoveObstacle().
GetObstacleCenterX()
virtual double Antipatrea::Scene2D::GetObstacleCenterX (const int i) const inline virtual
Get the x-coordinate of the center of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References m_obstacles.
GetObstacleCenterY()
virtual double Antipatrea::Scene2D::GetObstacleCenterY (const int i) const inline virtual
Get the y-coordinate of the center of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References m_obstacles.
GetObstacleRadius()
virtual double Antipatrea::Scene2D::GetObstacleRadius (const int i) const inline virtual
Get the radius of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References m_obstacles.
SetObstacleCenterX()
virtual void Antipatrea::Scene2D::SetObstacleCenterX (const int i, const double x) inline virtual
Set the x-coordinate of the center of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References m_obstacles.
Referenced by SetObstacle().
SetObstacleCenterY()
virtual void Antipatrea::Scene2D::SetObstacleCenterY (const int i, const double y) inline virtual
Set the y-coordinate of the center of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References m_obstacles.
SetObstacleRadius()
virtual void Antipatrea::Scene2D::SetObstacleRadius (const int i, const double r) inline virtual
Set the radius of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References m_obstacles.
SetObstacle()
virtual void Antipatrea::Scene2D::SetObstacle (const int i, const double cx, const double cy, const double r) inline virtual
Set the center and radius of the ith obstacle.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrObstacles() - 1.
References SetObstacleCenterX().
AddObstacle()
virtual void Antipatrea::Scene2D::AddObstacle (const double cx, const double cy, const double r) inline virtual
Add a disk obstacle with radius r centered at (cx, cy).
Author
Erion Plaku, Amarda Shehu
References m_obstacles.
RemoveObstacle()
virtual void Antipatrea::Scene2D::RemoveObstacle (const int i) inline virtual
Remove the ith obstacle.
Author
Erion Plaku, Amarda Shehu
References GetNrObstacles(), IsPointInCollision(), IsSegmentInCollision(), m_obstacles, and NearestObstacleToPoint().
IsPointInCollision()
virtual bool Antipatrea::Scene2D::IsPointInCollision (const double p[]) const virtual
Return true iff the point p is inside an obstacle.
Author
Erion Plaku, Amarda Shehu
Referenced by RemoveObstacle().
IsSegmentInCollision()
virtual bool Antipatrea::Scene2D::IsSegmentInCollision (const double p1[], const double p2[]) const virtual
Return true iff the segment (p1, p2) is inside or intersects an obstacle.
Author
Erion Plaku, Amarda Shehu
Referenced by RemoveObstacle().
NearestObstacleToPoint()
virtual int Antipatrea::Scene2D::NearestObstacleToPoint (const double p[], double & d) const virtual
Find the obstacle closest to the point p.
Author
Erion Plaku, Amarda Shehu
Remarks
Function also computes the distance from p to the closest obstacle.
Referenced by RemoveObstacle().
GetBoundingBox() [1/2]
virtual const double* Antipatrea::Scene2D::GetBoundingBox (void) const inline virtual
Get a pointer to the bounding box.
Author
Erion Plaku, Amarda Shehu
Remarks
The first two values represent the coordinates of the lowest-left corner (minimum).
The last two values represent the coordinates of the top-right corner (maximum).
References m_bbox.
GetBoundingBox() [2/2]
virtual double* Antipatrea::Scene2D::GetBoundingBox (void) inline virtual
Get a pointer to the bounding box.
Author
Erion Plaku, Amarda Shehu
Remarks
The first two values represent the coordinates of the lowest-left corner (minimum).
The last two values represent the coordinates of the top-right corner (maximum).
References Draw(), m_bbox, Print(), and Read().
Print()
virtual std::ostream& Antipatrea::Scene2D::Print (std::ostream & out) const virtual
Print the bounding box and the obstacles to the output stream.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Writer.
Referenced by GetBoundingBox(), and Info().
Read()
virtual std::istream& Antipatrea::Scene2D::Read (std::istream & in) virtual
Read the bounding box and the obstacles from the input stream.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Reader.
Referenced by GetBoundingBox().
Draw()
virtual void Antipatrea::Scene2D::Draw (void) virtual
Draw the bounding box and the obstacles.
Author
Erion Plaku, Amarda Shehu
Referenced by GetBoundingBox().
Member Data Documentation
m_obstacles
std::vector<double> Antipatrea::Scene2D::m_obstacles protected
Disk obstacles.
Author
Erion Plaku, Amarda Shehu
Remarks
The center and radius of the ith obstacle are stored in positions 3i, 3i + 1, 3i + 2, respectively.
Referenced by AddObstacle(), GetNrObstacles(), GetObstacleCenterX(), GetObstacleCenterY(), GetObstacleRadius(), RemoveObstacle(), SetObstacleCenterX(), SetObstacleCenterY(), and SetObstacleRadius().
m_bbox
double Antipatrea::Scene2D::m_bbox[4] protected
Bounding box of the scene.
Author
Erion Plaku, Amarda Shehu
Remarks
m_bbox[0]: minimum x-coordinate.
m_bbox[1]: minimum y-coordinate.
m_bbox[2]: maximum x-coordinate.
m_bbox[3]: maximum y-coordinate.
Referenced by GetBoundingBox(), and Scene2D().
The documentation for this class was generated from the following file:
Scene2D.hpp