Antipatrea::CfgImproveSampler Class Reference
Antipatrea::CfgImproveSampler Class Reference
Sample a configuration and then try to improve it, e.g., via energy minimization.
#include <CfgImproveSampler.hpp>
Public Member Functions
CfgImproveSampler (void)
virtual ~CfgImproveSampler (void)
virtual bool CheckSetup (void)
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual bool Sample (Cfg &cfg)
Sample a configuration and then try to improve it, e.g., via energy minimization.
Public Member Functions inherited from Antipatrea::CfgSampler
CfgSampler (void)
virtual ~CfgSampler (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Sample a configuration and then try to improve it, e.g., via energy minimization.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgSampler and CfgImprover in order to sample a configuration and then improve it.
Constructor & Destructor Documentation
Antipatrea::CfgImproveSampler::CfgImproveSampler (void) inline
virtual Antipatrea::CfgImproveSampler::~CfgImproveSampler (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgImproveSampler::CheckSetup (void) inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::CfgImproveSampler::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual bool Antipatrea::CfgImproveSampler::Sample (Cfg & cfg) inline virtual
Sample a configuration and then try to improve it, e.g., via energy minimization.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgSampler.
References Antipatrea::ClassContainer().
The documentation for this class was generated from the following file:
CfgImproveSampler.hpp