Antipatrea::CfgDistanceInJointSpace Class Reference
Antipatrea::CfgDistanceInJointSpace Class Reference
Defines the distance between two configurations in joint space.
#include <CfgDistanceInJointSpace.hpp>
Public Member Functions
CfgDistanceInJointSpace (void)
virtual ~CfgDistanceInJointSpace (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual double Distance (const Cfg &cfg1, const Cfg &cfg2)
Computes the distance between two configurations in joint space.
Public Member Functions inherited from Antipatrea::CfgDistance
CfgDistance (void)
virtual ~CfgDistance (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Detailed Description
Defines the distance between two configurations in joint space.
Author
Erion Plaku, Amarda Shehu
Remarks
The distance is computed as the L2 norm of the vector defined by taking the pairwise joint distances as defined by JointSignedDistance component.
This class requires access to CfgManager component in order to access the configuration dimension.
It also requires access to JointSignedDistance component in order to compute the distance between any two joint values.
Constructor & Destructor Documentation
Antipatrea::CfgDistanceInJointSpace::CfgDistanceInJointSpace (void) inline
virtual Antipatrea::CfgDistanceInJointSpace::~CfgDistanceInJointSpace (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgDistanceInJointSpace::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::CfgDistanceInJointSpace::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::ClassContainer(), Distance(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual double Antipatrea::CfgDistanceInJointSpace::Distance (const Cfg & cfg1, const Cfg & cfg2) virtual
Computes the distance between two configurations in joint space.
Author
Erion Plaku, Amarda Shehu
Remarks
Distance is computed as L2norm(a_{0}, ..., a_{dim-1}) where a_{i} = GetJointSignedDistance()->SignedDistance(cfg1->GetValues()[i], cfg2->GetValues()[i])
Implements Antipatrea::CfgDistance.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgDistanceInJointSpace.hpp