Antipatrea::FELTR Class Reference
Antipatrea::FELTR Class Reference
Implement the FELTR algorithm. See IJRR (2010) Shehu, Olson Guiding the Search for Native-like Protein Conformations with an Ab-Initio Tree-based exploration and Olson, Molloy, Shehu In Search of the Protein Native State with a Probabilistic Sampling Approach (JBCC 2011).
#include <FELTR.hpp>
Public Member Functions
FELTR (void)
virtual ~FELTR (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
Public Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
TreeSamplingBasedPlanner (void)
virtual ~TreeSamplingBasedPlanner (void)
virtual double GetExtendMaxNrSteps (void) const
Get the maximum number of steps for the tree-branch expansion.
virtual double GetExtendReachedTargetDistanceThreshold (void) const
Get the distance threshold to determine whether the target configuration has been reached.
virtual double GetGoalBias (void) const
Get the goal bias.
virtual bool GetSampleValidTargetCfg (void) const
Get the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void SetExtendMaxNrSteps (const int n)
Set the maximum number of steps for the tree-branch expansion.
virtual void SetExtendReachedTargetDistanceThreshold (const double d)
Set the distance threshold to determine whether the target configuration has been reached.
virtual void SetGoalBias (const double bias)
Set the goal bias.
virtual void SetSampleValidTargetCfg (const bool valid)
Set the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void Start (void)
Root the tree at the initial configuration.
virtual bool Solve (const double tmax)
Iteratively expand the motion tree by adding new vertices and edges.
Public Member Functions inherited from Antipatrea::SamplingBasedPlanner
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual bool CheckSetup (void)
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Member Functions
virtual PlannerVertex * NewVertex (void) const
Create a new planner vertices.
virtual Selector< FELTRRegion * >::Node * GetEnergyRegion (double projection[])
Given a 4d FELTR projection, return a FELTRRegion from the SELECTOR structure (not the graph).
virtual int AddVertex (Cfg *const cfg)
Given a configuration, add it to the FELTR projections and the TreeBasedPlanner data structures. Returns the vid, or -1 is no vertex was added. Recall that because of the granularity reduction, vertices may not added (and a -1 is returned).
virtual int SelectVertex (void)
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Protected Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
virtual void SampleTargetCfg (Cfg &cfg)
Sample a target at random or as the goal configuration.
virtual ExtendStatus ExtendToward (const int vidFrom, Cfg &cfgTo)
Extend a branch in the planner graph from the selected vertex toward the target configuration.
Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Protected Attributes
int m_cellGridGranularity
The granularity (number of cells in each dimension) within a FELTRCell (projections within an energy level).
int m_energyGridGranularity
The granularity (number of cells in each dimension) for the FELTRRegions.
double m_energyGridMin
Low end of the energy projection. All cfgs with lower energies are simply projected to this region.
double m_energyGridMax
High end of the energy projection. All cfgs with higher energies are projected into this region.
Grid m_energyGrid
Object that accepts the 4 projection coordinates and returns an integer scalar that can be used to map to a specific energy region.
Selector< FELTRRegion * > m_selector
Allow for efficient probabilistic selection for an energy region (stores pointers to energy regions and their associated weight).
std::map< int, Selector< FELTRRegion * >::Node * > m_FELTRRegionToSelectorMap
Maps the scalar returns by m_energyGrid to its cooresponding node within the selector tree.
Protected Attributes inherited from Antipatrea::TreeSamplingBasedPlanner
int m_extendMaxNrSteps
Maximum number of steps for the tree-branch expansion.
double m_extendReachedTargetDistanceThreshold
Distance threshold to determine whether the target configuration has been reached.
double m_goalBias
Goal bias.
bool m_sampleValidTargetCfg
Flag indicating whether the target should be sampled as a valid configuration.
Cfg * m_cfgTarget
Target configuration, which is set by the planner at each iteration.
Protected Attributes inherited from Antipatrea::SamplingBasedPlanner
const int SAMPLING_PLANNER_VERBOSE_FULL = 3
constants for verbosity control
const int SAMPLING_PLANNER_VERBOSE_MED = 2
const int SAMPLING_PLANNER_VERBOSE_LOW = 1
const int SAMPLING_PLANNER_VERBOSE_NONE = 0
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
int m_verbosityFlag
verbosity flag
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Protected Types inherited from Antipatrea::TreeSamplingBasedPlanner
enum ExtendStatus {
EXTEND_FAILED,
EXTEND_OK,
EXTEND_REACHED_TARGET,
EXTEND_REACHED_GOAL
}
Status of the planner-graph branch expansion.
Static Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Detailed Description
Implement the FELTR algorithm. See IJRR (2010) Shehu, Olson Guiding the Search for Native-like Protein Conformations with an Ab-Initio Tree-based exploration and Olson, Molloy, Shehu In Search of the Protein Native State with a Probabilistic Sampling Approach (JBCC 2011).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
This implementation uses Rosetta for the forward kinematics, energy functions, and fragment libraries.
Constructor & Destructor Documentation
FELTR()
Antipatrea::FELTR::FELTR (void) inline
~FELTR()
virtual Antipatrea::FELTR::~FELTR (void) inline virtual
Member Function Documentation
Info()
virtual void Antipatrea::FELTR::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::TreeSamplingBasedPlanner::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::FELTR::SetupFromParams (Params & params) inline virtual
Set the parameter values of the planner from the given parameters.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function first invokes TreeSamplingBasedPlanner::SetupFromParams(params).
It then sets the neighborhood radius (keyword Constants::KW_NeighborhoodRadius)
It uses the parameter group associated with the keyword Constants::KW_EST.
The parameter values can be specified in a text file as, for example, EST { NeighborhoodRadius 1.0 } }
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References FELTR_ENERGY_COORD_OFFSET, FELTR_PROJECTION_COORDS, FELTR_USR_COORDS, Antipatrea::Params::GetData(), Antipatrea::Constants::KW_FELTR, Antipatrea::Constants::KW_FELTR_CELLGRID_GRAN, Antipatrea::Constants::KW_FELTR_ENERGYGRID_GRAN, Antipatrea::Constants::KW_FELTR_ENERGYGRID_MAX, Antipatrea::Constants::KW_FELTR_ENERGYGRID_MIN, Antipatrea::Logger::m_out, and Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
NewVertex()
virtual PlannerVertex* Antipatrea::FELTR::NewVertex (void) const inline protected virtual
Create a new planner vertices.
Author
Erion Plaku, Amarda Shehu
Remarks
Create FELTRVertex instead of PlannerVertex.
Reimplemented from Antipatrea::SamplingBasedPlanner.
References Antipatrea::FELTRVertex::FELTRVertex().
GetEnergyRegion()
virtual Selector<FELTRRegion *>::Node* Antipatrea::FELTR::GetEnergyRegion (double projection[]) protected virtual
Given a 4d FELTR projection, return a FELTRRegion from the SELECTOR structure (not the graph).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
AddVertex()
virtual int Antipatrea::FELTR::AddVertex (Cfg *const cfg) protected virtual
Given a configuration, add it to the FELTR projections and the TreeBasedPlanner data structures. Returns the vid, or -1 is no vertex was added. Recall that because of the granularity reduction, vertices may not added (and a -1 is returned).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::SamplingBasedPlanner.
SelectVertex()
virtual int Antipatrea::FELTR::SelectVertex (void) protected virtual
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function returns the vid of the selected vertex.
First, an energy region is selected using the desired weighting function, and then a cell within that energy region is selected.
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
Member Data Documentation
m_cellGridGranularity
int Antipatrea::FELTR::m_cellGridGranularity protected
The granularity (number of cells in each dimension) within a FELTRCell (projections within an energy level).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_energyGridGranularity
int Antipatrea::FELTR::m_energyGridGranularity protected
The granularity (number of cells in each dimension) for the FELTRRegions.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_energyGridMin
double Antipatrea::FELTR::m_energyGridMin protected
Low end of the energy projection. All cfgs with lower energies are simply projected to this region.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_energyGridMax
double Antipatrea::FELTR::m_energyGridMax protected
High end of the energy projection. All cfgs with higher energies are projected into this region.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_energyGrid
Grid Antipatrea::FELTR::m_energyGrid protected
Object that accepts the 4 projection coordinates and returns an integer scalar that can be used to map to a specific energy region.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_selector
Selector<FELTRRegion *> Antipatrea::FELTR::m_selector protected
Allow for efficient probabilistic selection for an energy region (stores pointers to energy regions and their associated weight).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_FELTRRegionToSelectorMap
std::map<int,Selector<FELTRRegion*>::Node *> Antipatrea::FELTR::m_FELTRRegionToSelectorMap protected
Maps the scalar returns by m_energyGrid to its cooresponding node within the selector tree.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
The documentation for this class was generated from the following file:
FELTR.hpp