Antipatrea::CfgEnergyEvaluatorRosetta Class Reference
Antipatrea::CfgEnergyEvaluatorRosetta Class Reference
Use Rosetta to evaluate the energy of the configuration.
#include <CfgEnergyEvaluatorRosetta.hpp>
Public Member Functions
CfgEnergyEvaluatorRosetta (void)
virtual ~CfgEnergyEvaluatorRosetta (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual double EvaluateEnergy (Cfg &cfg)
Use Rosetta to evaluate the energy of the configuration.
Public Member Functions inherited from Antipatrea::CfgEnergyEvaluator
CfgEnergyEvaluator (void)
virtual ~CfgEnergyEvaluator (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Use Rosetta to evaluate the energy of the configuration.
Author
Erion Plaku, Amarda Shehu
Notes for Kevin
Add all the necessary components that you need to implement this class.
Constructor & Destructor Documentation
CfgEnergyEvaluatorRosetta()
Antipatrea::CfgEnergyEvaluatorRosetta::CfgEnergyEvaluatorRosetta (void) inline
~CfgEnergyEvaluatorRosetta()
virtual Antipatrea::CfgEnergyEvaluatorRosetta::~CfgEnergyEvaluatorRosetta (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgEnergyEvaluatorRosetta::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgEnergyEvaluatorRosetta::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::ClassContainer(), EvaluateEnergy(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, Antipatrea::Object::Name(), and SetupFromParams().
SetupFromParams()
virtual void Antipatrea::CfgEnergyEvaluatorRosetta::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Component.
Referenced by Info().
EvaluateEnergy()
virtual double Antipatrea::CfgEnergyEvaluatorRosetta::EvaluateEnergy (Cfg & cfg) virtual
Use Rosetta to evaluate the energy of the configuration.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgEnergyEvaluator.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgEnergyEvaluatorRosetta.hpp