Antipatrea::Selector< Key >::Node Class Reference
Antipatrea::Selector< Key >::Node Class Reference
Contains item key and weight as well as left, right, and parent pointers.
#include <Selector.hpp>
Public Member Functions
Node (void)
Initially the node is empty.
virtual ~Node (void)
Destructor does nothing.
virtual Key GetKey (void) const
Get node key.
virtual double GetWeight (void) const
Get node weight.
virtual void SetKey (Key key)
Set node key.
virtual void SetWeight (const double w)
Set node weight.
Protected Member Functions
virtual void Update (void)
Update node weight, i.e., set to sum of its children' weights.
Protected Attributes
Key m_key
Node key.
double m_weight
Node weight.
Node * m_left
Pointer to left child.
Node * m_right
Pointer to right child.
Node * m_parent
Pointer to parent.
Friends
class Selector
Detailed Description
template<typename Key>
class Antipatrea::Selector< Key >::Node
Contains item key and weight as well as left, right, and parent pointers.
Author
Erion Plaku
Constructor & Destructor Documentation
Node()
template<typename Key> Antipatrea::Selector< Key >::Node::Node (void) inline
Initially the node is empty.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Create(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Find(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Select(), and Antipatrea::Selector< Antipatrea::FELTRCell *>::Update().
~Node()
template<typename Key> virtual Antipatrea::Selector< Key >::Node::~Node (void) inline virtual
Destructor does nothing.
Author
Erion Plaku
Member Function Documentation
GetKey()
template<typename Key> virtual Key Antipatrea::Selector< Key >::Node::GetKey (void) const inline virtual
Get node key.
Author
Erion Plaku
References Antipatrea::Selector< Key >::Node::m_key.
GetWeight()
template<typename Key> virtual double Antipatrea::Selector< Key >::Node::GetWeight (void) const inline virtual
Get node weight.
Author
Erion Plaku
References Antipatrea::Selector< Key >::Node::m_weight.
SetKey()
template<typename Key> virtual void Antipatrea::Selector< Key >::Node::SetKey (Key key) inline virtual
Set node key.
Author
Erion Plaku
Parameters
key node key
References Antipatrea::Selector< Key >::Node::m_key.
SetWeight()
template<typename Key> virtual void Antipatrea::Selector< Key >::Node::SetWeight (const double w) inline virtual
Set node weight.
Author
Erion Plaku
Parameters
w node weight
References Antipatrea::Selector< Key >::Node::m_weight.
Update()
template<typename Key> virtual void Antipatrea::Selector< Key >::Node::Update (void) inline protected virtual
Update node weight, i.e., set to sum of its children' weights.
Author
Erion Plaku
References Antipatrea::Selector< Key >::Node::m_left, Antipatrea::Selector< Key >::Node::m_right, and Antipatrea::Selector< Key >::Node::m_weight.
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove(), and Antipatrea::Selector< Antipatrea::FELTRCell *>::Update().
Friends And Related Function Documentation
Selector
template<typename Key> friend class Selector friend
Member Data Documentation
m_key
template<typename Key> Key Antipatrea::Selector< Key >::Node::m_key protected
Node key.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Key >::Node::GetKey(), and Antipatrea::Selector< Key >::Node::SetKey().
m_weight
template<typename Key> double Antipatrea::Selector< Key >::Node::m_weight protected
Node weight.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Key >::Node::GetWeight(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Select(), Antipatrea::Selector< Key >::Node::SetWeight(), and Antipatrea::Selector< Key >::Node::Update().
m_left
template<typename Key> Node* Antipatrea::Selector< Key >::Node::m_left protected
Pointer to left child.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Select(), and Antipatrea::Selector< Key >::Node::Update().
m_right
template<typename Key> Node* Antipatrea::Selector< Key >::Node::m_right protected
Pointer to right child.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove(), and Antipatrea::Selector< Key >::Node::Update().
m_parent
template<typename Key> Node* Antipatrea::Selector< Key >::Node::m_parent protected
Pointer to parent.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove().
The documentation for this class was generated from the following file:
Selector.hpp