Antipatrea::CfgAcceptorBasedOnMMC Class Reference
Antipatrea::CfgAcceptorBasedOnMMC Class Reference
Motion-planning component which accepts a configuration only if the difference in energy is below accepted based on a temperature and a Metropolis test.
#include <CfgAcceptorBasedOnMMC.hpp>
Public Member Functions
CfgAcceptorBasedOnMMC (void)
virtual ~CfgAcceptorBasedOnMMC (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual double GetTemperature (void) const
Name says it all.
virtual void SetTemperature (const double temperature)
Name says it all.
virtual void SetTemperatureAdjRate (const double temperatureAdjRate)
Name says it all.
virtual const Cfg * GetSourceCfg (void) const
Get pointer to target/goal cfg.
virtual void SetSourceCfg (Cfg *const cfg)
Set pointer to target/goal cfg.
virtual bool IsAcceptable (Cfg &cfg)
Returns true iff the energy of cfg is lower than the CfgSource configuration OR it passes a probabalistic test based on the current temperature.
Public Member Functions inherited from Antipatrea::CfgAcceptor
CfgAcceptor (void)
virtual ~CfgAcceptor (void)
virtual Cfg * GetAnAcceptableCfg (void)
When possible, return a pointer to a configuration that is acceptable.
virtual bool IsUsedAsGoalAcceptor (void) const
Get the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void UseAsGoalAcceptor (const bool use)
Set the class purpose: goal acceptor (true) or configuration acceptor (false).
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
double m_temperature
User-defined temperature used in MMC test.
double m_temperatureAdjRate
Rate at which temperature increases after a failed MMC test.
double m_maxEnergy
max energy encountered so far.
double m_minEnergy
min energy encountered so far.
unsigned int m_testSuccessCount
Count of number of passed MMC tests.
unsigned int m_testFailCount
Count of number of failed MMC tests.
Cfg * m_cfgSource
Pointer to prior/source cfg.
Protected Attributes inherited from Antipatrea::CfgAcceptor
bool m_useAsGoalAcceptor
Class purpose: goal acceptor (true) or configuration acceptor (false).
bool m_verboseFlag
flag to control verbosity
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Motion-planning component which accepts a configuration only if the difference in energy is below accepted based on a temperature and a Metropolis test.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgEnergyEvaluator component in order to evaluate the energy of the configuration.
The initial temperature and adjustment factor are user parameters.
Constructor & Destructor Documentation
CfgAcceptorBasedOnMMC()
Antipatrea::CfgAcceptorBasedOnMMC::CfgAcceptorBasedOnMMC (void) inline
References m_maxEnergy, m_minEnergy, m_temperature, m_temperatureAdjRate, m_testFailCount, m_testSuccessCount, Antipatrea::Constants::VAL_CfgAcceptorBasedOnMMC_Temperature, and Antipatrea::Constants::VAL_CfgAcceptorBasedOnMMC_TemperatureAdjRate.
~CfgAcceptorBasedOnMMC()
virtual Antipatrea::CfgAcceptorBasedOnMMC::~CfgAcceptorBasedOnMMC (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgAcceptorBasedOnMMC::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgAcceptorBasedOnMMC::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References GetTemperature(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
SetupFromParams()
virtual void Antipatrea::CfgAcceptorBasedOnMMC::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function first invokes CfgAcceptor::SetupFromParams(params).
It then sets the energy threshold (keyword Constants::KW_EnergyThreshold).
Used as general cfg acceptor, it uses the parameter group associated with the keyword Constants::KW_CfgAcceptorBasedOnMMC.
The parameter value can be specified in a text file as, for example, CfgAcceptorBasedOnMMC { Temperature 70.00 }
Reimplemented from Antipatrea::CfgAcceptor.
References Antipatrea::Params::GetData(), Antipatrea::Params::GetValueAsDouble(), Antipatrea::Constants::KW_CfgAcceptorBasedOnMMC, Antipatrea::Constants::KW_MCCTemperature, Antipatrea::Constants::KW_MCCTemperatureAdjRate, Antipatrea::Logger::m_out, Antipatrea::Params::Data::m_params, m_temperature, m_temperatureAdjRate, SetTemperature(), SetTemperatureAdjRate(), and Antipatrea::CfgAcceptor::SetupFromParams().
GetTemperature()
virtual double Antipatrea::CfgAcceptorBasedOnMMC::GetTemperature (void) const inline virtual
Name says it all.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_temperature.
Referenced by Info().
SetTemperature()
virtual void Antipatrea::CfgAcceptorBasedOnMMC::SetTemperature (const double temperature) inline virtual
Name says it all.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_temperature.
Referenced by SetupFromParams().
SetTemperatureAdjRate()
virtual void Antipatrea::CfgAcceptorBasedOnMMC::SetTemperatureAdjRate (const double temperatureAdjRate) inline virtual
Name says it all.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_temperatureAdjRate.
Referenced by SetupFromParams().
GetSourceCfg()
virtual const Cfg* Antipatrea::CfgAcceptorBasedOnMMC::GetSourceCfg (void) const inline virtual
Get pointer to target/goal cfg.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function does not perform a copy – just returns the pointer to target/goal cfg.
References m_cfgSource.
SetSourceCfg()
virtual void Antipatrea::CfgAcceptorBasedOnMMC::SetSourceCfg (Cfg *const cfg) inline virtual
Set pointer to target/goal cfg.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function does not perform a copy – just pointer assignment.
References m_cfgSource.
IsAcceptable()
virtual bool Antipatrea::CfgAcceptorBasedOnMMC::IsAcceptable (Cfg & cfg) inline virtual
Returns true iff the energy of cfg is lower than the CfgSource configuration OR it passes a probabalistic test based on the current temperature.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
The function will call CfgEnergyEvaluator component to evaluate the energy of cfg
It will do so, however, only if the energy of cfg has not been previously evaluated (it checks whether the energy field is undefined – if so, it computes the energy; otherwise, it accesses the energy value).
Implements Antipatrea::CfgAcceptor.
References Antipatrea::Cfg::GetEnergy(), Antipatrea::Cfg::IsEnergySet(), m_cfgSource, m_maxEnergy, m_minEnergy, Antipatrea::Logger::m_out, m_temperature, m_temperatureAdjRate, m_testFailCount, m_testSuccessCount, Antipatrea::RandomUniformReal(), Antipatrea::Cfg::SetEnergy(), and Antipatrea::Constants::VAL_Boltzman_K.
Member Data Documentation
m_temperature
double Antipatrea::CfgAcceptorBasedOnMMC::m_temperature protected
User-defined temperature used in MMC test.
Author
Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnMMC(), GetTemperature(), IsAcceptable(), SetTemperature(), and SetupFromParams().
m_temperatureAdjRate
double Antipatrea::CfgAcceptorBasedOnMMC::m_temperatureAdjRate protected
Rate at which temperature increases after a failed MMC test.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnMMC(), IsAcceptable(), SetTemperatureAdjRate(), and SetupFromParams().
m_maxEnergy
double Antipatrea::CfgAcceptorBasedOnMMC::m_maxEnergy protected
max energy encountered so far.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnMMC(), and IsAcceptable().
m_minEnergy
double Antipatrea::CfgAcceptorBasedOnMMC::m_minEnergy protected
min energy encountered so far.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnMMC(), and IsAcceptable().
m_testSuccessCount
unsigned int Antipatrea::CfgAcceptorBasedOnMMC::m_testSuccessCount protected
Count of number of passed MMC tests.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnMMC(), and IsAcceptable().
m_testFailCount
unsigned int Antipatrea::CfgAcceptorBasedOnMMC::m_testFailCount protected
Count of number of failed MMC tests.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnMMC(), and IsAcceptable().
m_cfgSource
Cfg* Antipatrea::CfgAcceptorBasedOnMMC::m_cfgSource protected
Pointer to prior/source cfg.
Author
Erion Plaku, Amarda Shehu
Referenced by GetSourceCfg(), IsAcceptable(), and SetSourceCfg().
The documentation for this class was generated from the following file:
CfgAcceptorBasedOnMMC.hpp