Antipatrea::SetupRosetta Class Reference
Antipatrea::SetupRosetta Class Reference
Setup the planning problem for a molecular structure based on Rosetta representation as well as the planner and its components.
#include <SetupRosetta.hpp>
Public Member Functions
SetupRosetta (void)
virtual ~SetupRosetta (void)
virtual const MolecularStructureRosetta * GetMolecularStructureRosetta (void) const
Get a pointer to the molecular structure.
virtual MolecularStructureRosetta * GetMolecularStructureRosetta (void)
Get a pointer to the molecular structure.
virtual void Prepare (Params &params)
Create new instances, setup pointers, and setup the parameters.
virtual void PlannerCfgs ()
virtual void Test (void)
Write whatever you would like for testing purposes.
Public Member Functions inherited from Antipatrea::Setup
Setup (void)
virtual ~Setup (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void NewCfgForwardKinematics (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgEnergyEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgImprover (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgOffspringGenerator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgSampler (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgProjector (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointersCfgEnergyEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgImprover (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgOffspringGenerator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgSampler (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgProjector (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgDistance (void)
Setup the pointers for the indicated component.
Protected Member Functions inherited from Antipatrea::Setup
virtual void OnNewInstance (Component *const comp)
Add the instance to the set of component instances.
virtual void NewInstances (Params &params)
Create all the new instances.
virtual void SetupPointers (void)
Setup the component pointers.
virtual void NewCfgAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewGoalAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgManager (Params &params)
Create a new instance for the indicated component.
virtual void NewSignedDistanceBetweenTwoValues (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgDistance (Params &params)
Create a new instance for the indicated component.
virtual void NewEdgeCostEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerProblem (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerSolution (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerGraph (Params &params)
Create a new instance for the indicated component.
virtual void NewSamplingBasedPlanner (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointersComponent (Component *const comp)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersGoalAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgManager (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSignedDistanceBetweenTwoValues (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgForwardKinematics (void)
Setup the pointers for the indicated component.
virtual void SetupPointersEdgeCostEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerProblem (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerSolution (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerGraph (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSamplingBasedPlanner (void)
Setup the pointers for the indicated component.
virtual void SetupFromParams (Params &params)
Setup the paramater values of each component instance using the user-provided parameters.
Protected Attributes
std::string pdbOutputDirectory
Protected Attributes inherited from Antipatrea::Setup
std::vector< Component * > m_components
Component instances.
Private Member Functions
void RosettaInit (const char DBDir[])
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Setup the planning problem for a molecular structure based on Rosetta representation as well as the planner and its components.
Author
Erion Plaku, Amarda Shehu, Kevin Molloy
Remarks
Setup creates instances of the planning components based on keywords provided by the user or default settings when the user does not provide any keywords.
Only one instance per class is created.
After creating the components, Setup sets the pointers so that components/planners that depend on, for example, CfgDistance will have the CfgDistance pointer set to the CfgDistance instance created in the first step.
After setting the pointers, Setup iterates over all the instances that were created in step 1, and calls the function SetupFromParams in order to set the parameter values for each instance.
Constructor & Destructor Documentation
SetupRosetta()
Antipatrea::SetupRosetta::SetupRosetta (void) inline
~SetupRosetta()
virtual Antipatrea::SetupRosetta::~SetupRosetta (void) inline virtual
Member Function Documentation
GetMolecularStructureRosetta() [1/2]
virtual const MolecularStructureRosetta* Antipatrea::SetupRosetta::GetMolecularStructureRosetta (void) const inline virtual
Get a pointer to the molecular structure.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersCfgDistance(), SetupPointersCfgEnergyEvaluator(), SetupPointersCfgImprover(), SetupPointersCfgOffspringGenerator(), SetupPointersCfgProjector(), and SetupPointersCfgSampler().
GetMolecularStructureRosetta() [2/2]
virtual MolecularStructureRosetta* Antipatrea::SetupRosetta::GetMolecularStructureRosetta (void) inline virtual
Get a pointer to the molecular structure.
Author
Erion Plaku, Amarda Shehu
References PlannerCfgs(), Prepare(), and Test().
Prepare()
virtual void Antipatrea::SetupRosetta::Prepare (Params & params) virtual
Create new instances, setup pointers, and setup the parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Do everything that needs to be done in order to setup the planning problem, the planner, and its components.
Implements Antipatrea::Setup.
Referenced by GetMolecularStructureRosetta().
PlannerCfgs()
virtual void Antipatrea::SetupRosetta::PlannerCfgs () virtual
Referenced by GetMolecularStructureRosetta().
Test()
virtual void Antipatrea::SetupRosetta::Test (void) virtual
Write whatever you would like for testing purposes.
Author
Erion Plaku, Amarda Shehu
Remarks
Add code to test various components.
Reimplemented from Antipatrea::Setup.
Referenced by GetMolecularStructureRosetta().
NewCfgForwardKinematics()
virtual void Antipatrea::SetupRosetta::NewCfgForwardKinematics (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Params::GetValue(), Antipatrea::Constants::KW_MolecularStructureRosetta, Antipatrea::Constants::KW_UseCfgForwardKinematics, Antipatrea::Setup::NewCfgForwardKinematics(), Antipatrea::Setup::OnNewInstance(), and Antipatrea::StrSameContent().
NewCfgEnergyEvaluator()
virtual void Antipatrea::SetupRosetta::NewCfgEnergyEvaluator (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Params::GetValue(), Antipatrea::Constants::KW_CfgEnergyEvaluatorRosetta, Antipatrea::Constants::KW_UseCfgEnergyEvaluator, Antipatrea::Setup::NewCfgEnergyEvaluator(), Antipatrea::Setup::OnNewInstance(), and Antipatrea::StrSameContent().
NewCfgImprover()
virtual void Antipatrea::SetupRosetta::NewCfgImprover (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Params::GetValue(), Antipatrea::Constants::KW_CfgImproverRosetta, Antipatrea::Constants::KW_UseCfgImprover, Antipatrea::Setup::NewCfgImprover(), Antipatrea::Setup::OnNewInstance(), and Antipatrea::StrSameContent().
NewCfgOffspringGenerator()
virtual void Antipatrea::SetupRosetta::NewCfgOffspringGenerator (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Params::GetValue(), Antipatrea::Constants::KW_CfgOffspringGeneratorRosetta, Antipatrea::Constants::KW_CfgOffspringGeneratorRosettaWBias, Antipatrea::Constants::KW_UseCfgOffspringGenerator, Antipatrea::Setup::NewCfgOffspringGenerator(), Antipatrea::Setup::OnNewInstance(), and Antipatrea::StrSameContent().
NewCfgSampler()
virtual void Antipatrea::SetupRosetta::NewCfgSampler (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Params::GetValue(), Antipatrea::Constants::KW_CfgSamplerRosetta, Antipatrea::Constants::KW_UseCfgSampler, Antipatrea::Setup::NewCfgSampler(), Antipatrea::Setup::OnNewInstance(), and Antipatrea::StrSameContent().
NewCfgProjector()
virtual void Antipatrea::SetupRosetta::NewCfgProjector (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Params::GetValue(), Antipatrea::Constants::KW_CfgProjectorDeltaR, Antipatrea::Constants::KW_CfgProjectorUSREnergy, Antipatrea::Constants::KW_UseCfgProjector, Antipatrea::Setup::NewCfgProjector(), Antipatrea::Setup::OnNewInstance(), and Antipatrea::StrSameContent().
SetupPointersCfgEnergyEvaluator()
virtual void Antipatrea::SetupRosetta::SetupPointersCfgEnergyEvaluator (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetMolecularStructureRosetta(), and Antipatrea::Setup::SetupPointersCfgEnergyEvaluator().
SetupPointersCfgImprover()
virtual void Antipatrea::SetupRosetta::SetupPointersCfgImprover (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetMolecularStructureRosetta(), and Antipatrea::Setup::SetupPointersCfgImprover().
SetupPointersCfgOffspringGenerator()
virtual void Antipatrea::SetupRosetta::SetupPointersCfgOffspringGenerator (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetMolecularStructureRosetta(), and Antipatrea::Setup::SetupPointersCfgOffspringGenerator().
SetupPointersCfgSampler()
virtual void Antipatrea::SetupRosetta::SetupPointersCfgSampler (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetMolecularStructureRosetta(), and Antipatrea::Setup::SetupPointersCfgSampler().
SetupPointersCfgProjector()
virtual void Antipatrea::SetupRosetta::SetupPointersCfgProjector (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetMolecularStructureRosetta(), Antipatrea::MolecularStructureRosetta::Info(), and Antipatrea::Setup::SetupPointersCfgProjector().
SetupPointersCfgDistance()
virtual void Antipatrea::SetupRosetta::SetupPointersCfgDistance (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetMolecularStructureRosetta().
RosettaInit()
void Antipatrea::SetupRosetta::RosettaInit (const char DBDir[]) private
Member Data Documentation
pdbOutputDirectory
std::string Antipatrea::SetupRosetta::pdbOutputDirectory protected
The documentation for this class was generated from the following file:
SetupRosetta.hpp