Antipatrea::FromToPathGenerator Class Reference
Antipatrea::FromToPathGenerator Class Reference
#include <FromToPathGenerator.hpp>
Public Member Functions
FromToPathGenerator (void)
virtual ~FromToPathGenerator (void)
virtual void Info (const char prefix[]) const
virtual const Cfg * GetFromCfg (void) const
virtual const Cfg * GetToCfg (void) const
virtual void SetFromCfg (const Cfg *const cfg)
virtual void SetToCfg (const Cfg *const cfg)
Public Member Functions inherited from Antipatrea::PathGenerator
PathGenerator (void)
virtual ~PathGenerator (void)
virtual void GetCfgAtTime (const double t, Cfg &cfg)=0
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
const Cfg * m_cfgFrom
const Cfg * m_cfgTo
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Constructor & Destructor Documentation
Antipatrea::FromToPathGenerator::FromToPathGenerator (void) inline
virtual Antipatrea::FromToPathGenerator::~FromToPathGenerator (void) inline virtual
Member Function Documentation
virtual void Antipatrea::FromToPathGenerator::Info (const char prefix[]) const inline virtual
Reimplemented from Antipatrea::Object.
Reimplemented in Antipatrea::FromToPathGeneratorByInterpolationInJointSpace.
References GetFromCfg(), GetToCfg(), Antipatrea::Object::Info(), and Antipatrea::Logger::m_out.
Referenced by Antipatrea::FromToPathGeneratorByInterpolationInJointSpace::Info().
virtual const Cfg* Antipatrea::FromToPathGenerator::GetFromCfg (void) const inline virtual
References m_cfgFrom.
Referenced by Antipatrea::FromToPathGeneratorPoint2D::GetCfgAtTime(), and Info().
virtual const Cfg* Antipatrea::FromToPathGenerator::GetToCfg (void) const inline virtual
References m_cfgTo.
Referenced by Antipatrea::FromToPathGeneratorPoint2D::GetCfgAtTime(), and Info().
virtual void Antipatrea::FromToPathGenerator::SetFromCfg (const Cfg *const cfg) inline virtual
References m_cfgFrom.
virtual void Antipatrea::FromToPathGenerator::SetToCfg (const Cfg *const cfg) inline virtual
References m_cfgTo.
Member Data Documentation
const Cfg* Antipatrea::FromToPathGenerator::m_cfgFrom protected
Referenced by GetFromCfg(), and SetFromCfg().
const Cfg* Antipatrea::FromToPathGenerator::m_cfgTo protected
Referenced by GetToCfg(), and SetToCfg().
The documentation for this class was generated from the following file:
FromToPathGenerator.hpp