Antipatrea::CfgNearTargetSampler Class Reference
Antipatrea::CfgNearTargetSampler Class Reference
Interface for sampling a configuration near a target configuration.
#include <CfgNearTargetSampler.hpp>
Public Member Functions
CfgNearTargetSampler (void)
virtual ~CfgNearTargetSampler (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual const Cfg * GetTargetCfg (void) const
Get the pointer to the target configuration.
virtual void SetTargetCfg (const Cfg *const cfg)
Set the pointer to the target configuration.
Public Member Functions inherited from Antipatrea::CfgSampler
CfgSampler (void)
virtual ~CfgSampler (void)
virtual bool Sample (Cfg &cfg)=0
Sample a configuration.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
const Cfg * m_cfgTarget
Pointer to the target configuration.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for sampling a configuration near a target configuration.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Antipatrea::CfgNearTargetSampler::CfgNearTargetSampler (void) inline
virtual Antipatrea::CfgNearTargetSampler::~CfgNearTargetSampler (void) inline virtual
Member Function Documentation
virtual void Antipatrea::CfgNearTargetSampler::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Reimplemented in Antipatrea::CfgNearTargetSamplerByGaussianPerturbation.
References GetTargetCfg(), Antipatrea::Object::Info(), and Antipatrea::Logger::m_out.
Referenced by Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::Info().
virtual const Cfg* Antipatrea::CfgNearTargetSampler::GetTargetCfg (void) const inline virtual
Get the pointer to the target configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgTarget.
Referenced by Info().
virtual void Antipatrea::CfgNearTargetSampler::SetTargetCfg (const Cfg *const cfg) inline virtual
Set the pointer to the target configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgTarget.
Member Data Documentation
const Cfg* Antipatrea::CfgNearTargetSampler::m_cfgTarget protected
Pointer to the target configuration.
Author
Erion Plaku, Amarda Shehu
Referenced by GetTargetCfg(), and SetTargetCfg().
The documentation for this class was generated from the following file:
CfgNearTargetSampler.hpp