Antipatrea::GraphSearch< Key > Class Template Reference
Antipatrea::GraphSearch< Key > Class Template Reference
#include <GraphSearch.hpp>
Classes
struct Data
struct DataCompare
Public Member Functions
GraphSearch (void)
virtual ~GraphSearch (void)
void SetInfo (GraphSearchInfo< Key > *info)
bool DFS (const Key start, Key &goal)
bool BFS (const Key start, Key &goal)
bool AStar (const Key start, const bool breakEarly, Key &goal)
void GetReversePathFromStart (const Key u, std::vector< Key > &rpath) const
void GetPathFromStart (const Key u, std::vector< Key > &path) const
int GetPathLengthFromStart (const Key u) const
double GetPathCostFromStart (const Key u) const
Protected Attributes
GraphSearchInfo< Key > * m_info
std::unordered_map< Key, Data > m_map
Constructor & Destructor Documentation
template<typename Key> Antipatrea::GraphSearch< Key >::GraphSearch (void) inline
template<typename Key> virtual Antipatrea::GraphSearch< Key >::~GraphSearch (void) inline virtual
Member Function Documentation
template<typename Key> void Antipatrea::GraphSearch< Key >::SetInfo (GraphSearchInfo< Key > * info) inline
template<typename Key> bool Antipatrea::GraphSearch< Key >::DFS (const Key start, Key & goal)
References Antipatrea::GraphSearch< Key >::Data::m_gCost, Antipatrea::GraphSearch< Key >::Data::m_hCost, Antipatrea::GraphSearch< Key >::Data::m_key, and Antipatrea::GraphSearch< Key >::Data::m_parent.
template<typename Key> bool Antipatrea::GraphSearch< Key >::BFS (const Key start, Key & goal)
References Antipatrea::GraphSearch< Key >::Data::m_gCost, Antipatrea::GraphSearch< Key >::Data::m_hCost, Antipatrea::GraphSearch< Key >::Data::m_key, and Antipatrea::GraphSearch< Key >::Data::m_parent.
template<typename Key> bool Antipatrea::GraphSearch< Key >::AStar (const Key start, const bool breakEarly, Key & goal)
References Antipatrea::Heap< Key, Compare, Equal, Hash >::Insert(), Antipatrea::Heap< Key, Compare, Equal, Hash >::IsEmpty(), Antipatrea::GraphSearch< Key >::Data::m_gCost, Antipatrea::GraphSearch< Key >::DataCompare::m_gs, Antipatrea::GraphSearch< Key >::Data::m_hCost, Antipatrea::GraphSearch< Key >::Data::m_key, Antipatrea::GraphSearch< Key >::Data::m_parent, Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveTop(), Antipatrea::Heap< Key, Compare, Equal, Hash >::SetKeyCompare(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::Update().
template<typename Key> void Antipatrea::GraphSearch< Key >::GetReversePathFromStart (const Key u, std::vector< Key > & rpath) const
template<typename Key> void Antipatrea::GraphSearch< Key >::GetPathFromStart (const Key u, std::vector< Key > & path) const
template<typename Key> int Antipatrea::GraphSearch< Key >::GetPathLengthFromStart (const Key u) const
template<typename Key> double Antipatrea::GraphSearch< Key >::GetPathCostFromStart (const Key u) const
Member Data Documentation
template<typename Key> GraphSearchInfo<Key>* Antipatrea::GraphSearch< Key >::m_info protected
template<typename Key> std::unordered_map<Key, Data> Antipatrea::GraphSearch< Key >::m_map protected
The documentation for this class was generated from the following file:
GraphSearch.hpp