Antipatrea::SamplingBasedPlanner Class Reference
Antipatrea::SamplingBasedPlanner Class Reference
Interface for a sampling-based planner which explores the configuration space by sampling acceptable configurations, expanding branches, and connecting neighboring configurations.
#include <SamplingBasedPlanner.hpp>
Public Member Functions
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual void Start (void)
Initialize the planner.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
virtual bool Solve (const double tmax)=0
Run the planner for a certain amount of time.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Member Functions
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual int AddVertex (Cfg *const cfg)
Add a new vertex to the graph with cfg as its associated configuration.
virtual PlannerVertex * NewVertex (void) const
Factory for creating new planner vertices.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Static Protected Member Functions
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Protected Attributes
const int SAMPLING_PLANNER_VERBOSE_FULL = 3
constants for verbosity control
const int SAMPLING_PLANNER_VERBOSE_MED = 2
const int SAMPLING_PLANNER_VERBOSE_LOW = 1
const int SAMPLING_PLANNER_VERBOSE_NONE = 0
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
int m_verbosityFlag
verbosity flag
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Detailed Description
Interface for a sampling-based planner which explores the configuration space by sampling acceptable configurations, expanding branches, and connecting neighboring configurations.
Author
Erion Plaku, Amarda Shehu
Remarks
A sampling-based planner constructs a planner graph.
A sampling-based planner could be roadmap- or tree-based.
A sampling-based planner often relies on a proximity data structure to compute nearest neighbors.
This class requires access to several components such as PlannerGraph, CfgSampler, CfgImprover, CfgManager, CfgDistance, CfgAcceptor, CfgOffspringGenerator, and EdgeCostEvaluator.
Constructor & Destructor Documentation
SamplingBasedPlanner()
Antipatrea::SamplingBasedPlanner::SamplingBasedPlanner (void) inline
References m_proximityDataStructure, and ProximityDistFn().
~SamplingBasedPlanner()
virtual Antipatrea::SamplingBasedPlanner::~SamplingBasedPlanner (void) inline virtual
References m_proximityAuxCfg.
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::SamplingBasedPlanner::CheckSetup (void) inline virtual
Reimplemented from Antipatrea::Planner.
Reimplemented in Antipatrea::PGT.
References Antipatrea::Planner::CheckSetup().
Referenced by Antipatrea::PGT::CheckSetup().
Info()
virtual void Antipatrea::SamplingBasedPlanner::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Planner.
Reimplemented in Antipatrea::Sprint, Antipatrea::EST, Antipatrea::FELTR, Antipatrea::PGT, Antipatrea::PRM, and Antipatrea::TreeSamplingBasedPlanner.
References GetOneStepDistance(), Antipatrea::Planner::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
Referenced by Antipatrea::TreeSamplingBasedPlanner::Info(), and Antipatrea::PRM::Info().
SetupFromParams()
virtual void Antipatrea::SamplingBasedPlanner::SetupFromParams (Params & params) inline virtual
Set the parameter values of the planner from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes Planner::SetupFromParams(params).
It then sets the one-step distance (keyword Constants::KW_OneStepDistance), which is used by sampling-based planners to determine the resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
It uses the parameter group associated with the keyword Constants::KW_SamplingBasedPlanner.
The parameter value can be specified in a text file as, for example, SamplingBasedPlanner { OneStepDistance 0.01 }
Reimplemented from Antipatrea::Component.
Reimplemented in Antipatrea::Sprint, Antipatrea::EST, Antipatrea::FELTR, Antipatrea::PGT, Antipatrea::PRM, and Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::Params::GetData(), GetOneStepDistance(), Antipatrea::Constants::KW_OneStepDistance, Antipatrea::Constants::KW_SamplingBasedPlanner, SetOneStepDistance(), and Antipatrea::Component::SetupFromParams().
Referenced by Antipatrea::TreeSamplingBasedPlanner::SetupFromParams(), and Antipatrea::PRM::SetupFromParams().
GetOneStepDistance()
virtual double Antipatrea::SamplingBasedPlanner::GetOneStepDistance (void) const inline virtual
Get the one-step distance.
Author
Erion Plaku, Amarda Shehu
Remarks
This is used by sampling-based planners to determine the resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
References m_oneStepDistance.
Referenced by Info(), and SetupFromParams().
SetOneStepDistance()
virtual void Antipatrea::SamplingBasedPlanner::SetOneStepDistance (const double d) inline virtual
Set the one-step distance.
Author
Erion Plaku, Amarda Shehu
Remarks
This is used by sampling-based planners to determine the resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
References GetSolution(), IsSolved(), m_oneStepDistance, Print(), Read(), and Start().
Referenced by SetupFromParams().
Start()
virtual void Antipatrea::SamplingBasedPlanner::Start (void) virtual
Initialize the planner.
Author
Erion Plaku, Amarda Shehu
Remarks
This function should be called only once at the beginning after the problem and other components have been setup.
The function allocates memory for an auxilary configuration needed to compute nearest neighbors.
Implements Antipatrea::Planner.
Reimplemented in Antipatrea::TreeSamplingBasedPlanner, and Antipatrea::PRM.
Referenced by SetOneStepDistance().
IsSolved()
virtual bool Antipatrea::SamplingBasedPlanner::IsSolved (void) virtual
Return true iff the planner has found a solution.
Author
Erion Plaku, Amarda Shehu
Remarks
The function uses the disjoint-set data structure to check whether any vertex that is marked as goal belongs to the same connected component as the initial vertex.
Implements Antipatrea::Planner.
Referenced by SetOneStepDistance().
GetSolution()
virtual bool Antipatrea::SamplingBasedPlanner::GetSolution (PlannerSolution & sol) virtual
Construct the solution that the planner has found.
Author
Erion Plaku, Amarda Shehu
Remarks
The function returns true iff the planner has found a solution.
If a solution is found, A* is used to find the shortest path in the planner graph. The solution is constructed based on the vertex ids of this shortest path and the corresponding configurations.
Implements Antipatrea::Planner.
Referenced by SetOneStepDistance().
Print()
virtual std::ostream& Antipatrea::SamplingBasedPlanner::Print (std::ostream & out) const virtual
Print the configurations, vertices, and edges of the planner graph.
Author
Erion Plaku, Amarda Shehu
Remarks
This function can be used to save the planner graph to an output stream for later use.
Implements Antipatrea::Writer.
Referenced by SetOneStepDistance().
Read()
virtual std::istream& Antipatrea::SamplingBasedPlanner::Read (std::istream & in) virtual
Read configurations, vertices, and edges and add them to the planner graph.
Author
Erion Plaku, Amarda Shehu
Remarks
This allows the user to reuse a previously-stored planner graph or to populate the planner graph with additinal configurations and edges that may come from other sources, e.g., databases of known good configurations/structures.
The function avoids adding configurations or edges that already exist in the planner graph (using FindCfg and PlannerGraph::FindEdge).
Implements Antipatrea::Reader.
Referenced by SetOneStepDistance().
FindCfg()
virtual int Antipatrea::SamplingBasedPlanner::FindCfg (Cfg & cfg) protected virtual
If there is a vertex whose configuration is the same as cfg, then return its id.
Author
Erion Plaku, Amarda Shehu
Remarks
The function finds the closest vertex to cfg that is within Constants::EPSILON distance:
If successful, it returns the id of that vertex.
If there is no configuration in the planner graph that is within Constants::EPSILON distance from cfg, then the function returns Constants::ID_UNDEFINED.
If the planner uses the proximity data structure, then the function uses it to find the configuration. Otherwise, it does a brute-force search.
AddVertex()
virtual int Antipatrea::SamplingBasedPlanner::AddVertex (Cfg *const cfg) protected virtual
Add a new vertex to the graph with cfg as its associated configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
The function does not make a copy of cfg; it simply does pointer assignment.
The function does not check if cfg is already in the graph. It is the responsibility of the calling function to perform such a check (using FindCfg) if indeed there is a possibility that the same configuration is added to the graph multiple times (which even if it happened would not cause any errors).
Reimplemented in Antipatrea::PRM, Antipatrea::EST, Antipatrea::Sprint, Antipatrea::FELTR, and Antipatrea::PGT.
NewVertex()
virtual PlannerVertex* Antipatrea::SamplingBasedPlanner::NewVertex (void) const inline protected virtual
Factory for creating new planner vertices.
Author
Erion Plaku, Amarda Shehu
Remarks
Planners should use NewVertex instead of new PlannerVertex() to allocate memory for a new vertex, since planners extending SamplingBasedPlanner could also extend PlannerVertex. For example, EST does exactly this.
Reimplemented in Antipatrea::Sprint, Antipatrea::EST, and Antipatrea::FELTR.
NewEdge()
virtual PlannerEdge* Antipatrea::SamplingBasedPlanner::NewEdge (void) const inline protected virtual
Factory for creating new planner edges.
Author
Erion Plaku, Amarda Shehu
Remarks
Planners should use NewEdge instead of new PlannerEdge() to allocate memory for a new edge, since planners extending SamplingBasedPlanner could also extend PlannerEdge.
References FromVertexSequenceToCfgs(), and ProximityDistFn().
FromVertexSequenceToCfgs()
virtual void Antipatrea::SamplingBasedPlanner::FromVertexSequenceToCfgs (PlannerSolution & sol) protected virtual
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Author
Erion Plaku, Amarda Shehu
Remarks
Additional intermediate configurations could be added to the solution since the paths associated with the edges of the solution could be discretized (using OneStepDistance to define the resolution).
Referenced by NewEdge().
ProximityDistFn()
static double Antipatrea::SamplingBasedPlanner::ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner * sbPlanner) static protected
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Author
Erion Plaku, Amarda Shehu
Referenced by NewEdge(), and SamplingBasedPlanner().
Member Data Documentation
SAMPLING_PLANNER_VERBOSE_FULL
const int Antipatrea::SamplingBasedPlanner::SAMPLING_PLANNER_VERBOSE_FULL = 3 protected
constants for verbosity control
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
SAMPLING_PLANNER_VERBOSE_MED
const int Antipatrea::SamplingBasedPlanner::SAMPLING_PLANNER_VERBOSE_MED = 2 protected
SAMPLING_PLANNER_VERBOSE_LOW
const int Antipatrea::SamplingBasedPlanner::SAMPLING_PLANNER_VERBOSE_LOW = 1 protected
SAMPLING_PLANNER_VERBOSE_NONE
const int Antipatrea::SamplingBasedPlanner::SAMPLING_PLANNER_VERBOSE_NONE = 0 protected
m_proximityDataStructure
ProximityDefault<int, SamplingBasedPlanner*> Antipatrea::SamplingBasedPlanner::m_proximityDataStructure protected
Proximity data structure to facilitate nearest-neighbors queires.
Author
Erion Plaku, Amarda Shehu
Referenced by SamplingBasedPlanner().
m_verbosityFlag
int Antipatrea::SamplingBasedPlanner::m_verbosityFlag protected
verbosity flag
Author
Erion Plaku, Amarda Shehu
m_proximityAuxCfg
Cfg* Antipatrea::SamplingBasedPlanner::m_proximityAuxCfg protected
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
Author
Erion Plaku, Amarda Shehu
Referenced by ~SamplingBasedPlanner().
m_vidInit
int Antipatrea::SamplingBasedPlanner::m_vidInit protected
The id of the vertex associated with the initial configuration.
Author
Erion Plaku, Amarda Shehu
m_vidsGoal
std::vector<int> Antipatrea::SamplingBasedPlanner::m_vidsGoal protected
The set of vertices marked as goal (where the goal is satisfied).
Author
Erion Plaku, Amarda Shehu
m_graphSearch
GraphSearch<int> Antipatrea::SamplingBasedPlanner::m_graphSearch protected
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
Author
Erion Plaku, Amarda Shehu
m_graphSearchInfo
PlannerGraphSearchInfo Antipatrea::SamplingBasedPlanner::m_graphSearchInfo protected
Implicit representation of the planner graph.
Author
Erion Plaku, Amarda Shehu
m_oneStepDistance
double Antipatrea::SamplingBasedPlanner::m_oneStepDistance protected
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Author
Erion Plaku, Amarda Shehu
Referenced by GetOneStepDistance(), and SetOneStepDistance().
The documentation for this class was generated from the following file:
SamplingBasedPlanner.hpp