Antipatrea::Stats Class Reference
Antipatrea::Stats Class Reference
#include <Stats.hpp>
Public Member Functions
Stats (void)
virtual ~Stats (void)
virtual double GetValue (const char id[])
virtual void SetValue (const char id[], const double t)
virtual double AddValue (const char id[], const double t)
virtual std::ostream & Print (std::ostream &out) const
Write to the output stream.
virtual std::istream & Read (std::istream &in)
Read the content from the input stream.
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Static Public Member Functions
static Stats * GetSingleton (void)
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Protected Attributes
std::unordered_map< std::string, double > m_values
Static Protected Attributes
static Stats * m_singleton
Constructor & Destructor Documentation
Stats()
Antipatrea::Stats::Stats (void) inline
~Stats()
virtual Antipatrea::Stats::~Stats (void) inline virtual
References AddValue(), GetValue(), Print(), Read(), and SetValue().
Member Function Documentation
GetValue()
virtual double Antipatrea::Stats::GetValue (const char id[]) virtual
Referenced by ~Stats().
SetValue()
virtual void Antipatrea::Stats::SetValue (const char id[], const double t) virtual
Referenced by ~Stats().
AddValue()
virtual double Antipatrea::Stats::AddValue (const char id[], const double t) virtual
Referenced by ~Stats().
Print()
virtual std::ostream& Antipatrea::Stats::Print (std::ostream & out) const virtual
Write to the output stream.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Writer.
Referenced by ~Stats().
Read()
virtual std::istream& Antipatrea::Stats::Read (std::istream & in) virtual
Read the content from the input stream.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Reader.
Referenced by ~Stats().
GetSingleton()
static Stats* Antipatrea::Stats::GetSingleton (void) inline static
References m_singleton.
Member Data Documentation
m_singleton
Stats* Antipatrea::Stats::m_singleton static protected
Referenced by GetSingleton().
m_values
std::unordered_map<std::string, double> Antipatrea::Stats::m_values protected
The documentation for this class was generated from the following file:
Stats.hpp