Antipatrea::CfgProjectorUSR Class Reference
Antipatrea::CfgProjectorUSR Class Reference
Use Rosetta to compute the USR projection of the configuration values.
#include <CfgProjectorUSR.hpp>
Public Member Functions
CfgProjectorUSR (void)
virtual ~CfgProjectorUSR (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void Project (Cfg &cfg, double proj[])
Use Rosetta to compute the USR projection of the configuration values.
Public Member Functions inherited from Antipatrea::CfgProjector
CfgProjector (const int dim=0)
virtual ~CfgProjector (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Allocator
Allocator (const int dim=0)
virtual ~Allocator (void)
virtual void SetDim (const int dim)
Set dimension.
virtual int GetDim (void) const
Get the dimension.
virtual double * NewValues (void) const
Allocate memory for the array.
virtual void DeleteValues (double values[]) const
Delete the memory allocated to the array.
virtual void CopyValues (double dest[], const double src[]) const
Copy the values from src to dest.
virtual double * CopyValues (const double values[]) const
Return a copy of the array.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::Allocator
int m_dim
Array dimension.
Detailed Description
Use Rosetta to compute the USR projection of the configuration values.
Author
Erion Plaku, Amarda Shehu
Notes for Kevin
Add all the necessary components that you need to implement this class.
Constructor & Destructor Documentation
Antipatrea::CfgProjectorUSR::CfgProjectorUSR (void) inline
virtual Antipatrea::CfgProjectorUSR::~CfgProjectorUSR (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgProjectorUSR::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::CfgProjector.
References Antipatrea::CfgProjector::CheckSetup().
virtual void Antipatrea::CfgProjectorUSR::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgProjector.
References Antipatrea::ClassContainer(), Antipatrea::CfgProjector::Info(), Antipatrea::Logger::m_out, Antipatrea::Object::Name(), Project(), and SetupFromParams().
virtual void Antipatrea::CfgProjectorUSR::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::CfgProjector.
Referenced by Info().
virtual void Antipatrea::CfgProjectorUSR::Project (Cfg & cfg, double proj[]) virtual
Use Rosetta to compute the USR projection of the configuration values.
Author
Erion Plaku, Amarda Shehu
Remarks
The function assumes that proj has been properly allocated (using CfgProjector::NewValues())
Implements Antipatrea::CfgProjector.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgProjectorUSR.hpp