Antipatrea::CfgOffspringGeneratorRosetta Class Reference
Antipatrea::CfgOffspringGeneratorRosetta Class Reference
Use Rosetta/library to generate an offspring near the parent configuration.
#include <CfgOffspringGeneratorRosetta.hpp>
Public Member Functions
CfgOffspringGeneratorRosetta (void)
virtual ~CfgOffspringGeneratorRosetta (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void GenerateOffspringCfg (Cfg &cfg)
Use Rosetta to generate the offspring configuration near the parent configuration.
Public Member Functions inherited from Antipatrea::CfgOffspringGenerator
CfgOffspringGenerator (void)
virtual ~CfgOffspringGenerator (void)
virtual const Cfg * GetParentCfg (void) const
Get the pointer to the parent configuration.
virtual void SetParentCfg (const Cfg *const cfgParent)
Set the pointer to the parent configuration.
virtual double GetStep (void) const
Get the step size used for guiding the offspring generation.
virtual void SetStep (const double step)
Get the step size used for guiding the offspring generation.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::CfgOffspringGenerator
const Cfg * m_cfgParent
Pointer to the parent configuration.
double m_step
Step size to guide the offspring generation.
Detailed Description
Use Rosetta/library to generate an offspring near the parent configuration.
Author
Erion Plaku, Amarda Shehu
Notes for Kevin
Add all the necessary components that you need to implement this class.
Base class already contains CfgManager, so it is not added here.
Constructor & Destructor Documentation
Antipatrea::CfgOffspringGeneratorRosetta::CfgOffspringGeneratorRosetta (void) inline
virtual Antipatrea::CfgOffspringGeneratorRosetta::~CfgOffspringGeneratorRosetta (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgOffspringGeneratorRosetta::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::CfgOffspringGenerator.
References Antipatrea::CfgOffspringGenerator::CheckSetup().
virtual void Antipatrea::CfgOffspringGeneratorRosetta::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgOffspringGenerator.
References Antipatrea::ClassContainer(), GenerateOffspringCfg(), Antipatrea::CfgOffspringGenerator::Info(), Antipatrea::Logger::m_out, Antipatrea::Object::Name(), and SetupFromParams().
virtual void Antipatrea::CfgOffspringGeneratorRosetta::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::CfgOffspringGenerator.
Referenced by Info().
virtual void Antipatrea::CfgOffspringGeneratorRosetta::GenerateOffspringCfg (Cfg & cfg) virtual
Use Rosetta to generate the offspring configuration near the parent configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
Use GetStep() as a measure of how far/different the offspring should be from its parent.
Implements Antipatrea::CfgOffspringGenerator.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgOffspringGeneratorRosetta.hpp