Antipatrea::FELTRRegion Class Reference
Antipatrea::FELTRRegion Class Reference
#include <FELTRRegion.hpp>
Public Types
enum WeightFunc {
RAND =1,
QUAD =2,
METR =3,
COV1 =4,
COV2 =5,
MTCV =6,
NORM =7
}
typedef enum WeightFunc WeightFunc
Public Member Functions
FELTRRegion (void)
FELTRRegion (int id, int cellCount, unsigned int objDim)
virtual ~FELTRRegion (void)
void AddVertex (int vid, const Cfg *cfg, const double *const p, FELTRRegion *&region, FELTRCell *&cell)
void IncNew (int inc=1)
int GetId ()
int GetNrGridCells ()
int GetNrSelections (void) const
double GetAvgE (void) const
double GetSumE (void) const
double GetMinE (void) const
double GetMaxE (void) const
int GetNrConfs (void) const
double GetWeight (void) const
void PrintCellIdList (std::ostream &stream)
int SelectVertex (void)
bool CheckVertex (Cfg *const cfg, double [])
Protected Member Functions
void UpdateWeightOnSelection (const int nsel)
void UpdateWeightOnEnergy (const double energy)
void UpdateWeightQUAD (void)
void UpdateWeightNORM (void)
void UpdateWeight ()
Protected Attributes
int m_nsel
int m_nrConfs
double m_sumE
double m_minE
double m_maxE
double m_weight
Selector< FELTRCell * > m_selector
std::map< int, Selector< FELTRCell * >::Node * > m_CellToSelectorMap
Grid * m_gridCells
int m_id
int m_newPaths
unsigned int m_objDim
unsigned int m_reductionCount
unsigned int m_weightFunction
Member Typedef Documentation
WeightFunc
typedef enum WeightFunc Antipatrea::FELTRRegion::WeightFunc
Member Enumeration Documentation
WeightFunc
enum Antipatrea::FELTRRegion::WeightFunc
Enumerator
RAND
QUAD
METR
COV1
COV2
MTCV
NORM
Constructor & Destructor Documentation
FELTRRegion() [1/2]
Antipatrea::FELTRRegion::FELTRRegion (void) inline
FELTRRegion() [2/2]
Antipatrea::FELTRRegion::FELTRRegion (int id, int cellCount, unsigned int objDim) inline
References FELTR_PROJECTION_COORDS, and Antipatrea::get_constrained_R0().
~FELTRRegion()
virtual Antipatrea::FELTRRegion::~FELTRRegion (void) inline virtual
References Antipatrea::FELTRCell::AddVertex().
Member Function Documentation
AddVertex()
void Antipatrea::FELTRRegion::AddVertex (int vid, const Cfg * cfg, const double *const p, FELTRRegion *& region, FELTRCell *& cell)
IncNew()
void Antipatrea::FELTRRegion::IncNew (int inc = 1) inline
References Antipatrea::FELTRCell::m_newPaths.
GetId()
int Antipatrea::FELTRRegion::GetId () inline
References Antipatrea::FELTRCell::m_id.
GetNrGridCells()
int Antipatrea::FELTRRegion::GetNrGridCells () inline
GetNrSelections()
int Antipatrea::FELTRRegion::GetNrSelections (void) const inline
References Antipatrea::FELTRCell::m_nsel.
GetAvgE()
double Antipatrea::FELTRRegion::GetAvgE (void) const inline
GetSumE()
double Antipatrea::FELTRRegion::GetSumE (void) const inline
GetMinE()
double Antipatrea::FELTRRegion::GetMinE (void) const inline
GetMaxE()
double Antipatrea::FELTRRegion::GetMaxE (void) const inline
GetNrConfs()
int Antipatrea::FELTRRegion::GetNrConfs (void) const inline
GetWeight()
double Antipatrea::FELTRRegion::GetWeight (void) const inline
References Antipatrea::FELTRCell::m_weight, and Antipatrea::FELTRCell::SelectVertex().
PrintCellIdList()
void Antipatrea::FELTRRegion::PrintCellIdList (std::ostream & stream)
SelectVertex()
int Antipatrea::FELTRRegion::SelectVertex (void)
CheckVertex()
bool Antipatrea::FELTRRegion::CheckVertex (Cfg *const cfg, double [])
UpdateWeightOnSelection()
void Antipatrea::FELTRRegion::UpdateWeightOnSelection (const int nsel) inline protected
References Antipatrea::FELTRCell::m_nsel.
UpdateWeightOnEnergy()
void Antipatrea::FELTRRegion::UpdateWeightOnEnergy (const double energy) inline protected
References Antipatrea::FELTRCell::UpdateWeight().
UpdateWeightQUAD()
void Antipatrea::FELTRRegion::UpdateWeightQUAD (void) inline protected
References Antipatrea::FELTRCell::m_weight.
UpdateWeightNORM()
void Antipatrea::FELTRRegion::UpdateWeightNORM (void) inline protected
References Antipatrea::FELTRCell::m_weight.
UpdateWeight()
void Antipatrea::FELTRRegion::UpdateWeight (void) inline protected
Member Data Documentation
m_nsel
int Antipatrea::FELTRRegion::m_nsel protected
m_nrConfs
int Antipatrea::FELTRRegion::m_nrConfs protected
m_sumE
double Antipatrea::FELTRRegion::m_sumE protected
m_minE
double Antipatrea::FELTRRegion::m_minE protected
m_maxE
double Antipatrea::FELTRRegion::m_maxE protected
m_weight
double Antipatrea::FELTRRegion::m_weight protected
m_selector
Selector<FELTRCell *> Antipatrea::FELTRRegion::m_selector protected
m_CellToSelectorMap
std::map<int, Selector<FELTRCell *>::Node *> Antipatrea::FELTRRegion::m_CellToSelectorMap protected
m_gridCells
Grid* Antipatrea::FELTRRegion::m_gridCells protected
m_id
int Antipatrea::FELTRRegion::m_id protected
m_newPaths
int Antipatrea::FELTRRegion::m_newPaths protected
m_objDim
unsigned int Antipatrea::FELTRRegion::m_objDim protected
m_reductionCount
unsigned int Antipatrea::FELTRRegion::m_reductionCount protected
m_weightFunction
unsigned int Antipatrea::FELTRRegion::m_weightFunction protected
The documentation for this class was generated from the following file:
FELTRRegion.hpp