Antipatrea::CfgDistanceAtomRMSD Class Reference
Antipatrea::CfgDistanceAtomRMSD Class Reference
Defines the distance between two configurations as the least root mean square deviation (RMSD) between the backbone atoms.
#include <CfgDistanceAtomRMSD.hpp>
Public Member Functions
CfgDistanceAtomRMSD (void)
virtual ~CfgDistanceAtomRMSD (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual double Distance (const Cfg &cfg1, const Cfg &cfg2)
Computes the distance between two configurations as the least RMSD of the pairwise distances between heavy backbone atom positions.
virtual double DistancePrint (const Cfg &cfg1, const Cfg &cfg2)
Public Member Functions inherited from Antipatrea::CfgDistance
CfgDistance (void)
virtual ~CfgDistance (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
unsigned int distCalcs
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Defines the distance between two configurations as the least root mean square deviation (RMSD) between the backbone atoms.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Distance is computed as the normalized sum of the square of the differences in each atom's position.
It requires access to CfgManager to access the configuration dimension.
Constructor & Destructor Documentation
CfgDistanceAtomRMSD()
Antipatrea::CfgDistanceAtomRMSD::CfgDistanceAtomRMSD (void) inline
References distCalcs.
~CfgDistanceAtomRMSD()
virtual Antipatrea::CfgDistanceAtomRMSD::~CfgDistanceAtomRMSD (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgDistanceAtomRMSD::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgDistanceAtomRMSD::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
SetupFromParams()
virtual void Antipatrea::CfgDistanceAtomRMSD::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function first invokes CfgDistance::SetupFromParams(params).
Reimplemented from Antipatrea::Component.
References Distance(), DistancePrint(), and Antipatrea::Component::SetupFromParams().
Distance()
virtual double Antipatrea::CfgDistanceAtomRMSD::Distance (const Cfg & cfg1, const Cfg & cfg2) virtual
Computes the distance between two configurations as the least RMSD of the pairwise distances between heavy backbone atom positions.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgDistance.
Referenced by Antipatrea::CfgProjectorDeltaR::PostSetup(), and SetupFromParams().
DistancePrint()
virtual double Antipatrea::CfgDistanceAtomRMSD::DistancePrint (const Cfg & cfg1, const Cfg & cfg2) virtual
Reimplemented from Antipatrea::CfgDistance.
Referenced by SetupFromParams().
Member Data Documentation
distCalcs
unsigned int Antipatrea::CfgDistanceAtomRMSD::distCalcs protected
Referenced by CfgDistanceAtomRMSD().
The documentation for this class was generated from the following file:
CfgDistanceAtomRMSD.hpp