Antipatrea::CfgProjectorChain2D Class Reference
Antipatrea::CfgProjectorChain2D Class Reference
CfgProjectorChain2D computes the projection as the position of the end effector of the chain.
#include <CfgProjectorChain2D.hpp>
Public Member Functions
CfgProjectorChain2D (void)
virtual ~CfgProjectorChain2D (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void Project (const Cfg &cfg, double proj[])
Compute the configuration projection as the position of the end effector.
Public Member Functions inherited from Antipatrea::CfgProjector
CfgProjector (const int dim=0)
virtual ~CfgProjector (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Allocator
Allocator (const int dim=0)
virtual ~Allocator (void)
virtual void SetDim (const int dim)
Set dimension.
virtual int GetDim (void) const
Get the dimension.
virtual double * NewValues (void) const
Allocate memory for the array.
virtual void DeleteValues (double values[]) const
Delete the memory allocated to the array.
virtual void CopyValues (double dest[], const double src[]) const
Copy the values from src to dest.
virtual double * CopyValues (const double values[]) const
Return a copy of the array.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::Allocator
int m_dim
Array dimension.
Detailed Description
CfgProjectorChain2D computes the projection as the position of the end effector of the chain.
Author
Erion Plaku, Amarda Shehu
Remarks
CfgAcceptorChain2D needs access to Chain2D.
Constructor & Destructor Documentation
CfgProjectorChain2D()
Antipatrea::CfgProjectorChain2D::CfgProjectorChain2D (void) inline
~CfgProjectorChain2D()
virtual Antipatrea::CfgProjectorChain2D::~CfgProjectorChain2D (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgProjectorChain2D::CheckSetup (void) inline virtual
References Antipatrea::CfgProjector::CheckSetup().
Info()
virtual void Antipatrea::CfgProjectorChain2D::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgProjector.
References Antipatrea::ClassContainer(), Antipatrea::CfgProjector::Info(), Antipatrea::Logger::m_out, Antipatrea::Object::Name(), and Project().
Project()
virtual void Antipatrea::CfgProjectorChain2D::Project (const Cfg & cfg, double proj[]) virtual
Compute the configuration projection as the position of the end effector.
Author
Erion Plaku, Amarda Shehu
Remarks
The function assumes that proj has been properly allocated (using CfgProjector::NewValues())
Implements Antipatrea::CfgProjector.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgProjectorChain2D.hpp