Antipatrea::FromToPathGeneratorPoint2D Class Reference
Antipatrea::FromToPathGeneratorPoint2D Class Reference
#include <FromToPathGeneratorPoint2D.hpp>
Public Member Functions
FromToPathGeneratorPoint2D (void)
virtual ~FromToPathGeneratorPoint2D (void)
virtual void GetCfgAtTime (const double t, Cfg &cfg)
Public Member Functions inherited from Antipatrea::FromToPathGenerator
FromToPathGenerator (void)
virtual ~FromToPathGenerator (void)
virtual void Info (const char prefix[]) const
virtual const Cfg * GetFromCfg (void) const
virtual const Cfg * GetToCfg (void) const
virtual void SetFromCfg (const Cfg *const cfg)
virtual void SetToCfg (const Cfg *const cfg)
Public Member Functions inherited from Antipatrea::PathGenerator
PathGenerator (void)
virtual ~PathGenerator (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Protected Attributes inherited from Antipatrea::FromToPathGenerator
const Cfg * m_cfgFrom
const Cfg * m_cfgTo
Constructor & Destructor Documentation
Antipatrea::FromToPathGeneratorPoint2D::FromToPathGeneratorPoint2D (void) inline
virtual Antipatrea::FromToPathGeneratorPoint2D::~FromToPathGeneratorPoint2D (void) inline virtual
Member Function Documentation
virtual void Antipatrea::FromToPathGeneratorPoint2D::GetCfgAtTime (const double t, Cfg & cfg) inline virtual
Implements Antipatrea::PathGenerator.
References Antipatrea::ClassContainer(), Antipatrea::FromToPathGenerator::GetFromCfg(), Antipatrea::FromToPathGenerator::GetToCfg(), Antipatrea::Cfg::GetValues(), and Antipatrea::Cfg::SetValues().
The documentation for this class was generated from the following file:
FromToPathGeneratorPoint2D.hpp