Antipatrea::Writer Class Reference
Antipatrea::Writer Class Reference abstract
Interface for writing to an output stream.
#include <Writer.hpp>
Public Member Functions
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
virtual std::ostream & Print (std::ostream &out) const =0
Write to the output stream.
Detailed Description
Interface for writing to an output stream.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Antipatrea::Writer::Writer (void) inline
virtual Antipatrea::Writer::~Writer (void) inline virtual
References Print(), and PrintToFile().
Member Function Documentation
virtual void Antipatrea::Writer::PrintToFile (const char fname[], std::ios_base::openmode mode = std::ios_base::out) const virtual
Open a file for writing, write the content, and then close the file.
Author
Erion Plaku, Amarda Shehu
Remarks
The file is opened in ios_base::out mode by default.
Referenced by ~Writer().
virtual std::ostream& Antipatrea::Writer::Print (std::ostream & out) const pure virtual
Write to the output stream.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::Scene2D, Antipatrea::SamplingBasedPlanner, Antipatrea::PlannerSolution, Antipatrea::Params, and Antipatrea::Stats.
Referenced by ~Writer().
The documentation for this class was generated from the following file:
Writer.hpp