Antipatrea::CfgProjector Class Reference
Antipatrea::CfgProjector Class Reference abstract
Motion-planning component for managing and defining configuration projections.
#include <CfgProjector.hpp>
Public Member Functions
CfgProjector (const int dim=0)
virtual ~CfgProjector (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void Project (Cfg &cfg, double proj[])=0
Compute the configuration projection.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Allocator
Allocator (const int dim=0)
virtual ~Allocator (void)
virtual void SetDim (const int dim)
Set dimension.
virtual int GetDim (void) const
Get the dimension.
virtual double * NewValues (void) const
Allocate memory for the array.
virtual void DeleteValues (double values[]) const
Delete the memory allocated to the array.
virtual void CopyValues (double dest[], const double src[]) const
Copy the values from src to dest.
virtual double * CopyValues (const double values[]) const
Return a copy of the array.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::Allocator
int m_dim
Array dimension.
Detailed Description
Motion-planning component for managing and defining configuration projections.
Author
Erion Plaku, Amarda Shehu
Remarks
Projections are usually over a low-dimensional (Euclidean) space.
The user should set the projection dimension.
Constructor & Destructor Documentation
Antipatrea::CfgProjector::CfgProjector (const int dim = 0) inline
virtual Antipatrea::CfgProjector::~CfgProjector (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgProjector::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
Reimplemented in Antipatrea::CfgProjectorDeltaR, and Antipatrea::CfgProjectorUSR.
References Antipatrea::Component::CheckSetup(), and Antipatrea::Allocator::GetDim().
Referenced by Antipatrea::CfgProjectorChain2D::CheckSetup(), Antipatrea::CfgProjectorUSR::CheckSetup(), and Antipatrea::CfgProjectorDeltaR::CheckSetup().
virtual void Antipatrea::CfgProjector::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Reimplemented in Antipatrea::CfgProjectorDeltaR, Antipatrea::CfgProjectorUSR, and Antipatrea::CfgProjectorChain2D.
References Antipatrea::Allocator::GetDim(), Antipatrea::Object::Info(), and Antipatrea::Logger::m_out.
Referenced by Antipatrea::CfgProjectorChain2D::Info(), Antipatrea::CfgProjectorUSR::Info(), and Antipatrea::CfgProjectorDeltaR::Info().
virtual void Antipatrea::CfgProjector::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes Component::SetupFromParams(params).
It then sets the projection dimension (keyword defined in Constants::KW_Dim).
It uses the parameter group associated with the keyword Constants::KW_CfgProjector.
The parameter value can be specified in a text file as, for example, CfgProjector { Dim 2 }
Reimplemented from Antipatrea::Component.
Reimplemented in Antipatrea::CfgProjectorDeltaR, and Antipatrea::CfgProjectorUSR.
References Antipatrea::ClassContainer(), Antipatrea::Params::GetData(), Antipatrea::Allocator::GetDim(), Antipatrea::Constants::KW_CfgProjector, Antipatrea::Constants::KW_Dim, Project(), Antipatrea::Allocator::SetDim(), and Antipatrea::Component::SetupFromParams().
virtual void Antipatrea::CfgProjector::Project (Cfg & cfg, double proj[]) pure virtual
Compute the configuration projection.
Author
Erion Plaku, Amarda Shehu
Remarks
The function assumes that proj has been properly allocated (using CfgProjector::NewValues())
Implemented in Antipatrea::CfgProjectorDeltaR, Antipatrea::CfgProjectorUSR, Antipatrea::CfgProjectorChain2D, and Antipatrea::CfgProjectorPoint2D.
Referenced by SetupFromParams().
The documentation for this class was generated from the following file:
CfgProjector.hpp