Antipatrea::CfgManager Class Reference
Antipatrea::CfgManager Class Reference
Motion-planning component for managing configurations.
#include <CfgManager.hpp>
Public Member Functions
CfgManager (const int dim=0)
virtual ~CfgManager (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual Cfg * NewCfg (void) const
Create a new configuration and allocate memory for the configuration values.
virtual void DeleteCfg (Cfg *cfg)
Delete the configuration.
virtual void CopyCfg (Cfg &cfgDest, const Cfg &cfgSrc) const
Copy the configuration values from cfgSrc to cfgDest.
virtual Cfg * CopyCfg (const Cfg &cfgSrc) const
Return a copy of the configuration.
virtual std::ostream & PrintCfg (std::ostream &out, const Cfg &cfg) const
Print the configuration to the output stream.
virtual std::istream & ReadCfg (std::istream &in, Cfg &cfg) const
Read the configuration from the input stream.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Allocator
Allocator (const int dim=0)
virtual ~Allocator (void)
virtual void SetDim (const int dim)
Set dimension.
virtual int GetDim (void) const
Get the dimension.
virtual double * NewValues (void) const
Allocate memory for the array.
virtual void DeleteValues (double values[]) const
Delete the memory allocated to the array.
virtual void CopyValues (double dest[], const double src[]) const
Copy the values from src to dest.
virtual double * CopyValues (const double values[]) const
Return a copy of the array.
Protected Attributes
int m_dim
Configuration dimension.
Protected Attributes inherited from Antipatrea::Allocator
int m_dim
Array dimension.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Motion-planning component for managing configurations.
Author
Erion Plaku, Amarda Shehu
Remarks
This class provides functionality to create, delete, copy, read, or print configurations.
The user should set the configuration dimension.
Why design it this way? Consider the alternative where Cfg allocates itself. Then, inside a planner/component one could write Cfg *cfg = new Cfg() to create a new configuration. This is problematic however if someone extends the configuration class, e.g., class MyCfg : public Cfg and wants to use MyCfg instead of Cfg for planning purposes. By using CfgManager, such issue is avoided since one would write a class class MyCfgManager : public CfgManager, set the allocator for the planner/component to an instance of MyCfgManager, and then write inside the planner/component Cfg *cfg = GetCfgManager()->NewCfg() .
Constructor & Destructor Documentation
CfgManager()
Antipatrea::CfgManager::CfgManager (const int dim = 0) inline
~CfgManager()
virtual Antipatrea::CfgManager::~CfgManager (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgManager::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup(), and Antipatrea::Allocator::GetDim().
Info()
virtual void Antipatrea::CfgManager::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Cfg::ENERGY_UNDEFINED, Antipatrea::Allocator::GetDim(), Antipatrea::Object::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::CfgManager::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes Component::SetupFromParams(params).
It then sets the configuration dimension (keyword Constants::KW_Dim).
It uses the parameter group associated with the keyword Constants::KW_CfgManager.
The parameter value can be specified in a text file as, for example, CfgManager { Dim 2 }
Reimplemented from Antipatrea::Component.
References Antipatrea::Params::GetData(), Antipatrea::Allocator::GetDim(), Antipatrea::Constants::KW_CfgManager, Antipatrea::Constants::KW_Dim, Antipatrea::Allocator::SetDim(), and Antipatrea::Component::SetupFromParams().
NewCfg()
virtual Cfg* Antipatrea::CfgManager::NewCfg (void) const inline virtual
Create a new configuration and allocate memory for the configuration values.
Author
Erion Plaku, Amarda Shehu
References Antipatrea::Allocator::NewValues(), and Antipatrea::Cfg::SetValues().
Referenced by CopyCfg().
DeleteCfg()
virtual void Antipatrea::CfgManager::DeleteCfg (Cfg * cfg) inline virtual
Delete the configuration.
Author
Erion Plaku, Amarda Shehu
CopyCfg() [1/2]
virtual void Antipatrea::CfgManager::CopyCfg (Cfg & cfgDest, const Cfg & cfgSrc) const inline virtual
Copy the configuration values from cfgSrc to cfgDest.
Author
Erion Plaku, Amarda Shehu
Remarks
It creates a deep copy of the values of cfgSrc, not just pointer assignment.
It also copies the energy value from cfgSrc to cfgDest
References Antipatrea::Allocator::CopyValues(), Antipatrea::Cfg::GetEnergy(), Antipatrea::Cfg::GetValues(), and Antipatrea::Cfg::SetEnergy().
Referenced by CopyCfg().
CopyCfg() [2/2]
virtual Cfg* Antipatrea::CfgManager::CopyCfg (const Cfg & cfgSrc) const inline virtual
Return a copy of the configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
It creates a deep copy of the values of cfgSrc, not just pointer assignment.
It also copies the energy value from cfgSrc to cfgDest
References CopyCfg(), NewCfg(), PrintCfg(), and ReadCfg().
PrintCfg()
virtual std::ostream& Antipatrea::CfgManager::PrintCfg (std::ostream & out, const Cfg & cfg) const virtual
Print the configuration to the output stream.
Author
Erion Plaku, Amarda Shehu
Remarks
It first prints the configuration values and then the energy.
Referenced by CopyCfg().
ReadCfg()
virtual std::istream& Antipatrea::CfgManager::ReadCfg (std::istream & in, Cfg & cfg) const virtual
Read the configuration from the input stream.
Author
Erion Plaku, Amarda Shehu
Remarks
It first reads the configuration values and then the energy.
Referenced by CopyCfg().
Member Data Documentation
m_dim
int Antipatrea::CfgManager::m_dim protected
Configuration dimension.
Author
Erion Plaku, Amarda Shehu
The documentation for this class was generated from the following file:
CfgManager.hpp