Antipatrea::CfgSamplerPoint2D Class Reference
Antipatrea::CfgSamplerPoint2D Class Reference
Sample a point uniformly at random inside the bounding box of the scene.
#include <CfgSamplerPoint2D.hpp>
Public Member Functions
CfgSamplerPoint2D (void)
virtual ~CfgSamplerPoint2D (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual bool Sample (Cfg &cfg)
Sample a point uniformly at random inside the bounding box of the scene.
Public Member Functions inherited from Antipatrea::CfgSampler
CfgSampler (void)
virtual ~CfgSampler (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Sample a point uniformly at random inside the bounding box of the scene.
Author
Erion Plaku, Amarda Shehu
Remarks
CfgSamplerPoint2D needs access to Scene2D.
Constructor & Destructor Documentation
CfgSamplerPoint2D()
Antipatrea::CfgSamplerPoint2D::CfgSamplerPoint2D (void) inline
~CfgSamplerPoint2D()
virtual Antipatrea::CfgSamplerPoint2D::~CfgSamplerPoint2D (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgSamplerPoint2D::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgSamplerPoint2D::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
Sample()
virtual bool Antipatrea::CfgSamplerPoint2D::Sample (Cfg & cfg) inline virtual
Sample a point uniformly at random inside the bounding box of the scene.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgSampler.
References Antipatrea::ClassContainer(), Antipatrea::Cfg::GetValues(), Antipatrea::RandomUniformReal(), and Antipatrea::Cfg::SetValues().
The documentation for this class was generated from the following file:
CfgSamplerPoint2D.hpp