Antipatrea::SetupChain2D Class Reference
Antipatrea::SetupChain2D Class Reference
Setup the planning problem for a robot kinematic chain operating in a 2D scene as well as the planner and its components.
#include <SetupChain2D.hpp>
Public Member Functions
SetupChain2D (void)
virtual ~SetupChain2D (void)
virtual const Chain2D * GetChain2D (void) const
Get a pointer to the kinematic chain.
virtual Chain2D * GetChain2D (void)
Get a pointer to the kinematic chain.
virtual void Prepare (Params &params)
Create new instances, setup pointers, and setup the parameters.
Public Member Functions inherited from Antipatrea::Setup2D
Setup2D (void)
virtual ~Setup2D (void)
Public Member Functions inherited from Antipatrea::Setup
Setup (void)
virtual ~Setup (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void Test (void)
Write whatever you would like for testing purposes.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void NewCfgForwardKinematics (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgProjector (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointersCfgAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgProjector (void)
Setup the pointers for the indicated component.
Protected Member Functions inherited from Antipatrea::Setup2D
virtual void NewInstances (Params &params)
Create all the new instances.
virtual void NewScene2D (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointers (void)
Setup the component pointers.
virtual void SetupPointersScene2D (void)
Setup the pointers for the indicated component.
virtual void FixGrid (void)
Fix grid dimensions.
Protected Member Functions inherited from Antipatrea::Setup
virtual void OnNewInstance (Component *const comp)
Add the instance to the set of component instances.
virtual void NewGoalAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgManager (Params &params)
Create a new instance for the indicated component.
virtual void NewSignedDistanceBetweenTwoValues (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgDistance (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgEnergyEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgImprover (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgSampler (Params &params)
Create a new instance for the indicated component.
virtual void NewEdgeCostEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgOffspringGenerator (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerProblem (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerSolution (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerGraph (Params &params)
Create a new instance for the indicated component.
virtual void NewSamplingBasedPlanner (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointersComponent (Component *const comp)
Setup the pointers for the indicated component.
virtual void SetupPointersGoalAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgManager (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgDistance (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSignedDistanceBetweenTwoValues (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgEnergyEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgForwardKinematics (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgImprover (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgSampler (void)
Setup the pointers for the indicated component.
virtual void SetupPointersEdgeCostEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgOffspringGenerator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerProblem (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerSolution (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerGraph (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSamplingBasedPlanner (void)
Setup the pointers for the indicated component.
virtual void SetupFromParams (Params &params)
Setup the paramater values of each component instance using the user-provided parameters.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::Setup
std::vector< Component * > m_components
Component instances.
Detailed Description
Setup the planning problem for a robot kinematic chain operating in a 2D scene as well as the planner and its components.
Author
Erion Plaku, Amarda Shehu
Remarks
Setup creates instances of the planning components based on keywords provided by the user or default settings when the user does not provide any keywords.
Only one instance per class is created.
After creating the components, Setup sets the pointers so that components/planners that depend on, for example, CfgDistance will have the CfgDistance pointer set to the CfgDistance instance created in the first step.
After setting the pointers, Setup iterates over all the instances that were created in step 1, and calls the function SetupFromParams in order to set the parameter values for each instance.
Constructor & Destructor Documentation
SetupChain2D()
Antipatrea::SetupChain2D::SetupChain2D (void) inline
~SetupChain2D()
virtual Antipatrea::SetupChain2D::~SetupChain2D (void) inline virtual
Member Function Documentation
GetChain2D() [1/2]
virtual const Chain2D* Antipatrea::SetupChain2D::GetChain2D (void) const inline virtual
Get a pointer to the kinematic chain.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersCfgAcceptor(), and SetupPointersCfgProjector().
GetChain2D() [2/2]
virtual Chain2D* Antipatrea::SetupChain2D::GetChain2D (void) inline virtual
Get a pointer to the kinematic chain.
Author
Erion Plaku, Amarda Shehu
References Prepare().
Prepare()
virtual void Antipatrea::SetupChain2D::Prepare (Params & params) virtual
Create new instances, setup pointers, and setup the parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Do everything that needs to be done in order to setup the planning problem, the planner, and its components.
Implements Antipatrea::Setup.
Referenced by GetChain2D().
NewCfgForwardKinematics()
virtual void Antipatrea::SetupChain2D::NewCfgForwardKinematics (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Setup::OnNewInstance().
NewCfgAcceptor()
virtual void Antipatrea::SetupChain2D::NewCfgAcceptor (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Setup::OnNewInstance().
NewCfgProjector()
virtual void Antipatrea::SetupChain2D::NewCfgProjector (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Setup::OnNewInstance().
SetupPointersCfgAcceptor()
virtual void Antipatrea::SetupChain2D::SetupPointersCfgAcceptor (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetChain2D(), and Antipatrea::Setup::SetupPointersCfgAcceptor().
SetupPointersCfgProjector()
virtual void Antipatrea::SetupChain2D::SetupPointersCfgProjector (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Setup.
References GetChain2D(), and Antipatrea::Setup::SetupPointersCfgProjector().
The documentation for this class was generated from the following file:
SetupChain2D.hpp