Antipatrea::PlannerSolution Class Reference
Antipatrea::PlannerSolution Class Reference
Data structure to store the solution obtained by a motion planner.
#include <PlannerSolution.hpp>
Public Member Functions
PlannerSolution (void)
virtual ~PlannerSolution (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void Clear (void)
Set the cost to zero, delete any previously allocated memory, and empty the sequence of vertices and configurations.
virtual void ClearCfgs (void)
Delete any previously allocated memory and empty the sequence of configurations.
virtual const std::vector< int > * GetVertexSequence (void) const
Get the pointer to the vertex sequence.
virtual std::vector< int > * GetVertexSequence (void)
Get the pointer to the vertex sequence.
virtual double GetCost (void) const
Get the overall cost of the solution.
virtual void SetCost (const double cost)
Set the overall cost of the solution.
virtual int GetNrCfgs (void) const
Get the number of configurations.
virtual const Cfg * GetCfg (const int i) const
Get a pointer to the i-th configuration.
virtual Cfg * GetCfg (const int i)
Get a pointer to the i-th configuration.
virtual void AddCfg (Cfg *const cfg)
Add a configuration to the sequence.
virtual std::ostream & Print (std::ostream &out) const
Print the cost, sequence of vertices, and sequence of configurations.
virtual std::istream & Read (std::istream &in)
Read the cost, sequence of vertices, and sequence of configurations.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Protected Attributes
std::vector< int > m_vids
Sequence of vertices making up the solution.
double m_cost
Solution cost.
std::vector< Cfg * > m_cfgs
Sequence of configurations making up the solution.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Detailed Description
Data structure to store the solution obtained by a motion planner.
Author
Erion Plaku, Amarda Shehu
Remarks
Solution keeps track of the sequence of vertices in the planner graph, overall cost, and the sequence of configurations.
The sequence of configurations, m_cfgs may not necessarily correspond to the sequence of vertices, m_vids. In fact, m_cfgs could contain additional configurations, which would come from discretizing the paths associated with the edges in the solution. In other words, when considering the edge (m_vids[i], m_vids[i+1]), the path from m_vids[i] to m_vids[i+1] is discretized according to a time step and the resulting configurations are added to m_cfgs.
This class requires access to CfgManager to print/read configurations.
Constructor & Destructor Documentation
PlannerSolution()
Antipatrea::PlannerSolution::PlannerSolution (void) inline
~PlannerSolution()
virtual Antipatrea::PlannerSolution::~PlannerSolution (void) inline virtual
References Clear().
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::PlannerSolution::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::PlannerSolution::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
Clear()
virtual void Antipatrea::PlannerSolution::Clear (void) inline virtual
Set the cost to zero, delete any previously allocated memory, and empty the sequence of vertices and configurations.
Author
Erion Plaku, Amarda Shehu
References ClearCfgs(), m_cost, and m_vids.
Referenced by ~PlannerSolution().
ClearCfgs()
virtual void Antipatrea::PlannerSolution::ClearCfgs (void) inline virtual
Delete any previously allocated memory and empty the sequence of configurations.
Author
Erion Plaku, Amarda Shehu
References m_cfgs.
Referenced by Clear().
GetVertexSequence() [1/2]
virtual const std::vector<int>* Antipatrea::PlannerSolution::GetVertexSequence (void) const inline virtual
Get the pointer to the vertex sequence.
Author
Erion Plaku, Amarda Shehu
References m_vids.
GetVertexSequence() [2/2]
virtual std::vector<int>* Antipatrea::PlannerSolution::GetVertexSequence (void) inline virtual
Get the pointer to the vertex sequence.
Author
Erion Plaku, Amarda Shehu
References m_vids.
GetCost()
virtual double Antipatrea::PlannerSolution::GetCost (void) const inline virtual
Get the overall cost of the solution.
Author
Erion Plaku, Amarda Shehu
References m_cost.
SetCost()
virtual void Antipatrea::PlannerSolution::SetCost (const double cost) inline virtual
Set the overall cost of the solution.
Author
Erion Plaku, Amarda Shehu
References m_cost.
GetNrCfgs()
virtual int Antipatrea::PlannerSolution::GetNrCfgs (void) const inline virtual
Get the number of configurations.
Author
Erion Plaku, Amarda Shehu
References m_cfgs.
GetCfg() [1/2]
virtual const Cfg* Antipatrea::PlannerSolution::GetCfg (const int i) const inline virtual
Get a pointer to the i-th configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
Index i should be between 0 and GetNrCfgs()-1.
The function does not check whether i is within range.
References m_cfgs.
GetCfg() [2/2]
virtual Cfg* Antipatrea::PlannerSolution::GetCfg (const int i) inline virtual
Get a pointer to the i-th configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
Index i should be between 0 and GetNrCfgs()-1.
The function does not check whether i is within range.
References m_cfgs.
AddCfg()
virtual void Antipatrea::PlannerSolution::AddCfg (Cfg *const cfg) inline virtual
Add a configuration to the sequence.
Author
Erion Plaku, Amarda Shehu
References m_cfgs, Print(), and Read().
Print()
virtual std::ostream& Antipatrea::PlannerSolution::Print (std::ostream & out) const virtual
Print the cost, sequence of vertices, and sequence of configurations.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Writer.
Referenced by AddCfg().
Read()
virtual std::istream& Antipatrea::PlannerSolution::Read (std::istream & in) virtual
Read the cost, sequence of vertices, and sequence of configurations.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Reader.
Referenced by AddCfg().
Member Data Documentation
m_vids
std::vector<int> Antipatrea::PlannerSolution::m_vids protected
Sequence of vertices making up the solution.
Author
Erion Plaku, Amarda Shehu
Referenced by Clear(), and GetVertexSequence().
m_cost
double Antipatrea::PlannerSolution::m_cost protected
Solution cost.
Author
Erion Plaku, Amarda Shehu
Referenced by Clear(), GetCost(), and SetCost().
m_cfgs
std::vector<Cfg*> Antipatrea::PlannerSolution::m_cfgs protected
Sequence of configurations making up the solution.
Author
Erion Plaku, Amarda Shehu
Remarks
Referenced by AddCfg(), ClearCfgs(), GetCfg(), and GetNrCfgs().
The documentation for this class was generated from the following file:
PlannerSolution.hpp