Antipatrea::Component Class Reference
Antipatrea::Component Class Reference
Base class for each motion-planning component.
#include <Component.hpp>
Public Member Functions
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Base class for each motion-planning component.
Author
Erion Plaku, Amarda Shehu
Remarks
Each motion-planning component should extend this class and provide additional functionality as needed.
Constructor & Destructor Documentation
Component()
Antipatrea::Component::Component (void) inline
~Component()
virtual Antipatrea::Component::~Component (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::Component::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented in Antipatrea::CfgOffspringGeneratorRosetta, Antipatrea::Setup, Antipatrea::PlannerSolution, Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation, Antipatrea::CfgProjector, Antipatrea::CfgDistanceLp, Antipatrea::CfgManager, Antipatrea::CfgProjectorDeltaR, Antipatrea::CfgDistanceAtomRMSD, Antipatrea::MolecularStructureRosetta, Antipatrea::CfgOffspringGenerator, Antipatrea::CfgProjectorUSREnergy, Antipatrea::CfgEnergyEvaluatorRosetta, Antipatrea::CfgImproverRosetta, Antipatrea::CfgSamplerRosetta, and Antipatrea::CfgUniformSamplerInJointSpace.
Referenced by Antipatrea::CfgSamplerPoint2D::CheckSetup(), Antipatrea::CfgUniformSamplerInJointSpace::CheckSetup(), Antipatrea::EdgeCostEvaluatorBasedOnDistance::CheckSetup(), Antipatrea::CfgEnergyEvaluatorRosetta::CheckSetup(), Antipatrea::EdgeCostEvaluatorBasedOnMW::CheckSetup(), Antipatrea::CfgImproverRosetta::CheckSetup(), Antipatrea::CfgAcceptorPoint2D::CheckSetup(), Antipatrea::CfgSamplerRosetta::CheckSetup(), Antipatrea::CfgOffspringGenerator::CheckSetup(), Antipatrea::CfgAcceptorChain2D::CheckSetup(), Antipatrea::Planner::CheckSetup(), Antipatrea::CfgAcceptorBasedOnEnergy::CheckSetup(), Antipatrea::CfgDistanceAtomRMSD::CheckSetup(), Antipatrea::PlannerProblem::CheckSetup(), Antipatrea::EdgeCostEvaluatorBasedOnEnergy::CheckSetup(), Antipatrea::CfgManager::CheckSetup(), Antipatrea::CfgDistanceLp::CheckSetup(), Antipatrea::CfgProjector::CheckSetup(), Antipatrea::PlannerSolution::CheckSetup(), Antipatrea::CfgAcceptorBasedOnFixedMMC::CheckSetup(), Antipatrea::CfgAcceptorBasedOnMMC::CheckSetup(), and Antipatrea::CfgAcceptorBasedOnDistance::CheckSetup().
SetupFromParams()
virtual void Antipatrea::Component::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
For each parameter value of the component, use the associated keyword to get the corresponding paramater value from params.
Reimplemented in Antipatrea::CfgOffspringGeneratorRosetta, Antipatrea::Setup, Antipatrea::Sprint, Antipatrea::SamplingBasedPlanner, Antipatrea::EST, Antipatrea::CfgAcceptorBasedOnDistance, Antipatrea::FELTR, Antipatrea::PGT, Antipatrea::PRM, Antipatrea::CfgAcceptor, Antipatrea::CfgAcceptorBasedOnMMC, Antipatrea::CfgProjector, Antipatrea::TreeSamplingBasedPlanner, Antipatrea::CfgAcceptorBasedOnFixedMMC, Antipatrea::CfgProjectorDeltaR, Antipatrea::CfgDistanceLp, Antipatrea::CfgProjectorUSREnergy, Antipatrea::CfgManager, Antipatrea::CfgAcceptorBasedOnEnergy, Antipatrea::CfgOffspringGeneratorByGaussianPerturbation, Antipatrea::CfgDistanceAtomRMSD, Antipatrea::CfgOffspringGenerator, Antipatrea::Scene2D, Antipatrea::CfgEnergyEvaluatorRosetta, Antipatrea::CfgImproverRosetta, Antipatrea::CfgSamplerRosetta, Antipatrea::MolecularStructureRosetta, Antipatrea::Chain2D, and Antipatrea::CfgOffspringGeneratorRosettaWBias.
Referenced by Antipatrea::CfgOffspringGenerator::SetupFromParams(), Antipatrea::CfgDistanceAtomRMSD::SetupFromParams(), Antipatrea::CfgManager::SetupFromParams(), Antipatrea::CfgDistanceLp::SetupFromParams(), Antipatrea::CfgProjector::SetupFromParams(), Antipatrea::CfgAcceptor::SetupFromParams(), and Antipatrea::SamplingBasedPlanner::SetupFromParams().
The documentation for this class was generated from the following file:
Component.hpp