Antipatrea::CfgOffspringGeneratorByGaussianPerturbation Class Reference
Antipatrea::CfgOffspringGeneratorByGaussianPerturbation Class Reference
Generate an offspring configuration near the parent configuration by perturbing one or more values.
#include <CfgOffspringGeneratorByGaussianPerturbation.hpp>
Public Member Functions
CfgOffspringGeneratorByGaussianPerturbation (void)
virtual ~CfgOffspringGeneratorByGaussianPerturbation (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual bool GetConsecutive (void) const
Indicate whether the values that are perturbed during the offspring generation should be consecutive.
virtual int GetMinNrValuesToPerturb (void) const
Get the minimum number of values that should be perturbed when generating the offspring.
virtual int GetMaxNrValuesToPerturb (void) const
Get the maximum number of values that should be perturbed when generating the offspring.
virtual void SetConsecutive (const bool consecutive)
Set the falg to indicate whether the values that are perturbed during the offspring generation should be consecutive.
virtual void SetMinNrValuesToPerturb (const int n)
Set the minimum number of values that should be perturbed when generating the offspring.
virtual void SetMaxNrValuesToPerturb (const int n)
Set the maximum number of values that should be perturbed when generating the offspring.
virtual void GenerateOffspringCfg (Cfg &cfg)
Generate an offspring configuration near the parent configuration by perturbing one or more values.
Public Member Functions inherited from Antipatrea::CfgOffspringGenerator
CfgOffspringGenerator (void)
virtual ~CfgOffspringGenerator (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual const Cfg * GetParentCfg (void) const
Get the pointer to the parent configuration.
virtual void SetParentCfg (const Cfg *const cfgParent)
Set the pointer to the parent configuration.
virtual double GetStep (void) const
Get the step size used for guiding the offspring generation.
virtual void SetStep (const double step)
Get the step size used for guiding the offspring generation.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
bool m_consecutive
Indicate whether the perturbed values should be consecutive.
int m_minNrValuesToPerturb
Minimum number of values that should be perturbed.
int m_maxNrValuesToPerturb
Maximum number of values that should be perturbed.
Protected Attributes inherited from Antipatrea::CfgOffspringGenerator
const Cfg * m_cfgParent
Pointer to the parent configuration.
double m_step
Step size to guide the offspring generation.
bool m_verboseFlag
Verbosity Flag for all offspring generators.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Generate an offspring configuration near the parent configuration by perturbing one or more values.
Author
Erion Plaku, Amarda Shehu
Remarks
The parameter, m_step, is interpreted here as the standard deviation of the Gaussian perturbation.
Other parameters (m_minNrValuesToPerturb, m_maxNrValuesToPerturb, m_consecutive) are used to decide the minimum/maximum number of values to be perturbed and whether the perturbed values should be consecutive.
The offspring generator first selects the number of values to be perturbed (uniformly at random from min/max values).
If the consecutive flag is set to true, the start position is selected uniformly at random (from the applicable range) and the selected number of values are perturbed using a Gaussian distribution centered around the parent cfg.
If the consecutive flag is set to false, a subset is selected uniformly at random (from the applicable range) and the values in the subset are perturbed using a Gaussian distribution centered around the parent cfg.
Constructor & Destructor Documentation
CfgOffspringGeneratorByGaussianPerturbation()
Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::CfgOffspringGeneratorByGaussianPerturbation (void) inline
~CfgOffspringGeneratorByGaussianPerturbation()
virtual Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::~CfgOffspringGeneratorByGaussianPerturbation (void) inline virtual
Member Function Documentation
Info()
virtual void Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgOffspringGenerator.
References GetConsecutive(), GetMaxNrValuesToPerturb(), GetMinNrValuesToPerturb(), Antipatrea::CfgOffspringGenerator::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes CfgOffspringGenerator::SetupFromParams(params).
It then sets the minimum number of values to perturb, maximum number of values to perturb, and whether the values to be perturbed should be in consecutive order (keywords Constants::KW_Consecutive, Constants::KW_MinNrValuesToPerturb, Constants::KW_MaxNrValuesToPerturb).
It uses the parameter group associated with the keyword Constants::KW_CfgOffspringGeneratorByGaussianPerturbation.
The parameter values can be specified in a text file as, for example, CfgOffspringGeneratorByGaussianPerturbation { Consecutive false MinNrValuesToPerturb 1 MaxNrValuesToPerturb 100000 }
Reimplemented from Antipatrea::CfgOffspringGenerator.
References GetConsecutive(), Antipatrea::Params::GetData(), GetMaxNrValuesToPerturb(), GetMinNrValuesToPerturb(), Antipatrea::Constants::KW_CfgOffspringGeneratorByGaussianPerturbation, Antipatrea::Constants::KW_Consecutive, Antipatrea::Constants::KW_MaxNrValuesToPerturb, Antipatrea::Constants::KW_MinNrValuesToPerturb, SetConsecutive(), SetMaxNrValuesToPerturb(), SetMinNrValuesToPerturb(), and Antipatrea::CfgOffspringGenerator::SetupFromParams().
GetConsecutive()
virtual bool Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::GetConsecutive (void) const inline virtual
Indicate whether the values that are perturbed during the offspring generation should be consecutive.
Author
Erion Plaku, Amarda Shehu
References m_consecutive.
Referenced by Info(), and SetupFromParams().
GetMinNrValuesToPerturb()
virtual int Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::GetMinNrValuesToPerturb (void) const inline virtual
Get the minimum number of values that should be perturbed when generating the offspring.
Author
Erion Plaku, Amarda Shehu
References m_minNrValuesToPerturb.
Referenced by Info(), and SetupFromParams().
GetMaxNrValuesToPerturb()
virtual int Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::GetMaxNrValuesToPerturb (void) const inline virtual
Get the maximum number of values that should be perturbed when generating the offspring.
Author
Erion Plaku, Amarda Shehu
Remarks
This value is capped to the number of configuration dimensions when used even when the user initially sets it to a larger number.
References m_maxNrValuesToPerturb.
Referenced by Info(), and SetupFromParams().
SetConsecutive()
virtual void Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetConsecutive (const bool consecutive) inline virtual
Set the falg to indicate whether the values that are perturbed during the offspring generation should be consecutive.
Author
Erion Plaku, Amarda Shehu
References m_consecutive.
Referenced by SetupFromParams().
SetMinNrValuesToPerturb()
virtual void Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetMinNrValuesToPerturb (const int n) inline virtual
Set the minimum number of values that should be perturbed when generating the offspring.
Author
Erion Plaku, Amarda Shehu
References m_minNrValuesToPerturb.
Referenced by SetupFromParams().
SetMaxNrValuesToPerturb()
virtual void Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetMaxNrValuesToPerturb (const int n) inline virtual
Set the maximum number of values that should be perturbed when generating the offspring.
Author
Erion Plaku, Amarda Shehu
Remarks
This value is capped to the number of configuration dimensions when used even when the user initially sets it to a larger number.
References GenerateOffspringCfg(), and m_maxNrValuesToPerturb.
Referenced by SetupFromParams().
GenerateOffspringCfg()
virtual void Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::GenerateOffspringCfg (Cfg & cfg) virtual
Generate an offspring configuration near the parent configuration by perturbing one or more values.
Author
Erion Plaku, Amarda Shehu
Remarks
The parameter, m_step, is interpreted here as the standard deviation of the Gaussian perturbation.
The offspring generator first selects the number of values to be perturbed (uniformly at random from min/max values).
If the consecutive flag is set to true, the start position is selected uniformly at random (from the applicable range) and the selected number of values are perturbed using a Gaussian distribution centered around the parent cfg.
If the consecutive flag is set to false, a subset is selected uniformly at random (from the applicable range) and the values in the subset are perturbed using a Gaussian distribution centered around the parent cfg.
Implements Antipatrea::CfgOffspringGenerator.
Referenced by SetMaxNrValuesToPerturb().
Member Data Documentation
m_consecutive
bool Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::m_consecutive protected
Indicate whether the perturbed values should be consecutive.
Author
Erion Plaku, Amarda Shehu
Referenced by GetConsecutive(), and SetConsecutive().
m_minNrValuesToPerturb
int Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::m_minNrValuesToPerturb protected
Minimum number of values that should be perturbed.
Author
Erion Plaku, Amarda Shehu
Referenced by GetMinNrValuesToPerturb(), and SetMinNrValuesToPerturb().
m_maxNrValuesToPerturb
int Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::m_maxNrValuesToPerturb protected
Maximum number of values that should be perturbed.
Author
Erion Plaku, Amarda Shehu
Remarks
This value is capped to the number of configuration dimensions when used even when the user initially sets it to a larger number.
Referenced by GetMaxNrValuesToPerturb(), and SetMaxNrValuesToPerturb().
The documentation for this class was generated from the following file:
CfgOffspringGeneratorByGaussianPerturbation.hpp