Antipatrea::CfgAcceptorBasedOnDistance Class Reference
Antipatrea::CfgAcceptorBasedOnDistance Class Reference
Motion-planning component which accepts a configuration only if it is within a user-defined distance from a target/goal configuration.
#include <CfgAcceptorBasedOnDistance.hpp>
Public Member Functions
CfgAcceptorBasedOnDistance (void)
virtual ~CfgAcceptorBasedOnDistance (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual Cfg * GetAnAcceptableCfg (void)
Returns a pointer to the target/goal configuration.
void CheckQueue (Cfg &cfg, double dist)
Checks the priority queue so that it keeps the m_closeCfgsToKeep closest cfgs to the goal.
virtual bool IsAcceptable (Cfg &cfg)
Returns true iff the distance between cfg and the target cfg is no more than a user-defined threshold.
virtual Cfg * GetClosest (void)
Get pointer to target/goal cfg.
virtual Cfg * GetTargetCfg (void)
virtual const Cfg * GetTargetCfg (void) const
Get pointer to target/goal cfg.
virtual void SetTargetCfg (Cfg *const cfg)
Set pointer to target/goal cfg.
virtual double GetDistanceThreshold (void) const
Name says it all.
virtual double GetMinDistanceAboveThresolhold () const
std::vector< Cfg * > GetNClosest ()
Empties the priority queue and returns a vector of cfg pointers to these objects (furthest cfgs first, closest last).
virtual void SetDistanceThreshold (const double distanceThreshold)
Name says it all.
Public Member Functions inherited from Antipatrea::CfgAcceptor
CfgAcceptor (void)
virtual ~CfgAcceptor (void)
virtual bool IsUsedAsGoalAcceptor (void) const
Get the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void UseAsGoalAcceptor (const bool use)
Set the class purpose: goal acceptor (true) or configuration acceptor (false).
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
Cfg * m_cfgTarget
Pointer to target/goal cfg.
double m_distanceThreshold
User-defined distance threshold.
double m_minDistanceAboveThreshold
min distance that exceeded the threshold. Nice to show progress towards goal
Cfg * m_minDistanceCfg
std::priority_queue< qObj, std::vector< qObj >, CfgAcceptorBasedOnDistanceCompare > m_closeCfgs
priority queue to keep closest cfgs to goal so they can be reported at the end
unsigned int m_closeCfgsToKeep
Number of close objects to keep.
Protected Attributes inherited from Antipatrea::CfgAcceptor
bool m_useAsGoalAcceptor
Class purpose: goal acceptor (true) or configuration acceptor (false).
bool m_verboseFlag
flag to control verbosity
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Motion-planning component which accepts a configuration only if it is within a user-defined distance from a target/goal configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgDistance component in order to compute the distance between two configurations.
The user should also set the distance threshold.
Constructor & Destructor Documentation
CfgAcceptorBasedOnDistance()
Antipatrea::CfgAcceptorBasedOnDistance::CfgAcceptorBasedOnDistance (void) inline
References Antipatrea::Constants::VAL_CfgAcceptorBasedOnDistance_DistanceThreshold, and Antipatrea::Constants::VAL_GoalAcceptorBasedOnDistance_DistanceThreshold.
~CfgAcceptorBasedOnDistance()
virtual Antipatrea::CfgAcceptorBasedOnDistance::~CfgAcceptorBasedOnDistance (void) inline virtual
Author
Erion Plaku, Amarda Shehu
Remarks
It does not delete m_cfgTarget since it is not the one that allocates it.
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgAcceptorBasedOnDistance::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgAcceptorBasedOnDistance::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::CfgAcceptorBasedOnDistance::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes CfgAcceptor::SetupFromParams(params).
It then sets the distance threshold (keyword Constants::KW_DistanceThreshold).
When used as a goal acceptor, it uses the parameter group associated with the keyword Constants::KW_GoalAcceptorBasedOnDistance.
When used as general cfg acceptor, it uses the paramater group associated with the keyword Constants::KW_CfgAcceptorBasedOnDistance
The parameter value can be specified in a text file as, for example, CfgAcceptorBasedOnDistance { DistanceThreshold 0.5 } or GoalAcceptorBasedOnDistance { DistanceThreshold 0.01 }
Reimplemented from Antipatrea::CfgAcceptor.
References Antipatrea::Params::GetData(), Antipatrea::Constants::KW_CfgAcceptorBasedOnDistance, Antipatrea::Constants::KW_DistanceThreshold, Antipatrea::Constants::KW_GoalAcceptorBasedOnDistance, and Antipatrea::CfgAcceptor::SetupFromParams().
GetAnAcceptableCfg()
virtual Cfg* Antipatrea::CfgAcceptorBasedOnDistance::GetAnAcceptableCfg (void) inline virtual
Returns a pointer to the target/goal configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
The returned pointer should not be deleted since the function returns the address of a class variable. Deleting the pointer could cause memory issues.
Reimplemented from Antipatrea::CfgAcceptor.
CheckQueue()
void Antipatrea::CfgAcceptorBasedOnDistance::CheckQueue (Cfg & cfg, double dist) inline
Checks the priority queue so that it keeps the m_closeCfgsToKeep closest cfgs to the goal.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
IsAcceptable()
virtual bool Antipatrea::CfgAcceptorBasedOnDistance::IsAcceptable (Cfg & cfg) inline virtual
Returns true iff the distance between cfg and the target cfg is no more than a user-defined threshold.
Author
Erion Plaku, Amarda Shehu Kevin Molloy – mod – for a general exploration of the search space, a goal might not be defined. We avoid this computation when no target has been specified.
Implements Antipatrea::CfgAcceptor.
References exit(), and Antipatrea::Logger::m_out.
GetClosest()
virtual Cfg* Antipatrea::CfgAcceptorBasedOnDistance::GetClosest (void) inline virtual
Get pointer to target/goal cfg.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not perform a copy – just returns the pointer to target/goal cfg.
GetTargetCfg() [1/2]
virtual Cfg* Antipatrea::CfgAcceptorBasedOnDistance::GetTargetCfg (void) inline virtual
GetTargetCfg() [2/2]
virtual const Cfg* Antipatrea::CfgAcceptorBasedOnDistance::GetTargetCfg (void) const inline virtual
Get pointer to target/goal cfg.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not perform a copy – just returns the pointer to target/goal cfg.
SetTargetCfg()
virtual void Antipatrea::CfgAcceptorBasedOnDistance::SetTargetCfg (Cfg *const cfg) inline virtual
Set pointer to target/goal cfg.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not perform a copy – just pointer assignment.
GetDistanceThreshold()
virtual double Antipatrea::CfgAcceptorBasedOnDistance::GetDistanceThreshold (void) const inline virtual
Name says it all.
Author
Erion Plaku, Amarda Shehu
GetMinDistanceAboveThresolhold()
virtual double Antipatrea::CfgAcceptorBasedOnDistance::GetMinDistanceAboveThresolhold () const inline virtual
GetNClosest()
std::vector<Cfg *> Antipatrea::CfgAcceptorBasedOnDistance::GetNClosest () inline
Empties the priority queue and returns a vector of cfg pointers to these objects (furthest cfgs first, closest last).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References Antipatrea::Logger::m_out.
SetDistanceThreshold()
virtual void Antipatrea::CfgAcceptorBasedOnDistance::SetDistanceThreshold (const double distanceThreshold) inline virtual
Name says it all.
Author
Erion Plaku, Amarda Shehu
Member Data Documentation
m_cfgTarget
Cfg* Antipatrea::CfgAcceptorBasedOnDistance::m_cfgTarget protected
Pointer to target/goal cfg.
Author
Erion Plaku, Amarda Shehu
m_distanceThreshold
double Antipatrea::CfgAcceptorBasedOnDistance::m_distanceThreshold protected
User-defined distance threshold.
Author
Erion Plaku, Amarda Shehu
m_minDistanceAboveThreshold
double Antipatrea::CfgAcceptorBasedOnDistance::m_minDistanceAboveThreshold protected
min distance that exceeded the threshold. Nice to show progress towards goal
Author
Erion Plaku, Amarda Shehu
m_minDistanceCfg
Cfg* Antipatrea::CfgAcceptorBasedOnDistance::m_minDistanceCfg protected
m_closeCfgs
std::priority_queue<qObj,std::vector<qObj>,CfgAcceptorBasedOnDistanceCompare> Antipatrea::CfgAcceptorBasedOnDistance::m_closeCfgs protected
priority queue to keep closest cfgs to goal so they can be reported at the end
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_closeCfgsToKeep
unsigned int Antipatrea::CfgAcceptorBasedOnDistance::m_closeCfgsToKeep protected
Number of close objects to keep.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
The documentation for this class was generated from the following file:
CfgAcceptorBasedOnDistance.hpp