Antipatrea::DisjointSet Class Reference
Antipatrea::DisjointSet Class Reference
#include <DisjointSet.hpp>
Classes
struct Elem
Public Member Functions
DisjointSet (void)
~DisjointSet (void)
int GetNrComponents (void) const
Elem * Make (void)
Elem * Find (Elem *elem)
void Join (Elem *x, Elem *y)
bool Same (Elem *x, Elem *y)
Protected Attributes
int m_nrComps
Constructor & Destructor Documentation
DisjointSet()
Antipatrea::DisjointSet::DisjointSet (void) inline
~DisjointSet()
Antipatrea::DisjointSet::~DisjointSet (void) inline
Member Function Documentation
GetNrComponents()
int Antipatrea::DisjointSet::GetNrComponents (void) const inline
References Find(), Join(), m_nrComps, and Make().
Make()
Elem* Antipatrea::DisjointSet::Make (void)
Referenced by Antipatrea::PlannerGraph::AddVertex(), and GetNrComponents().
Find()
Elem* Antipatrea::DisjointSet::Find (Elem * elem)
Referenced by GetNrComponents(), and Same().
Join()
void Antipatrea::DisjointSet::Join (Elem * x, Elem * y)
Referenced by GetNrComponents().
Same()
bool Antipatrea::DisjointSet::Same (Elem * x, Elem * y) inline
References Find().
Referenced by Antipatrea::PlannerGraph::AreVerticesPathConnected().
Member Data Documentation
m_nrComps
int Antipatrea::DisjointSet::m_nrComps protected
Referenced by GetNrComponents().
The documentation for this class was generated from the following file:
DisjointSet.hpp