Antipatrea::GCamera Class Reference
Antipatrea::GCamera Class Reference
#include <GCamera.hpp>
Public Member Functions
GCamera (void)
virtual ~GCamera (void)
virtual void SetupFromParams (Params &params)
void GetModelViewMatrixOpenGL (double *const m)
const double * GetEye (void) const
const double * GetCenter (void) const
const double * GetUpAxis (void) const
const double * GetRightAxis (void) const
const double * GetForwardAxis (void) const
void SetLookAt (const double eye_x, const double eye_y, const double eye_z, const double center_x, const double center_y, const double center_z, const double up_x, const double up_y, const double up_z)
void SetLookAtStandardPosition (void)
void MoveForward (const double d)
void MoveRight (const double d)
void MoveUp (const double d)
void Move (const double df, const double dr, const double du)
void RotateAtEye (const double *const R)
void RotateAtEye (const double r0, const double r1, const double r2, const double r3, const double r4, const double r5, const double r6, const double r7, const double r8)
void RotateAtCenter (const double *const R)
void RotateAtCenter (const double r0, const double r1, const double r2, const double r3, const double r4, const double r5, const double r6, const double r7, const double r8)
void RotateAtPoint (const double *const R, const double px, const double py, const double pz)
void RotateAtPoint (const double r0, const double r1, const double r2, const double r3, const double r4, const double r5, const double r6, const double r7, const double r8, const double px, const double py, const double pz)
void RotateAroundAxisAtEye (const double theta, const double vx, const double vy, const double vz)
void RotateAroundAxisAtCenter (const double theta, const double vx, const double vy, const double vz)
void RotateAroundAxisAtPoint (const double theta, const double vx, const double vy, const double vz, const double px, const double py, const double pz)
void RotateAroundRightAxisAtEye (const double theta)
void RotateAroundRightAxisAtCenter (const double theta)
void RotateAroundRightAxisAtPoint (const double theta, const double px, const double py, const double pz)
void RotateAroundUpAxisAtEye (const double theta)
void RotateAroundUpAxisAtCenter (const double theta)
void RotateAroundUpAxisAtPoint (const double theta, const double px, const double py, const double pz)
void RotateAroundForwardAxisAtEye (const double theta)
void RotateAroundForwardAxisAtCenter (const double theta)
void RotateAroundForwardAxisAtPoint (const double theta, const double px, const double py, const double pz)
void SetEyeCenterRightForward (const double eye[], const double center[], const double right[], const double forward[])
Protected Attributes
double m_center [3]
double m_eye [3]
double m_up [3]
double m_right [3]
double m_forward [3]
Constructor & Destructor Documentation
Antipatrea::GCamera::GCamera (void) inline
References SetLookAtStandardPosition().
virtual Antipatrea::GCamera::~GCamera (void) inline virtual
References GetModelViewMatrixOpenGL(), and SetupFromParams().
Member Function Documentation
virtual void Antipatrea::GCamera::SetupFromParams (Params & params) virtual
Referenced by ~GCamera().
void Antipatrea::GCamera::GetModelViewMatrixOpenGL (double *const m)
Referenced by ~GCamera().
const double* Antipatrea::GCamera::GetEye (void) const inline
References m_eye.
const double* Antipatrea::GCamera::GetCenter (void) const inline
References m_center.
const double* Antipatrea::GCamera::GetUpAxis (void) const inline
References m_up.
const double* Antipatrea::GCamera::GetRightAxis (void) const inline
References m_right.
const double* Antipatrea::GCamera::GetForwardAxis (void) const inline
References m_forward, Move(), MoveForward(), MoveRight(), MoveUp(), SetLookAt(), and SetLookAtStandardPosition().
void Antipatrea::GCamera::SetLookAt (const double eye_x, const double eye_y, const double eye_z, const double center_x, const double center_y, const double center_z, const double up_x, const double up_y, const double up_z)
Referenced by GetForwardAxis().
void Antipatrea::GCamera::SetLookAtStandardPosition (void)
Referenced by GCamera(), and GetForwardAxis().
void Antipatrea::GCamera::MoveForward (const double d)
Referenced by GetForwardAxis().
void Antipatrea::GCamera::MoveRight (const double d)
Referenced by GetForwardAxis().
void Antipatrea::GCamera::MoveUp (const double d)
Referenced by GetForwardAxis().
void Antipatrea::GCamera::Move (const double df, const double dr, const double du)
Referenced by GetForwardAxis().
void Antipatrea::GCamera::RotateAtEye (const double *const R) inline
void Antipatrea::GCamera::RotateAtEye (const double r0, const double r1, const double r2, const double r3, const double r4, const double r5, const double r6, const double r7, const double r8)
void Antipatrea::GCamera::RotateAtCenter (const double *const R) inline
void Antipatrea::GCamera::RotateAtCenter (const double r0, const double r1, const double r2, const double r3, const double r4, const double r5, const double r6, const double r7, const double r8) inline
References m_center, and RotateAtPoint().
void Antipatrea::GCamera::RotateAtPoint (const double *const R, const double px, const double py, const double pz) inline
Referenced by RotateAtCenter().
void Antipatrea::GCamera::RotateAtPoint (const double r0, const double r1, const double r2, const double r3, const double r4, const double r5, const double r6, const double r7, const double r8, const double px, const double py, const double pz)
void Antipatrea::GCamera::RotateAroundAxisAtEye (const double theta, const double vx, const double vy, const double vz) inline
References m_eye, and RotateAroundAxisAtPoint().
Referenced by RotateAroundForwardAxisAtEye(), RotateAroundRightAxisAtEye(), and RotateAroundUpAxisAtEye().
void Antipatrea::GCamera::RotateAroundAxisAtCenter (const double theta, const double vx, const double vy, const double vz) inline
References m_center, and RotateAroundAxisAtPoint().
Referenced by RotateAroundForwardAxisAtCenter(), RotateAroundRightAxisAtCenter(), and RotateAroundUpAxisAtCenter().
void Antipatrea::GCamera::RotateAroundAxisAtPoint (const double theta, const double vx, const double vy, const double vz, const double px, const double py, const double pz)
Referenced by RotateAroundAxisAtCenter(), RotateAroundAxisAtEye(), RotateAroundForwardAxisAtPoint(), RotateAroundRightAxisAtPoint(), and RotateAroundUpAxisAtPoint().
void Antipatrea::GCamera::RotateAroundRightAxisAtEye (const double theta) inline
References m_right, and RotateAroundAxisAtEye().
void Antipatrea::GCamera::RotateAroundRightAxisAtCenter (const double theta) inline
References m_right, and RotateAroundAxisAtCenter().
void Antipatrea::GCamera::RotateAroundRightAxisAtPoint (const double theta, const double px, const double py, const double pz) inline
References m_right, and RotateAroundAxisAtPoint().
void Antipatrea::GCamera::RotateAroundUpAxisAtEye (const double theta) inline
References m_up, and RotateAroundAxisAtEye().
void Antipatrea::GCamera::RotateAroundUpAxisAtCenter (const double theta) inline
References m_up, and RotateAroundAxisAtCenter().
void Antipatrea::GCamera::RotateAroundUpAxisAtPoint (const double theta, const double px, const double py, const double pz) inline
References m_up, and RotateAroundAxisAtPoint().
void Antipatrea::GCamera::RotateAroundForwardAxisAtEye (const double theta) inline
References m_forward, and RotateAroundAxisAtEye().
void Antipatrea::GCamera::RotateAroundForwardAxisAtCenter (const double theta) inline
References m_forward, and RotateAroundAxisAtCenter().
void Antipatrea::GCamera::RotateAroundForwardAxisAtPoint (const double theta, const double px, const double py, const double pz) inline
References m_forward, RotateAroundAxisAtPoint(), and SetEyeCenterRightForward().
void Antipatrea::GCamera::SetEyeCenterRightForward (const double eye[], const double center[], const double right[], const double forward[])
Referenced by RotateAroundForwardAxisAtPoint().
Member Data Documentation
double Antipatrea::GCamera::m_center[3] protected
Referenced by GetCenter(), RotateAroundAxisAtCenter(), and RotateAtCenter().
double Antipatrea::GCamera::m_eye[3] protected
Referenced by GetEye(), and RotateAroundAxisAtEye().
double Antipatrea::GCamera::m_up[3] protected
Referenced by GetUpAxis(), RotateAroundUpAxisAtCenter(), RotateAroundUpAxisAtEye(), and RotateAroundUpAxisAtPoint().
double Antipatrea::GCamera::m_right[3] protected
Referenced by GetRightAxis(), RotateAroundRightAxisAtCenter(), RotateAroundRightAxisAtEye(), and RotateAroundRightAxisAtPoint().
double Antipatrea::GCamera::m_forward[3] protected
Referenced by GetForwardAxis(), RotateAroundForwardAxisAtCenter(), RotateAroundForwardAxisAtEye(), and RotateAroundForwardAxisAtPoint().
The documentation for this class was generated from the following file:
GCamera.hpp