Antipatrea::Cfg Class Reference
Antipatrea::Cfg Class Reference
Configuration representation.
#include <Cfg.hpp>
Public Member Functions
virtual ~Cfg (void)
virtual const double * GetValues (void) const
Get pointer to values.
virtual double * GetValues (void)
Get pointer to values.
virtual void SetValues (double *const values)
Set pointer to values and mark the energy field as undefined.
virtual double GetEnergy (void) const
Get the energy value associated with the configuration.
virtual void SetEnergy (const double energy)
Set the energy value.
virtual bool IsEnergySet (void) const
Return true iff the energy value is not the same as ENERGY_UNDEFINED.
Static Public Attributes
static double ENERGY_UNDEFINED
Special value to indicate that the energy of the configuration is undefined and needs to be computed. It should be set to some value (by default its INFINITY) that does not correspond to an actual energy value.
Protected Member Functions
Cfg (void)
Constructor is made protected since new configurations should be allocated only via CfgManager.
Cfg (const Cfg &)=delete
Copy constructor is disabled since copies should be performed only via CfgManager.
Cfg & operator= (const Cfg &)=delete
Assignment operator is disabled since copies should be performed only via CfgManager.
Protected Attributes
double * m_values
Pointer to configuration values.
double m_energy
Energy value.
Friends
class CfgManager
CfgManager performs allocate/copy functions for configurations.
Detailed Description
Configuration representation.
Author
Erion Plaku, Amarda Shehu
Remarks
A configuration is represented by its values which could correspond to joint/dihedral angles.
The energy value is also added as a field to the configuration so that once it is evaluated it is stored there.
Other interpretations of values are possible – it all depends on the motion-planning problem that is being solved. See Plugin2D/ for alternative examples.
By design, Cfg does not know how to allocate/copy itself – in particular, it does not store its dimension. There is another class, CfgManager, which is responsible for allocating/copying configurations. For this reason, the constructor is made protected and the copy constructor/assignment operator are disabled.
In this way, a planner/component can have access to CfgManager to create new configurations.
Why design it this way? Consider the alternative where Cfg allocates itself. Then, inside a planner/component one could write Cfg *cfg = new Cfg() to create a new configuration. This is problematic however if someone extends the configuration class, e.g., class MyCfg : public Cfg and wants to use MyCfg instead of Cfg for planning purposes. By using CfgManager, such issue is avoided since one would write a class class MyCfgManager : public CfgManager, set the allocator for the planner/component to an instance of MyCfgManager, and then write inside the planner/component Cfg *cfg = GetCfgManager()->NewCfg() .
Constructor & Destructor Documentation
~Cfg()
virtual Antipatrea::Cfg::~Cfg (void) inline virtual
References m_values.
Cfg() [1/2]
Antipatrea::Cfg::Cfg (void) inline protected
Constructor is made protected since new configurations should be allocated only via CfgManager.
Author
Erion Plaku, Amarda Shehu
References operator=().
Cfg() [2/2]
Antipatrea::Cfg::Cfg (const Cfg &) protected delete
Copy constructor is disabled since copies should be performed only via CfgManager.
Author
Erion Plaku, Amarda Shehu
Member Function Documentation
GetValues() [1/2]
virtual const double* Antipatrea::Cfg::GetValues (void) const inline virtual
Get pointer to values.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns just the pointer, not a deep copy.
The values are allocated by CfgManager.
References m_values.
Referenced by Antipatrea::CfgManager::CopyCfg(), Antipatrea::GManagerRunPlannerChain2D::DrawCfg(), Antipatrea::GManagerRunPlannerPoint2D::DrawCfg(), Antipatrea::GManagerRunPlannerPoint2D::DrawEdge(), Antipatrea::GManagerRunPlannerChain2D::DrawEdge(), Antipatrea::CfgAcceptorPoint2D::IsAcceptable(), Antipatrea::CfgProjectorPoint2D::Project(), and Antipatrea::CfgSamplerPoint2D::Sample().
GetValues() [2/2]
virtual double* Antipatrea::Cfg::GetValues (void) inline virtual
Get pointer to values.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns just the pointer; not a deep copy.
The values are allocated by CfgManager.
References m_values.
SetValues()
virtual void Antipatrea::Cfg::SetValues (double *const values) inline virtual
Set pointer to values and mark the energy field as undefined.
Author
Erion Plaku, Amarda Shehu
Remarks
Function just does pointer assignment; not a deep copy.
The values are allocated by CfgManager.
The energy field is marked as undefined to indicate that the energy should be computed (since the values changed).
References m_values, and SetEnergy().
Referenced by Antipatrea::CfgManager::NewCfg(), and Antipatrea::CfgSamplerPoint2D::Sample().
GetEnergy()
virtual double Antipatrea::Cfg::GetEnergy (void) const inline virtual
Get the energy value associated with the configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
The function just returns the energy value stored with the configuration.
It does not perform an energy evaluation.
References m_energy.
Referenced by Antipatrea::CfgManager::CopyCfg(), Antipatrea::CfgAcceptorBasedOnEnergy::IsAcceptable(), Antipatrea::CfgAcceptorBasedOnFixedMMC::IsAcceptable(), Antipatrea::CfgAcceptorBasedOnMMC::IsAcceptable(), and IsEnergySet().
SetEnergy()
virtual void Antipatrea::Cfg::SetEnergy (const double energy) inline virtual
Set the energy value.
Author
Erion Plaku, Amarda Shehu
References m_energy.
Referenced by Antipatrea::CfgManager::CopyCfg(), Antipatrea::CfgAcceptorBasedOnEnergy::IsAcceptable(), Antipatrea::CfgAcceptorBasedOnFixedMMC::IsAcceptable(), Antipatrea::CfgAcceptorBasedOnMMC::IsAcceptable(), and SetValues().
IsEnergySet()
virtual bool Antipatrea::Cfg::IsEnergySet (void) const inline virtual
Return true iff the energy value is not the same as ENERGY_UNDEFINED.
Author
Erion Plaku, Amarda Shehu
References ENERGY_UNDEFINED, and GetEnergy().
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::IsAcceptable(), Antipatrea::CfgAcceptorBasedOnFixedMMC::IsAcceptable(), and Antipatrea::CfgAcceptorBasedOnMMC::IsAcceptable().
operator=()
Cfg& Antipatrea::Cfg::operator= (const Cfg &) protected delete
Assignment operator is disabled since copies should be performed only via CfgManager.
Author
Erion Plaku, Amarda Shehu
Referenced by Cfg().
Friends And Related Function Documentation
CfgManager
friend class CfgManager friend
CfgManager performs allocate/copy functions for configurations.
Author
Erion Plaku, Amarda Shehu
Member Data Documentation
ENERGY_UNDEFINED
double Antipatrea::Cfg::ENERGY_UNDEFINED static
Special value to indicate that the energy of the configuration is undefined and needs to be computed. It should be set to some value (by default its INFINITY) that does not correspond to an actual energy value.
Author
Erion Plaku, Amarda Shehu
Referenced by Antipatrea::CfgManager::Info(), and IsEnergySet().
m_values
double* Antipatrea::Cfg::m_values protected
Pointer to configuration values.
Author
Erion Plaku, Amarda Shehu
Referenced by GetValues(), SetValues(), and ~Cfg().
m_energy
double Antipatrea::Cfg::m_energy protected
Energy value.
Author
Erion Plaku, Amarda Shehu
Referenced by GetEnergy(), and SetEnergy().
The documentation for this class was generated from the following file:
Cfg.hpp