Antipatrea::CfgSampler Class Reference
Antipatrea::CfgSampler Class Reference abstract
Interface for configuration sampling.
#include <CfgSampler.hpp>
Public Member Functions
CfgSampler (void)
virtual ~CfgSampler (void)
virtual bool Sample (Cfg &cfg)=0
Sample a configuration.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for configuration sampling.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
CfgSampler()
Antipatrea::CfgSampler::CfgSampler (void) inline
~CfgSampler()
virtual Antipatrea::CfgSampler::~CfgSampler (void) inline virtual
References Antipatrea::ClassContainer(), and Sample().
Member Function Documentation
Sample()
virtual bool Antipatrea::CfgSampler::Sample (Cfg & cfg) pure virtual
Sample a configuration.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::CfgSamplerRosetta, Antipatrea::CfgSamplerPoint2D, and Antipatrea::CfgUniformSamplerInJointSpace.
Referenced by ~CfgSampler().
The documentation for this class was generated from the following file:
CfgSampler.hpp