Antipatrea::CfgDistance Class Reference
Antipatrea::CfgDistance Class Reference abstract
Interface for computing the distance between two configurations.
#include <CfgDistance.hpp>
Public Member Functions
CfgDistance (void)
virtual ~CfgDistance (void)
virtual double Distance (const Cfg &cfg1, const Cfg &cfg2)=0
Computes the distance between two configurations.
virtual double DistancePrint (const Cfg &cfg1, const Cfg &cfg2)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for computing the distance between two configurations.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
CfgDistance()
Antipatrea::CfgDistance::CfgDistance (void) inline
~CfgDistance()
virtual Antipatrea::CfgDistance::~CfgDistance (void) inline virtual
References Distance().
Member Function Documentation
Distance()
virtual double Antipatrea::CfgDistance::Distance (const Cfg & cfg1, const Cfg & cfg2) pure virtual
Computes the distance between two configurations.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::CfgDistanceLp, and Antipatrea::CfgDistanceAtomRMSD.
Referenced by DistancePrint(), and ~CfgDistance().
DistancePrint()
virtual double Antipatrea::CfgDistance::DistancePrint (const Cfg & cfg1, const Cfg & cfg2) inline virtual
Reimplemented in Antipatrea::CfgDistanceAtomRMSD.
References Antipatrea::ClassContainer(), and Distance().
The documentation for this class was generated from the following file:
CfgDistance.hpp