Antipatrea::TreeSamplingBasedPlanner Class Reference
Antipatrea::TreeSamplingBasedPlanner Class Reference
Sampling-based planners that expand a tree in the configuration space.
#include <TreeSamplingBasedPlanner.hpp>
Public Member Functions
TreeSamplingBasedPlanner (void)
virtual ~TreeSamplingBasedPlanner (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
virtual double GetExtendMaxNrSteps (void) const
Get the maximum number of steps for the tree-branch expansion.
virtual double GetExtendReachedTargetDistanceThreshold (void) const
Get the distance threshold to determine whether the target configuration has been reached.
virtual double GetGoalBias (void) const
Get the goal bias.
virtual bool GetSampleValidTargetCfg (void) const
Get the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void SetExtendMaxNrSteps (const int n)
Set the maximum number of steps for the tree-branch expansion.
virtual void SetExtendReachedTargetDistanceThreshold (const double d)
Set the distance threshold to determine whether the target configuration has been reached.
virtual void SetGoalBias (const double bias)
Set the goal bias.
virtual void SetSampleValidTargetCfg (const bool valid)
Set the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void Start (void)
Root the tree at the initial configuration.
virtual bool Solve (const double tmax)
Iteratively expand the motion tree by adding new vertices and edges.
Public Member Functions inherited from Antipatrea::SamplingBasedPlanner
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual bool CheckSetup (void)
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Types
enum ExtendStatus {
EXTEND_FAILED,
EXTEND_OK,
EXTEND_REACHED_TARGET,
EXTEND_REACHED_GOAL
}
Status of the planner-graph branch expansion.
Protected Member Functions
virtual void SampleTargetCfg (Cfg &cfg)
Sample a target at random or as the goal configuration.
virtual int SelectVertex (void)
Select a vertex from which to expand and a target toward which to expand a branch in the planner graph.
virtual ExtendStatus ExtendToward (const int vidFrom, Cfg &cfgTo)
Extend a branch in the planner graph from the selected vertex toward the target configuration.
Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual int AddVertex (Cfg *const cfg)
Add a new vertex to the graph with cfg as its associated configuration.
virtual PlannerVertex * NewVertex (void) const
Factory for creating new planner vertices.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Protected Attributes
int m_extendMaxNrSteps
Maximum number of steps for the tree-branch expansion.
double m_extendReachedTargetDistanceThreshold
Distance threshold to determine whether the target configuration has been reached.
double m_goalBias
Goal bias.
bool m_sampleValidTargetCfg
Flag indicating whether the target should be sampled as a valid configuration.
Cfg * m_cfgTarget
Target configuration, which is set by the planner at each iteration.
Protected Attributes inherited from Antipatrea::SamplingBasedPlanner
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Static Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Detailed Description
Sampling-based planners that expand a tree in the configuration space.
Author
Erion Plaku, Amarda Shehu
Remarks
The tree is rooted at the initial configuration.
The tree is iteratively expanded by adding new vertices and new edges.
Specifically, at each iteration a new branch is expanded from an existing vertex in the tree using CfgOffspringGenerator to define the path. Intermediate configurations along the path are added to the tree when they are valid. The branch expansion stops as soon as an invalid configuration is encountered (as determined by CfgAcceptor), the goal is reached, the target is reached, or a maximum number of expansion steps is reached.
If the path generator corresponds to an instance of CfgOffspringGeneratorTowardTarget, the branch is expanded toward a target configuration which could be selected at random or according to some other probability distribution or strategy.
A parameter, m_extendMaxNrSteps, defines the maximum number of steps to expand each branch.
Another parameter, m_extendReachedTargetDistanceThreshold, defines the threshold distance to be used when determining whether or not a configuration has reached the target.
A third parameter, m_goalBias, defines the goal bias used when sampling the target configuration. With probability 1-m_goalBias, the target is sampled using CfgSampler. With probability m_goalBias, the target is sampled using CfgNearTargetSampler with the target set as the goal configuration (as obtained by PlannerProblem::GetGoalAcceptor()->GetAnAcceptableCfg()).
Member Enumeration Documentation
enum Antipatrea::TreeSamplingBasedPlanner::ExtendStatus protected
Status of the planner-graph branch expansion.
Author
Erion Plaku, Amarda Shehu
Remarks
EXTEND_FAILED: no extension occurred.
EXTEND_OK: at least one extension step succeeded.
EXTEND_REACHED_TARGET: target was reached.
EXTEND_REACHED_GOAL: goal was reached.
Enumerator
EXTEND_FAILED
EXTEND_OK
EXTEND_REACHED_TARGET
EXTEND_REACHED_GOAL
Constructor & Destructor Documentation
Antipatrea::TreeSamplingBasedPlanner::TreeSamplingBasedPlanner (void) inline
virtual Antipatrea::TreeSamplingBasedPlanner::~TreeSamplingBasedPlanner (void) inline virtual
References m_cfgTarget.
Member Function Documentation
virtual void Antipatrea::TreeSamplingBasedPlanner::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::SamplingBasedPlanner.
Reimplemented in Antipatrea::EST, and Antipatrea::PGT.
References GetExtendMaxNrSteps(), GetExtendReachedTargetDistanceThreshold(), GetGoalBias(), GetSampleValidTargetCfg(), Antipatrea::SamplingBasedPlanner::Info(), and Antipatrea::Logger::m_out.
Referenced by Antipatrea::PGT::Info(), and Antipatrea::EST::Info().
virtual void Antipatrea::TreeSamplingBasedPlanner::SetupFromParams (Params & params) inline virtual
Set the parameter values of the planner from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes SamplingBasedPlanner::SetupFromParams(params).
It then sets the maximum number of steps for the tree-branch expansion, the distance threshold to determine whether the target configuration has been reached, the goal bias, and the flag to indicate whether the target should be sampled as a valid cfg (keywords Constants::KW_ExtendMaxNrSteps, Constants::KW_ExtendReachedTargetDistanceThreshold, Constants::KW_GoalBias, Constants::KW_SampleValidTargetCfg).
It uses the parameter group associated with the keyword Constants::KW_TreeSamplingBasedPlanner.
The parameter value can be specified in a text file as, for example, TreeSamplingBasedPlanner { ExtendMaxNrSteps 100 ExtendReachedTargetDistanceThreshold 0.1 GoalBias 0.05 SampleValidTargetCfg true }
Reimplemented from Antipatrea::SamplingBasedPlanner.
Reimplemented in Antipatrea::EST, and Antipatrea::PGT.
References Antipatrea::Params::GetData(), GetExtendMaxNrSteps(), GetExtendReachedTargetDistanceThreshold(), GetGoalBias(), GetSampleValidTargetCfg(), Antipatrea::Constants::KW_ExtendMaxNrSteps, Antipatrea::Constants::KW_ExtendReachedTargetDistanceThreshold, Antipatrea::Constants::KW_GoalBias, Antipatrea::Constants::KW_SampleValidTargetCfg, Antipatrea::Constants::KW_TreeSamplingBasedPlanner, SetExtendMaxNrSteps(), SetExtendReachedTargetDistanceThreshold(), SetGoalBias(), SetSampleValidTargetCfg(), and Antipatrea::SamplingBasedPlanner::SetupFromParams().
Referenced by Antipatrea::EST::SetupFromParams().
virtual double Antipatrea::TreeSamplingBasedPlanner::GetExtendMaxNrSteps (void) const inline virtual
Get the maximum number of steps for the tree-branch expansion.
Author
Erion Plaku, Amarda Shehu
References m_extendMaxNrSteps.
Referenced by Info(), and SetupFromParams().
virtual double Antipatrea::TreeSamplingBasedPlanner::GetExtendReachedTargetDistanceThreshold (void) const inline virtual
Get the distance threshold to determine whether the target configuration has been reached.
Author
Erion Plaku, Amarda Shehu
References m_extendReachedTargetDistanceThreshold.
Referenced by Info(), and SetupFromParams().
virtual double Antipatrea::TreeSamplingBasedPlanner::GetGoalBias (void) const inline virtual
Get the goal bias.
Author
Erion Plaku, Amarda Shehu
References m_goalBias.
Referenced by Info(), and SetupFromParams().
virtual bool Antipatrea::TreeSamplingBasedPlanner::GetSampleValidTargetCfg (void) const inline virtual
Get the value of the flag indicating whether the target should be sampled as a valid configuration.
Author
Erion Plaku, Amarda Shehu
References m_sampleValidTargetCfg.
Referenced by Info(), and SetupFromParams().
virtual void Antipatrea::TreeSamplingBasedPlanner::SetExtendMaxNrSteps (const int n) inline virtual
Set the maximum number of steps for the tree-branch expansion.
Author
Erion Plaku, Amarda Shehu
References m_extendMaxNrSteps.
Referenced by SetupFromParams().
virtual void Antipatrea::TreeSamplingBasedPlanner::SetExtendReachedTargetDistanceThreshold (const double d) inline virtual
Set the distance threshold to determine whether the target configuration has been reached.
Author
Erion Plaku, Amarda Shehu
References m_extendReachedTargetDistanceThreshold.
Referenced by SetupFromParams().
virtual void Antipatrea::TreeSamplingBasedPlanner::SetGoalBias (const double bias) inline virtual
Set the goal bias.
Author
Erion Plaku, Amarda Shehu
References m_goalBias.
Referenced by SetupFromParams().
virtual void Antipatrea::TreeSamplingBasedPlanner::SetSampleValidTargetCfg (const bool valid) inline virtual
Set the value of the flag indicating whether the target should be sampled as a valid configuration.
Author
Erion Plaku, Amarda Shehu
References m_sampleValidTargetCfg, SampleTargetCfg(), Solve(), and Start().
Referenced by SetupFromParams().
virtual void Antipatrea::TreeSamplingBasedPlanner::Start (void) virtual
Root the tree at the initial configuration.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::SamplingBasedPlanner.
Referenced by SetSampleValidTargetCfg().
virtual bool Antipatrea::TreeSamplingBasedPlanner::Solve (const double tmax) virtual
Iteratively expand the motion tree by adding new vertices and edges.
Author
Erion Plaku, Amarda Shehu
Remarks
Solve should be called after Start.
Solve can be called repeatedly until a solution is found.
Solve returns true as soon as it finds a solution.
Solve calls SelectVertexAndTarget and then ExpandTowardTarget.
Implements Antipatrea::Planner.
Referenced by SetSampleValidTargetCfg().
virtual void Antipatrea::TreeSamplingBasedPlanner::SampleTargetCfg (Cfg & cfg) protected virtual
Sample a target at random or as the goal configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
With probability 1-m_goalBias, the target is sampled using CfgSampler.
With probability m_goalBias, the target is sampled using CfgNearTargetSampler with the target set as the goal configuration (as obtained by PlannerProblem::GetGoalAcceptor()->GetAnAcceptableCfg()).
Referenced by SetSampleValidTargetCfg().
virtual int Antipatrea::TreeSamplingBasedPlanner::SelectVertex (void) inline protected virtual
Select a vertex from which to expand and a target toward which to expand a branch in the planner graph.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns the id of the selected vertex.
Reimplemented in Antipatrea::EST, Antipatrea::PGT, and Antipatrea::RRT.
References Antipatrea::RandomUniformInteger().
virtual ExtendStatus Antipatrea::TreeSamplingBasedPlanner::ExtendToward (const int vidFrom, Cfg & cfgTo) protected virtual
Extend a branch in the planner graph from the selected vertex toward the target configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
If the path generator can be dynamically cast to CfgOffspringGeneratorTowardTarget, the branch is expanded from the selected vertex toward the target configuration.
Otherwise, CfgOffspringGenerator is used to expand the branch from the selected vertex.
Intermediate configurations along the path are added to the planner graph when they are valid. The branch expansion stops as soon as an invalid configuration is encountered (as determined by CfgAcceptor), the goal is reached, the target is reached, or a maximum number of expansion steps is reached.
Member Data Documentation
int Antipatrea::TreeSamplingBasedPlanner::m_extendMaxNrSteps protected
Maximum number of steps for the tree-branch expansion.
Author
Erion Plaku, Amarda Shehu
Referenced by GetExtendMaxNrSteps(), and SetExtendMaxNrSteps().
double Antipatrea::TreeSamplingBasedPlanner::m_extendReachedTargetDistanceThreshold protected
Distance threshold to determine whether the target configuration has been reached.
Author
Erion Plaku, Amarda Shehu
Referenced by GetExtendReachedTargetDistanceThreshold(), and SetExtendReachedTargetDistanceThreshold().
double Antipatrea::TreeSamplingBasedPlanner::m_goalBias protected
Goal bias.
Author
Erion Plaku, Amarda Shehu
Referenced by GetGoalBias(), and SetGoalBias().
bool Antipatrea::TreeSamplingBasedPlanner::m_sampleValidTargetCfg protected
Flag indicating whether the target should be sampled as a valid configuration.
Author
Erion Plaku, Amarda Shehu
Referenced by GetSampleValidTargetCfg(), and SetSampleValidTargetCfg().
Cfg* Antipatrea::TreeSamplingBasedPlanner::m_cfgTarget protected
Target configuration, which is set by the planner at each iteration.
Author
Erion Plaku, Amarda Shehu
Referenced by ~TreeSamplingBasedPlanner().
The documentation for this class was generated from the following file:
TreeSamplingBasedPlanner.hpp