Antipatrea::Selector< Key > Class Template Reference
Antipatrea::Selector< Key > Class Template Reference
Given items p1, p2, ..., pn with weights w1, w2, ..., wn, select item pi with probability wi / (w1 + ... + wn)
#include <Selector.hpp>
Classes
class Node
Contains item key and weight as well as left, right, and parent pointers.
Public Member Functions
Selector (void)
Initially the binary tree is empty.
virtual ~Selector (void)
Destructor deletes the binary tree.
int GetNrNodes (void) const
virtual Node * Select (void) const
Select item.
virtual Node * Select (const double wselect) const
Select item.
virtual Node * Create (void) const
Create new node.
virtual void Insert (Node *const node)
Insert node into selector.
virtual void Update (Node *const node, const double w)
Update selector.
virtual void Update (Node *const node)
Update selector.
virtual void Remove (Node *const node)
Remove node from selection.
virtual void Clear (void)
Clear selector by removing all items.
virtual Node * Find (Key key)
virtual Node * Find (Key key, Node *root)
Protected Member Functions
virtual void DeleteSubTree (Node *const node)
Delete subtree rooted at node
Protected Attributes
Node * m_root
Root of binary tree.
int m_nNodes
Detailed Description
template<typename Key>
class Antipatrea::Selector< Key >
Given items p1, p2, ..., pn with weights w1, w2, ..., wn, select item pi with probability wi / (w1 + ... + wn)
Author
Erion Plaku
Description:
Items are inserted into a balanced binary tree (according to the weights). This makes it possible to select/update weights in logarithmic time.
Constructor & Destructor Documentation
Selector()
template<typename Key> Antipatrea::Selector< Key >::Selector (void) inline
Initially the binary tree is empty.
Author
Erion Plaku
~Selector()
template<typename Key> virtual Antipatrea::Selector< Key >::~Selector (void) inline virtual
Destructor deletes the binary tree.
Author
Erion Plaku
Member Function Documentation
GetNrNodes()
template<typename Key> int Antipatrea::Selector< Key >::GetNrNodes (void) const inline
Select() [1/2]
template<typename Key> virtual Node* Antipatrea::Selector< Key >::Select (void) const inline virtual
Select item.
Author
Erion Plaku
Parameters
wselect selection weight between 0 and w1 + ... + wn
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Select().
Select() [2/2]
template<typename Key> virtual Node* Antipatrea::Selector< Key >::Select (const double wselect) const inline virtual
Select item.
Author
Erion Plaku
Parameters
wselect selection weight between 0 and w1 + ... + wn
Create()
template<typename Key> virtual Node* Antipatrea::Selector< Key >::Create (void) const inline virtual
Create new node.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert().
Insert()
template<typename Key> virtual void Antipatrea::Selector< Key >::Insert (Node *const node) inline virtual
Insert node into selector.
Author
Erion Plaku
Parameters
node node to be inserted
Remarks
Key and weight should be set prior to inserting node into the selector
Update() [1/2]
template<typename Key> virtual void Antipatrea::Selector< Key >::Update (Node *const node, const double w) inline virtual
Update selector.
Author
Erion Plaku
Parameters
node node to be updated
w new node weight
Update() [2/2]
template<typename Key> virtual void Antipatrea::Selector< Key >::Update (Node *const node) inline virtual
Update selector.
Author
Erion Plaku
Parameters
node node to be updated
Remove()
template<typename Key> virtual void Antipatrea::Selector< Key >::Remove (Node *const node) inline virtual
Remove node from selection.
Author
Erion Plaku
Parameters
node node to be removed
Remarks
Items are stored in leaf nodes, so only leaf nodes can be removed. That is, the left and right children of node should be NULL.
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove().
Clear()
template<typename Key> virtual void Antipatrea::Selector< Key >::Clear (void) inline virtual
Clear selector by removing all items.
Author
Erion Plaku
DeleteSubTree()
template<typename Key> virtual void Antipatrea::Selector< Key >::DeleteSubTree (Node *const node) inline protected virtual
Delete subtree rooted at node
Author
Erion Plaku
Parameters
node root of subtree
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Clear(), Antipatrea::Selector< Antipatrea::FELTRCell *>::DeleteSubTree(), and Antipatrea::Selector< Antipatrea::FELTRCell *>::~Selector().
Find() [1/2]
template<typename Key> virtual Node* Antipatrea::Selector< Key >::Find (Key key) inline virtual
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Find().
Find() [2/2]
template<typename Key> virtual Node* Antipatrea::Selector< Key >::Find (Key key, Node * root) inline virtual
Member Data Documentation
m_root
template<typename Key> Node* Antipatrea::Selector< Key >::m_root protected
Root of binary tree.
Author
Erion Plaku
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Clear(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Select(), and Antipatrea::Selector< Antipatrea::FELTRCell *>::~Selector().
m_nNodes
template<typename Key> int Antipatrea::Selector< Key >::m_nNodes protected
Referenced by Antipatrea::Selector< Antipatrea::FELTRCell *>::Clear(), Antipatrea::Selector< Antipatrea::FELTRCell *>::GetNrNodes(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Insert(), and Antipatrea::Selector< Antipatrea::FELTRCell *>::Remove().
The documentation for this class was generated from the following file:
Selector.hpp