Antipatrea::GManagerRunPlanner Class Reference
Antipatrea::GManagerRunPlanner Class Reference abstract
GUI for running a planner.
#include <GManagerRunPlanner.hpp>
Public Member Functions
GManagerRunPlanner (void)
virtual ~GManagerRunPlanner (void)
virtual void SetupFromParams (Params &params)
virtual void HandleEventOnDisplay (void)
virtual bool HandleEventOnNormalKeyPress (const int key)
virtual bool HandleEventOnMenu (const int item)
virtual void HandleEventOnTimer (void)
virtual void DrawCfg (Cfg &cfg)=0
Draw the configuration.
virtual void DrawEdge (Cfg &cfg1, Cfg &cfg2)=0
Draw the edge connecting the two configurations.
Public Member Functions inherited from Antipatrea::GManager
GManager (void)
virtual ~GManager (void)
virtual void Help (void)
virtual void MainLoop (const char *const title, const int width=1000, const int height=600)
virtual bool HandleEventOnMouseLeftBtnDown (const int x, const int y)
virtual bool HandleEventOnMouseLeftBtnUp (const int x, const int y)
virtual bool HandleEventOnActiveMouseMove (const int x, const int y)
virtual bool HandleEventOnPassiveMouseMove (const int x, const int y)
virtual bool HandleEventOnSpecialKeyPress (const int key)
virtual bool HandleEventOnNormalKeyUp (const int key)
virtual bool HandleEventOnSpecialKeyUp (const int key)
virtual bool HandleEventOnIdle (void)
virtual double GetValue (const int i)
virtual void SetValue (const int i, const double val)
Public Attributes
Setup * m_setup
Pointer to the setup data structure, which contains pointers to the planning problem, the motion planner and its components.
Protected Types
enum { FLAG_PAUSE = 1 }
Protected Member Functions
virtual void MenuOptions (void)
Protected Attributes
const char * m_plannerGraphFile
Flags m_flags
int m_solutionIndex
int m_idMenuMain
int m_idMenuPlanner
int MENU_ITEM_PLANNER_START
int MENU_ITEM_PLANNER_SOLVE
int MENU_ITEM_PLANNER_PRINT_GRAPH
int MENU_ITEM_PLANNER_READ_GRAPH
int MENU_ITEM_PLANNER_STATS
std::vector< Cfg * > m_cfgs
Protected Attributes inherited from Antipatrea::GManager
int m_idWindow
int m_timer
int m_mousePrevX
int m_mousePrevY
GCamera m_gCamera
Flags m_flags
int m_nrMenuItems
int m_menuSelItem
std::unordered_map< int, int > m_mapKeysToMenuItems
std::vector< double > m_values
Additional Inherited Members
Public Types inherited from Antipatrea::GManager
enum {
INDEX_MINX,
INDEX_MINY,
INDEX_MAXX,
INDEX_MAXY,
INDEX_ORTHO_NEAR_PLANE,
INDEX_ORTHO_FAR_PLANE,
NR_INDICES
}
Static Public Member Functions inherited from Antipatrea::GManager
static void MousePosFromScreenToWorld (const int x, const int y, double *const wx, double *const wy, double *const wz)
Static Protected Member Functions inherited from Antipatrea::GManager
static void CallbackEventOnActiveMouseMove (int x, int y)
static void CallbackEventOnPassiveMouseMove (int x, int y)
static void CallbackEventOnMouse (int button, int state, int x, int y)
static void CallbackEventOnTimer (int id)
static void CallbackEventOnMenu (int item)
static void CallbackEventOnSpecialKeyPress (int key, int x, int y)
static void CallbackEventOnNormalKeyPress (unsigned char key, int x, int y)
static void CallbackEventOnSpecialKeyUp (int key, int x, int y)
static void CallbackEventOnNormalKeyUp (unsigned char key, int x, int y)
static void CallbackEventOnDisplay (void)
static void CallbackEventOnIdle (void)
static int CreateMenu (void)
static void SetMenu (const int menu)
static void AddSubMenu (const char name[], const int item)
static void AddMenuEntry (const char name[], const int item)
static void ChangeToMenuEntry (const int pos, const char name[], const int item)
Detailed Description
GUI for running a planner.
Author
Erion Plaku, Amarda Shehu
Member Enumeration Documentation
anonymous enum protected
Enumerator
FLAG_PAUSE
Constructor & Destructor Documentation
Antipatrea::GManagerRunPlanner::GManagerRunPlanner (void)
virtual Antipatrea::GManagerRunPlanner::~GManagerRunPlanner (void) inline virtual
References DrawCfg(), DrawEdge(), HandleEventOnDisplay(), HandleEventOnMenu(), HandleEventOnNormalKeyPress(), HandleEventOnTimer(), m_setup, and SetupFromParams().
Member Function Documentation
virtual void Antipatrea::GManagerRunPlanner::SetupFromParams (Params & params) virtual
Reimplemented from Antipatrea::GManager.
Reimplemented in Antipatrea::GManagerRunPlanner2D.
Referenced by ~GManagerRunPlanner().
virtual void Antipatrea::GManagerRunPlanner::HandleEventOnDisplay (void) virtual
Reimplemented from Antipatrea::GManager.
Reimplemented in Antipatrea::GManagerRunPlanner2D.
Referenced by ~GManagerRunPlanner().
virtual bool Antipatrea::GManagerRunPlanner::HandleEventOnNormalKeyPress (const int key) virtual
Reimplemented from Antipatrea::GManager.
Referenced by ~GManagerRunPlanner().
virtual bool Antipatrea::GManagerRunPlanner::HandleEventOnMenu (const int item) virtual
Reimplemented from Antipatrea::GManager.
Reimplemented in Antipatrea::GManagerRunPlanner2D.
Referenced by ~GManagerRunPlanner().
virtual void Antipatrea::GManagerRunPlanner::HandleEventOnTimer (void) virtual
Reimplemented from Antipatrea::GManager.
Referenced by ~GManagerRunPlanner().
virtual void Antipatrea::GManagerRunPlanner::DrawCfg (Cfg & cfg) pure virtual
Draw the configuration.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::GManagerRunPlannerChain2D, and Antipatrea::GManagerRunPlannerPoint2D.
Referenced by ~GManagerRunPlanner().
virtual void Antipatrea::GManagerRunPlanner::DrawEdge (Cfg & cfg1, Cfg & cfg2) pure virtual
Draw the edge connecting the two configurations.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::GManagerRunPlannerChain2D, and Antipatrea::GManagerRunPlannerPoint2D.
Referenced by ~GManagerRunPlanner().
virtual void Antipatrea::GManagerRunPlanner::MenuOptions (void) protected virtual
Reimplemented from Antipatrea::GManager.
Reimplemented in Antipatrea::GManagerRunPlanner2D.
Member Data Documentation
Setup* Antipatrea::GManagerRunPlanner::m_setup
Pointer to the setup data structure, which contains pointers to the planning problem, the motion planner and its components.
Author
Erion Plaku, Amarda Shehu
Referenced by Antipatrea::GManagerRunPlannerChain2D::DrawCfg(), Antipatrea::GManagerRunPlannerChain2D::DrawEdge(), Antipatrea::GManagerRunPlannerChain2D::GManagerRunPlannerChain2D(), Antipatrea::GManagerRunPlannerPoint2D::GManagerRunPlannerPoint2D(), ~GManagerRunPlanner(), and Antipatrea::GManagerRunPlanner2D::~GManagerRunPlanner2D().
const char* Antipatrea::GManagerRunPlanner::m_plannerGraphFile protected
Flags Antipatrea::GManagerRunPlanner::m_flags protected
int Antipatrea::GManagerRunPlanner::m_solutionIndex protected
int Antipatrea::GManagerRunPlanner::m_idMenuMain protected
int Antipatrea::GManagerRunPlanner::m_idMenuPlanner protected
int Antipatrea::GManagerRunPlanner::MENU_ITEM_PLANNER_START protected
int Antipatrea::GManagerRunPlanner::MENU_ITEM_PLANNER_SOLVE protected
int Antipatrea::GManagerRunPlanner::MENU_ITEM_PLANNER_PRINT_GRAPH protected
int Antipatrea::GManagerRunPlanner::MENU_ITEM_PLANNER_READ_GRAPH protected
int Antipatrea::GManagerRunPlanner::MENU_ITEM_PLANNER_STATS protected
std::vector<Cfg*> Antipatrea::GManagerRunPlanner::m_cfgs protected
The documentation for this class was generated from the following file:
GManagerRunPlanner.hpp