Antipatrea::ProximityQuery< Key > Class Template Reference
Antipatrea::ProximityQuery< Key > Class Template Reference
#include <ProximityQuery.hpp>
Public Member Functions
ProximityQuery (void)
virtual ~ProximityQuery (void)
int GetNrNeighbors (void) const
double GetRange (void)
Key GetKey (void) const
virtual void Clear (void)
virtual void SetNrNeighbors (const int k)
virtual void SetRange (const double range)
virtual void SetKey (Key key)
Protected Attributes
int m_k
double m_range
Key m_key
Constructor & Destructor Documentation
ProximityQuery()
template<typename Key> Antipatrea::ProximityQuery< Key >::ProximityQuery (void) inline
References Antipatrea::ProximityQuery< Key >::m_k, and Antipatrea::ProximityQuery< Key >::m_range.
~ProximityQuery()
template<typename Key> virtual Antipatrea::ProximityQuery< Key >::~ProximityQuery (void) inline virtual
Member Function Documentation
GetNrNeighbors()
template<typename Key> int Antipatrea::ProximityQuery< Key >::GetNrNeighbors (void) const inline
References Antipatrea::ProximityQuery< Key >::m_k.
Referenced by Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors(), and Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors().
GetRange()
template<typename Key> double Antipatrea::ProximityQuery< Key >::GetRange (void) inline
References Antipatrea::ProximityQuery< Key >::m_range.
Referenced by Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors(), and Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors().
GetKey()
template<typename Key> Key Antipatrea::ProximityQuery< Key >::GetKey (void) const inline
References Antipatrea::ProximityQuery< Key >::m_key.
Referenced by Antipatrea::Proximity< int, Antipatrea::SamplingBasedPlanner * >::Neighbor(), Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors(), and Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors().
Clear()
template<typename Key> virtual void Antipatrea::ProximityQuery< Key >::Clear (void) inline virtual
SetNrNeighbors()
template<typename Key> virtual void Antipatrea::ProximityQuery< Key >::SetNrNeighbors (const int k) inline virtual
References Antipatrea::ProximityQuery< Key >::m_k.
Referenced by Antipatrea::Proximity< int, Antipatrea::SamplingBasedPlanner * >::Neighbor().
SetRange()
template<typename Key> virtual void Antipatrea::ProximityQuery< Key >::SetRange (const double range) inline virtual
References Antipatrea::ProximityQuery< Key >::m_range.
SetKey()
template<typename Key> virtual void Antipatrea::ProximityQuery< Key >::SetKey (Key key) inline virtual
References Antipatrea::ProximityQuery< Key >::m_key.
Member Data Documentation
m_k
template<typename Key> int Antipatrea::ProximityQuery< Key >::m_k protected
Referenced by Antipatrea::ProximityQuery< Key >::GetNrNeighbors(), Antipatrea::ProximityQuery< Key >::ProximityQuery(), and Antipatrea::ProximityQuery< Key >::SetNrNeighbors().
m_range
template<typename Key> double Antipatrea::ProximityQuery< Key >::m_range protected
Referenced by Antipatrea::ProximityQuery< Key >::GetRange(), Antipatrea::ProximityQuery< Key >::ProximityQuery(), and Antipatrea::ProximityQuery< Key >::SetRange().
m_key
template<typename Key> Key Antipatrea::ProximityQuery< Key >::m_key protected
Referenced by Antipatrea::ProximityQuery< Key >::GetKey(), and Antipatrea::ProximityQuery< Key >::SetKey().
The documentation for this class was generated from the following file:
ProximityQuery.hpp