Antipatrea::Planner Class Reference
Antipatrea::Planner Class Reference abstract
Interface for a planner which takes a planning problem, tries to solve it, and, if successful, provides a solution.
#include <Planner.hpp>
Public Member Functions
Planner (void)
virtual ~Planner (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void Start (void)=0
Initialize the planner.
virtual bool Solve (const double tmax)=0
Run the planner for a certain amount of time.
virtual bool IsSolved (void)=0
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)=0
Construct the solution that the planner has found.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
virtual std::istream & Read (std::istream &in)=0
Read the content from the input stream.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
virtual std::ostream & Print (std::ostream &out) const =0
Write to the output stream.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Detailed Description
Interface for a planner which takes a planning problem, tries to solve it, and, if successful, provides a solution.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to PlannerProblem to access the planning problem.
Constructor & Destructor Documentation
Antipatrea::Planner::Planner (void) inline
virtual Antipatrea::Planner::~Planner (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::Planner::CheckSetup (void) inline virtual
Reimplemented in Antipatrea::SamplingBasedPlanner, and Antipatrea::PGT.
References Antipatrea::Component::CheckSetup().
Referenced by Antipatrea::SamplingBasedPlanner::CheckSetup().
virtual void Antipatrea::Planner::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Reimplemented in Antipatrea::EST, Antipatrea::SamplingBasedPlanner, Antipatrea::PGT, Antipatrea::PRM, and Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::ClassContainer(), GetSolution(), Antipatrea::Object::Info(), IsSolved(), Antipatrea::Logger::m_out, Antipatrea::Object::Name(), Solve(), and Start().
Referenced by Antipatrea::SamplingBasedPlanner::Info().
virtual void Antipatrea::Planner::Start (void) pure virtual
Initialize the planner.
Author
Erion Plaku, Amarda Shehu
Remarks
This function should be called only once at the beginning after the problem and other components have been setup.
Implemented in Antipatrea::TreeSamplingBasedPlanner, Antipatrea::SamplingBasedPlanner, and Antipatrea::PRM.
Referenced by Info().
virtual bool Antipatrea::Planner::Solve (const double tmax) pure virtual
Run the planner for a certain amount of time.
Author
Erion Plaku, Amarda Shehu
Remarks
Solve should be called after Start.
Solve can be called repeatedly until a solution is found.
Solve returns true as soon as it finds a solution.
Implemented in Antipatrea::TreeSamplingBasedPlanner, and Antipatrea::PRM.
Referenced by Info().
virtual bool Antipatrea::Planner::IsSolved (void) pure virtual
Return true iff the planner has found a solution.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::SamplingBasedPlanner.
Referenced by Info().
virtual bool Antipatrea::Planner::GetSolution (PlannerSolution & sol) pure virtual
Construct the solution that the planner has found.
Author
Erion Plaku, Amarda Shehu
Remarks
The function returns true iff the planner has found a solution.
Implemented in Antipatrea::SamplingBasedPlanner.
Referenced by Info().
The documentation for this class was generated from the following file:
Planner.hpp