Antipatrea::Sprint Class Reference
Antipatrea::Sprint Class Reference
Implement methods to calculate motions between stable protein states. Based on work by Molloy et al (see BMC Structural Biology (2012) Molloy, Shehu, Elucidating the ensemble of functionally-relevant transitions in protein systems with a robotics-inspired method.
#include <Sprint.hpp>
Public Member Functions
Sprint (void)
virtual ~Sprint (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
void SetupDeltaRRegions ()
Public Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
TreeSamplingBasedPlanner (void)
virtual ~TreeSamplingBasedPlanner (void)
virtual double GetExtendMaxNrSteps (void) const
Get the maximum number of steps for the tree-branch expansion.
virtual double GetExtendReachedTargetDistanceThreshold (void) const
Get the distance threshold to determine whether the target configuration has been reached.
virtual double GetGoalBias (void) const
Get the goal bias.
virtual bool GetSampleValidTargetCfg (void) const
Get the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void SetExtendMaxNrSteps (const int n)
Set the maximum number of steps for the tree-branch expansion.
virtual void SetExtendReachedTargetDistanceThreshold (const double d)
Set the distance threshold to determine whether the target configuration has been reached.
virtual void SetGoalBias (const double bias)
Set the goal bias.
virtual void SetSampleValidTargetCfg (const bool valid)
Set the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void Start (void)
Root the tree at the initial configuration.
virtual bool Solve (const double tmax)
Iteratively expand the motion tree by adding new vertices and edges.
Public Member Functions inherited from Antipatrea::SamplingBasedPlanner
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual bool CheckSetup (void)
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Member Functions
virtual PlannerVertex * NewVertex (void) const
Create a new planner vertices.
virtual int AddVertex (Cfg *const cfg)
Given a configuration, add it to the Sprint projections and the TreeBasedPlanner data structures. Returns the vid, or -1 is no vertex was added. Recall that because of the granularity reduction, vertices may not added (and a -1 is returned).
virtual int SelectVertex (void)
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Protected Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
virtual void SampleTargetCfg (Cfg &cfg)
Sample a target at random or as the goal configuration.
virtual ExtendStatus ExtendToward (const int vidFrom, Cfg &cfgTo)
Extend a branch in the planner graph from the selected vertex toward the target configuration.
Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Protected Attributes
int m_cellGridGranularity
The granularity (number of cells in each dimension) within a FELTRCell (projections within an energy level).
int m_deltaRGridGranularity
The granularity (number of cells in each dimension) for mapping the Delta R values.
double m_deltaRGridMin
Low end of the DeltaR projection. All cfgs with lower DeltaR are simply projected to this region.
double m_deltaRGridMax
High end of the DeltaR projection. All cfgs with higher DeltaR are projected into this region.
std::vector< DeltaRRegion > m_regions
Allow for efficient probabilistic selection for an energy region (stores pointers to energy regions and their associated weight).
Selector< unsigned int > m_selector
int m_regionExp
Protected Attributes inherited from Antipatrea::TreeSamplingBasedPlanner
int m_extendMaxNrSteps
Maximum number of steps for the tree-branch expansion.
double m_extendReachedTargetDistanceThreshold
Distance threshold to determine whether the target configuration has been reached.
double m_goalBias
Goal bias.
bool m_sampleValidTargetCfg
Flag indicating whether the target should be sampled as a valid configuration.
Cfg * m_cfgTarget
Target configuration, which is set by the planner at each iteration.
Protected Attributes inherited from Antipatrea::SamplingBasedPlanner
const int SAMPLING_PLANNER_VERBOSE_FULL = 3
constants for verbosity control
const int SAMPLING_PLANNER_VERBOSE_MED = 2
const int SAMPLING_PLANNER_VERBOSE_LOW = 1
const int SAMPLING_PLANNER_VERBOSE_NONE = 0
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
int m_verbosityFlag
verbosity flag
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Protected Types inherited from Antipatrea::TreeSamplingBasedPlanner
enum ExtendStatus {
EXTEND_FAILED,
EXTEND_OK,
EXTEND_REACHED_TARGET,
EXTEND_REACHED_GOAL
}
Status of the planner-graph branch expansion.
Static Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Detailed Description
Implement methods to calculate motions between stable protein states. Based on work by Molloy et al (see BMC Structural Biology (2012) Molloy, Shehu, Elucidating the ensemble of functionally-relevant transitions in protein systems with a robotics-inspired method.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
This implementation does not support all the techniques used in the publication above.
Constructor & Destructor Documentation
Sprint()
Antipatrea::Sprint::Sprint (void) inline
~Sprint()
virtual Antipatrea::Sprint::~Sprint (void) inline virtual
Member Function Documentation
Info()
virtual void Antipatrea::Sprint::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::TreeSamplingBasedPlanner::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::Sprint::SetupFromParams (Params & params) inline virtual
Set the parameter values of the planner from the given parameters.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function first invokes TreeSamplingBasedPlanner::SetupFromParams(params).
It uses the parameter group associated with the keyword Constants::KW_SPRINT.
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::Params::GetData(), Antipatrea::Params::GetValueAsInt(), Antipatrea::Constants::KW_SPRINT, Antipatrea::Constants::KW_SPRINT_REGION_EXP, Antipatrea::Params::Data::m_params, Antipatrea::TreeSamplingBasedPlanner::SetupFromParams(), and Antipatrea::Constants::VAL_SPRINT_REGION_EXP.
SetupDeltaRRegions()
void Antipatrea::Sprint::SetupDeltaRRegions ()
NewVertex()
virtual PlannerVertex* Antipatrea::Sprint::NewVertex (void) const inline protected virtual
Create a new planner vertices.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Create SprintVertex instead of PlannerVertex.
Reimplemented from Antipatrea::SamplingBasedPlanner.
References Antipatrea::SprintVertex::SprintVertex().
AddVertex()
virtual int Antipatrea::Sprint::AddVertex (Cfg *const cfg) protected virtual
Given a configuration, add it to the Sprint projections and the TreeBasedPlanner data structures. Returns the vid, or -1 is no vertex was added. Recall that because of the granularity reduction, vertices may not added (and a -1 is returned).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::SamplingBasedPlanner.
SelectVertex()
virtual int Antipatrea::Sprint::SelectVertex (void) protected virtual
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Function returns the vid of the selected vertex.
First, an RMSD energy region is selected using the desired weighting function, and then a cell within that energy region is selected.
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
Member Data Documentation
m_cellGridGranularity
int Antipatrea::Sprint::m_cellGridGranularity protected
The granularity (number of cells in each dimension) within a FELTRCell (projections within an energy level).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_deltaRGridGranularity
int Antipatrea::Sprint::m_deltaRGridGranularity protected
The granularity (number of cells in each dimension) for mapping the Delta R values.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_deltaRGridMin
double Antipatrea::Sprint::m_deltaRGridMin protected
Low end of the DeltaR projection. All cfgs with lower DeltaR are simply projected to this region.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_deltaRGridMax
double Antipatrea::Sprint::m_deltaRGridMax protected
High end of the DeltaR projection. All cfgs with higher DeltaR are projected into this region.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_regions
std::vector<DeltaRRegion> Antipatrea::Sprint::m_regions protected
Allow for efficient probabilistic selection for an energy region (stores pointers to energy regions and their associated weight).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_selector
Selector<unsigned int> Antipatrea::Sprint::m_selector protected
m_regionExp
int Antipatrea::Sprint::m_regionExp protected
The documentation for this class was generated from the following file:
Sprint.hpp