Antipatrea::CfgNearTargetSamplerByGaussianPerturbation Class Reference
Antipatrea::CfgNearTargetSamplerByGaussianPerturbation Class Reference
Sample a configuration near a target configuration by using a Gaussian distribution to perturb its values.
#include <CfgNearTargetSamplerByGaussianPerturbation.hpp>
Public Member Functions
CfgNearTargetSamplerByGaussianPerturbation (void)
virtual ~CfgNearTargetSamplerByGaussianPerturbation (void)
virtual bool CheckSetup (void)
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual double GetStandardDeviation (void) const
Name says it all.
virtual void SetStandardDeviation (const double stddev)
Name says it all.
virtual bool Sample (Cfg &cfg)
Sample a configuration near a target configuration by using a Gaussian distribution to perturb its values.
Public Member Functions inherited from Antipatrea::CfgNearTargetSampler
CfgNearTargetSampler (void)
virtual ~CfgNearTargetSampler (void)
virtual const Cfg * GetTargetCfg (void) const
Get the pointer to the target configuration.
virtual void SetTargetCfg (const Cfg *const cfg)
Set the pointer to the target configuration.
Public Member Functions inherited from Antipatrea::CfgSampler
CfgSampler (void)
virtual ~CfgSampler (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
double m_stddev
The standard deviation of the Gaussian distribution used for the perturbation of the values of the target configuration.
Protected Attributes inherited from Antipatrea::CfgNearTargetSampler
const Cfg * m_cfgTarget
Pointer to the target configuration.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Sample a configuration near a target configuration by using a Gaussian distribution to perturb its values.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgManager as it uses the configuration dimension.
The user should also set the standard deviation of the Gaussian distribution used for the perturbation of the values of the target configuration.
Constructor & Destructor Documentation
Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::CfgNearTargetSamplerByGaussianPerturbation (void) inline
virtual Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::~CfgNearTargetSamplerByGaussianPerturbation (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::CheckSetup (void) inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgNearTargetSampler.
References GetStandardDeviation(), Antipatrea::CfgNearTargetSampler::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual void Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Sets the standard deviation for the Gaussian distribution (keyword defined in Constants::KW_CfgNearTargetSamplerByGaussianDistribution_Stddev).
It uses the parameter group associated with the keyword Constants::KW_CfgNearTargetSamplerByGaussianDistribution.
The parameter value can be specified in a text file as, for example, CfgNearTargetSamplerByGaussianPerturbation { Stddev 0.1 }
Reimplemented from Antipatrea::Component.
References Antipatrea::Params::GetData(), GetStandardDeviation(), Antipatrea::Constants::KW_CfgNearTargetSamplerByGaussianPerturbation, Antipatrea::Constants::KW_CfgNearTargetSamplerByGaussianPerturbation_Stddev, SetStandardDeviation(), and Antipatrea::Component::SetupFromParams().
virtual double Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::GetStandardDeviation (void) const inline virtual
Name says it all.
Author
Erion Plaku, Amarda Shehu
References m_stddev.
Referenced by Info(), and SetupFromParams().
virtual void Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::SetStandardDeviation (const double stddev) inline virtual
Name says it all.
Author
Erion Plaku, Amarda Shehu
References m_stddev, and Sample().
Referenced by SetupFromParams().
virtual bool Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::Sample (Cfg & cfg) virtual
Sample a configuration near a target configuration by using a Gaussian distribution to perturb its values.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgSampler.
Referenced by SetStandardDeviation().
Member Data Documentation
double Antipatrea::CfgNearTargetSamplerByGaussianPerturbation::m_stddev protected
The standard deviation of the Gaussian distribution used for the perturbation of the values of the target configuration.
Author
Erion Plaku, Amarda Shehu
Referenced by GetStandardDeviation(), and SetStandardDeviation().
The documentation for this class was generated from the following file:
CfgNearTargetSamplerByGaussianPerturbation.hpp