Antipatrea::PathCostEvaluator Class Reference
Antipatrea::PathCostEvaluator Class Reference abstract
Interface for evaluating the direct and reverse cost of a path.
#include <PathCostEvaluator.hpp>
Classes
struct Costs
Representing the direct and reverse costs of a path.
Public Member Functions
PathCostEvaluator (void)
virtual ~PathCostEvaluator (void)
virtual Costs EvaluateBasedOnFromToCfgs (Cfg &cfgFrom, Cfg &cfgTo)=0
Evaluate the direct and reverse cost of a path based solely on its start and end configurations.
virtual Costs EvaluateBasedOnPathGenerator (Cfg &cfgFrom, Cfg &cfgTo, PathGenerator &pgen, const double tstep)
Evaluate the direct and reverse cost of a path using not only its start and end configurations but also intermediate configurations along the path.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for evaluating the direct and reverse cost of a path.
Author
Erion Plaku, Amarda Shehu
Remarks
The reverse cost of a path from A to B corresponds to the cost of the reverse path, namely from B to A.
Often the direct and reverse costs are the same but not always. This interface allows someone to implement nonsymmetric path-cost evaluators.
Constructor & Destructor Documentation
Antipatrea::PathCostEvaluator::PathCostEvaluator (void) inline
virtual Antipatrea::PathCostEvaluator::~PathCostEvaluator (void) inline virtual
Member Function Documentation
virtual Costs Antipatrea::PathCostEvaluator::EvaluateBasedOnFromToCfgs (Cfg & cfgFrom, Cfg & cfgTo) pure virtual
Evaluate the direct and reverse cost of a path based solely on its start and end configurations.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::PathCostEvaluatorBasedOnDistance.
Referenced by EvaluateBasedOnPathGenerator().
virtual Costs Antipatrea::PathCostEvaluator::EvaluateBasedOnPathGenerator (Cfg & cfgFrom, Cfg & cfgTo, PathGenerator & pgen, const double tstep) inline virtual
Evaluate the direct and reverse cost of a path using not only its start and end configurations but also intermediate configurations along the path.
Author
Erion Plaku, Amarda Shehu
Remarks
In many cases, e.g., straight-line path in Euclidean space, the path cost does not depend on the intermediate configurations but only on its start and end configurations.
This is the default implementation.
There are, however, many other cases where the path cost depends on the intermediate configurations. For example, when the path cost is related to the energy values attained by the configurations along the path.
When implementing this function, one can use the PathGenerator pgen to generate the intermediate configurations to better evaluate the path cost.
A suggested time-step resolution is also provided as an argument.
References Antipatrea::ClassContainer(), and EvaluateBasedOnFromToCfgs().
The documentation for this class was generated from the following file:
PathCostEvaluator.hpp