Antipatrea::Grid Class Reference
Antipatrea::Grid Class Reference
#include <Grid.hpp>
Public Member Functions
Grid (void)
virtual ~Grid (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
virtual void Setup2D (const int dimsX, const int dimsY, const double minX, const double minY, const double maxX, const double maxY)
virtual void Setup3D (const int dimsX, const int dimsY, const int dimsZ, const double minX, const double minY, const double minZ, const double maxX, const double maxY, const double maxZ)
virtual void Setup (const int ndims, const int dims[], const double min[], const double max[])
int GetNrCells (void) const
int GetNrDims (void) const
const int * GetDims (void) const
const double * GetMin (void) const
const double * GetMax (void) const
const double * GetUnits (void) const
double GetCellVolume (void) const
virtual int GetCellIdFromPoint (const double *const p) const
Get the id of the cell where the point p falls into.
virtual int GetCellIdFromCoords (const int coords[]) const
virtual void GetCoordsFromCellId (const int id, int coords[]) const
virtual void GetCoords (const double p[], int coords[]) const
virtual int GetCellId (const double p[]) const
virtual void GetCellFromCoords (const int coords[], double min[], double max[]) const
virtual void GetCellFromCoords (const int coords[], double bbox[]) const
virtual void GetCellFromId (const int id, double min[], double max[]) const
virtual void GetCellFromId (const int id, double bbox[]) const
virtual void GetCellCenterFromCoords (const int coords[], double c[]) const
virtual void GetCellCenterFromId (const int id, double c[]) const
virtual bool IsPointInside (const double p[]) const
virtual bool IsPointInsideCell (const int coords[], const double p[]) const
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Static Protected Member Functions
static int GetCoord (const double x, const double min, const double max, const double unit, const int ndims)
Protected Attributes
int m_ndims
std::vector< int > m_dims
std::vector< double > m_min
std::vector< double > m_max
std::vector< double > m_units
double m_cvol
int m_ncells
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Constructor & Destructor Documentation
Grid()
Antipatrea::Grid::Grid (void) inline
References m_cvol, m_ncells, and m_ndims.
~Grid()
virtual Antipatrea::Grid::~Grid (void) inline virtual
References Info(), and SetupFromParams().
Member Function Documentation
Info()
virtual void Antipatrea::Grid::Info (const char prefix[]) const virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Referenced by Antipatrea::PGT::Info(), and ~Grid().
SetupFromParams()
virtual void Antipatrea::Grid::SetupFromParams (Params & params) virtual
Referenced by ~Grid().
Setup2D()
virtual void Antipatrea::Grid::Setup2D (const int dimsX, const int dimsY, const double minX, const double minY, const double maxX, const double maxY) inline virtual
References Setup().
Setup3D()
virtual void Antipatrea::Grid::Setup3D (const int dimsX, const int dimsY, const int dimsZ, const double minX, const double minY, const double minZ, const double maxX, const double maxY, const double maxZ) inline virtual
References Setup().
Setup()
virtual void Antipatrea::Grid::Setup (const int ndims, const int dims[], const double min[], const double max[]) virtual
Referenced by Antipatrea::Setup2D::FixGrid(), Setup2D(), and Setup3D().
GetNrCells()
int Antipatrea::Grid::GetNrCells (void) const inline
References m_ncells.
GetNrDims()
int Antipatrea::Grid::GetNrDims (void) const inline
References m_dims.
GetDims()
const int* Antipatrea::Grid::GetDims (void) const inline
References m_dims.
GetMin()
const double* Antipatrea::Grid::GetMin (void) const inline
References m_min.
GetMax()
const double* Antipatrea::Grid::GetMax (void) const inline
References m_max.
GetUnits()
const double* Antipatrea::Grid::GetUnits (void) const inline
References m_units.
GetCellVolume()
double Antipatrea::Grid::GetCellVolume (void) const inline
References GetCellFromCoords(), GetCellId(), GetCellIdFromCoords(), GetCellIdFromPoint(), GetCoords(), GetCoordsFromCellId(), and m_cvol.
GetCellIdFromPoint()
virtual int Antipatrea::Grid::GetCellIdFromPoint (const double *const p) const virtual
Get the id of the cell where the point p falls into.
Author
Erion Plaku
Parameters
p point
Referenced by GetCellVolume().
GetCellIdFromCoords()
virtual int Antipatrea::Grid::GetCellIdFromCoords (const int coords[]) const virtual
Referenced by GetCellVolume().
GetCoordsFromCellId()
virtual void Antipatrea::Grid::GetCoordsFromCellId (const int id, int coords[]) const virtual
Referenced by GetCellVolume().
GetCoords()
virtual void Antipatrea::Grid::GetCoords (const double p[], int coords[]) const virtual
Referenced by GetCellVolume().
GetCellId()
virtual int Antipatrea::Grid::GetCellId (const double p[]) const virtual
Referenced by GetCellVolume().
GetCellFromCoords() [1/2]
virtual void Antipatrea::Grid::GetCellFromCoords (const int coords[], double min[], double max[]) const virtual
Referenced by GetCellFromCoords(), and GetCellVolume().
GetCellFromCoords() [2/2]
virtual void Antipatrea::Grid::GetCellFromCoords (const int coords[], double bbox[]) const inline virtual
References GetCellFromCoords(), GetCellFromId(), and m_ndims.
GetCellFromId() [1/2]
virtual void Antipatrea::Grid::GetCellFromId (const int id, double min[], double max[]) const virtual
Referenced by GetCellFromCoords(), and GetCellFromId().
GetCellFromId() [2/2]
virtual void Antipatrea::Grid::GetCellFromId (const int id, double bbox[]) const inline virtual
References GetCellCenterFromCoords(), GetCellCenterFromId(), GetCellFromId(), IsPointInside(), IsPointInsideCell(), and m_ndims.
GetCellCenterFromCoords()
virtual void Antipatrea::Grid::GetCellCenterFromCoords (const int coords[], double c[]) const virtual
Referenced by GetCellFromId().
GetCellCenterFromId()
virtual void Antipatrea::Grid::GetCellCenterFromId (const int id, double c[]) const virtual
Referenced by GetCellFromId().
IsPointInside()
virtual bool Antipatrea::Grid::IsPointInside (const double p[]) const virtual
Referenced by GetCellFromId().
IsPointInsideCell()
virtual bool Antipatrea::Grid::IsPointInsideCell (const int coords[], const double p[]) const virtual
Referenced by GetCellFromId().
GetCoord()
static int Antipatrea::Grid::GetCoord (const double x, const double min, const double max, const double unit, const int ndims) inline static protected
Member Data Documentation
m_ndims
int Antipatrea::Grid::m_ndims protected
Referenced by GetCellFromCoords(), GetCellFromId(), and Grid().
m_dims
std::vector<int> Antipatrea::Grid::m_dims protected
Referenced by GetDims(), and GetNrDims().
m_min
std::vector<double> Antipatrea::Grid::m_min protected
Referenced by GetMin().
m_max
std::vector<double> Antipatrea::Grid::m_max protected
Referenced by GetMax().
m_units
std::vector<double> Antipatrea::Grid::m_units protected
Referenced by GetUnits().
m_cvol
double Antipatrea::Grid::m_cvol protected
Referenced by GetCellVolume(), and Grid().
m_ncells
int Antipatrea::Grid::m_ncells protected
Referenced by GetNrCells(), and Grid().
The documentation for this class was generated from the following file:
Grid.hpp