Antipatrea::MolecularStructureRosetta Class Reference
Antipatrea::MolecularStructureRosetta Class Reference
Forward kinematics for a molecular structure.
#include <MolecularStructureRosetta.hpp>
Public Member Functions
MolecularStructureRosetta (void)
virtual ~MolecularStructureRosetta (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void Draw (void)
Drawing a molecular configuration is not implemented.
virtual void LoadPDBFile (const char fileName[])
Load the Rosetta pose from a PDB file.
virtual void WritePDBFile (const Cfg &cfg, const char fileName[])
Write PDB file for a configuration.
virtual void WriteScoredPDBFile (const Cfg &cfg, const char fileName[])
void SetExtented (Cfg &cfg)
Set a cfg to the extended conformation.
virtual int GetNrResidues (void) const
Return the number of residues/amino acids within the loaded protein.
virtual void SetCfgDOFs (Cfg &cfgToSet)
Export phi, psi, omega angles from current pose.
virtual void CreateEnergyFunction (const char *)
Create a Rosetta scoring/energy function.
virtual double EvaluateEnergy (Cfg &cfg)
Export the configuration into the pose object and evaluate its energy.
virtual void LoadPose (const Cfg &cfg)
Export the configuration into the pose object.
virtual std::vector< point > GetAtomPositions (const Cfg &cfg)
Return the set of 3-d coordinates corresponding to the heavy backbone atoms (N-CA-C-O) of the protein.
Public Member Functions inherited from Antipatrea::CfgForwardKinematics
CfgForwardKinematics (void)
virtual ~CfgForwardKinematics (void)
virtual void CopyJointValues (const double vals[])
Copy the joint values.
virtual void FK (void)
Compute the forward kinematics if FLAG_RECOMPUTE_FK has been set.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void DoFK (void)
Implement the forward kinematics.
Protected Member Functions inherited from Antipatrea::CfgForwardKinematics
virtual void OnValuesChanged (void)
Set FLAG_RECOMPUTE_FK when values change.
Protected Attributes
core::pose::Pose m_pose
Rosetta pose.
core::scoring::ScoreFunctionOP m_scoreFn
Rosetta Scoring (energy) function.
Protected Attributes inherited from Antipatrea::CfgForwardKinematics
std::vector< double > m_joints
Joint values.
Flags m_flags
Flags to keep track of status, e.g., whether or not FK should be recomputed.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Types inherited from Antipatrea::CfgForwardKinematics
enum { FLAG_RECOMPUTE_FK = 1 }
Detailed Description
Forward kinematics for a molecular structure.
Author
Erion Plaku, Amarda Shehu Gets joints, computes FK
Constructor & Destructor Documentation
MolecularStructureRosetta()
Antipatrea::MolecularStructureRosetta::MolecularStructureRosetta (void)
~MolecularStructureRosetta()
virtual Antipatrea::MolecularStructureRosetta::~MolecularStructureRosetta (void) virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::MolecularStructureRosetta::CheckSetup (void) const virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
Info()
virtual void Antipatrea::MolecularStructureRosetta::Info (const char prefix[]) const virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Referenced by Antipatrea::SetupRosetta::SetupPointersCfgProjector().
SetupFromParams()
virtual void Antipatrea::MolecularStructureRosetta::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::Component.
Draw()
virtual void Antipatrea::MolecularStructureRosetta::Draw (void) virtual
Drawing a molecular configuration is not implemented.
Author
Erion Plaku, Amarda Shehu
LoadPDBFile()
virtual void Antipatrea::MolecularStructureRosetta::LoadPDBFile (const char fileName[]) virtual
Load the Rosetta pose from a PDB file.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
WritePDBFile()
virtual void Antipatrea::MolecularStructureRosetta::WritePDBFile (const Cfg & cfg, const char fileName[]) virtual
Write PDB file for a configuration.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
WriteScoredPDBFile()
virtual void Antipatrea::MolecularStructureRosetta::WriteScoredPDBFile (const Cfg & cfg, const char fileName[]) virtual
SetExtented()
void Antipatrea::MolecularStructureRosetta::SetExtented (Cfg & cfg)
Set a cfg to the extended conformation.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
GetNrResidues()
virtual int Antipatrea::MolecularStructureRosetta::GetNrResidues (void) const inline virtual
Return the number of residues/amino acids within the loaded protein.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References CreateEnergyFunction(), DoFK(), EvaluateEnergy(), GetAtomPositions(), LoadPose(), m_pose, and SetCfgDOFs().
SetCfgDOFs()
virtual void Antipatrea::MolecularStructureRosetta::SetCfgDOFs (Cfg & cfgToSet) virtual
Export phi, psi, omega angles from current pose.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetNrResidues().
CreateEnergyFunction()
virtual void Antipatrea::MolecularStructureRosetta::CreateEnergyFunction (const char *) virtual
Create a Rosetta scoring/energy function.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetNrResidues().
EvaluateEnergy()
virtual double Antipatrea::MolecularStructureRosetta::EvaluateEnergy (Cfg & cfg) virtual
Export the configuration into the pose object and evaluate its energy.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetNrResidues().
LoadPose()
virtual void Antipatrea::MolecularStructureRosetta::LoadPose (const Cfg & cfg) virtual
Export the configuration into the pose object.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetNrResidues().
GetAtomPositions()
virtual std::vector<point> Antipatrea::MolecularStructureRosetta::GetAtomPositions (const Cfg & cfg) virtual
Return the set of 3-d coordinates corresponding to the heavy backbone atoms (N-CA-C-O) of the protein.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetNrResidues().
DoFK()
virtual void Antipatrea::MolecularStructureRosetta::DoFK (void) protected virtual
Implement the forward kinematics.
Author
Erion Plaku, Amarda Shehu
Remarks
This function always computes the forward kinematics, ignoring flag values.
Since FK are implmeneted by Rosetta as a byproduct of setting the
the proteins dihedral angles, this function does not have to do any work.
Implements Antipatrea::CfgForwardKinematics.
Referenced by GetNrResidues().
Member Data Documentation
m_pose
core::pose::Pose Antipatrea::MolecularStructureRosetta::m_pose protected
Rosetta pose.
Author
Erion Plaku, Amarda Shehu, Kevin Molloy
Remarks
Make sure to load it within the desired cfg before evaluating any forward kinematics
Referenced by GetNrResidues().
m_scoreFn
core::scoring::ScoreFunctionOP Antipatrea::MolecularStructureRosetta::m_scoreFn protected
Rosetta Scoring (energy) function.
Author
Erion Plaku, Amarda Shehu, Kevin Molloy
The documentation for this class was generated from the following file:
MolecularStructureRosetta.hpp