Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation Class Reference
Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation Class Reference
The offspring generator defines a path that starts at the parent configuration and reaches the target configuration by linearly interpolating the configuration values.
#include <CfgOffspringGeneratorToTargetByLinearInterpolation.hpp>
Public Member Functions
CfgOffspringGeneratorToTargetByLinearInterpolation (void)
virtual ~CfgOffspringGeneratorToTargetByLinearInterpolation (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void GenerateOffspringCfg (Cfg &cfg)
Generate the offspring by linearly interpolating the parent and target configurations.
Public Member Functions inherited from Antipatrea::CfgOffspringGeneratorToTarget
CfgOffspringGeneratorToTarget (void)
virtual ~CfgOffspringGeneratorToTarget (void)
Public Member Functions inherited from Antipatrea::CfgOffspringGeneratorTowardTarget
CfgOffspringGeneratorTowardTarget (void)
virtual ~CfgOffspringGeneratorTowardTarget (void)
virtual const Cfg * GetTargetCfg (void) const
Get the pointer to the target configuration.
virtual void SetTargetCfg (const Cfg *const cfgTarget)
Set the pointer to the target configuration.
Public Member Functions inherited from Antipatrea::CfgOffspringGenerator
CfgOffspringGenerator (void)
virtual ~CfgOffspringGenerator (void)
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual const Cfg * GetParentCfg (void) const
Get the pointer to the parent configuration.
virtual void SetParentCfg (const Cfg *const cfgParent)
Set the pointer to the parent configuration.
virtual double GetStep (void) const
Get the step size used for guiding the offspring generation.
virtual void SetStep (const double step)
Get the step size used for guiding the offspring generation.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::CfgOffspringGeneratorTowardTarget
const Cfg * m_cfgTarget
Pointer to the target configuration.
Protected Attributes inherited from Antipatrea::CfgOffspringGenerator
const Cfg * m_cfgParent
Pointer to the parent configuration.
double m_step
Step size to guide the offspring generation.
bool m_verboseFlag
Verbosity Flag for all offspring generators.
Detailed Description
The offspring generator defines a path that starts at the parent configuration and reaches the target configuration by linearly interpolating the configuration values.
Author
Erion Plaku, Amarda Shehu
Remarks
The parameter, m_step, is interpreted here as time, ranging from 0 to 1.
The linear interpolation uses SignedDistanceBetweenTwoValues to determine the direction and magnitude of the change between the values being interpolated.
If SignedDistanceBetweenTwoValues points to an object from the class SignedDistanceBetweenTwoAngles, then the linear interpolation between each pairwise angles in the configuration values is done along the shortest arc connecting the two angles.
If SignedDistanceBetweenTwoValues points to an object from the class SignedDistanceBetweenTwoNumbers, then the linear interpolation is the normal one, i.e., (1 - t) * start + t * end.
When dealing with joint values, the angle interpolation should be used.
When dealing with positions, the number interpolation should be used.
This class needs access to CfgManager to allocate auxilary configurations and to SignedDistanceBetweenTwoValues to compute the pairwise value interpolations.
Constructor & Destructor Documentation
CfgOffspringGeneratorToTargetByLinearInterpolation()
Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::CfgOffspringGeneratorToTargetByLinearInterpolation (void) inline
~CfgOffspringGeneratorToTargetByLinearInterpolation()
virtual Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::~CfgOffspringGeneratorToTargetByLinearInterpolation (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::CfgOffspringGenerator.
References Antipatrea::CfgOffspringGenerator::CheckSetup().
Info()
virtual void Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgOffspringGenerator.
References Antipatrea::ClassContainer(), GenerateOffspringCfg(), Antipatrea::CfgOffspringGenerator::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
GenerateOffspringCfg()
virtual void Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::GenerateOffspringCfg (Cfg & cfg) virtual
Generate the offspring by linearly interpolating the parent and target configurations.
Author
Erion Plaku, Amarda Shehu
Remarks
The parameter, m_step, is interpreted here as time, ranging from 0 to 1.
The linear interpolation uses SignedDistanceBetweenTwoValues to determine the direction and magnitude of the change between the values being interpolated.
If SignedDistanceBetweenTwoValues points to an object from the class SignedDistanceBetweenTwoAngles, then the linear interpolation between each pairwise angles in the configuration values is done along the shortest arc connecting the two angles.
If SignedDistanceBetweenTwoValues points to an object from the class SignedDistanceBetweenTwoNumbers, then the linear interpolation is the normal one, i.e., (1 - t) * start + t * end.
When dealing with joint values, the angle interpolation should be used.
When dealing with positions, the number interpolation should be used.
Implements Antipatrea::CfgOffspringGenerator.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgOffspringGeneratorToTargetByLinearInterpolation.hpp