Antipatrea::SignedDistanceBetweenTwoValues Class Reference
Antipatrea::SignedDistanceBetweenTwoValues Class Reference abstract
Interface to define the signed distance between two values.
#include <SignedDistanceBetweenTwoValues.hpp>
Public Member Functions
SignedDistanceBetweenTwoValues (void)
virtual ~SignedDistanceBetweenTwoValues (void)
virtual double SignedDistance (const double from, const double to)=0
Computes the distance between two values.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface to define the signed distance between two values.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Antipatrea::SignedDistanceBetweenTwoValues::SignedDistanceBetweenTwoValues (void) inline
virtual Antipatrea::SignedDistanceBetweenTwoValues::~SignedDistanceBetweenTwoValues (void) inline virtual
References Antipatrea::ClassContainer(), and SignedDistance().
Member Function Documentation
virtual double Antipatrea::SignedDistanceBetweenTwoValues::SignedDistance (const double from, const double to) pure virtual
Computes the distance between two values.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::SignedDistanceBetweenTwoAngles, and Antipatrea::SignedDistanceBetweenTwoNumbers.
Referenced by ~SignedDistanceBetweenTwoValues().
The documentation for this class was generated from the following file:
SignedDistanceBetweenTwoValues.hpp