Antipatrea::ProximityResults< Key > Class Template Reference
Antipatrea::ProximityResults< Key > Class Template Reference
#include <ProximityResults.hpp>
Public Member Functions
ProximityResults (void)
~ProximityResults (void)
void SetNrNeighborsAndRange (const int n, const double range)
double GetMaxDistance (void) const
int GetSize (void) const
int GetNrResults (void) const
Key GetKey (const int i) const
double GetDistance (const int i) const
void Insert (const Key key, const double d)
void Clear (void)
Protected Attributes
std::vector< Key > m_keys
std::vector< double > m_dists
int m_nrKeysInserted
Constructor & Destructor Documentation
ProximityResults()
template<typename Key> Antipatrea::ProximityResults< Key >::ProximityResults (void) inline
References Antipatrea::ProximityResults< Key >::m_nrKeysInserted.
~ProximityResults()
template<typename Key> Antipatrea::ProximityResults< Key >::~ProximityResults (void) inline
Member Function Documentation
SetNrNeighborsAndRange()
template<typename Key> void Antipatrea::ProximityResults< Key >::SetNrNeighborsAndRange (const int n, const double range) inline
References Antipatrea::ProximityResults< Key >::m_dists, and Antipatrea::ProximityResults< Key >::m_keys.
Referenced by Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors(), and Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors().
GetMaxDistance()
template<typename Key> double Antipatrea::ProximityResults< Key >::GetMaxDistance (void) const inline
References Antipatrea::ProximityResults< Key >::m_dists.
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors(), and Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Neighbors().
GetSize()
template<typename Key> int Antipatrea::ProximityResults< Key >::GetSize (void) const inline
References Antipatrea::ProximityResults< Key >::m_keys.
GetNrResults()
template<typename Key> int Antipatrea::ProximityResults< Key >::GetNrResults (void) const inline
References Antipatrea::ProximityResults< Key >::m_keys, and Antipatrea::ProximityResults< Key >::m_nrKeysInserted.
Referenced by Antipatrea::Proximity< int, Antipatrea::SamplingBasedPlanner * >::Neighbor().
GetKey()
template<typename Key> Key Antipatrea::ProximityResults< Key >::GetKey (const int i) const inline
References Antipatrea::ProximityResults< Key >::m_keys.
Referenced by Antipatrea::Proximity< int, Antipatrea::SamplingBasedPlanner * >::Neighbor().
GetDistance()
template<typename Key> double Antipatrea::ProximityResults< Key >::GetDistance (const int i) const inline
References Antipatrea::ProximityResults< Key >::m_dists.
Referenced by Antipatrea::Proximity< int, Antipatrea::SamplingBasedPlanner * >::Neighbor().
Insert()
template<typename Key> void Antipatrea::ProximityResults< Key >::Insert (const Key key, const double d) inline
References Antipatrea::ProximityResults< Key >::m_dists, Antipatrea::ProximityResults< Key >::m_keys, and Antipatrea::ProximityResults< Key >::m_nrKeysInserted.
Referenced by Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors(), and Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Neighbors().
Clear()
template<typename Key> void Antipatrea::ProximityResults< Key >::Clear (void) inline
References Antipatrea::ProximityResults< Key >::m_dists, Antipatrea::ProximityResults< Key >::m_keys, and Antipatrea::ProximityResults< Key >::m_nrKeysInserted.
Referenced by Antipatrea::ProximityBruteForce< Key, DistFnData >::Neighbors(), and Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors().
Member Data Documentation
m_keys
template<typename Key> std::vector<Key> Antipatrea::ProximityResults< Key >::m_keys protected
Referenced by Antipatrea::ProximityResults< Key >::Clear(), Antipatrea::ProximityResults< Key >::GetKey(), Antipatrea::ProximityResults< Key >::GetNrResults(), Antipatrea::ProximityResults< Key >::GetSize(), Antipatrea::ProximityResults< Key >::Insert(), and Antipatrea::ProximityResults< Key >::SetNrNeighborsAndRange().
m_dists
template<typename Key> std::vector<double> Antipatrea::ProximityResults< Key >::m_dists protected
Referenced by Antipatrea::ProximityResults< Key >::Clear(), Antipatrea::ProximityResults< Key >::GetDistance(), Antipatrea::ProximityResults< Key >::GetMaxDistance(), Antipatrea::ProximityResults< Key >::Insert(), and Antipatrea::ProximityResults< Key >::SetNrNeighborsAndRange().
m_nrKeysInserted
template<typename Key> int Antipatrea::ProximityResults< Key >::m_nrKeysInserted protected
Referenced by Antipatrea::ProximityResults< Key >::Clear(), Antipatrea::ProximityResults< Key >::GetNrResults(), Antipatrea::ProximityResults< Key >::Insert(), and Antipatrea::ProximityResults< Key >::ProximityResults().
The documentation for this class was generated from the following file:
ProximityResults.hpp