Antipatrea::ProximityGNAT< Key, DistFnData >::Node Class Reference
Antipatrea::ProximityGNAT< Key, DistFnData >::Node Class Reference
#include <ProximityGNAT.hpp>
Public Member Functions
Node (Node *const parent, const int indexInParent)
virtual ~Node (void)
bool ShouldExpand (ProximityGNAT< Key, DistFnData > *const gnat) const
void Expand (ProximityGNAT< Key, DistFnData > *const gnat)
void Partition (ProximityGNAT< Key, DistFnData > *const gnat)
void InsertKey (ProximityGNAT< Key, DistFnData > *const gnat, const Key key)
void Neighbors (ProximityGNAT< Key, DistFnData > *const gnat, const Key qkey, ProximityResults< Key > &results)
Public Attributes
Node * m_parent
int m_indexInParent
int m_degree
std::vector< Key > m_keys
std::vector< InnerData * > m_inner
Constructor & Destructor Documentation
template<typename Key, typename DistFnData> Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Node (Node *const parent, const int indexInParent) inline
template<typename Key, typename DistFnData> virtual Antipatrea::ProximityGNAT< Key, DistFnData >::Node::~Node (void) inline virtual
Member Function Documentation
template<typename Key, typename DistFnData> bool Antipatrea::ProximityGNAT< Key, DistFnData >::Node::ShouldExpand (ProximityGNAT< Key, DistFnData > *const gnat) const inline
References Antipatrea::Proximity< Key, DistFnData >::m_keys, and Antipatrea::ProximityGNAT< Key, DistFnData >::m_maxNrPtsInLeaf.
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::ConstructDataStructure(), and Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Expand().
template<typename Key, typename DistFnData> void Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Expand (ProximityGNAT< Key, DistFnData > *const gnat) inline
References Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Expand(), Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::InnerData(), Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_child, and Antipatrea::ProximityGNAT< Key, DistFnData >::Node::ShouldExpand().
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::ConstructDataStructure(), and Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Expand().
template<typename Key, typename DistFnData> void Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Partition (ProximityGNAT< Key, DistFnData > *const gnat) inline
References Antipatrea::ProximityGNAT< Key, DistFnData >::EnsureDists(), Antipatrea::ProximityGNAT< Key, DistFnData >::KCenters(), Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_center, Antipatrea::ProximityGNAT< Key, DistFnData >::m_centers, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_child, Antipatrea::ProximityGNAT< Key, DistFnData >::m_dists, Antipatrea::Proximity< Key, DistFnData >::m_keys, Antipatrea::ProximityGNAT< Key, DistFnData >::Node::m_keys, Antipatrea::ProximityGNAT< Key, DistFnData >::m_maxDegree, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_maxRadius, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_maxRange, Antipatrea::ProximityGNAT< Key, DistFnData >::m_minDegree, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_minRadius, and Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_minRange.
template<typename Key, typename DistFnData> void Antipatrea::ProximityGNAT< Key, DistFnData >::Node::InsertKey (ProximityGNAT< Key, DistFnData > *const gnat, const Key key) inline
References Antipatrea::Proximity< Key, DistFnData >::m_distFn, Antipatrea::Proximity< Key, DistFnData >::m_distFnData, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_distToCenter, Antipatrea::Proximity< Key, DistFnData >::m_keys, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_maxRadius, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_maxRange, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_minRadius, and Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_minRange.
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::AddKey().
template<typename Key, typename DistFnData> void Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Neighbors (ProximityGNAT< Key, DistFnData > *const gnat, const Key qkey, ProximityResults< Key > & results) inline
References Antipatrea::ProximityResults< Key >::GetMaxDistance(), Antipatrea::ProximityResults< Key >::Insert(), Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_center, Antipatrea::Proximity< Key, DistFnData >::m_distFn, Antipatrea::Proximity< Key, DistFnData >::m_distFnData, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_distToCenter, Antipatrea::Proximity< Key, DistFnData >::m_keys, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_maxRadius, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_maxRange, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_minRadius, Antipatrea::ProximityGNAT< Key, DistFnData >::InnerData::m_minRange, Antipatrea::ProximityGNAT< Key, DistFnData >::m_perm, and Antipatrea::ProximityGNAT< Key, DistFnData >::m_scheduler.
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::Neighbors().
Member Data Documentation
template<typename Key, typename DistFnData> Node* Antipatrea::ProximityGNAT< Key, DistFnData >::Node::m_parent
template<typename Key, typename DistFnData> int Antipatrea::ProximityGNAT< Key, DistFnData >::Node::m_indexInParent
template<typename Key, typename DistFnData> int Antipatrea::ProximityGNAT< Key, DistFnData >::Node::m_degree
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::ConstructDataStructure().
template<typename Key, typename DistFnData> std::vector<Key> Antipatrea::ProximityGNAT< Key, DistFnData >::Node::m_keys
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::ConstructDataStructure(), and Antipatrea::ProximityGNAT< Key, DistFnData >::Node::Partition().
template<typename Key, typename DistFnData> std::vector<InnerData *> Antipatrea::ProximityGNAT< Key, DistFnData >::Node::m_inner
The documentation for this class was generated from the following file:
ProximityGNAT.hpp