Antipatrea::FELTRCell Class Reference
Antipatrea::FELTRCell Class Reference
Implement the FELTR algorithm. See IJRR (2010) Shehu, Olson Guiding the Search for Native-like Protein Conformations with an Ab-Initio Tree-based exploration and Olson, Molloy, Shehu In Search of the Protein Native State with a Probabilistic Sampling Approach (JBCC 2011).
#include <FELTRRegion.hpp>
Public Member Functions
FELTRCell (void)
virtual ~FELTRCell (void)
int SelectVertex (void)
Select a vertex from the cell. The vid is returned.
void SetId (unsigned int pId)
Store the scalar ID of the cell.
unsigned int GetId ()
void IncNew (int inc=1)
int GetNrSelections (void) const
return the number of times this cell has been selected.
int GetNrConfs (void) const
return the number of cfgs within this cell.
double GetWeight (void) const
Get the weight of this cell..
void AddVertex (int vid, const Cfg *cfg)
Add a vertex to the cell and adjust the weight.
bool SimilarCfgExists (Cfg *const cfg)
Return true iff a similar cfg already exists within the cell. Similarity is defined by the distance function and the user specified threshold.
Protected Member Functions
void UpdateWeightOnSelection (const int nsel)
Update the weight of the cell based on it being selected.
void UpdateWeightOnInsert ()
void UpdateWeight (void)
Protected Attributes
int weightType
int m_nsel
double m_weight
int m_nconfs
double m_threshold
Selector< int > m_insideCellSelector
unsigned int m_reductionCount
std::vector< const Cfg * > m_cfgs
int m_newPaths
int m_id
Detailed Description
Implement the FELTR algorithm. See IJRR (2010) Shehu, Olson Guiding the Search for Native-like Protein Conformations with an Ab-Initio Tree-based exploration and Olson, Molloy, Shehu In Search of the Protein Native State with a Probabilistic Sampling Approach (JBCC 2011).
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
Each energy region is discretized into a set of 3d cells based on the cfg's USR coordinates.
Constructor & Destructor Documentation
FELTRCell()
Antipatrea::FELTRCell::FELTRCell (void) inline
~FELTRCell()
virtual Antipatrea::FELTRCell::~FELTRCell (void) inline virtual
References SelectVertex().
Member Function Documentation
SelectVertex()
int Antipatrea::FELTRCell::SelectVertex (void)
Select a vertex from the cell. The vid is returned.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by Antipatrea::FELTRRegion::GetWeight(), and ~FELTRCell().
SetId()
void Antipatrea::FELTRCell::SetId (unsigned int pId) inline
Store the scalar ID of the cell.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_id.
GetId()
unsigned int Antipatrea::FELTRCell::GetId () inline
References m_id.
IncNew()
void Antipatrea::FELTRCell::IncNew (int inc = 1) inline
References m_newPaths.
GetNrSelections()
int Antipatrea::FELTRCell::GetNrSelections (void) const inline
return the number of times this cell has been selected.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_nsel.
GetNrConfs()
int Antipatrea::FELTRCell::GetNrConfs (void) const inline
return the number of cfgs within this cell.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_nconfs.
GetWeight()
double Antipatrea::FELTRCell::GetWeight (void) const inline
Get the weight of this cell..
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References AddVertex(), m_weight, and SimilarCfgExists().
AddVertex()
void Antipatrea::FELTRCell::AddVertex (int vid, const Cfg * cfg)
Add a vertex to the cell and adjust the weight.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetWeight(), and Antipatrea::FELTRRegion::~FELTRRegion().
SimilarCfgExists()
bool Antipatrea::FELTRCell::SimilarCfgExists (Cfg *const cfg)
Return true iff a similar cfg already exists within the cell. Similarity is defined by the distance function and the user specified threshold.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by GetWeight().
UpdateWeightOnSelection()
void Antipatrea::FELTRCell::UpdateWeightOnSelection (const int nsel) inline protected
Update the weight of the cell based on it being selected.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References m_nsel, and UpdateWeight().
UpdateWeightOnInsert()
void Antipatrea::FELTRCell::UpdateWeightOnInsert () inline protected
References m_nconfs, and UpdateWeight().
UpdateWeight()
void Antipatrea::FELTRCell::UpdateWeight (void) inline protected
References m_nconfs, m_nsel, and m_weight.
Referenced by Antipatrea::FELTRRegion::UpdateWeightOnEnergy(), UpdateWeightOnInsert(), and UpdateWeightOnSelection().
Member Data Documentation
weightType
int Antipatrea::FELTRCell::weightType protected
m_nsel
int Antipatrea::FELTRCell::m_nsel protected
Referenced by GetNrSelections(), Antipatrea::FELTRRegion::GetNrSelections(), UpdateWeight(), UpdateWeightOnSelection(), and Antipatrea::FELTRRegion::UpdateWeightOnSelection().
m_weight
double Antipatrea::FELTRCell::m_weight protected
Referenced by GetWeight(), Antipatrea::FELTRRegion::GetWeight(), UpdateWeight(), Antipatrea::FELTRRegion::UpdateWeightNORM(), and Antipatrea::FELTRRegion::UpdateWeightQUAD().
m_nconfs
int Antipatrea::FELTRCell::m_nconfs protected
Referenced by GetNrConfs(), UpdateWeight(), and UpdateWeightOnInsert().
m_threshold
double Antipatrea::FELTRCell::m_threshold protected
m_insideCellSelector
Selector<int> Antipatrea::FELTRCell::m_insideCellSelector protected
m_reductionCount
unsigned int Antipatrea::FELTRCell::m_reductionCount protected
m_cfgs
std::vector<const Cfg *> Antipatrea::FELTRCell::m_cfgs protected
m_newPaths
int Antipatrea::FELTRCell::m_newPaths protected
Referenced by IncNew(), and Antipatrea::FELTRRegion::IncNew().
m_id
int Antipatrea::FELTRCell::m_id protected
Referenced by GetId(), Antipatrea::FELTRRegion::GetId(), and SetId().
The documentation for this class was generated from the following file:
FELTRRegion.hpp