Antipatrea::Reader Class Reference
Antipatrea::Reader Class Reference abstract
Interface for reading from an input stream.
#include <Reader.hpp>
Public Member Functions
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
virtual std::istream & Read (std::istream &in)=0
Read the content from the input stream.
Static Public Member Functions
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Detailed Description
Interface for reading from an input stream.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Reader()
Antipatrea::Reader::Reader (void) inline
~Reader()
virtual Antipatrea::Reader::~Reader (void) inline virtual
References Read(), ReadDouble(), and ReadFromFile().
Member Function Documentation
ReadDouble()
static std::istream& Antipatrea::Reader::ReadDouble (std::istream & in, double & val) static
Read a double value from the input stream.
Author
Erion Plaku, Amarda Shehu
Remarks
ReadDouble will read not only double values but also inf, which will be assigned the value INFINITY.
Referenced by ~Reader().
ReadFromFile()
virtual void Antipatrea::Reader::ReadFromFile (const char fname[], std::ios_base::openmode mode = std::ios_base::in) virtual
Open a file for reading, read the content, and then close the file.
Author
Erion Plaku, Amarda Shehu
Remarks
The file is opened in ios_base::in mode by default.
The function Read is used to read the content from the file.
Referenced by ~Reader().
Read()
virtual std::istream& Antipatrea::Reader::Read (std::istream & in) pure virtual
Read the content from the input stream.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::Scene2D, Antipatrea::SamplingBasedPlanner, Antipatrea::PlannerSolution, Antipatrea::Params, and Antipatrea::Stats.
Referenced by ~Reader().
The documentation for this class was generated from the following file:
Reader.hpp