Antipatrea::Setup Class Reference
Antipatrea::Setup Class Reference abstract
Facilitate setting up the planning problem as well as the planner and its components.
#include <Setup.hpp>
Public Member Functions
Setup (void)
virtual ~Setup (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void Prepare (Params &params)=0
Create new instances, setup pointers, and setup the parameters.
virtual void Test (void)
Write whatever you would like for testing purposes.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void OnNewInstance (Component *const comp)
Add the instance to the set of component instances.
virtual void NewInstances (Params &params)
Create all the new instances.
virtual void SetupPointers (void)
Setup the component pointers.
virtual void NewCfgAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewGoalAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgManager (Params &params)
Create a new instance for the indicated component.
virtual void NewSignedDistanceBetweenTwoValues (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgDistance (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgEnergyEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgForwardKinematics (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgImprover (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgProjector (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgSampler (Params &params)
Create a new instance for the indicated component.
virtual void NewEdgeCostEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgOffspringGenerator (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerProblem (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerSolution (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerGraph (Params &params)
Create a new instance for the indicated component.
virtual void NewSamplingBasedPlanner (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointersComponent (Component *const comp)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersGoalAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgManager (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgDistance (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSignedDistanceBetweenTwoValues (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgEnergyEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgForwardKinematics (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgImprover (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgProjector (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgSampler (void)
Setup the pointers for the indicated component.
virtual void SetupPointersEdgeCostEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgOffspringGenerator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerProblem (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerSolution (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerGraph (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSamplingBasedPlanner (void)
Setup the pointers for the indicated component.
virtual void SetupFromParams (Params &params)
Setup the paramater values of each component instance using the user-provided parameters.
Protected Attributes
std::vector< Component * > m_components
Component instances.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Facilitate setting up the planning problem as well as the planner and its components.
Author
Erion Plaku, Amarda Shehu
Remarks
Setup creates instances of the planning components based on keywords provided by the user or default settings when the user does not provide any keywords.
Only one instance per class is created.
After creating the components, Setup sets the pointers so that components/planners that depend on, for example, CfgDistance will have the CfgDistance pointer set to the CfgDistance instance created in the first step.
After setting the pointers, Setup iterates over all the instances that were created in step 1, and calls the function SetupFromParams in order to set the parameter values for each instance.
Constructor & Destructor Documentation
Antipatrea::Setup::Setup (void) inline
virtual Antipatrea::Setup::~Setup (void) inline virtual
References CheckSetup(), Info(), m_components, and Prepare().
Member Function Documentation
virtual bool Antipatrea::Setup::CheckSetup (void) const virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
Referenced by ~Setup().
virtual void Antipatrea::Setup::Info (const char prefix[]) const virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Referenced by ~Setup().
virtual void Antipatrea::Setup::Prepare (Params & params) pure virtual
Create new instances, setup pointers, and setup the parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Do everything that needs to be done in order to setup the planning problem, the planner, and its components.
Implemented in Antipatrea::SetupRosetta, Antipatrea::SetupChain2D, and Antipatrea::SetupPoint2D.
Referenced by ~Setup().
virtual void Antipatrea::Setup::Test (void) inline virtual
Write whatever you would like for testing purposes.
Author
Erion Plaku, Amarda Shehu
Remarks
Add code to test various components.
Reimplemented in Antipatrea::SetupRosetta.
virtual void Antipatrea::Setup::OnNewInstance (Component *const comp) inline protected virtual
Add the instance to the set of component instances.
Author
Erion Plaku, Amarda Shehu
References m_components, NewCfgAcceptor(), NewCfgDistance(), NewCfgEnergyEvaluator(), NewCfgForwardKinematics(), NewCfgImprover(), NewCfgManager(), NewCfgOffspringGenerator(), NewCfgProjector(), NewCfgSampler(), NewEdgeCostEvaluator(), NewGoalAcceptor(), NewInstances(), NewPlannerGraph(), NewPlannerProblem(), NewPlannerSolution(), NewSamplingBasedPlanner(), NewSignedDistanceBetweenTwoValues(), and SetupPointers().
Referenced by Antipatrea::SetupPoint2D::NewCfgAcceptor(), Antipatrea::SetupChain2D::NewCfgAcceptor(), Antipatrea::SetupRosetta::NewCfgEnergyEvaluator(), Antipatrea::SetupChain2D::NewCfgForwardKinematics(), Antipatrea::SetupRosetta::NewCfgForwardKinematics(), Antipatrea::SetupRosetta::NewCfgImprover(), Antipatrea::SetupRosetta::NewCfgOffspringGenerator(), Antipatrea::SetupPoint2D::NewCfgProjector(), Antipatrea::SetupChain2D::NewCfgProjector(), Antipatrea::SetupRosetta::NewCfgProjector(), Antipatrea::SetupPoint2D::NewCfgSampler(), Antipatrea::SetupRosetta::NewCfgSampler(), and Antipatrea::Setup2D::NewScene2D().
virtual void Antipatrea::Setup::NewInstances (Params & params) protected virtual
Create all the new instances.
Author
Erion Plaku, Amarda Shehu
Remarks
Function calls all the specific New functions listed below, e.g., NewCfgAcceptor, NewGoalAcceptor, and so on.
Reimplemented in Antipatrea::Setup2D.
Referenced by Antipatrea::Setup2D::NewInstances(), and OnNewInstance().
virtual void Antipatrea::Setup::SetupPointers (void) protected virtual
Setup the component pointers.
Author
Erion Plaku, Amarda Shehu
Remarks
After creating the components, Setup sets the pointers so that components/planners that depend on, for example, CfgDistance will have the CfgDistance pointer set to the CfgDistance instance created when NewInstances() was called.
Reimplemented in Antipatrea::Setup2D.
Referenced by OnNewInstance(), and Antipatrea::Setup2D::SetupPointers().
virtual void Antipatrea::Setup::NewCfgAcceptor (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupChain2D, and Antipatrea::SetupPoint2D.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewGoalAcceptor (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewCfgManager (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewSignedDistanceBetweenTwoValues (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewCfgDistance (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewCfgEnergyEvaluator (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupRosetta.
Referenced by Antipatrea::SetupRosetta::NewCfgEnergyEvaluator(), and OnNewInstance().
virtual void Antipatrea::Setup::NewCfgForwardKinematics (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupRosetta, and Antipatrea::SetupChain2D.
Referenced by Antipatrea::SetupRosetta::NewCfgForwardKinematics(), and OnNewInstance().
virtual void Antipatrea::Setup::NewCfgImprover (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupRosetta.
Referenced by Antipatrea::SetupRosetta::NewCfgImprover(), and OnNewInstance().
virtual void Antipatrea::Setup::NewCfgProjector (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupRosetta, Antipatrea::SetupChain2D, and Antipatrea::SetupPoint2D.
Referenced by Antipatrea::SetupRosetta::NewCfgProjector(), and OnNewInstance().
virtual void Antipatrea::Setup::NewCfgSampler (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupRosetta, and Antipatrea::SetupPoint2D.
Referenced by Antipatrea::SetupRosetta::NewCfgSampler(), and OnNewInstance().
virtual void Antipatrea::Setup::NewEdgeCostEvaluator (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewCfgOffspringGenerator (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Reimplemented in Antipatrea::SetupRosetta.
Referenced by Antipatrea::SetupRosetta::NewCfgOffspringGenerator(), and OnNewInstance().
virtual void Antipatrea::Setup::NewPlannerProblem (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewPlannerSolution (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewPlannerGraph (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::NewSamplingBasedPlanner (Params & params) protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
Referenced by OnNewInstance().
virtual void Antipatrea::Setup::SetupPointersComponent (Component *const comp) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
References SetupFromParams(), SetupPointersCfgAcceptor(), SetupPointersCfgDistance(), SetupPointersCfgEnergyEvaluator(), SetupPointersCfgForwardKinematics(), SetupPointersCfgImprover(), SetupPointersCfgManager(), SetupPointersCfgOffspringGenerator(), SetupPointersCfgProjector(), SetupPointersCfgSampler(), SetupPointersEdgeCostEvaluator(), SetupPointersGoalAcceptor(), SetupPointersPlannerGraph(), SetupPointersPlannerProblem(), SetupPointersPlannerSolution(), SetupPointersSamplingBasedPlanner(), and SetupPointersSignedDistanceBetweenTwoValues().
Referenced by Antipatrea::Setup2D::SetupPointersScene2D().
virtual void Antipatrea::Setup::SetupPointersCfgAcceptor (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented in Antipatrea::SetupChain2D, and Antipatrea::SetupPoint2D.
Referenced by Antipatrea::SetupPoint2D::SetupPointersCfgAcceptor(), Antipatrea::SetupChain2D::SetupPointersCfgAcceptor(), and SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersGoalAcceptor (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgManager (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgDistance (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersSignedDistanceBetweenTwoValues (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgEnergyEvaluator (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented in Antipatrea::SetupRosetta.
Referenced by Antipatrea::SetupRosetta::SetupPointersCfgEnergyEvaluator(), and SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgForwardKinematics (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgImprover (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented in Antipatrea::SetupRosetta.
Referenced by Antipatrea::SetupRosetta::SetupPointersCfgImprover(), and SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgProjector (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented in Antipatrea::SetupRosetta, and Antipatrea::SetupChain2D.
Referenced by Antipatrea::SetupChain2D::SetupPointersCfgProjector(), Antipatrea::SetupRosetta::SetupPointersCfgProjector(), and SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgSampler (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented in Antipatrea::SetupRosetta, and Antipatrea::SetupPoint2D.
Referenced by Antipatrea::SetupPoint2D::SetupPointersCfgSampler(), Antipatrea::SetupRosetta::SetupPointersCfgSampler(), and SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersEdgeCostEvaluator (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersCfgOffspringGenerator (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Reimplemented in Antipatrea::SetupRosetta.
Referenced by Antipatrea::SetupRosetta::SetupPointersCfgOffspringGenerator(), and SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersPlannerProblem (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersPlannerSolution (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersPlannerGraph (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupPointersSamplingBasedPlanner (void) protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
Referenced by SetupPointersComponent().
virtual void Antipatrea::Setup::SetupFromParams (Params & params) protected virtual
Setup the paramater values of each component instance using the user-provided parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Iterate over all the component instances comp that were created by NewInstances and call the function comp->SetupFromParams(params) in order to set the parameter values for each instance.
Reimplemented from Antipatrea::Component.
Referenced by SetupPointersComponent().
Member Data Documentation
std::vector<Component*> Antipatrea::Setup::m_components protected
Component instances.
Author
Erion Plaku, Amarda Shehu
Referenced by OnNewInstance(), and ~Setup().
The documentation for this class was generated from the following file:
Setup.hpp