Antipatrea::CfgUniformSamplerInJointSpace Class Reference
Antipatrea::CfgUniformSamplerInJointSpace Class Reference
Sample a configuration by sampling each value at random from [-PI, PI].
#include <CfgUniformSamplerInJointSpace.hpp>
Public Member Functions
CfgUniformSamplerInJointSpace (void)
virtual ~CfgUniformSamplerInJointSpace (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual bool Sample (Cfg &cfg)
Sample a configuration by sampling each value at random from [-PI, PI].
Public Member Functions inherited from Antipatrea::CfgSampler
CfgSampler (void)
virtual ~CfgSampler (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Sample a configuration by sampling each value at random from [-PI, PI].
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgManager as it uses the configuration dimension.
Constructor & Destructor Documentation
CfgUniformSamplerInJointSpace()
Antipatrea::CfgUniformSamplerInJointSpace::CfgUniformSamplerInJointSpace (void) inline
~CfgUniformSamplerInJointSpace()
virtual Antipatrea::CfgUniformSamplerInJointSpace::~CfgUniformSamplerInJointSpace (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgUniformSamplerInJointSpace::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgUniformSamplerInJointSpace::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::ClassContainer(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, Antipatrea::Object::Name(), and Sample().
Sample()
virtual bool Antipatrea::CfgUniformSamplerInJointSpace::Sample (Cfg & cfg) virtual
Sample a configuration by sampling each value at random from [-PI, PI].
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgSampler.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgUniformSamplerInJointSpace.hpp