Antipatrea::Object Class Reference
Antipatrea::Object Class Reference
#include <Object.hpp>
Public Member Functions
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Static Public Member Functions
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Constructor & Destructor Documentation
Object()
Antipatrea::Object::Object (void) inline
~Object()
virtual Antipatrea::Object::~Object (void) inline virtual
Member Function Documentation
Name()
static const char* Antipatrea::Object::Name (const Object *const obj) inline static
Return the class name associated with the object.
Author
Erion Plaku, Amarda Shehu
Referenced by Antipatrea::CfgUniformSamplerInJointSpace::Info(), Antipatrea::EdgeCostEvaluatorBasedOnDistance::Info(), Antipatrea::CfgAcceptorPoint2D::Info(), Antipatrea::EdgeCostEvaluatorBasedOnMW::Info(), Antipatrea::CfgProjectorChain2D::Info(), Antipatrea::CfgSamplerPoint2D::Info(), Antipatrea::CfgOffspringGenerator::Info(), Antipatrea::CfgImproverRosetta::Info(), Antipatrea::CfgSamplerRosetta::Info(), Antipatrea::CfgEnergyEvaluatorRosetta::Info(), Info(), Antipatrea::CfgAcceptorBasedOnEnergy::Info(), Antipatrea::Planner::Info(), Antipatrea::EdgeCostEvaluatorBasedOnEnergy::Info(), Antipatrea::PlannerProblem::Info(), Antipatrea::CfgAcceptorChain2D::Info(), Antipatrea::CfgDistanceAtomRMSD::Info(), Antipatrea::CfgProjectorDeltaR::Info(), Antipatrea::CfgDistanceLp::Info(), Antipatrea::PlannerSolution::Info(), Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::Info(), Antipatrea::CfgProjectorUSREnergy::Info(), Antipatrea::CfgAcceptorBasedOnFixedMMC::Info(), Antipatrea::CfgAcceptorBasedOnMMC::Info(), Antipatrea::PGT::Info(), and Antipatrea::SamplingBasedPlanner::Info().
Info()
virtual void Antipatrea::Object::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented in Antipatrea::CfgOffspringGeneratorRosetta, Antipatrea::Sprint, Antipatrea::EST, Antipatrea::SamplingBasedPlanner, Antipatrea::CfgAcceptorBasedOnDistance, Antipatrea::Setup, Antipatrea::FELTR, Antipatrea::PGT, Antipatrea::PRM, Antipatrea::CfgProjector, Antipatrea::CfgAcceptorBasedOnFixedMMC, Antipatrea::CfgAcceptorBasedOnMMC, Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation, Antipatrea::CfgProjectorUSREnergy, Antipatrea::PlannerSolution, Antipatrea::TreeSamplingBasedPlanner, Antipatrea::CfgDistanceLp, Antipatrea::CfgManager, Antipatrea::CfgProjectorDeltaR, Antipatrea::CfgAcceptorChain2D, Antipatrea::CfgDistanceAtomRMSD, Antipatrea::EdgeCostEvaluatorBasedOnEnergy, Antipatrea::PlannerProblem, Antipatrea::CfgAcceptorBasedOnEnergy, Antipatrea::Planner, Antipatrea::CfgEnergyEvaluatorRosetta, Antipatrea::CfgImproverRosetta, Antipatrea::CfgSamplerRosetta, Antipatrea::CfgOffspringGenerator, Antipatrea::EdgeCostEvaluatorBasedOnMW, Antipatrea::CfgAcceptorPoint2D, Antipatrea::CfgProjectorChain2D, Antipatrea::CfgSamplerPoint2D, Antipatrea::Scene2D, Antipatrea::CfgOffspringGeneratorByGaussianPerturbation, Antipatrea::CfgUniformSamplerInJointSpace, Antipatrea::EdgeCostEvaluatorBasedOnDistance, Antipatrea::MolecularStructureRosetta, Antipatrea::Chain2D, and Antipatrea::Grid.
References Antipatrea::Logger::m_out, and Name().
Referenced by Antipatrea::CfgUniformSamplerInJointSpace::Info(), Antipatrea::EdgeCostEvaluatorBasedOnDistance::Info(), Antipatrea::CfgAcceptorPoint2D::Info(), Antipatrea::EdgeCostEvaluatorBasedOnMW::Info(), Antipatrea::Scene2D::Info(), Antipatrea::CfgSamplerPoint2D::Info(), Antipatrea::CfgOffspringGenerator::Info(), Antipatrea::CfgEnergyEvaluatorRosetta::Info(), Antipatrea::CfgImproverRosetta::Info(), Antipatrea::CfgSamplerRosetta::Info(), Antipatrea::Planner::Info(), Antipatrea::CfgAcceptorBasedOnEnergy::Info(), Antipatrea::EdgeCostEvaluatorBasedOnEnergy::Info(), Antipatrea::PlannerProblem::Info(), Antipatrea::CfgAcceptorChain2D::Info(), Antipatrea::CfgDistanceAtomRMSD::Info(), Antipatrea::CfgManager::Info(), Antipatrea::CfgDistanceLp::Info(), Antipatrea::PlannerSolution::Info(), Antipatrea::CfgAcceptorBasedOnFixedMMC::Info(), Antipatrea::CfgAcceptorBasedOnMMC::Info(), Antipatrea::CfgProjector::Info(), and Antipatrea::CfgAcceptorBasedOnDistance::Info().
The documentation for this class was generated from the following file:
Object.hpp