Antipatrea::GManagerRunPlannerPoint2D Class Reference
Antipatrea::GManagerRunPlannerPoint2D Class Reference
GUI for running a planner for a point robot operating in a 2D scene.
#include <GManagerRunPlannerPoint2D.hpp>
Public Member Functions
GManagerRunPlannerPoint2D (void)
virtual ~GManagerRunPlannerPoint2D (void)
virtual void DrawCfg (Cfg &cfg)
Draw the configuration.
virtual void DrawEdge (Cfg &cfg1, Cfg &cfg2)
Draw the edge connecting the two configurations.
Public Member Functions inherited from Antipatrea::GManagerRunPlanner2D
GManagerRunPlanner2D (void)
virtual ~GManagerRunPlanner2D (void)
virtual void SetupFromParams (Params &params)
virtual void HandleEventOnDisplay (void)
virtual bool HandleEventOnMouseLeftBtnDown (const int x, const int y)
virtual bool HandleEventOnMouseLeftBtnUp (const int x, const int y)
virtual bool HandleEventOnActiveMouseMove (int x, int y)
virtual bool HandleEventOnMenu (const int item)
Public Member Functions inherited from Antipatrea::GManagerRunPlanner
GManagerRunPlanner (void)
virtual ~GManagerRunPlanner (void)
virtual bool HandleEventOnNormalKeyPress (const int key)
virtual void HandleEventOnTimer (void)
Public Member Functions inherited from Antipatrea::GManager
GManager (void)
virtual ~GManager (void)
virtual void Help (void)
virtual void MainLoop (const char *const title, const int width=1000, const int height=600)
virtual bool HandleEventOnPassiveMouseMove (const int x, const int y)
virtual bool HandleEventOnSpecialKeyPress (const int key)
virtual bool HandleEventOnNormalKeyUp (const int key)
virtual bool HandleEventOnSpecialKeyUp (const int key)
virtual bool HandleEventOnIdle (void)
virtual double GetValue (const int i)
virtual void SetValue (const int i, const double val)
Additional Inherited Members
Public Types inherited from Antipatrea::GManager
enum {
INDEX_MINX,
INDEX_MINY,
INDEX_MAXX,
INDEX_MAXY,
INDEX_ORTHO_NEAR_PLANE,
INDEX_ORTHO_FAR_PLANE,
NR_INDICES
}
Static Public Member Functions inherited from Antipatrea::GManager
static void MousePosFromScreenToWorld (const int x, const int y, double *const wx, double *const wy, double *const wz)
Public Attributes inherited from Antipatrea::GManagerRunPlanner
Setup * m_setup
Pointer to the setup data structure, which contains pointers to the planning problem, the motion planner and its components.
Protected Types inherited from Antipatrea::GManagerRunPlanner
enum { FLAG_PAUSE = 1 }
Protected Member Functions inherited from Antipatrea::GManagerRunPlanner2D
virtual void MenuOptions (void)
Static Protected Member Functions inherited from Antipatrea::GManager
static void CallbackEventOnActiveMouseMove (int x, int y)
static void CallbackEventOnPassiveMouseMove (int x, int y)
static void CallbackEventOnMouse (int button, int state, int x, int y)
static void CallbackEventOnTimer (int id)
static void CallbackEventOnMenu (int item)
static void CallbackEventOnSpecialKeyPress (int key, int x, int y)
static void CallbackEventOnNormalKeyPress (unsigned char key, int x, int y)
static void CallbackEventOnSpecialKeyUp (int key, int x, int y)
static void CallbackEventOnNormalKeyUp (unsigned char key, int x, int y)
static void CallbackEventOnDisplay (void)
static void CallbackEventOnIdle (void)
static int CreateMenu (void)
static void SetMenu (const int menu)
static void AddSubMenu (const char name[], const int item)
static void AddMenuEntry (const char name[], const int item)
static void ChangeToMenuEntry (const int pos, const char name[], const int item)
Protected Attributes inherited from Antipatrea::GManagerRunPlanner2D
int m_idMenuScene
int MENU_ITEM_SCENE_ADD_OBSTACLE
int MENU_ITEM_SCENE_EDIT_OBSTACLE
int MENU_ITEM_SCENE_MOVE_OBSTACLE
int MENU_ITEM_SCENE_REMOVE_OBSTACLE
int MENU_ITEM_SCENE_SAVE
int MENU_ITEM_SCENE_LOAD
int m_sceneSelObstacle
const char * m_sceneFile
Protected Attributes inherited from Antipatrea::GManagerRunPlanner
const char * m_plannerGraphFile
Flags m_flags
int m_solutionIndex
int m_idMenuMain
int m_idMenuPlanner
int MENU_ITEM_PLANNER_START
int MENU_ITEM_PLANNER_SOLVE
int MENU_ITEM_PLANNER_PRINT_GRAPH
int MENU_ITEM_PLANNER_READ_GRAPH
int MENU_ITEM_PLANNER_STATS
std::vector< Cfg * > m_cfgs
Protected Attributes inherited from Antipatrea::GManager
int m_idWindow
int m_timer
int m_mousePrevX
int m_mousePrevY
GCamera m_gCamera
Flags m_flags
int m_nrMenuItems
int m_menuSelItem
std::unordered_map< int, int > m_mapKeysToMenuItems
std::vector< double > m_values
Detailed Description
GUI for running a planner for a point robot operating in a 2D scene.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Antipatrea::GManagerRunPlannerPoint2D::GManagerRunPlannerPoint2D (void) inline
References Antipatrea::GManagerRunPlanner::m_setup.
virtual Antipatrea::GManagerRunPlannerPoint2D::~GManagerRunPlannerPoint2D (void) inline virtual
Member Function Documentation
virtual void Antipatrea::GManagerRunPlannerPoint2D::DrawCfg (Cfg & cfg) inline virtual
Draw the configuration.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::GManagerRunPlanner.
References Antipatrea::GDrawCircle2D(), and Antipatrea::Cfg::GetValues().
virtual void Antipatrea::GManagerRunPlannerPoint2D::DrawEdge (Cfg & cfg1, Cfg & cfg2) inline virtual
Draw the edge connecting the two configurations.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::GManagerRunPlanner.
References Antipatrea::GDrawSegment2D(), and Antipatrea::Cfg::GetValues().
The documentation for this class was generated from the following file:
GManagerRunPlannerPoint2D.hpp