Antipatrea::PRM Class Reference
Antipatrea::PRM Class Reference
Probabilistic RoadMap Method (PRM).
#include <PRM.hpp>
Public Member Functions
PRM (void)
virtual ~PRM (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
virtual int GetNrNeighbors (void) const
Get the number of neighbors.
virtual int GetBatchSizeToGenerateVertices (void) const
Get the number of acceptable configurations that need to be generated for each batch.
virtual double GetProbAllowCycles (void) const
Get the probability to allow cycles in the planner graph.
virtual void SetNrNeighbors (const int k)
Set the number of neighbors.
virtual void SetBatchSizeToGenerateVertices (const int n)
Set the number of acceptable configurations that need to be generated for each batch.
virtual void SetProbAllowCycles (const double p)
Set the probability to allow cycles in the planner graph.
virtual void Start (void)
Initialize PRM by adding the initial configuration and any goal configuration to the planner graph.
virtual bool Solve (const double tmax)
Populate the planner graph and connect neighboring configurations.
Public Member Functions inherited from Antipatrea::SamplingBasedPlanner
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual bool CheckSetup (void)
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Member Functions
virtual int AddVertex (Cfg *const cfg)
Add a new vertex to the graph with cfg as its associated configuration.
virtual int GenerateVertices (const int nrCfgs, const double tmax)
Use sampling to generate at most nrCfgs new vertices – stop earlier if the time limit is reached.
virtual int GenerateEdgesForRemainingVertices (const double tmax)
Generate edges for the newly added vertices.
virtual void GenerateEdgesForVertex (const int vid)
Compute the nearest neighbors for the vertex and attempt to generate an edge to each neighbor.
virtual bool GenerateEdge (const int vid1, const int vid2, const double d)
Generate the edge connecting these two vertices.
Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual PlannerVertex * NewVertex (void) const
Factory for creating new planner vertices.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Protected Attributes
int m_nrNeighbors
Number of neighbors.
int m_batchSizeToGenerateVertices
Number of acceptable configurations that need to be generated for each batch.
double m_probAllowCycles
Probability to allow cycles in the roadmap graph.
int m_nrRemainingToCompleteBatch
Internal variable to keep track of how many more vertices need to be generated to complete the batch (in case PRM reaches the time limit)
std::unordered_set< int > m_vidsToBeConnected
Vertices for which the nearest neighbors and edge connections have not yet been computed.
Protected Attributes inherited from Antipatrea::SamplingBasedPlanner
const int SAMPLING_PLANNER_VERBOSE_FULL = 3
constants for verbosity control
const int SAMPLING_PLANNER_VERBOSE_MED = 2
const int SAMPLING_PLANNER_VERBOSE_LOW = 1
const int SAMPLING_PLANNER_VERBOSE_NONE = 0
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
int m_verbosityFlag
verbosity flag
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Static Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Detailed Description
Probabilistic RoadMap Method (PRM).
Author
Erion Plaku, Amarda Shehu
Remarks
PRM requires access to an exact path generator (CfgOffspringGeneratorToTarget) to connect neighboring configurations and to PathAcceptor to determine whether those connections are valid.
PRM starts by adding the initial and goal configuration(s) to the planner graph.
The planner graph is further populated by generating acceptable configurations and adding those as vertices to the planner graph. The component CfgValidSampler is used to generate such configurations.
To capture the connectivity of the configuration space, attempts are made to connect neighboring configurations. A proximity data structure is used to compute several neighbors for each vertex according to the distance metric defined by CfgDistance. For each vertex pair (A, B), PathAcceptor and CfgOffspringGenerator are used to determine if the pair are connected with a valid path. If so, EdgeCostEvaluator is used to compute the cost of the edge (A, B) as well as of its reverse edge (B, A). Both edges, (A, B) and (B, A), are then added to the planner graph.
This process of populating the planner graph and connecting neighboring vertices is repeated until a solution is found (the initial vertex and a goal vertex belong to the same connected component) or a runtime limit is reached.
A parameter, m_batchSizeToGenerateVertices, governs how many (additional) vertices are generated before making (additional) attempts to connect neighboring configurations.
Another parameter, m_nrNeighbors, determines how many neighbors to compute for each vertex.
A third parameter, m_probAllowCycles, determines whether or not cycles should be allowed during the construction of the planner graph. When set to 0, cycles are not allowed. When set to 1, cycles are always allowed. For any other value, if a candidate edge (A, B) would result in a cycle and RandomUniformReal(0, 1) <= m_probAllowCycles, then the candidate edge (A, B) is ignored.
Note that cycles are only useful when interested in selecting the best among many solutions that could be computed by PRM.
If, however, the user is interested in just finding any solution, as quickly as possible, then cycles should not be allowed as they only increase the runtime (since PathAcceptor would be called on many more edges).
Constructor & Destructor Documentation
PRM()
Antipatrea::PRM::PRM (void) inline
~PRM()
virtual Antipatrea::PRM::~PRM (void) inline virtual
Member Function Documentation
Info()
virtual void Antipatrea::PRM::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::SamplingBasedPlanner.
References GetBatchSizeToGenerateVertices(), GetNrNeighbors(), GetProbAllowCycles(), Antipatrea::SamplingBasedPlanner::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::PRM::SetupFromParams (Params & params) inline virtual
Set the parameter values of the planner from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes SamplingBasedPlanner::SetupFromParams(params).
It then sets the number of neighbors, batch size, and probability to allow cycles (keywords Constants::KW_NrNeighbors, Constants::KW_BatchSizeToGenerateVertices, Constants::KW_ProbAllowCycles).
It uses the parameter group associated with the keyword Constants::KW_PEM.
The parameter value can be specified in a text file as, for example, PRM { NrNeighbors 10 BatchSizeToGenerateVertices 100 ProbAllowCycles 0.0 }
Reimplemented from Antipatrea::SamplingBasedPlanner.
References GetBatchSizeToGenerateVertices(), Antipatrea::Params::GetData(), GetNrNeighbors(), GetProbAllowCycles(), Antipatrea::Constants::KW_BatchSizeToGenerateVertices, Antipatrea::Constants::KW_NrNeighbors, Antipatrea::Constants::KW_PRM, Antipatrea::Constants::KW_ProbAllowCycles, SetBatchSizeToGenerateVertices(), SetNrNeighbors(), SetProbAllowCycles(), and Antipatrea::SamplingBasedPlanner::SetupFromParams().
GetNrNeighbors()
virtual int Antipatrea::PRM::GetNrNeighbors (void) const inline virtual
Get the number of neighbors.
Author
Erion Plaku, Amarda Shehu
References m_nrNeighbors.
Referenced by Info(), and SetupFromParams().
GetBatchSizeToGenerateVertices()
virtual int Antipatrea::PRM::GetBatchSizeToGenerateVertices (void) const inline virtual
Get the number of acceptable configurations that need to be generated for each batch.
Author
Erion Plaku, Amarda Shehu
References m_batchSizeToGenerateVertices.
Referenced by Info(), and SetupFromParams().
GetProbAllowCycles()
virtual double Antipatrea::PRM::GetProbAllowCycles (void) const inline virtual
Get the probability to allow cycles in the planner graph.
Author
Erion Plaku, Amarda Shehu
References m_probAllowCycles.
Referenced by Info(), and SetupFromParams().
SetNrNeighbors()
virtual void Antipatrea::PRM::SetNrNeighbors (const int k) inline virtual
Set the number of neighbors.
Author
Erion Plaku, Amarda Shehu
References m_nrNeighbors.
Referenced by SetupFromParams().
SetBatchSizeToGenerateVertices()
virtual void Antipatrea::PRM::SetBatchSizeToGenerateVertices (const int n) inline virtual
Set the number of acceptable configurations that need to be generated for each batch.
Author
Erion Plaku, Amarda Shehu
References m_batchSizeToGenerateVertices.
Referenced by SetupFromParams().
SetProbAllowCycles()
virtual void Antipatrea::PRM::SetProbAllowCycles (const double p) inline virtual
Set the probability to allow cycles in the planner graph.
Author
Erion Plaku, Amarda Shehu
References AddVertex(), GenerateEdge(), GenerateEdgesForRemainingVertices(), GenerateEdgesForVertex(), GenerateVertices(), m_probAllowCycles, Solve(), and Start().
Referenced by SetupFromParams().
Start()
virtual void Antipatrea::PRM::Start (void) virtual
Initialize PRM by adding the initial configuration and any goal configuration to the planner graph.
Author
Erion Plaku, Amarda Shehu
Remarks
PlannerProblem::GetInitialCfg is added as the initial configuration.
PlannerProblem::GetGoalAcceptor()->GetAnAcceptableCfg() is added as a goal configuration (if the function does not returns a NULL pointer);
This function should be called only once at the beginning after the problem and other components have been setup.
Reimplemented from Antipatrea::SamplingBasedPlanner.
Referenced by SetProbAllowCycles().
Solve()
virtual bool Antipatrea::PRM::Solve (const double tmax) virtual
Populate the planner graph and connect neighboring configurations.
Author
Erion Plaku, Amarda Shehu
Remarks
Solve should be called after Start.
Solve can be called repeatedly until a solution is found.
Solve returns true as soon as it finds a solution.
See the class description for more details on how the Solve is implemented in PRM.
Implements Antipatrea::Planner.
Referenced by SetProbAllowCycles().
AddVertex()
virtual int Antipatrea::PRM::AddVertex (Cfg *const cfg) protected virtual
Add a new vertex to the graph with cfg as its associated configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
The function returns the id of the new vertex.
The new vertex is also added to the set of vertices that need to be connected.
The function does not make a copy of cfg; it simply does pointer assignment.
The function does not check if cfg is already in the graph. It is the responsibility of the calling function to perform such a check (using FindCfg) if indeed there is a possibility that the same configuration is added to the graph multiple times (which even if it happened would not cause any errors).
Reimplemented from Antipatrea::SamplingBasedPlanner.
Referenced by SetProbAllowCycles().
GenerateVertices()
virtual int Antipatrea::PRM::GenerateVertices (const int nrCfgs, const double tmax) protected virtual
Use sampling to generate at most nrCfgs new vertices – stop earlier if the time limit is reached.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns the number of vertices that were generated.
Referenced by SetProbAllowCycles().
GenerateEdgesForRemainingVertices()
virtual int Antipatrea::PRM::GenerateEdgesForRemainingVertices (const double tmax) protected virtual
Generate edges for the newly added vertices.
Author
Erion Plaku, Amarda Shehu
Remarks
While there is time, do:
select a vertex from the set of those that need to be connected;
generate the edges for the selected vertex (using GenerateEdgesForVertex);
remove the selected vertex from the set of vertices that need to be connected.
Function returns the number of remaining vertices that still need to be connected.
Referenced by SetProbAllowCycles().
GenerateEdgesForVertex()
virtual void Antipatrea::PRM::GenerateEdgesForVertex (const int vid) protected virtual
Compute the nearest neighbors for the vertex and attempt to generate an edge to each neighbor.
Author
Erion Plaku, Amarda Shehu
Remarks
GenerateEdge is used to generate each edge from the vertex to a neighbor.
Referenced by SetProbAllowCycles().
GenerateEdge()
virtual bool Antipatrea::PRM::GenerateEdge (const int vid1, const int vid2, const double d) protected virtual
Generate the edge connecting these two vertices.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns true iff the edge was generated.
CfgOffspringGeneratorToTarget is used to define the path from the configuration associated with the vertex vid1 to the configuration associated with the vertex vid2.
PathAcceptor is used to determine whether or not such path is valid.
PathAcceptor uses the distance d (distance between the configurations associated with the vertices vid1 and vid2) and GetOneStepDistance() to determine an appropriate time-step resolution.
Referenced by SetProbAllowCycles().
Member Data Documentation
m_nrNeighbors
int Antipatrea::PRM::m_nrNeighbors protected
Number of neighbors.
Author
Erion Plaku, Amarda Shehu
Referenced by GetNrNeighbors(), and SetNrNeighbors().
m_batchSizeToGenerateVertices
int Antipatrea::PRM::m_batchSizeToGenerateVertices protected
Number of acceptable configurations that need to be generated for each batch.
Author
Erion Plaku, Amarda Shehu
Referenced by GetBatchSizeToGenerateVertices(), and SetBatchSizeToGenerateVertices().
m_probAllowCycles
double Antipatrea::PRM::m_probAllowCycles protected
Probability to allow cycles in the roadmap graph.
Author
Erion Plaku, Amarda Shehu
Referenced by GetProbAllowCycles(), and SetProbAllowCycles().
m_nrRemainingToCompleteBatch
int Antipatrea::PRM::m_nrRemainingToCompleteBatch protected
Internal variable to keep track of how many more vertices need to be generated to complete the batch (in case PRM reaches the time limit)
Author
Erion Plaku, Amarda Shehu
m_vidsToBeConnected
std::unordered_set<int> Antipatrea::PRM::m_vidsToBeConnected protected
Vertices for which the nearest neighbors and edge connections have not yet been computed.
Author
Erion Plaku, Amarda Shehu
The documentation for this class was generated from the following file:
PRM.hpp