Antipatrea::PlannerProblem Class Reference
Antipatrea::PlannerProblem Class Reference
The planning problem is defined by the initial configuration and a goal acceptor.
#include <PlannerProblem.hpp>
Public Member Functions
PlannerProblem (void)
virtual ~PlannerProblem (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual const Cfg * GetInitialCfg (void) const
Get a pointer to the initial configuration.
virtual Cfg * GetInitialCfg (void)
Get a pointer to the initial configuration.
virtual void SetInitialCfg (Cfg *const cfg)
Set the initial configuration.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
Cfg * m_cfgInit
Pointer to the initial configuration.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
The planning problem is defined by the initial configuration and a goal acceptor.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to GoalAcceptor to determine whether or not the goal has been reached.
Constructor & Destructor Documentation
Antipatrea::PlannerProblem::PlannerProblem (void) inline
virtual Antipatrea::PlannerProblem::~PlannerProblem (void) inline virtual
Author
Erion Plaku, Amarda Shehu
Remarks
Destructor deletes the initial configuration.
References m_cfgInit.
Member Function Documentation
virtual bool Antipatrea::PlannerProblem::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::PlannerProblem::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual const Cfg* Antipatrea::PlannerProblem::GetInitialCfg (void) const inline virtual
Get a pointer to the initial configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgInit.
virtual Cfg* Antipatrea::PlannerProblem::GetInitialCfg (void) inline virtual
Get a pointer to the initial configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgInit.
virtual void Antipatrea::PlannerProblem::SetInitialCfg (Cfg *const cfg) inline virtual
Set the initial configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgInit.
Member Data Documentation
Cfg* Antipatrea::PlannerProblem::m_cfgInit protected
Pointer to the initial configuration.
Author
Erion Plaku, Amarda Shehu
Referenced by GetInitialCfg(), SetInitialCfg(), and ~PlannerProblem().
The documentation for this class was generated from the following file:
PlannerProblem.hpp