Antipatrea::USRFactory Class Reference
Antipatrea::USRFactory Class Reference
Produce the Ultrafast Shape Recognization (USR) coordinates.
#include <USRFactory.hpp>
Public Member Functions
USRFactory ()
virtual ~USRFactory (void)
int GetCoordsSize ()
point GetPointAtIndex (const int i)
point GetCtd ()
point GetCst ()
point GetFct ()
point GetFtf ()
void outputReferences (FILE *outFp)
void outputCtd (FILE *outFp)
void outputCst (FILE *outFp)
void outputFct (FILE *outFp)
void outputFtf (FILE *outFp)
bool ProjectConfigCoordsToMomenta (point *configCoords, const int coordsSize, bool usingctd, bool usingcst, bool usingfct, bool usingftf, int nrMomenta, double *projState, int projSize)
bool ProjectConfigCoordsToFirstMomenta (point *configCoords, const int coordsSize, bool usingctd, bool usingcst, bool usingfct, bool usingftf, int nrMomenta, double *projState, int projSize)
bool ProjectConfigCoordsToMomentaInOrder (point *configCoords, const int coordsSize, bool usingctd, bool usingcst, bool usingfct, bool usingftf, int nrMomenta, double *projState, int projSize)
bool appendMomenta (char *outUSRFilename, double *projState, int projSize)
Protected Member Functions
void computeUSRReferences ()
void computeDsFromReferences ()
void computeMomenta ()
void computeDsFromctd ()
void computeMomentaFromctd ()
void computeDsFromcst ()
void computeMomentaFromcst ()
void computeDsFromfct ()
void computeMomentaFromfct ()
void computeDsFromftf ()
void computeMomentaFromftf ()
void outputPoint (FILE *outFp, point pt)
void computeDsFromReference (int indexOfReferencePoint, double *dsFromReferencePoint)
void computeMomentaOfDistribution (double *ds, double *momenta)
double computeMean (double *ds)
double computeVariance (double *ds, double mean)
double computeSkewness (double *ds, double variance)
Protected Attributes
int coordsSize
point * configCoords
point ctd
int indexOfcst
int indexOffct
int indexOfftf
double * dsFromctd
double * dsFromcst
double * dsFromfct
double * dsFromftf
Vector3Algebra::Vector3_t momentaFromctd
Vector3Algebra::Vector3_t momentaFromcst
Vector3Algebra::Vector3_t momentaFromfct
Vector3Algebra::Vector3_t momentaFromftf
Detailed Description
Produce the Ultrafast Shape Recognization (USR) coordinates.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
usingctd – centroid of the points usingcst – point closest to the ctd (centroid) usingfct – further point from ctd usingftf – further point from ftf
Constructor & Destructor Documentation
USRFactory()
Antipatrea::USRFactory::USRFactory ()
~USRFactory()
virtual Antipatrea::USRFactory::~USRFactory (void) virtual
Member Function Documentation
GetCoordsSize()
int Antipatrea::USRFactory::GetCoordsSize () inline
References coordsSize.
GetPointAtIndex()
point Antipatrea::USRFactory::GetPointAtIndex (const int i) inline
References configCoords, and Antipatrea::undefPoint.
Referenced by GetCst(), GetFct(), and GetFtf().
GetCtd()
point Antipatrea::USRFactory::GetCtd () inline
References ctd.
GetCst()
point Antipatrea::USRFactory::GetCst () inline
References GetPointAtIndex(), and indexOfcst.
GetFct()
point Antipatrea::USRFactory::GetFct () inline
References GetPointAtIndex(), and indexOffct.
GetFtf()
point Antipatrea::USRFactory::GetFtf () inline
References GetPointAtIndex(), and indexOfftf.
outputReferences()
void Antipatrea::USRFactory::outputReferences (FILE * outFp) inline
References indexOfcst, indexOffct, indexOfftf, outputCst(), outputCtd(), outputFct(), and outputFtf().
outputCtd()
void Antipatrea::USRFactory::outputCtd (FILE * outFp) inline
References ctd, and outputPoint().
Referenced by outputReferences().
outputCst()
void Antipatrea::USRFactory::outputCst (FILE * outFp) inline
References configCoords, indexOfcst, and outputPoint().
Referenced by outputReferences().
outputFct()
void Antipatrea::USRFactory::outputFct (FILE * outFp) inline
References configCoords, indexOffct, and outputPoint().
Referenced by outputReferences().
outputFtf()
void Antipatrea::USRFactory::outputFtf (FILE * outFp) inline
References configCoords, coordsSize, indexOfftf, outputPoint(), ProjectConfigCoordsToFirstMomenta(), ProjectConfigCoordsToMomenta(), and ProjectConfigCoordsToMomentaInOrder().
Referenced by outputReferences().
ProjectConfigCoordsToMomenta()
bool Antipatrea::USRFactory::ProjectConfigCoordsToMomenta (point * configCoords, const int coordsSize, bool usingctd, bool usingcst, bool usingfct, bool usingftf, int nrMomenta, double * projState, int projSize)
Referenced by outputFtf().
ProjectConfigCoordsToFirstMomenta()
bool Antipatrea::USRFactory::ProjectConfigCoordsToFirstMomenta (point * configCoords, const int coordsSize, bool usingctd, bool usingcst, bool usingfct, bool usingftf, int nrMomenta, double * projState, int projSize)
Referenced by outputFtf().
ProjectConfigCoordsToMomentaInOrder()
bool Antipatrea::USRFactory::ProjectConfigCoordsToMomentaInOrder (point * configCoords, const int coordsSize, bool usingctd, bool usingcst, bool usingfct, bool usingftf, int nrMomenta, double * projState, int projSize)
Referenced by outputFtf().
appendMomenta()
bool Antipatrea::USRFactory::appendMomenta (char * outUSRFilename, double * projState, int projSize) inline
References computeDsFromcst(), computeDsFromctd(), computeDsFromfct(), computeDsFromftf(), computeDsFromReferences(), computeMomenta(), computeMomentaFromcst(), computeMomentaFromctd(), computeMomentaFromfct(), computeMomentaFromftf(), and computeUSRReferences().
computeUSRReferences()
void Antipatrea::USRFactory::computeUSRReferences () protected
Referenced by appendMomenta().
computeDsFromReferences()
void Antipatrea::USRFactory::computeDsFromReferences () protected
Referenced by appendMomenta().
computeMomenta()
void Antipatrea::USRFactory::computeMomenta () protected
Referenced by appendMomenta().
computeDsFromctd()
void Antipatrea::USRFactory::computeDsFromctd () protected
Referenced by appendMomenta().
computeMomentaFromctd()
void Antipatrea::USRFactory::computeMomentaFromctd () protected
Referenced by appendMomenta().
computeDsFromcst()
void Antipatrea::USRFactory::computeDsFromcst () protected
Referenced by appendMomenta().
computeMomentaFromcst()
void Antipatrea::USRFactory::computeMomentaFromcst () protected
Referenced by appendMomenta().
computeDsFromfct()
void Antipatrea::USRFactory::computeDsFromfct () protected
Referenced by appendMomenta().
computeMomentaFromfct()
void Antipatrea::USRFactory::computeMomentaFromfct () protected
Referenced by appendMomenta().
computeDsFromftf()
void Antipatrea::USRFactory::computeDsFromftf () protected
Referenced by appendMomenta().
computeMomentaFromftf()
void Antipatrea::USRFactory::computeMomentaFromftf () protected
Referenced by appendMomenta().
outputPoint()
void Antipatrea::USRFactory::outputPoint (FILE * outFp, point pt) inline protected
References Antipatrea::point::x, Antipatrea::point::y, and Antipatrea::point::z.
Referenced by outputCst(), outputCtd(), outputFct(), and outputFtf().
computeDsFromReference()
void Antipatrea::USRFactory::computeDsFromReference (int indexOfReferencePoint, double * dsFromReferencePoint) protected
computeMomentaOfDistribution()
void Antipatrea::USRFactory::computeMomentaOfDistribution (double * ds, double * momenta) protected
computeMean()
double Antipatrea::USRFactory::computeMean (double * ds) protected
computeVariance()
double Antipatrea::USRFactory::computeVariance (double * ds, double mean) protected
computeSkewness()
double Antipatrea::USRFactory::computeSkewness (double * ds, double variance) protected
Member Data Documentation
coordsSize
int Antipatrea::USRFactory::coordsSize protected
Referenced by GetCoordsSize(), and outputFtf().
configCoords
point* Antipatrea::USRFactory::configCoords protected
Referenced by GetPointAtIndex(), outputCst(), outputFct(), and outputFtf().
ctd
point Antipatrea::USRFactory::ctd protected
Referenced by GetCtd(), and outputCtd().
indexOfcst
int Antipatrea::USRFactory::indexOfcst protected
Referenced by GetCst(), outputCst(), and outputReferences().
indexOffct
int Antipatrea::USRFactory::indexOffct protected
Referenced by GetFct(), outputFct(), and outputReferences().
indexOfftf
int Antipatrea::USRFactory::indexOfftf protected
Referenced by GetFtf(), outputFtf(), and outputReferences().
dsFromctd
double* Antipatrea::USRFactory::dsFromctd protected
dsFromcst
double * Antipatrea::USRFactory::dsFromcst protected
dsFromfct
double * Antipatrea::USRFactory::dsFromfct protected
dsFromftf
double * Antipatrea::USRFactory::dsFromftf protected
momentaFromctd
Vector3Algebra::Vector3_t Antipatrea::USRFactory::momentaFromctd protected
momentaFromcst
Vector3Algebra::Vector3_t Antipatrea::USRFactory::momentaFromcst protected
momentaFromfct
Vector3Algebra::Vector3_t Antipatrea::USRFactory::momentaFromfct protected
momentaFromftf
Vector3Algebra::Vector3_t Antipatrea::USRFactory::momentaFromftf protected
The documentation for this class was generated from the following file:
USRFactory.hpp