Antipatrea::Chain2D Class Reference
Antipatrea::Chain2D Class Reference
Forward kinematics for a chain in a 2D environment.
#include <Chain2D.hpp>
Public Member Functions
Chain2D (void)
virtual ~Chain2D (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual int GetNrJoints (void) const
Get the number of joints in the chain.
virtual int GetNrLinks (void) const
Get the number of links in the chain.
virtual double GetLinkStartX (const int i) const
Get the x-coordinate of the start position of the ith link.
virtual double GetLinkStartY (const int i) const
Get the y-coordinate of the start position of the ith link.
virtual double GetLinkEndX (const int i) const
Get the x-coordinate of the end position of the ith link.
virtual double GetLinkEndY (const int i) const
Get the y-coordinate of the end position of the ith link.
virtual double GetLinkTheta (const int i) const
Get the angle (in radians) associated with the ith link.
virtual double GetLinkLength (const int i) const
Get the length of the ith link.
virtual void RemoveAllLinks (void)
Remove all links from the chain.
virtual void AddLink (const double length)
Add one link with length length.
virtual void AddLinks (const int n, const double length)
Add n links, each having length length.
virtual void Draw (void)
Draw the chain in the current configuration.
Public Member Functions inherited from Antipatrea::CfgForwardKinematics
CfgForwardKinematics (void)
virtual ~CfgForwardKinematics (void)
virtual void CopyJointValues (const double vals[])
Copy the joint values.
virtual void FK (void)
Compute the forward kinematics if FLAG_RECOMPUTE_FK has been set.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void DoFK (void)
Implement the forward kinematics.
virtual void MatrixMultMatrix (const double M1[6], const double M2[6], double M[6])
Protected Member Functions inherited from Antipatrea::CfgForwardKinematics
virtual void OnValuesChanged (void)
Set FLAG_RECOMPUTE_FK when values change.
Protected Attributes
std::vector< double > m_lengths
Lengths for each link in the chain.
std::vector< double > m_positions
Positions for each link in the chain.
Protected Attributes inherited from Antipatrea::CfgForwardKinematics
std::vector< double > m_joints
Joint values.
Flags m_flags
Flags to keep track of status, e.g., whether or not FK should be recomputed.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Types inherited from Antipatrea::CfgForwardKinematics
enum { FLAG_RECOMPUTE_FK = 1 }
Detailed Description
Forward kinematics for a chain in a 2D environment.
Author
Erion Plaku, Amarda Shehu
Remarks
The start position of the first link is (0, 0).
Constructor & Destructor Documentation
Chain2D()
Antipatrea::Chain2D::Chain2D (void)
~Chain2D()
virtual Antipatrea::Chain2D::~Chain2D (void) virtual
Member Function Documentation
Info()
virtual void Antipatrea::Chain2D::Info (const char prefix[]) const virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
SetupFromParams()
virtual void Antipatrea::Chain2D::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Sets the number of links and the link length (keywords Constants::KW_Chain2D_NrLinks, Constants::KW_Chain2D_LinkLength).
It uses the parameter group associated with the keyword Constants::KW_Chain2D.
The parameter values can be specified in a text file as, for example, Chain2D { NrLinks 8 LinkLength 1.0 }
Reimplemented from Antipatrea::Component.
GetNrJoints()
virtual int Antipatrea::Chain2D::GetNrJoints (void) const inline virtual
Get the number of joints in the chain.
Author
Erion Plaku, Amarda Shehu
References Antipatrea::CfgForwardKinematics::m_joints.
Referenced by GetNrLinks().
GetNrLinks()
virtual int Antipatrea::Chain2D::GetNrLinks (void) const inline virtual
Get the number of links in the chain.
Author
Erion Plaku, Amarda Shehu
References GetNrJoints().
GetLinkStartX()
virtual double Antipatrea::Chain2D::GetLinkStartX (const int i) const inline virtual
Get the x-coordinate of the start position of the ith link.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrLinks() - 1.
References m_positions.
Referenced by GetLinkEndX().
GetLinkStartY()
virtual double Antipatrea::Chain2D::GetLinkStartY (const int i) const inline virtual
Get the y-coordinate of the start position of the ith link.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrLinks() - 1.
References m_positions.
Referenced by GetLinkEndY().
GetLinkEndX()
virtual double Antipatrea::Chain2D::GetLinkEndX (const int i) const inline virtual
Get the x-coordinate of the end position of the ith link.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrLinks() - 1.
References GetLinkStartX().
GetLinkEndY()
virtual double Antipatrea::Chain2D::GetLinkEndY (const int i) const inline virtual
Get the y-coordinate of the end position of the ith link.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrLinks() - 1.
References GetLinkStartY().
GetLinkTheta()
virtual double Antipatrea::Chain2D::GetLinkTheta (const int i) const inline virtual
Get the angle (in radians) associated with the ith link.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrLinks() - 1.
References Antipatrea::CfgForwardKinematics::m_joints.
GetLinkLength()
virtual double Antipatrea::Chain2D::GetLinkLength (const int i) const inline virtual
Get the length of the ith link.
Author
Erion Plaku, Amarda Shehu
Remarks
Function does not check if i is in the range 0 to GetNrLinks() - 1.
References AddLink(), AddLinks(), DoFK(), Draw(), m_lengths, MatrixMultMatrix(), and RemoveAllLinks().
RemoveAllLinks()
virtual void Antipatrea::Chain2D::RemoveAllLinks (void) virtual
Remove all links from the chain.
Author
Erion Plaku, Amarda Shehu
Referenced by GetLinkLength().
AddLink()
virtual void Antipatrea::Chain2D::AddLink (const double length) virtual
Add one link with length length.
Author
Erion Plaku, Amarda Shehu
Referenced by GetLinkLength().
AddLinks()
virtual void Antipatrea::Chain2D::AddLinks (const int n, const double length) virtual
Add n links, each having length length.
Author
Erion Plaku, Amarda Shehu
Referenced by GetLinkLength().
Draw()
virtual void Antipatrea::Chain2D::Draw (void) virtual
Draw the chain in the current configuration.
Author
Erion Plaku, Amarda Shehu
Referenced by GetLinkLength().
DoFK()
virtual void Antipatrea::Chain2D::DoFK (void) protected virtual
Implement the forward kinematics.
Author
Erion Plaku, Amarda Shehu
Remarks
This function always computes the forward kinematics, ignoring flag values.
Implements Antipatrea::CfgForwardKinematics.
Referenced by GetLinkLength().
MatrixMultMatrix()
virtual void Antipatrea::Chain2D::MatrixMultMatrix (const double M1[6], const double M2[6], double M[6]) protected virtual
Referenced by GetLinkLength().
Member Data Documentation
m_lengths
std::vector<double> Antipatrea::Chain2D::m_lengths protected
Lengths for each link in the chain.
Author
Erion Plaku, Amarda Shehu
Referenced by GetLinkLength().
m_positions
std::vector<double> Antipatrea::Chain2D::m_positions protected
Positions for each link in the chain.
Author
Erion Plaku, Amarda Shehu
Remarks
The start position of the first link is (0, 0).
Referenced by GetLinkStartX(), and GetLinkStartY().
The documentation for this class was generated from the following file:
Chain2D.hpp