Antipatrea::Params Class Reference
Antipatrea::Params Class Reference
Class to facilitate setting of parameter values.
#include <Params.hpp>
Classes
struct Data
Public Member Functions
Params (void)
virtual ~Params (void)
virtual Data * GetData (const char id[])
virtual const char * GetValue (const char id[], const char notFound[]=NULL)
virtual double GetValueAsDouble (const char id[], const double notFound=INFINITY)
virtual int GetValueAsInt (const char id[], const int notFound=INT_MAX)
virtual bool GetValueAsBool (const char id[], const bool notFound=false)
virtual void SetValue (const char id[], const char val[])
virtual void AddValue (const char id[], const char val[])
virtual void SetParams (const char id[], Params *const params)
virtual std::istream & Read (std::istream &in)
Read the content from the input stream.
virtual std::ostream & Print (std::ostream &out) const
Write to the output stream.
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Static Public Member Functions
static Params * GetSingleton (void)
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Protected Attributes
std::unordered_map< std::string, Data * > m_map
Static Protected Attributes
static Params * m_singleton
Detailed Description
Class to facilitate setting of parameter values.
Author
Erion Plaku, Amarda Shehu
Remarks
A parameter is defined by a keyword and the data associated with that keyword.
The data could be a single value, a list of values, or a group of parameters (pointer to an instance of Params).
The data is retrieved by using the keyword as the index.
After retrieving the data, the calling function can enumerate the list of values or access the group of parameters.
The values can be converted to strings, integers, doubles, or booleans.
The parameters can also be read from an input stream and written to an output stream. The format is as follows:
<Entries> := <Entry> | <Entry><Whitespace><Entries>
<Entry> := <Comment> | <ParamName><Data>
<Comment> := any line where the first character is #
<ParamName> := string (no spaces or other whitespaces)
<Data> := <SingleValue> | <ListOfValues> | <Group>
<SingleValue> := string
<ListOfValues> := [<Whitespace><Values><Whitespace>]
<Values> := <SingleValue> | <SingleValue> <Whitespace> <Values>
<Group> := {<Whitespace><Entries><Whitespace>}
<Whitespace> := any white space character, e.g, empty space, tab, newline.
An example is provided below:
    NrPoints 10
    Dims [32 64]
    PRM { NrNeighbors 10 Grid { Dims [10 20] Min [-10 10] Max [-10 10] } }
Constructor & Destructor Documentation
Antipatrea::Params::Params (void) inline
References ~Params().
virtual Antipatrea::Params::~Params (void) virtual
Referenced by Params().
Member Function Documentation
virtual Data* Antipatrea::Params::GetData (const char id[]) virtual
Referenced by Antipatrea::CfgOffspringGenerator::SetupFromParams(), Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams(), Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams(), Antipatrea::CfgManager::SetupFromParams(), Antipatrea::CfgDistanceLp::SetupFromParams(), Antipatrea::CfgAcceptorBasedOnDistance::SetupFromParams(), Antipatrea::CfgProjector::SetupFromParams(), Antipatrea::TreeSamplingBasedPlanner::SetupFromParams(), Antipatrea::PRM::SetupFromParams(), Antipatrea::SamplingBasedPlanner::SetupFromParams(), and Antipatrea::EST::SetupFromParams().
virtual const char* Antipatrea::Params::GetValue (const char id[], const char notFound[] = NULL) virtual
Referenced by GetValueAsBool(), GetValueAsDouble(), GetValueAsInt(), Antipatrea::SetupRosetta::NewCfgEnergyEvaluator(), Antipatrea::SetupRosetta::NewCfgForwardKinematics(), Antipatrea::SetupRosetta::NewCfgImprover(), Antipatrea::SetupRosetta::NewCfgOffspringGenerator(), Antipatrea::SetupRosetta::NewCfgProjector(), and Antipatrea::SetupRosetta::NewCfgSampler().
virtual double Antipatrea::Params::GetValueAsDouble (const char id[], const double notFound = INFINITY) inline virtual
References GetValue(), and Antipatrea::StrToDouble().
virtual int Antipatrea::Params::GetValueAsInt (const char id[], const int notFound = INT_MAX) inline virtual
References GetValue(), and Antipatrea::StrToInt().
virtual bool Antipatrea::Params::GetValueAsBool (const char id[], const bool notFound = false) inline virtual
References AddValue(), GetValue(), Print(), Read(), SetParams(), SetValue(), and Antipatrea::StrToBool().
virtual void Antipatrea::Params::SetValue (const char id[], const char val[]) virtual
Referenced by GetValueAsBool().
virtual void Antipatrea::Params::AddValue (const char id[], const char val[]) virtual
Referenced by GetValueAsBool().
virtual void Antipatrea::Params::SetParams (const char id[], Params *const params) virtual
Referenced by GetValueAsBool().
virtual std::istream& Antipatrea::Params::Read (std::istream & in) virtual
Read the content from the input stream.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Reader.
Referenced by GetValueAsBool().
virtual std::ostream& Antipatrea::Params::Print (std::ostream & out) const virtual
Write to the output stream.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::Writer.
Referenced by GetValueAsBool().
static Params* Antipatrea::Params::GetSingleton (void) inline static
References m_singleton.
Member Data Documentation
Params* Antipatrea::Params::m_singleton static protected
Referenced by GetSingleton().
std::unordered_map<std::string, Data*> Antipatrea::Params::m_map protected
The documentation for this class was generated from the following file:
Params.hpp