Antipatrea::CfgAcceptorChain2D Class Reference
Antipatrea::CfgAcceptorChain2D Class Reference
CfgAcceptorChain2D accepts a configuration iff the chain avoids self collisions and collisions with the obstacles in the scene.
#include <CfgAcceptorChain2D.hpp>
Public Member Functions
CfgAcceptorChain2D (void)
virtual ~CfgAcceptorChain2D (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual bool IsAcceptable (Cfg &cfg)
Return true iff the chain avoids self collisions and collisions with the obstacles in the scene.
Public Member Functions inherited from Antipatrea::CfgAcceptor
CfgAcceptor (void)
virtual ~CfgAcceptor (void)
virtual Cfg * GetAnAcceptableCfg (void)
When possible, return a pointer to a configuration that is acceptable.
virtual bool IsUsedAsGoalAcceptor (void) const
Get the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void UseAsGoalAcceptor (const bool use)
Set the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::CfgAcceptor
bool m_useAsGoalAcceptor
Class purpose: goal acceptor (true) or configuration acceptor (false).
bool m_verboseFlag
flag to control verbosity
Detailed Description
CfgAcceptorChain2D accepts a configuration iff the chain avoids self collisions and collisions with the obstacles in the scene.
Author
Erion Plaku, Amarda Shehu
Remarks
The chain is considered to be in self-collision iff nonconsecutive links of the chain intersect with each other.
CfgAcceptorChain2D needs access to Scene2D and Chain2D.
Constructor & Destructor Documentation
CfgAcceptorChain2D()
Antipatrea::CfgAcceptorChain2D::CfgAcceptorChain2D (void) inline
~CfgAcceptorChain2D()
virtual Antipatrea::CfgAcceptorChain2D::~CfgAcceptorChain2D (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgAcceptorChain2D::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::CfgAcceptorChain2D::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::ClassContainer(), Antipatrea::Object::Info(), IsAcceptable(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
IsAcceptable()
virtual bool Antipatrea::CfgAcceptorChain2D::IsAcceptable (Cfg & cfg) virtual
Return true iff the chain avoids self collisions and collisions with the obstacles in the scene.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgAcceptor.
Referenced by Info().
The documentation for this class was generated from the following file:
CfgAcceptorChain2D.hpp