Antipatrea::EST Class Reference
Antipatrea::EST Class Reference
#include <EST.hpp>
Public Member Functions
EST (void)
virtual ~EST (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
virtual double GetNeighborhoodRadius (void) const
Get the radius of the neighboorhod used to measure the tree-coverage density.
virtual void SetNeighborhoodRadius (const double r)
Set the radius of the neighboorhod used to measure the tree-coverage density.
Public Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
TreeSamplingBasedPlanner (void)
virtual ~TreeSamplingBasedPlanner (void)
virtual double GetExtendMaxNrSteps (void) const
Get the maximum number of steps for the tree-branch expansion.
virtual double GetExtendReachedTargetDistanceThreshold (void) const
Get the distance threshold to determine whether the target configuration has been reached.
virtual double GetGoalBias (void) const
Get the goal bias.
virtual bool GetSampleValidTargetCfg (void) const
Get the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void SetExtendMaxNrSteps (const int n)
Set the maximum number of steps for the tree-branch expansion.
virtual void SetExtendReachedTargetDistanceThreshold (const double d)
Set the distance threshold to determine whether the target configuration has been reached.
virtual void SetGoalBias (const double bias)
Set the goal bias.
virtual void SetSampleValidTargetCfg (const bool valid)
Set the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void Start (void)
Root the tree at the initial configuration.
virtual bool Solve (const double tmax)
Iteratively expand the motion tree by adding new vertices and edges.
Public Member Functions inherited from Antipatrea::SamplingBasedPlanner
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual bool CheckSetup (void)
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Member Functions
virtual PlannerVertex * NewVertex (void) const
Factory for creating new planner vertices.
virtual int AddVertex (Cfg *const cfg)
Add a new vertex to the graph with cfg as its associated configuration.
virtual double GetVertexWeight (const ESTVertex &v) const
Get the vertex weight.
virtual int SelectVertex (void)
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Protected Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
virtual void SampleTargetCfg (Cfg &cfg)
Sample a target at random or as the goal configuration.
virtual ExtendStatus ExtendToward (const int vidFrom, Cfg &cfgTo)
Extend a branch in the planner graph from the selected vertex toward the target configuration.
Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Protected Attributes
double m_neighborhoodRadius
Radius of the neighboorhod used to measure the tree-coverage density.
double m_totalWeight
Sum of weights of associates with the tree vertices.
Protected Attributes inherited from Antipatrea::TreeSamplingBasedPlanner
int m_extendMaxNrSteps
Maximum number of steps for the tree-branch expansion.
double m_extendReachedTargetDistanceThreshold
Distance threshold to determine whether the target configuration has been reached.
double m_goalBias
Goal bias.
bool m_sampleValidTargetCfg
Flag indicating whether the target should be sampled as a valid configuration.
Cfg * m_cfgTarget
Target configuration, which is set by the planner at each iteration.
Protected Attributes inherited from Antipatrea::SamplingBasedPlanner
const int SAMPLING_PLANNER_VERBOSE_FULL = 3
constants for verbosity control
const int SAMPLING_PLANNER_VERBOSE_MED = 2
const int SAMPLING_PLANNER_VERBOSE_LOW = 1
const int SAMPLING_PLANNER_VERBOSE_NONE = 0
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
int m_verbosityFlag
verbosity flag
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Protected Types inherited from Antipatrea::TreeSamplingBasedPlanner
enum ExtendStatus {
EXTEND_FAILED,
EXTEND_OK,
EXTEND_REACHED_TARGET,
EXTEND_REACHED_GOAL
}
Status of the planner-graph branch expansion.
Static Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Constructor & Destructor Documentation
EST()
Antipatrea::EST::EST (void) inline
~EST()
virtual Antipatrea::EST::~EST (void) inline virtual
Member Function Documentation
Info()
virtual void Antipatrea::EST::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::TreeSamplingBasedPlanner::Info(), and Antipatrea::Logger::m_out.
SetupFromParams()
virtual void Antipatrea::EST::SetupFromParams (Params & params) inline virtual
Set the parameter values of the planner from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes TreeSamplingBasedPlanner::SetupFromParams(params).
It then sets the neighborhood radius (keyword Constants::KW_NeighborhoodRadius)
It uses the parameter group associated with the keyword Constants::KW_EST.
The parameter values can be specified in a text file as, for example, EST { NeighborhoodRadius 1.0 } }
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::Params::GetData(), Antipatrea::Constants::KW_EST, Antipatrea::Constants::KW_NeighborhoodRadius, and Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
GetNeighborhoodRadius()
virtual double Antipatrea::EST::GetNeighborhoodRadius (void) const inline virtual
Get the radius of the neighboorhod used to measure the tree-coverage density.
Author
Erion Plaku, Amarda Shehu
SetNeighborhoodRadius()
virtual void Antipatrea::EST::SetNeighborhoodRadius (const double r) inline virtual
Set the radius of the neighboorhod used to measure the tree-coverage density.
Author
Erion Plaku, Amarda Shehu
NewVertex()
virtual PlannerVertex* Antipatrea::EST::NewVertex (void) const inline protected virtual
Factory for creating new planner vertices.
Author
Erion Plaku, Amarda Shehu
Remarks
Create ESTVertex instead of PlannerVertex.
Reimplemented from Antipatrea::SamplingBasedPlanner.
References Antipatrea::ESTVertex::ESTVertex().
AddVertex()
virtual int Antipatrea::EST::AddVertex (Cfg *const cfg) protected virtual
Add a new vertex to the graph with cfg as its associated configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
The function also computes the number of vertices that fall inside the neighborhood centered at cfg (configurations whose distance from cfg is no more than GetNeighboorhodRadius(). For each of these configurations, it also increments the number of neighbors counter by one (since cfg will be inside their neighborhoods).
The function does not make a copy of cfg; it simply does pointer assignment.
The function does not check if cfg is already in the graph. It is the responsibility of the calling function to perform such a check (using FindCfg) if indeed there is a possibility that the same configuration is added to the graph multiple times (which even if it happened would not cause any errors).
Reimplemented from Antipatrea::SamplingBasedPlanner.
GetVertexWeight()
virtual double Antipatrea::EST::GetVertexWeight (const ESTVertex & v) const protected virtual
Get the vertex weight.
Author
Erion Plaku, Amarda Shehu
Remarks
The weight is high when the vertex has few neighbors inside its neighborhood in order to promote expansions from sparsely explored areas.
To avoid always selecting the same vertex, the weight decreases with the number of selections.
SelectVertex()
virtual int Antipatrea::EST::SelectVertex (void) protected virtual
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns the id of the selected vertex.
The vertex is selected with probability proportional to its weight.
TreeSamplingBasedPlanner::SelectTarget is used to select the target.
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
Member Data Documentation
m_neighborhoodRadius
double Antipatrea::EST::m_neighborhoodRadius protected
Radius of the neighboorhod used to measure the tree-coverage density.
Author
Erion Plaku, Amarda Shehu
m_totalWeight
double Antipatrea::EST::m_totalWeight protected
Sum of weights of associates with the tree vertices.
Author
Erion Plaku, Amarda Shehu
The documentation for this class was generated from the following file:
EST.hpp