Antipatrea::Allocator Class Reference
Antipatrea::Allocator Class Reference
Facilitates creating, deleting, and copying an array of values.
#include <Allocator.hpp>
Public Member Functions
Allocator (const int dim=0)
virtual ~Allocator (void)
virtual void SetDim (const int dim)
Set dimension.
virtual int GetDim (void) const
Get the dimension.
virtual double * NewValues (void) const
Allocate memory for the array.
virtual void DeleteValues (double values[]) const
Delete the memory allocated to the array.
virtual void CopyValues (double dest[], const double src[]) const
Copy the values from src to dest.
virtual double * CopyValues (const double values[]) const
Return a copy of the array.
Protected Attributes
int m_dim
Array dimension.
Detailed Description
Facilitates creating, deleting, and copying an array of values.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Allocator()
Antipatrea::Allocator::Allocator (const int dim = 0) inline
~Allocator()
virtual Antipatrea::Allocator::~Allocator (void) inline virtual
Member Function Documentation
SetDim()
virtual void Antipatrea::Allocator::SetDim (const int dim) inline virtual
Set dimension.
Author
Erion Plaku, Amarda Shehu
Remarks
The dimension should be set once at the beginning before any array is allocated.
References m_dim.
Referenced by Antipatrea::CfgManager::SetupFromParams(), and Antipatrea::CfgProjector::SetupFromParams().
GetDim()
virtual int Antipatrea::Allocator::GetDim (void) const inline virtual
Get the dimension.
Author
Erion Plaku, Amarda Shehu
References m_dim.
Referenced by Antipatrea::CfgManager::CheckSetup(), Antipatrea::CfgProjector::CheckSetup(), CopyValues(), Antipatrea::CfgManager::Info(), Antipatrea::CfgProjector::Info(), NewValues(), Antipatrea::CfgManager::SetupFromParams(), and Antipatrea::CfgProjector::SetupFromParams().
NewValues()
virtual double* Antipatrea::Allocator::NewValues (void) const inline virtual
Allocate memory for the array.
Author
Erion Plaku, Amarda Shehu
References GetDim().
Referenced by CopyValues(), and Antipatrea::CfgManager::NewCfg().
DeleteValues()
virtual void Antipatrea::Allocator::DeleteValues (double values[]) const inline virtual
Delete the memory allocated to the array.
Author
Erion Plaku, Amarda Shehu
CopyValues() [1/2]
virtual void Antipatrea::Allocator::CopyValues (double dest[], const double src[]) const inline virtual
Copy the values from src to dest.
Author
Erion Plaku, Amarda Shehu
References GetDim().
Referenced by Antipatrea::CfgManager::CopyCfg(), and CopyValues().
CopyValues() [2/2]
virtual double* Antipatrea::Allocator::CopyValues (const double values[]) const inline virtual
Return a copy of the array.
Author
Erion Plaku, Amarda Shehu
References CopyValues(), and NewValues().
Member Data Documentation
m_dim
int Antipatrea::Allocator::m_dim protected
Array dimension.
Author
Erion Plaku, Amarda Shehu
Referenced by GetDim(), and SetDim().
The documentation for this class was generated from the following file:
Allocator.hpp