Antipatrea::CfgAcceptor Class Reference
Antipatrea::CfgAcceptor Class Reference abstract
Interface for determining whether or not a given configuration is acceptable.
#include <CfgAcceptor.hpp>
Public Member Functions
CfgAcceptor (void)
virtual ~CfgAcceptor (void)
virtual bool IsAcceptable (Cfg &cfg)=0
Returns true iff the configuration cfg is acceptable.
virtual Cfg * GetAnAcceptableCfg (void)
When possible, return a pointer to a configuration that is acceptable.
virtual bool IsUsedAsGoalAcceptor (void) const
Get the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void UseAsGoalAcceptor (const bool use)
Set the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Protected Attributes
bool m_useAsGoalAcceptor
Class purpose: goal acceptor (true) or configuration acceptor (false).
bool m_verboseFlag
flag to control verbosity
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for determining whether or not a given configuration is acceptable.
Author
Erion Plaku, Amarda Shehu
Remarks
This class provides a general interface for checking whether or not a given configuration is acceptable.
It should be extended with specific implementations.
The class can be used for two purposes:
(1) to determine whether a configuration in PRM, RRT, or any other sampling-based approach satisfies the desired constraints, e.g., its energy level is below a certain threshold; and
(2) to determine whether a configuration satisfies the goal, e.g., its energy level is close to a native state, or is really close to the goal configuration.
By default it is used for the first purpose. The member function UseAsGoalAcceptor(true) should be called when an object from this class is used to test goal acceptance.
Constructor & Destructor Documentation
CfgAcceptor()
Antipatrea::CfgAcceptor::CfgAcceptor (void) inline
References m_verboseFlag.
~CfgAcceptor()
virtual Antipatrea::CfgAcceptor::~CfgAcceptor (void) inline virtual
References IsAcceptable().
Member Function Documentation
IsAcceptable()
virtual bool Antipatrea::CfgAcceptor::IsAcceptable (Cfg & cfg) pure virtual
Returns true iff the configuration cfg is acceptable.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::CfgAcceptorBasedOnDistance, Antipatrea::CfgAcceptorBasedOnMMC, Antipatrea::CfgAcceptorBasedOnFixedMMC, Antipatrea::CfgAcceptorBasedOnEnergy, Antipatrea::CfgAcceptorChain2D, and Antipatrea::CfgAcceptorPoint2D.
Referenced by ~CfgAcceptor().
GetAnAcceptableCfg()
virtual Cfg* Antipatrea::CfgAcceptor::GetAnAcceptableCfg (void) inline virtual
When possible, return a pointer to a configuration that is acceptable.
Author
Erion Plaku, Amarda Shehu
Remarks
Such function is useful for implementing biased sampling in RRT-like motion planners. As an illustration, the acceptor could be used for goal testing. The function could return a pointer to the goal configuration.
The returned pointer should not be deleted since the function may return the address of a class variable. Deleting the pointer could cause memory issues.
Reimplemented in Antipatrea::CfgAcceptorBasedOnDistance.
IsUsedAsGoalAcceptor()
virtual bool Antipatrea::CfgAcceptor::IsUsedAsGoalAcceptor (void) const inline virtual
Get the class purpose: goal acceptor (true) or configuration acceptor (false).
Author
Erion Plaku, Amarda Shehu
References m_useAsGoalAcceptor.
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::CfgAcceptorBasedOnEnergy(), Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams(), and SetupFromParams().
UseAsGoalAcceptor()
virtual void Antipatrea::CfgAcceptor::UseAsGoalAcceptor (const bool use) inline virtual
Set the class purpose: goal acceptor (true) or configuration acceptor (false).
Author
Erion Plaku, Amarda Shehu
References m_useAsGoalAcceptor.
SetupFromParams()
virtual void Antipatrea::CfgAcceptor::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
For each parameter value of the component, use the associated keyword to get the corresponding paramater value from params.
Reimplemented from Antipatrea::Component.
Reimplemented in Antipatrea::CfgAcceptorBasedOnDistance, Antipatrea::CfgAcceptorBasedOnMMC, Antipatrea::CfgAcceptorBasedOnFixedMMC, and Antipatrea::CfgAcceptorBasedOnEnergy.
References Antipatrea::Params::GetData(), IsUsedAsGoalAcceptor(), Antipatrea::Constants::KW_CfgAcceptorBasedOnDistance, Antipatrea::Constants::KW_GoalAcceptorBasedOnDistance, Antipatrea::Constants::KW_VerboseFlag, m_verboseFlag, and Antipatrea::Component::SetupFromParams().
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams(), Antipatrea::CfgAcceptorBasedOnFixedMMC::SetupFromParams(), Antipatrea::CfgAcceptorBasedOnMMC::SetupFromParams(), and Antipatrea::CfgAcceptorBasedOnDistance::SetupFromParams().
Member Data Documentation
m_useAsGoalAcceptor
bool Antipatrea::CfgAcceptor::m_useAsGoalAcceptor protected
Class purpose: goal acceptor (true) or configuration acceptor (false).
Author
Erion Plaku, Amarda Shehu
Referenced by IsUsedAsGoalAcceptor(), and UseAsGoalAcceptor().
m_verboseFlag
bool Antipatrea::CfgAcceptor::m_verboseFlag protected
flag to control verbosity
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgAcceptor(), Antipatrea::CfgAcceptorBasedOnFixedMMC::IsAcceptable(), and SetupFromParams().
The documentation for this class was generated from the following file:
CfgAcceptor.hpp