Antipatrea::PathAcceptorByIncrement Class Reference
Antipatrea::PathAcceptorByIncrement Class Reference
Test whether or not a path is valid at a given time-step resolution using the incremental method.
#include <PathAcceptorByIncrement.hpp>
Public Member Functions
PathAcceptorByIncrement (void)
virtual ~PathAcceptorByIncrement (void)
virtual bool IsAcceptable (PathGenerator &pathGenerator, const double tstep)
Test whether or not a path is valid at a given time-step resolution using the incremental method.
Public Member Functions inherited from Antipatrea::PathAcceptor
PathAcceptor (void)
virtual ~PathAcceptor (void)
virtual bool CheckSetup (void)
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Test whether or not a path is valid at a given time-step resolution using the incremental method.
Author
Erion Plaku, Amarda Shehu
Remarks
The end configurations (at time = 0 and time = 1) are not checked (assumed to be acceptable).
The incremental method checks the path at time steps t_j = (j + 1) tstep, starting with j = 0 and continuing as long as t_j < 1.
If one of this configurations is found to be not acceptable, then the incremental method deems the path nonacceptable and returns.
Constructor & Destructor Documentation
Antipatrea::PathAcceptorByIncrement::PathAcceptorByIncrement (void) inline
virtual Antipatrea::PathAcceptorByIncrement::~PathAcceptorByIncrement (void) inline virtual
References Antipatrea::ClassContainer(), and IsAcceptable().
Member Function Documentation
virtual bool Antipatrea::PathAcceptorByIncrement::IsAcceptable (PathGenerator & pathGenerator, const double tstep) virtual
Test whether or not a path is valid at a given time-step resolution using the incremental method.
Author
Erion Plaku, Amarda Shehu
Remarks
The end configurations (at time = 0 and time = 1) are not checked (assumed to be acceptable).
The incremental method checks the path at time steps t_j = (j + 1) tstep, starting with j = 0 and continuing as long as t_j < 1.
If one of this configurations is found to be not acceptable, then the incremental method deems the path nonacceptable and returns.
Implements Antipatrea::PathAcceptor.
Referenced by ~PathAcceptorByIncrement().
The documentation for this class was generated from the following file:
PathAcceptorByIncrement.hpp