Antipatrea::FragmentDB Class Reference
Antipatrea::FragmentDB Class Reference
DB of Rosetta fragments for a set of a protein.
#include <CfgOffspringGeneratorRosetta.hpp>
Public Member Functions
void Insert (unsigned int pos, Fragment &f)
Insert a new fragment.
unsigned int NumberOfPositions () const
Number of positions (protein positons) in the DB.
unsigned int NumberOfSamples (unsigned int pos)
Number of fragments for a given position.
double GetFragmentPhi (unsigned int pos, unsigned int fragmentNumber, unsigned int fragmentOffset)
Return the PHI angle for a specific position, fragment, and offset within the fragment.
double GetFragmentPsi (unsigned int pos, unsigned int fragmentNumber, unsigned int fragmentOffset)
double GetFragmentOmega (unsigned int pos, unsigned int fragmentNumber, unsigned int fragmentOffset)
Protected Attributes
unsigned int m_fragmentSize
Number of positions/amino acids within a single fragment.
std::vector< std::vector< Fragment > > m_fragments
Detailed Description
DB of Rosetta fragments for a set of a protein.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Member Function Documentation
Insert()
void Antipatrea::FragmentDB::Insert (unsigned int pos, Fragment & f) inline
Insert a new fragment.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
NumberOfPositions()
unsigned int Antipatrea::FragmentDB::NumberOfPositions () const inline
Number of positions (protein positons) in the DB.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
NumberOfSamples()
unsigned int Antipatrea::FragmentDB::NumberOfSamples (unsigned int pos) inline
Number of fragments for a given position.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
GetFragmentPhi()
double Antipatrea::FragmentDB::GetFragmentPhi (unsigned int pos, unsigned int fragmentNumber, unsigned int fragmentOffset) inline
Return the PHI angle for a specific position, fragment, and offset within the fragment.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
References Antipatrea::Fragment::GetPhi().
GetFragmentPsi()
double Antipatrea::FragmentDB::GetFragmentPsi (unsigned int pos, unsigned int fragmentNumber, unsigned int fragmentOffset) inline
References Antipatrea::Fragment::GetPsi().
GetFragmentOmega()
double Antipatrea::FragmentDB::GetFragmentOmega (unsigned int pos, unsigned int fragmentNumber, unsigned int fragmentOffset) inline
References Antipatrea::Fragment::GetOmega().
Member Data Documentation
m_fragmentSize
unsigned int Antipatrea::FragmentDB::m_fragmentSize protected
Number of positions/amino acids within a single fragment.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
m_fragments
std::vector<std::vector <Fragment> > Antipatrea::FragmentDB::m_fragments protected
The documentation for this class was generated from the following file:
CfgOffspringGeneratorRosetta.hpp