Antipatrea::PGT Class Reference
Antipatrea::PGT Class Reference
Projection-Guided Tree (PGT).
#include <PGT.hpp>
Classes
class Cell
Each cell keeps track of the vertices associated with it and the number of times it has been selected for expansion.
Public Member Functions
PGT (void)
virtual ~PGT (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the planner from the given parameters.
virtual const Grid * GetProjectionGrid (void) const
Get the pointer to the grid imposed over the projection space.
virtual Grid * GetProjectionGrid (void)
Get the pointer to the grid imposed over the projection space.
Public Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
TreeSamplingBasedPlanner (void)
virtual ~TreeSamplingBasedPlanner (void)
virtual double GetExtendMaxNrSteps (void) const
Get the maximum number of steps for the tree-branch expansion.
virtual double GetExtendReachedTargetDistanceThreshold (void) const
Get the distance threshold to determine whether the target configuration has been reached.
virtual double GetGoalBias (void) const
Get the goal bias.
virtual bool GetSampleValidTargetCfg (void) const
Get the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void SetExtendMaxNrSteps (const int n)
Set the maximum number of steps for the tree-branch expansion.
virtual void SetExtendReachedTargetDistanceThreshold (const double d)
Set the distance threshold to determine whether the target configuration has been reached.
virtual void SetGoalBias (const double bias)
Set the goal bias.
virtual void SetSampleValidTargetCfg (const bool valid)
Set the value of the flag indicating whether the target should be sampled as a valid configuration.
virtual void Start (void)
Root the tree at the initial configuration.
virtual bool Solve (const double tmax)
Iteratively expand the motion tree by adding new vertices and edges.
Public Member Functions inherited from Antipatrea::SamplingBasedPlanner
SamplingBasedPlanner (void)
virtual ~SamplingBasedPlanner (void)
virtual double GetOneStepDistance (void) const
Get the one-step distance.
virtual void SetOneStepDistance (const double d)
Set the one-step distance.
virtual bool IsSolved (void)
Return true iff the planner has found a solution.
virtual bool GetSolution (PlannerSolution &sol)
Construct the solution that the planner has found.
virtual std::ostream & Print (std::ostream &out) const
Print the configurations, vertices, and edges of the planner graph.
virtual std::istream & Read (std::istream &in)
Read configurations, vertices, and edges and add them to the planner graph.
Public Member Functions inherited from Antipatrea::Planner
Planner (void)
virtual ~Planner (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Reader
Reader (void)
virtual ~Reader (void)
virtual void ReadFromFile (const char fname[], std::ios_base::openmode mode=std::ios_base::in)
Open a file for reading, read the content, and then close the file.
Public Member Functions inherited from Antipatrea::Writer
Writer (void)
virtual ~Writer (void)
virtual void PrintToFile (const char fname[], std::ios_base::openmode mode=std::ios_base::out) const
Open a file for writing, write the content, and then close the file.
Protected Member Functions
virtual int AddVertex (Cfg *const cfg)
Add a new vertex to the graph with cfg as its associated configuration.
virtual int SelectVertex (void)
Select a vertex from which to expand the tree and a target toward which to expand the tree.
virtual Cell * NewCell (void) const
Factory for creating new cells.
Protected Member Functions inherited from Antipatrea::TreeSamplingBasedPlanner
virtual void SampleTargetCfg (Cfg &cfg)
Sample a target at random or as the goal configuration.
virtual ExtendStatus ExtendToward (const int vidFrom, Cfg &cfgTo)
Extend a branch in the planner graph from the selected vertex toward the target configuration.
Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
virtual int FindCfg (Cfg &cfg)
If there is a vertex whose configuration is the same as cfg, then return its id.
virtual PlannerVertex * NewVertex (void) const
Factory for creating new planner vertices.
virtual PlannerEdge * NewEdge (void) const
Factory for creating new planner edges.
virtual void FromVertexSequenceToCfgs (PlannerSolution &sol)
Construct the sequence of configurations based on the sequence of vertices associated with the planner solution.
Protected Attributes
double m_totalWeight
Sum of weights of the non-empty grid cells.
Grid m_grid
Grid over the projection space.
std::unordered_map< int, Cell * > m_cells
Non-empty grid cells.
Protected Attributes inherited from Antipatrea::TreeSamplingBasedPlanner
int m_extendMaxNrSteps
Maximum number of steps for the tree-branch expansion.
double m_extendReachedTargetDistanceThreshold
Distance threshold to determine whether the target configuration has been reached.
double m_goalBias
Goal bias.
bool m_sampleValidTargetCfg
Flag indicating whether the target should be sampled as a valid configuration.
Cfg * m_cfgTarget
Target configuration, which is set by the planner at each iteration.
Protected Attributes inherited from Antipatrea::SamplingBasedPlanner
const int SAMPLING_PLANNER_VERBOSE_FULL = 3
constants for verbosity control
const int SAMPLING_PLANNER_VERBOSE_MED = 2
const int SAMPLING_PLANNER_VERBOSE_LOW = 1
const int SAMPLING_PLANNER_VERBOSE_NONE = 0
ProximityDefault< int, SamplingBasedPlanner * > m_proximityDataStructure
Proximity data structure to facilitate nearest-neighbors queires.
int m_verbosityFlag
verbosity flag
Cfg * m_proximityAuxCfg
Auxilary configuration used by the proximity data structure to compute nearest-neighbors queries.
int m_vidInit
The id of the vertex associated with the initial configuration.
std::vector< int > m_vidsGoal
The set of vertices marked as goal (where the goal is satisfied).
GraphSearch< int > m_graphSearch
Graph-searching algorithms, e.g., DFS, BFS, A*, Dijkstra.
PlannerGraphSearchInfo m_graphSearchInfo
Implicit representation of the planner graph.
double m_oneStepDistance
Resolution at which to discretize paths (e.g., PRM-like planners) or to determine the step when expanding a branch (e.g., tree-based planners).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Static Public Member Functions inherited from Antipatrea::Reader
static std::istream & ReadDouble (std::istream &in, double &val)
Read a double value from the input stream.
Protected Types inherited from Antipatrea::TreeSamplingBasedPlanner
enum ExtendStatus {
EXTEND_FAILED,
EXTEND_OK,
EXTEND_REACHED_TARGET,
EXTEND_REACHED_GOAL
}
Status of the planner-graph branch expansion.
Static Protected Member Functions inherited from Antipatrea::SamplingBasedPlanner
static double ProximityDistFn (const int vid1, const int vid2, SamplingBasedPlanner *sbPlanner)
Wrapper for the distance function used by the proximity data structure – it uses CfgDistance.
Detailed Description
Projection-Guided Tree (PGT).
Author
Erion Plaku, Amarda Shehu
Remarks
PGT relies on CfgProjector to obtain a low-dimensional projection for each configuration/vertex that is added to the tree.
PGT also uses a grid (over the projection space) to partition the vertices into groups. In particular, vertices v_i and v_j belong to the same group iff their projections belong to the same grid cell.
Each grid cell is assigned a weight based on the number of vertices associated with it and the number of times it has been selected for expansion. The weight is high when it has few vertices in order to promote expansions from sparsely explored areas. To avoid always selecting the same grid cell, the weight decreases with the number of selections. This is essential to ensure that the tree expansion does not become stuck when expansion from vertices associated with a particular grid cell is difficult or impossible due to configuration constraints, e.g., energetic constraints when configurations represent molecular structures or collision-avoidance constraints in standard robotic motion planning.
At each iteration, PGT selects a non-empty grid cell with probability proportional to its weight and then it selects a vertex uniformly at random from the selected cell.
The target is selected as in the base class, using the function SelectTarget.
After the vertex and target have been selected, as in the base class, PGT uses ExpandTowardTarget to expand the tree from the selected vertex toward the selected target.
Constructor & Destructor Documentation
PGT()
Antipatrea::PGT::PGT (void) inline
References ~PGT().
~PGT()
virtual Antipatrea::PGT::~PGT (void) virtual
Referenced by PGT().
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::PGT::CheckSetup (void) inline virtual
Reimplemented from Antipatrea::SamplingBasedPlanner.
References Antipatrea::SamplingBasedPlanner::CheckSetup().
Info()
virtual void Antipatrea::PGT::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
References Antipatrea::Grid::Info(), Antipatrea::TreeSamplingBasedPlanner::Info(), m_grid, Antipatrea::Logger::m_out, Antipatrea::Object::Name(), and SetupFromParams().
SetupFromParams()
virtual void Antipatrea::PGT::SetupFromParams (Params & params) virtual
Set the parameter values of the planner from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes TreeSamplingBasedPlanner::SetupFromParams(params).
It then sets the projection grid (keyword Constants::KW_Grid)
It uses the parameter group associated with the keyword Constants::KW_PGT.
The parameter values can be specified in a text file as, for example, PGT { Grid { Dims [32 37] Min [-10 10] Max [10 10] } }
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
Referenced by Info().
GetProjectionGrid() [1/2]
virtual const Grid* Antipatrea::PGT::GetProjectionGrid (void) const inline virtual
Get the pointer to the grid imposed over the projection space.
Author
Erion Plaku, Amarda Shehu
References m_grid.
Referenced by Antipatrea::Setup2D::FixGrid().
GetProjectionGrid() [2/2]
virtual Grid* Antipatrea::PGT::GetProjectionGrid (void) inline virtual
Get the pointer to the grid imposed over the projection space.
Author
Erion Plaku, Amarda Shehu
References AddVertex(), m_grid, and SelectVertex().
AddVertex()
virtual int Antipatrea::PGT::AddVertex (Cfg *const cfg) protected virtual
Add a new vertex to the graph with cfg as its associated configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
The newly added vertex is also added to the corresponding grid cell (using CfgProjector to compute the projection of cfg).
The function does not make a copy of cfg; it simply does pointer assignment.
The function does not check if cfg is already in the graph. It is the responsibility of the calling function to perform such a check (using FindCfg) if indeed there is a possibility that the same configuration is added to the graph multiple times (which even if it happened would not cause any errors).
Reimplemented from Antipatrea::SamplingBasedPlanner.
Referenced by GetProjectionGrid().
SelectVertex()
virtual int Antipatrea::PGT::SelectVertex (void) protected virtual
Select a vertex from which to expand the tree and a target toward which to expand the tree.
Author
Erion Plaku, Amarda Shehu
Remarks
Function returns the id of the selected vertex.
The vertex is selected by first selecting a grid cell (among the non-empty grid cells) with probability proportional to its weight and then selecting a vertex uniformly at random from the vertices associated with the selected grid cell.
TreeSamplingBasedPlanner::SelectTarget is used to select the target.
Reimplemented from Antipatrea::TreeSamplingBasedPlanner.
Referenced by GetProjectionGrid().
NewCell()
virtual Cell* Antipatrea::PGT::NewCell (void) const inline protected virtual
Factory for creating new cells.
Author
Erion Plaku, Amarda Shehu
Remarks
PGT should use NewCell() instead of new Cell() to allocate memory for a new cell, since planners extending PGT could also extend Cell.
References Antipatrea::PGT::Cell::Cell().
Member Data Documentation
m_totalWeight
double Antipatrea::PGT::m_totalWeight protected
Sum of weights of the non-empty grid cells.
Author
Erion Plaku, Amarda Shehu
m_grid
Grid Antipatrea::PGT::m_grid protected
Grid over the projection space.
Author
Erion Plaku, Amarda Shehu
Referenced by GetProjectionGrid(), and Info().
m_cells
std::unordered_map<int, Cell*> Antipatrea::PGT::m_cells protected
Non-empty grid cells.
Author
Erion Plaku, Amarda Shehu
The documentation for this class was generated from the following file:
PGT.hpp