Antipatrea::Setup2D Class Reference
Antipatrea::Setup2D Class Reference
Facilitate setting up planning problems in 2D workspaces as well as the planner and its components.
#include <Setup2D.hpp>
Public Member Functions
Setup2D (void)
virtual ~Setup2D (void)
Public Member Functions inherited from Antipatrea::Setup
Setup (void)
virtual ~Setup (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void Prepare (Params &params)=0
Create new instances, setup pointers, and setup the parameters.
virtual void Test (void)
Write whatever you would like for testing purposes.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void NewInstances (Params &params)
Create all the new instances.
virtual void NewScene2D (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointers (void)
Setup the component pointers.
virtual void SetupPointersScene2D (void)
Setup the pointers for the indicated component.
virtual void FixGrid (void)
Fix grid dimensions.
Protected Member Functions inherited from Antipatrea::Setup
virtual void OnNewInstance (Component *const comp)
Add the instance to the set of component instances.
virtual void NewCfgAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewGoalAcceptor (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgManager (Params &params)
Create a new instance for the indicated component.
virtual void NewSignedDistanceBetweenTwoValues (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgDistance (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgEnergyEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgForwardKinematics (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgImprover (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgProjector (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgSampler (Params &params)
Create a new instance for the indicated component.
virtual void NewEdgeCostEvaluator (Params &params)
Create a new instance for the indicated component.
virtual void NewCfgOffspringGenerator (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerProblem (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerSolution (Params &params)
Create a new instance for the indicated component.
virtual void NewPlannerGraph (Params &params)
Create a new instance for the indicated component.
virtual void NewSamplingBasedPlanner (Params &params)
Create a new instance for the indicated component.
virtual void SetupPointersComponent (Component *const comp)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersGoalAcceptor (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgManager (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgDistance (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSignedDistanceBetweenTwoValues (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgEnergyEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgForwardKinematics (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgImprover (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgProjector (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgSampler (void)
Setup the pointers for the indicated component.
virtual void SetupPointersEdgeCostEvaluator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersCfgOffspringGenerator (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerProblem (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerSolution (void)
Setup the pointers for the indicated component.
virtual void SetupPointersPlannerGraph (void)
Setup the pointers for the indicated component.
virtual void SetupPointersSamplingBasedPlanner (void)
Setup the pointers for the indicated component.
virtual void SetupFromParams (Params &params)
Setup the paramater values of each component instance using the user-provided parameters.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Protected Attributes inherited from Antipatrea::Setup
std::vector< Component * > m_components
Component instances.
Detailed Description
Facilitate setting up planning problems in 2D workspaces as well as the planner and its components.
Author
Erion Plaku, Amarda Shehu
Remarks
Setup creates instances of the planning components based on keywords provided by the user or default settings when the user does not provide any keywords.
Only one instance per class is created.
After creating the components, Setup sets the pointers so that components/planners that depend on, for example, CfgDistance will have the CfgDistance pointer set to the CfgDistance instance created in the first step.
After setting the pointers, Setup iterates over all the instances that were created in step 1, and calls the function SetupFromParams in order to set the parameter values for each instance.
Constructor & Destructor Documentation
Antipatrea::Setup2D::Setup2D (void) inline
virtual Antipatrea::Setup2D::~Setup2D (void) inline virtual
Member Function Documentation
virtual void Antipatrea::Setup2D::NewInstances (Params & params) inline protected virtual
Create all the new instances.
Author
Erion Plaku, Amarda Shehu
Remarks
Function calls all the specific New functions listed below, e.g., NewCfgAcceptor, NewGoalAcceptor, and so on.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Setup::NewInstances(), and NewScene2D().
virtual void Antipatrea::Setup2D::NewScene2D (Params & params) inline protected virtual
Create a new instance for the indicated component.
Author
Erion Plaku, Amarda Shehu
Remarks
If more than one choice, use keywords defined in params to select among the various classes.
References Antipatrea::Setup::OnNewInstance().
Referenced by NewInstances().
virtual void Antipatrea::Setup2D::SetupPointers (void) inline protected virtual
Setup the component pointers.
Author
Erion Plaku, Amarda Shehu
Remarks
After creating the components, Setup sets the pointers so that components/planners that depend on, for example, CfgDistance will have the CfgDistance pointer set to the CfgDistance instance created when NewInstances() was called.
Reimplemented from Antipatrea::Setup.
References Antipatrea::Setup::SetupPointers(), and SetupPointersScene2D().
virtual void Antipatrea::Setup2D::SetupPointersScene2D (void) inline protected virtual
Setup the pointers for the indicated component.
Author
Erion Plaku, Amarda Shehu
References Antipatrea::Setup::SetupPointersComponent().
Referenced by SetupPointers().
virtual void Antipatrea::Setup2D::FixGrid (void) inline protected virtual
Fix grid dimensions.
Author
Erion Plaku, Amarda Shehu
Remarks
If PGT has been selected as the planner, fix the grid dimensions to match the bounding box of the scene.
References Antipatrea::PGT::GetProjectionGrid(), and Antipatrea::Grid::Setup().
The documentation for this class was generated from the following file:
Setup2D.hpp