Antipatrea::CfgOffspringGeneratorRosettaWBias Class Reference
Antipatrea::CfgOffspringGeneratorRosettaWBias Class Reference
Use Rosetta/library to generate an offspring near the parent configuration.
#include <CfgOffspringGeneratorRosettaWBias.hpp>
Public Member Functions
CfgOffspringGeneratorRosettaWBias (void)
virtual ~CfgOffspringGeneratorRosettaWBias (void)
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void GenerateOffspringCfg (Cfg &cfg)
Use Rosetta to generate the offspring configuration near the parent configuration.
Public Member Functions inherited from Antipatrea::CfgOffspringGeneratorRosetta
CfgOffspringGeneratorRosetta (void)
virtual ~CfgOffspringGeneratorRosetta (void)
virtual const Cfg * GetTargetCfg (void) const
Get the pointer to the target configuration.
Selector< int > SelectFragmentLength ()
select a fragment length to use based on weights
virtual void SetTargetCfg (const Cfg *const cfgTarget)
Set the pointer to the target configuration.
virtual void PrintSummary () const
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Public Member Functions inherited from Antipatrea::CfgOffspringGenerator
CfgOffspringGenerator (void)
virtual ~CfgOffspringGenerator (void)
virtual const Cfg * GetParentCfg (void) const
Get the pointer to the parent configuration.
virtual void SetParentCfg (const Cfg *const cfgParent)
Set the pointer to the parent configuration.
virtual double GetStep (void) const
Get the step size used for guiding the offspring generation.
virtual void SetStep (const double step)
Get the step size used for guiding the offspring generation.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual double GenerateAnOffspringCfg (Cfg &cfg)
Protected Member Functions inherited from Antipatrea::CfgOffspringGeneratorRosetta
unsigned int LoadFragmentLibrary (std::string fragmentFile, double fragmentProbability)
Read in a Rosetta fragment file. These files can be generated from the website http://robetta.bakerlab.org. The files are organized by having the position and neighbors(fragments) header, followed by the number of neighbors/fragments.
double GenerateAnOffspringCfg (Cfg &cfg)
Protected Attributes
int m_offspringToGenerate
Protected Attributes inherited from Antipatrea::CfgOffspringGeneratorRosetta
const Cfg * m_cfgTarget
Pointer to the target configuration.
Selector< int > m_selector
Structure to hold fragment library pointers. Allows easy random selection w/respect to the libraries weight.
double m_distanceTol
Threshold for distance of offspring from parent. When set to zero, no threshold is enforced.
std::unordered_map< unsigned int, FragmentDB > m_fragmentMap
A map of fragment databases organized by the fragment length.
std::vector< double > m_fragmentProbs
Set of probabilities for selecting each fragment library.
std::vector< std::string > m_fragmentFileNames
File names for the fragment libraries.
int m_offspringToGenerate
Number of offspring to evaluate per call. The offspring that is the closest to the passed to GenerateOffspringCfg will be accepted.
Protected Attributes inherited from Antipatrea::CfgOffspringGenerator
const Cfg * m_cfgParent
Pointer to the parent configuration.
double m_step
Step size to guide the offspring generation.
bool m_verboseFlag
Verbosity Flag for all offspring generators.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Use Rosetta/library to generate an offspring near the parent configuration.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
CfgOffspringGeneratorRosettaWBias()
Antipatrea::CfgOffspringGeneratorRosettaWBias::CfgOffspringGeneratorRosettaWBias (void) inline
~CfgOffspringGeneratorRosettaWBias()
virtual Antipatrea::CfgOffspringGeneratorRosettaWBias::~CfgOffspringGeneratorRosettaWBias (void) inline virtual
References Antipatrea::ClassContainer(), GenerateAnOffspringCfg(), GenerateOffspringCfg(), and SetupFromParams().
Member Function Documentation
SetupFromParams()
virtual void Antipatrea::CfgOffspringGeneratorRosettaWBias::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::CfgOffspringGeneratorRosetta.
Referenced by ~CfgOffspringGeneratorRosettaWBias().
GenerateOffspringCfg()
virtual void Antipatrea::CfgOffspringGeneratorRosettaWBias::GenerateOffspringCfg (Cfg & cfg) virtual
Use Rosetta to generate the offspring configuration near the parent configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
Use GetStep() as a measure of how far/different the offspring should be from its parent.
Reimplemented from Antipatrea::CfgOffspringGeneratorRosetta.
Referenced by ~CfgOffspringGeneratorRosettaWBias().
GenerateAnOffspringCfg()
virtual double Antipatrea::CfgOffspringGeneratorRosettaWBias::GenerateAnOffspringCfg (Cfg & cfg) protected virtual
Referenced by ~CfgOffspringGeneratorRosettaWBias().
Member Data Documentation
m_offspringToGenerate
int Antipatrea::CfgOffspringGeneratorRosettaWBias::m_offspringToGenerate protected
The documentation for this class was generated from the following file:
CfgOffspringGeneratorRosettaWBias.hpp