Antipatrea::PathAcceptorBySubdivision Class Reference
Antipatrea::PathAcceptorBySubdivision Class Reference
Test whether or not a path is valid at a given time-step resolution using the subdivision method.
#include <PathAcceptorBySubdivision.hpp>
Public Member Functions
PathAcceptorBySubdivision (void)
virtual ~PathAcceptorBySubdivision (void)
virtual bool IsAcceptable (PathGenerator &pathGenerator, const double tstep)
Test whether or not a path is valid at the given time-step resolution using the subdivision method.
Public Member Functions inherited from Antipatrea::PathAcceptor
PathAcceptor (void)
virtual ~PathAcceptor (void)
virtual bool CheckSetup (void)
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Test whether or not a path is valid at a given time-step resolution using the subdivision method.
Author
Erion Plaku, Amarda Shehu
Remarks
The end configurations (at time = 0 and time = 1) are not checked (assumed to be acceptable).
The subdivision method checks the path at different time-step resolutions.
It starts at 0.5 and then cuts the resolution in half until it reaches a user-provided minimum time-step resolution.
Specifically, the resolution at level i is set to res_i = (1/2)^i.
At level i, the path is checked at time steps t_j = 0.5 res_i + j * res_i, starting with j = 0 and continuing as long as t_j < 1.
If one of this configurations is found to be not acceptable, then the subdivision method deems the path nonacceptable and returns.
Constructor & Destructor Documentation
Antipatrea::PathAcceptorBySubdivision::PathAcceptorBySubdivision (void) inline
virtual Antipatrea::PathAcceptorBySubdivision::~PathAcceptorBySubdivision (void) inline virtual
References Antipatrea::ClassContainer(), and IsAcceptable().
Member Function Documentation
virtual bool Antipatrea::PathAcceptorBySubdivision::IsAcceptable (PathGenerator & pathGenerator, const double tstep) virtual
Test whether or not a path is valid at the given time-step resolution using the subdivision method.
Author
Erion Plaku, Amarda Shehu
Remarks
The end configurations (at time = 0 and time = 1) are not checked (assumed to be acceptable).
The subdivision method checks the path at different time-step resolutions.
It starts at 0.5 and then cuts the resolution in half until it reaches a user-provided minimum time-step resolution.
Specifically, the resolution at level i is set to res_i = (1/2)^i.
At level i, the path is checked starting at time steps t_{i,j} = 0.5 res_i + j * res_i (as long as t_{i,j} < 1.
If one of this configurations is found to be not acceptable, then the subdivision method deems the path nonacceptable and returns.
Implements Antipatrea::PathAcceptor.
Referenced by ~PathAcceptorBySubdivision().
The documentation for this class was generated from the following file:
PathAcceptorBySubdivision.hpp