Antipatrea::CfgDistanceLp Class Reference
Antipatrea::CfgDistanceLp Class Reference
Defines the distance between two configurations as the Lp norm of the pairwise distances between configuration values.
#include <CfgDistanceLp.hpp>
Public Member Functions
CfgDistanceLp (void)
virtual ~CfgDistanceLp (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual int GetExponent (void) const
Get the exponent used for the Lp norm calculation.
virtual void SetExponent (int exponent)
Set the exponent used for the Lp norm calculation.
virtual double Distance (const Cfg &cfg1, const Cfg &cfg2)
Computes the distance between two configurations as the Lp norm of the pairwise distances between configuration values.
Public Member Functions inherited from Antipatrea::CfgDistance
CfgDistance (void)
virtual ~CfgDistance (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
int m_exponent
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Defines the distance between two configurations as the Lp norm of the pairwise distances between configuration values.
Author
Erion Plaku, Amarda Shehu
Remarks
Distance is computed as LpNorm(a_{0}, ..., a_{dim-1}) where a_{i} = GetSignedDistanceBetweenTwoValues()->SignedDistance(cfg1->GetValues()[i], cfg2->GetValues()[i])
This class requires access to SignedDistanceBetweenTwoValues component in order to compute the distance between any two values.
It also requires access to CfgManager to access the configuration dimension.
The user also needs to set the exponent p in the Lp norm.
Constructor & Destructor Documentation
Antipatrea::CfgDistanceLp::CfgDistanceLp (void) inline
virtual Antipatrea::CfgDistanceLp::~CfgDistanceLp (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgDistanceLp::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::CfgDistanceLp::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual void Antipatrea::CfgDistanceLp::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes CfgDistance::SetupFromParams(params).
It then sets the exponent for the Lp norm (keyword Constants::KW_Exponent).
It uses the parameter group associated with the keyword Constants::KW_CfgDistanceLp.
The parameter value can be specified in a text file as, for example, CfgDistanceLp { Exponent 2 }
Reimplemented from Antipatrea::Component.
References Antipatrea::Params::GetData(), GetExponent(), Antipatrea::Constants::KW_CfgDistanceLp, Antipatrea::Constants::KW_Exponent, SetExponent(), and Antipatrea::Component::SetupFromParams().
virtual int Antipatrea::CfgDistanceLp::GetExponent (void) const inline virtual
Get the exponent used for the Lp norm calculation.
Author
Erion Plaku, Amarda Shehu
References m_exponent.
Referenced by SetupFromParams().
virtual void Antipatrea::CfgDistanceLp::SetExponent (int exponent) inline virtual
Set the exponent used for the Lp norm calculation.
Author
Erion Plaku, Amarda Shehu
References Distance(), and m_exponent.
Referenced by SetupFromParams().
virtual double Antipatrea::CfgDistanceLp::Distance (const Cfg & cfg1, const Cfg & cfg2) virtual
Computes the distance between two configurations as the Lp norm of the pairwise distances between configuration values.
Author
Erion Plaku, Amarda Shehu
Remarks
Distance is computed as LpNorm(a_{0}, ..., a_{dim-1}) where a_{i} = GetSignedDistanceBetweenTwoValues()->SignedDistance(cfg1->GetValues()[i], cfg2->GetValues()[i])
Implements Antipatrea::CfgDistance.
Referenced by SetExponent().
Member Data Documentation
int Antipatrea::CfgDistanceLp::m_exponent protected
Referenced by GetExponent(), and SetExponent().
The documentation for this class was generated from the following file:
CfgDistanceLp.hpp