Antipatrea::CfgProjectorDeltaR Class Reference
Antipatrea::CfgProjectorDeltaR Class Reference
#include <CfgProjectorDeltaR.hpp>
Public Member Functions
CfgProjectorDeltaR (void)
virtual ~CfgProjectorDeltaR (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void PostSetup ()
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void Project (const Cfg &cfg, double proj[])
Use Rosetta to compute the DeltaR projection of the configuration values.
unsigned int GetCellCount ()
Public Member Functions inherited from Antipatrea::CfgProjector
CfgProjector (const int dim=0)
virtual ~CfgProjector (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Public Member Functions inherited from Antipatrea::Allocator
Allocator (const int dim=0)
virtual ~Allocator (void)
virtual void SetDim (const int dim)
Set dimension.
virtual int GetDim (void) const
Get the dimension.
virtual double * NewValues (void) const
Allocate memory for the array.
virtual void DeleteValues (double values[]) const
Delete the memory allocated to the array.
virtual void CopyValues (double dest[], const double src[]) const
Copy the values from src to dest.
virtual double * CopyValues (const double values[]) const
Return a copy of the array.
Protected Attributes
CfgDistanceAtomRMSD distanceRMSD
Object to compute distances.
const Cfg * m_initCfg
const Cfg * m_goalCfg
unsigned int m_cellCount
double m_cellRange
double m_cellSize
double m_rmsdBetween
bool m_firstProjection
bool m_verboseFlag
Protected Attributes inherited from Antipatrea::Allocator
int m_dim
Array dimension.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Constructor & Destructor Documentation
CfgProjectorDeltaR()
Antipatrea::CfgProjectorDeltaR::CfgProjectorDeltaR (void) inline
References m_firstProjection, and m_verboseFlag.
~CfgProjectorDeltaR()
virtual Antipatrea::CfgProjectorDeltaR::~CfgProjectorDeltaR (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgProjectorDeltaR::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::CfgProjector.
References Antipatrea::CfgProjector::CheckSetup().
Info()
virtual void Antipatrea::CfgProjectorDeltaR::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::CfgProjector.
References Antipatrea::CfgProjector::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
PostSetup()
virtual void Antipatrea::CfgProjectorDeltaR::PostSetup () inline virtual
References Antipatrea::CfgDistanceAtomRMSD::Distance(), distanceRMSD, GetCellCount(), m_cellCount, m_cellRange, m_cellSize, m_goalCfg, m_initCfg, m_rmsdBetween, Project(), and SetupFromParams().
SetupFromParams()
virtual void Antipatrea::CfgProjectorDeltaR::SetupFromParams (Params & params) virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Reimplemented from Antipatrea::CfgProjector.
Referenced by PostSetup().
Project()
virtual void Antipatrea::CfgProjectorDeltaR::Project (const Cfg & cfg, double proj[]) virtual
Use Rosetta to compute the DeltaR projection of the configuration values.
Author
Erion Plaku, Amarda Shehu
Remarks
The function assumes that proj has been properly allocated (using CfgProjector::NewValues())
Implements Antipatrea::CfgProjector.
Referenced by PostSetup().
GetCellCount()
unsigned int Antipatrea::CfgProjectorDeltaR::GetCellCount ()
Referenced by PostSetup().
Member Data Documentation
distanceRMSD
CfgDistanceAtomRMSD Antipatrea::CfgProjectorDeltaR::distanceRMSD protected
Object to compute distances.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Remarks
The function assumes that proj has been properly allocated (using CfgProjector::NewValues())
Referenced by PostSetup().
m_initCfg
const Cfg* Antipatrea::CfgProjectorDeltaR::m_initCfg protected
Referenced by PostSetup().
m_goalCfg
const Cfg* Antipatrea::CfgProjectorDeltaR::m_goalCfg protected
Referenced by PostSetup().
m_cellCount
unsigned int Antipatrea::CfgProjectorDeltaR::m_cellCount protected
Referenced by PostSetup().
m_cellRange
double Antipatrea::CfgProjectorDeltaR::m_cellRange protected
Referenced by PostSetup().
m_cellSize
double Antipatrea::CfgProjectorDeltaR::m_cellSize protected
Referenced by PostSetup().
m_rmsdBetween
double Antipatrea::CfgProjectorDeltaR::m_rmsdBetween protected
Referenced by PostSetup().
m_firstProjection
bool Antipatrea::CfgProjectorDeltaR::m_firstProjection protected
Referenced by CfgProjectorDeltaR().
m_verboseFlag
bool Antipatrea::CfgProjectorDeltaR::m_verboseFlag protected
Referenced by CfgProjectorDeltaR().
The documentation for this class was generated from the following file:
CfgProjectorDeltaR.hpp