Antipatrea::CfgOffspringGenerator Class Reference
Antipatrea::CfgOffspringGenerator Class Reference abstract
Generate an offspring configuration near the parent configuration.
#include <CfgOffspringGenerator.hpp>
Public Member Functions
CfgOffspringGenerator (void)
virtual ~CfgOffspringGenerator (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual const Cfg * GetParentCfg (void) const
Get the pointer to the parent configuration.
virtual void SetParentCfg (const Cfg *const cfgParent)
Set the pointer to the parent configuration.
virtual double GetStep (void) const
Get the step size used for guiding the offspring generation.
virtual void SetStep (const double step)
Get the step size used for guiding the offspring generation.
virtual void GenerateOffspringCfg (Cfg &cfg)=0
Generate the offspring.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
const Cfg * m_cfgParent
Pointer to the parent configuration.
double m_step
Step size to guide the offspring generation.
bool m_verboseFlag
Verbosity Flag for all offspring generators.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Generate an offspring configuration near the parent configuration.
Author
Erion Plaku, Amarda Shehu
Remarks
A parameter, m_step, provides a measure of how far/different the offspring should be from its parent.
Constructor & Destructor Documentation
CfgOffspringGenerator()
Antipatrea::CfgOffspringGenerator::CfgOffspringGenerator (void) inline
References m_verboseFlag.
~CfgOffspringGenerator()
virtual Antipatrea::CfgOffspringGenerator::~CfgOffspringGenerator (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::CfgOffspringGenerator::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
Reimplemented in Antipatrea::CfgOffspringGeneratorRosetta, and Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation.
References Antipatrea::Component::CheckSetup().
Referenced by Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::CheckSetup(), and Antipatrea::CfgOffspringGeneratorRosetta::CheckSetup().
Info()
virtual void Antipatrea::CfgOffspringGenerator::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
Reimplemented in Antipatrea::CfgOffspringGeneratorRosetta, Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation, and Antipatrea::CfgOffspringGeneratorByGaussianPerturbation.
References GetStep(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
Referenced by Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::Info(), Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::Info(), and Antipatrea::CfgOffspringGeneratorRosetta::Info().
SetupFromParams()
virtual void Antipatrea::CfgOffspringGenerator::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes Component::SetupFromParams(params).
It then sets the step size used for guiding the offspring generation (keyword Constants::KW_Step).
It uses the parameter group associated with the keyword Constants::KW_CfgOffspringGenerator.
The parameter value can be specified in a text file as, for example, CfgOffspringGenerator { Step 0.1 }
Reimplemented from Antipatrea::Component.
Reimplemented in Antipatrea::CfgOffspringGeneratorRosetta, Antipatrea::CfgOffspringGeneratorByGaussianPerturbation, and Antipatrea::CfgOffspringGeneratorRosettaWBias.
References Antipatrea::Params::GetData(), GetStep(), Antipatrea::Constants::KW_CfgOffspringGenerator, Antipatrea::Constants::KW_Step, Antipatrea::Constants::KW_VerboseFlag, m_verboseFlag, SetStep(), and Antipatrea::Component::SetupFromParams().
Referenced by Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams().
GetParentCfg()
virtual const Cfg* Antipatrea::CfgOffspringGenerator::GetParentCfg (void) const inline virtual
Get the pointer to the parent configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgParent.
SetParentCfg()
virtual void Antipatrea::CfgOffspringGenerator::SetParentCfg (const Cfg *const cfgParent) inline virtual
Set the pointer to the parent configuration.
Author
Erion Plaku, Amarda Shehu
References m_cfgParent.
GetStep()
virtual double Antipatrea::CfgOffspringGenerator::GetStep (void) const inline virtual
Get the step size used for guiding the offspring generation.
Author
Erion Plaku, Amarda Shehu
Remarks
Step size is a measure of how far/different the offspring should be from its parent.
References m_step.
Referenced by Info(), and SetupFromParams().
SetStep()
virtual void Antipatrea::CfgOffspringGenerator::SetStep (const double step) inline virtual
Get the step size used for guiding the offspring generation.
Author
Erion Plaku, Amarda Shehu
Remarks
Step size is a measure of how far/different the offspring should be from its parent.
References GenerateOffspringCfg(), and m_step.
Referenced by SetupFromParams().
GenerateOffspringCfg()
virtual void Antipatrea::CfgOffspringGenerator::GenerateOffspringCfg (Cfg & cfg) pure virtual
Generate the offspring.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::CfgOffspringGeneratorRosetta, Antipatrea::CfgOffspringGeneratorByGaussianPerturbation, Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation, and Antipatrea::CfgOffspringGeneratorRosettaWBias.
Referenced by SetStep().
Member Data Documentation
m_cfgParent
const Cfg* Antipatrea::CfgOffspringGenerator::m_cfgParent protected
Pointer to the parent configuration.
Author
Erion Plaku, Amarda Shehu
Referenced by GetParentCfg(), and SetParentCfg().
m_step
double Antipatrea::CfgOffspringGenerator::m_step protected
Step size to guide the offspring generation.
Author
Erion Plaku, Amarda Shehu
Remarks
Step size is a measure of how far/different the offspring should be from its parent.
Referenced by GetStep(), and SetStep().
m_verboseFlag
bool Antipatrea::CfgOffspringGenerator::m_verboseFlag protected
Verbosity Flag for all offspring generators.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
Referenced by CfgOffspringGenerator(), and SetupFromParams().
The documentation for this class was generated from the following file:
CfgOffspringGenerator.hpp