Antipatrea::CfgAllocator Class Reference
Antipatrea::CfgAllocator Class Reference
#include <CfgAllocator.hpp>
Public Member Functions
CfgAllocator (const int dim=0)
virtual ~CfgAllocator (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual void SetDim (const int dim)
virtual int GetDim (void) const
virtual double * NewValues (void) const
virtual void DeleteValues (double cfg[]) const
virtual void CopyValues (double dest[], const double src[]) const
virtual double * CopyValues (const double cfg[]) const
virtual Cfg * NewCfg (void) const
virtual void DeleteCfg (Cfg *cfg)
virtual void CopyCfg (Cfg &cfgDest, const Cfg &cfgSource) const
virtual Cfg * CopyCfg (const Cfg &cfgSource) const
virtual std::ostream & Print (std::ostream &out, const Cfg &cfg) const
virtual std::istream & Read (std::istream &in, Cfg &cfg) const
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Member Functions
virtual void OnNewCfg (Cfg &cfg) const
Protected Attributes
int m_dim
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Constructor & Destructor Documentation
Antipatrea::CfgAllocator::CfgAllocator (const int dim = 0) inline
virtual Antipatrea::CfgAllocator::~CfgAllocator (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgAllocator::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup(), and GetDim().
virtual void Antipatrea::CfgAllocator::Info (const char prefix[]) const inline virtual
Reimplemented from Antipatrea::Object.
References Antipatrea::Cfg::ENERGY_UNDEFINED, GetDim(), Antipatrea::Object::Info(), and Antipatrea::Logger::m_out.
virtual void Antipatrea::CfgAllocator::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
For each parameter value of the component, use the associated keyword to get the corresponding paramater value from params.
Reimplemented from Antipatrea::Component.
References Antipatrea::Params::GetData(), GetDim(), Antipatrea::Constants::KW_CfgAllocator, SetDim(), and Antipatrea::Component::SetupFromParams().
virtual void Antipatrea::CfgAllocator::SetDim (const int dim) inline virtual
References m_dim.
Referenced by SetupFromParams().
virtual int Antipatrea::CfgAllocator::GetDim (void) const inline virtual
References m_dim.
Referenced by CheckSetup(), CopyValues(), Info(), NewValues(), and SetupFromParams().
virtual double* Antipatrea::CfgAllocator::NewValues (void) const inline virtual
References GetDim().
Referenced by CopyValues(), and OnNewCfg().
virtual void Antipatrea::CfgAllocator::DeleteValues (double cfg[]) const inline virtual
virtual void Antipatrea::CfgAllocator::CopyValues (double dest[], const double src[]) const inline virtual
References GetDim().
Referenced by CopyCfg(), and CopyValues().
virtual double* Antipatrea::CfgAllocator::CopyValues (const double cfg[]) const inline virtual
References CopyValues(), and NewValues().
virtual Cfg* Antipatrea::CfgAllocator::NewCfg (void) const inline virtual
References OnNewCfg().
Referenced by CopyCfg().
virtual void Antipatrea::CfgAllocator::DeleteCfg (Cfg * cfg) inline virtual
virtual void Antipatrea::CfgAllocator::CopyCfg (Cfg & cfgDest, const Cfg & cfgSource) const inline virtual
References CopyValues(), Antipatrea::Cfg::GetEnergy(), Antipatrea::Cfg::GetValues(), and Antipatrea::Cfg::SetEnergy().
Referenced by CopyCfg().
virtual Cfg* Antipatrea::CfgAllocator::CopyCfg (const Cfg & cfgSource) const inline virtual
References CopyCfg(), NewCfg(), Print(), and Read().
virtual std::ostream& Antipatrea::CfgAllocator::Print (std::ostream & out, const Cfg & cfg) const virtual
Referenced by CopyCfg().
virtual std::istream& Antipatrea::CfgAllocator::Read (std::istream & in, Cfg & cfg) const virtual
Referenced by CopyCfg().
virtual void Antipatrea::CfgAllocator::OnNewCfg (Cfg & cfg) const inline protected virtual
References NewValues(), and Antipatrea::Cfg::SetValues().
Referenced by NewCfg().
Member Data Documentation
int Antipatrea::CfgAllocator::m_dim protected
Referenced by GetDim(), and SetDim().
The documentation for this class was generated from the following file:
CfgAllocator.hpp