Antipatrea::GManager Class Reference
Antipatrea::GManager Class Reference
#include <GManager.hpp>
Public Types
enum {
INDEX_MINX,
INDEX_MINY,
INDEX_MAXX,
INDEX_MAXY,
INDEX_ORTHO_NEAR_PLANE,
INDEX_ORTHO_FAR_PLANE,
NR_INDICES
}
Public Member Functions
GManager (void)
virtual ~GManager (void)
virtual void SetupFromParams (Params &params)
virtual void Help (void)
virtual void MainLoop (const char *const title, const int width=1000, const int height=600)
virtual void HandleEventOnTimer (void)
virtual void HandleEventOnDisplay (void)
virtual bool HandleEventOnMouseLeftBtnDown (const int x, const int y)
virtual bool HandleEventOnMouseLeftBtnUp (const int x, const int y)
virtual bool HandleEventOnActiveMouseMove (const int x, const int y)
virtual bool HandleEventOnPassiveMouseMove (const int x, const int y)
virtual bool HandleEventOnNormalKeyPress (const int key)
virtual bool HandleEventOnSpecialKeyPress (const int key)
virtual bool HandleEventOnNormalKeyUp (const int key)
virtual bool HandleEventOnSpecialKeyUp (const int key)
virtual bool HandleEventOnIdle (void)
virtual bool HandleEventOnMenu (const int item)
virtual double GetValue (const int i)
virtual void SetValue (const int i, const double val)
Static Public Member Functions
static void MousePosFromScreenToWorld (const int x, const int y, double *const wx, double *const wy, double *const wz)
Protected Member Functions
virtual void MenuOptions (void)
Static Protected Member Functions
static void CallbackEventOnActiveMouseMove (int x, int y)
static void CallbackEventOnPassiveMouseMove (int x, int y)
static void CallbackEventOnMouse (int button, int state, int x, int y)
static void CallbackEventOnTimer (int id)
static void CallbackEventOnMenu (int item)
static void CallbackEventOnSpecialKeyPress (int key, int x, int y)
static void CallbackEventOnNormalKeyPress (unsigned char key, int x, int y)
static void CallbackEventOnSpecialKeyUp (int key, int x, int y)
static void CallbackEventOnNormalKeyUp (unsigned char key, int x, int y)
static void CallbackEventOnDisplay (void)
static void CallbackEventOnIdle (void)
static int CreateMenu (void)
static void SetMenu (const int menu)
static void AddSubMenu (const char name[], const int item)
static void AddMenuEntry (const char name[], const int item)
static void ChangeToMenuEntry (const int pos, const char name[], const int item)
Protected Attributes
int m_idWindow
int m_timer
int m_mousePrevX
int m_mousePrevY
GCamera m_gCamera
Flags m_flags
int m_nrMenuItems
int m_menuSelItem
std::unordered_map< int, int > m_mapKeysToMenuItems
std::vector< double > m_values
Member Enumeration Documentation
anonymous enum
Enumerator
INDEX_MINX
INDEX_MINY
INDEX_MAXX
INDEX_MAXY
INDEX_ORTHO_NEAR_PLANE
INDEX_ORTHO_FAR_PLANE
NR_INDICES
Constructor & Destructor Documentation
Antipatrea::GManager::GManager (void)
virtual Antipatrea::GManager::~GManager (void) virtual
Member Function Documentation
virtual void Antipatrea::GManager::SetupFromParams (Params & params) virtual
Reimplemented in Antipatrea::GManagerRunPlanner, and Antipatrea::GManagerRunPlanner2D.
virtual void Antipatrea::GManager::Help (void) virtual
virtual void Antipatrea::GManager::MainLoop (const char *const title, const int width = 1000, const int height = 600) virtual
static void Antipatrea::GManager::MousePosFromScreenToWorld (const int x, const int y, double *const wx, double *const wy, double *const wz) static
virtual void Antipatrea::GManager::HandleEventOnTimer (void) inline virtual
Reimplemented in Antipatrea::GManagerRunPlanner.
virtual void Antipatrea::GManager::HandleEventOnDisplay (void) inline virtual
Reimplemented in Antipatrea::GManagerRunPlanner, and Antipatrea::GManagerRunPlanner2D.
virtual bool Antipatrea::GManager::HandleEventOnMouseLeftBtnDown (const int x, const int y) inline virtual
Reimplemented in Antipatrea::GManagerRunPlanner2D.
virtual bool Antipatrea::GManager::HandleEventOnMouseLeftBtnUp (const int x, const int y) inline virtual
Reimplemented in Antipatrea::GManagerRunPlanner2D.
virtual bool Antipatrea::GManager::HandleEventOnActiveMouseMove (const int x, const int y) inline virtual
Reimplemented in Antipatrea::GManagerRunPlanner2D.
virtual bool Antipatrea::GManager::HandleEventOnPassiveMouseMove (const int x, const int y) inline virtual
References HandleEventOnNormalKeyPress(), and HandleEventOnSpecialKeyPress().
virtual bool Antipatrea::GManager::HandleEventOnNormalKeyPress (const int key) virtual
Reimplemented in Antipatrea::GManagerRunPlanner.
Referenced by HandleEventOnPassiveMouseMove().
virtual bool Antipatrea::GManager::HandleEventOnSpecialKeyPress (const int key) virtual
Referenced by HandleEventOnPassiveMouseMove().
virtual bool Antipatrea::GManager::HandleEventOnNormalKeyUp (const int key) inline virtual
virtual bool Antipatrea::GManager::HandleEventOnSpecialKeyUp (const int key) inline virtual
virtual bool Antipatrea::GManager::HandleEventOnIdle (void) inline virtual
virtual bool Antipatrea::GManager::HandleEventOnMenu (const int item) inline virtual
Reimplemented in Antipatrea::GManagerRunPlanner2D, and Antipatrea::GManagerRunPlanner.
virtual double Antipatrea::GManager::GetValue (const int i) inline virtual
References m_values.
virtual void Antipatrea::GManager::SetValue (const int i, const double val) inline virtual
References m_values.
virtual void Antipatrea::GManager::MenuOptions (void) inline protected virtual
Reimplemented in Antipatrea::GManagerRunPlanner, and Antipatrea::GManagerRunPlanner2D.
References AddMenuEntry(), AddSubMenu(), CallbackEventOnActiveMouseMove(), CallbackEventOnDisplay(), CallbackEventOnIdle(), CallbackEventOnMenu(), CallbackEventOnMouse(), CallbackEventOnNormalKeyPress(), CallbackEventOnNormalKeyUp(), CallbackEventOnPassiveMouseMove(), CallbackEventOnSpecialKeyPress(), CallbackEventOnSpecialKeyUp(), CallbackEventOnTimer(), ChangeToMenuEntry(), CreateMenu(), and SetMenu().
static void Antipatrea::GManager::CallbackEventOnActiveMouseMove (int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnPassiveMouseMove (int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnMouse (int button, int state, int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnTimer (int id) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnMenu (int item) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnSpecialKeyPress (int key, int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnNormalKeyPress (unsigned char key, int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnSpecialKeyUp (int key, int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnNormalKeyUp (unsigned char key, int x, int y) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnDisplay (void) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::CallbackEventOnIdle (void) static protected
Referenced by MenuOptions().
static int Antipatrea::GManager::CreateMenu (void) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::SetMenu (const int menu) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::AddSubMenu (const char name[], const int item) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::AddMenuEntry (const char name[], const int item) static protected
Referenced by MenuOptions().
static void Antipatrea::GManager::ChangeToMenuEntry (const int pos, const char name[], const int item) static protected
Referenced by MenuOptions().
Member Data Documentation
int Antipatrea::GManager::m_idWindow protected
int Antipatrea::GManager::m_timer protected
int Antipatrea::GManager::m_mousePrevX protected
int Antipatrea::GManager::m_mousePrevY protected
GCamera Antipatrea::GManager::m_gCamera protected
Flags Antipatrea::GManager::m_flags protected
int Antipatrea::GManager::m_nrMenuItems protected
int Antipatrea::GManager::m_menuSelItem protected
std::unordered_map<int, int> Antipatrea::GManager::m_mapKeysToMenuItems protected
std::vector<double> Antipatrea::GManager::m_values protected
Referenced by GetValue(), and SetValue().
The documentation for this class was generated from the following file:
GManager.hpp