Antipatrea::CfgValidSamplerByRepetition Class Reference
Antipatrea::CfgValidSamplerByRepetition Class Reference
Repeatedly sample a configuration until a valid one is generated.
#include <CfgValidSamplerByRepetition.hpp>
Public Member Functions
CfgValidSamplerByRepetition (void)
virtual ~CfgValidSamplerByRepetition (void)
virtual bool CheckSetup (void)
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual int GetMaxNrTries (void) const
Get the maximum number of tries to sample a configuration until it is accepted.
virtual void SetMaxNrTries (const int maxNrTries)
Set the maximum number of tries to sample a configuration until it is accepted.
virtual bool Sample (Cfg &cfg)
Repeatedly sample a configuration until a valid one is generated.
Public Member Functions inherited from Antipatrea::CfgValidSampler
CfgValidSampler (void)
virtual ~CfgValidSampler (void)
Public Member Functions inherited from Antipatrea::CfgSampler
CfgSampler (void)
virtual ~CfgSampler (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
int m_maxNrTries
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Repeatedly sample a configuration until a valid one is generated.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgSampler for sampling a configuration.
It also requires access to CfgAcceptor to test whether the sampled configuration is valid.
The user should also set the maximum number of tries to sample a valid configuration by repeatdly calling CfgSampler.
Constructor & Destructor Documentation
Antipatrea::CfgValidSamplerByRepetition::CfgValidSamplerByRepetition (void) inline
virtual Antipatrea::CfgValidSamplerByRepetition::~CfgValidSamplerByRepetition (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgValidSamplerByRepetition::CheckSetup (void) inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
References Antipatrea::Component::CheckSetup(), and GetMaxNrTries().
virtual void Antipatrea::CfgValidSamplerByRepetition::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References GetMaxNrTries(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual void Antipatrea::CfgValidSamplerByRepetition::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Sets the maximum number of tries to sample a configuration until it is accepted (keyword defined in Constants::KW_CfgValidSamplerByRepetion_MaxNrTries).
It uses the parameter group associated with the keyword Constants::KW_CfgValidSamplerByRepetition.
The parameter value can be specified in a text file as, for example, CfgValidSamplerByRepetition { MaxNrTries 1000 }
Reimplemented from Antipatrea::Component.
References Antipatrea::Params::GetData(), GetMaxNrTries(), Antipatrea::Constants::KW_CfgValidSamplerByRepetition, Antipatrea::Constants::KW_CfgValidSamplerByRepetition_MaxNrTries, SetMaxNrTries(), and Antipatrea::Component::SetupFromParams().
virtual int Antipatrea::CfgValidSamplerByRepetition::GetMaxNrTries (void) const inline virtual
Get the maximum number of tries to sample a configuration until it is accepted.
Author
Erion Plaku, Amarda Shehu
References m_maxNrTries.
Referenced by CheckSetup(), Info(), and SetupFromParams().
virtual void Antipatrea::CfgValidSamplerByRepetition::SetMaxNrTries (const int maxNrTries) inline virtual
Set the maximum number of tries to sample a configuration until it is accepted.
Author
Erion Plaku, Amarda Shehu
References m_maxNrTries, and Sample().
Referenced by SetupFromParams().
virtual bool Antipatrea::CfgValidSamplerByRepetition::Sample (Cfg & cfg) virtual
Repeatedly sample a configuration until a valid one is generated.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::CfgSampler.
Referenced by SetMaxNrTries().
Member Data Documentation
int Antipatrea::CfgValidSamplerByRepetition::m_maxNrTries protected
Referenced by GetMaxNrTries(), and SetMaxNrTries().
The documentation for this class was generated from the following file:
CfgValidSamplerByRepetition.hpp