Antipatrea::CfgDistanceInEuclideanSpace Class Reference
Antipatrea::CfgDistanceInEuclideanSpace Class Reference
Defines the distance between two configurations in Euclidean space.
#include <CfgDistanceInEuclideanSpace.hpp>
Public Member Functions
CfgDistanceInEuclideanSpace (void)
virtual ~CfgDistanceInEuclideanSpace (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual double Distance (const Cfg &cfg1, const Cfg &cfg2)
Computes the distance between two configurations in Euclidean space.
Public Member Functions inherited from Antipatrea::CfgDistance
CfgDistance (void)
virtual ~CfgDistance (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Detailed Description
Defines the distance between two configurations in Euclidean space.
Author
Erion Plaku, Amarda Shehu
Remarks
This class treats the configuration values as points in Euclidean space and computes the distance between two configurations as the Euclidean distance in R^dim, where dim is the configuration dimension.
This class requires access to CfgManager component in order to access the configuration dimension.
Constructor & Destructor Documentation
Antipatrea::CfgDistanceInEuclideanSpace::CfgDistanceInEuclideanSpace (void) inline
virtual Antipatrea::CfgDistanceInEuclideanSpace::~CfgDistanceInEuclideanSpace (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgDistanceInEuclideanSpace::CheckSetup (void) const inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
Reimplemented from Antipatrea::Component.
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::CfgDistanceInEuclideanSpace::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual double Antipatrea::CfgDistanceInEuclideanSpace::Distance (const Cfg & cfg1, const Cfg & cfg2) inline virtual
Computes the distance between two configurations in Euclidean space.
Author
Erion Plaku, Amarda Shehu
Remarks
This class treats the configuration values as points in Euclidean space and computes the distance between two configurations as the Euclidean distance in R^dim, where dim is the configuration dimension.
Implements Antipatrea::CfgDistance.
References Antipatrea::ClassContainer(), Antipatrea::Cfg::GetValues(), and Antipatrea::Algebra::PointDistance().
The documentation for this class was generated from the following file:
CfgDistanceInEuclideanSpace.hpp