Antipatrea::EdgeCostEvaluatorBasedOnDistance Class Reference
Antipatrea::EdgeCostEvaluatorBasedOnDistance Class Reference
Edge cost is defined as the distance between the start and end configurations.
#include <EdgeCostEvaluatorBasedOnDistance.hpp>
Public Member Functions
EdgeCostEvaluatorBasedOnDistance (void)
virtual ~EdgeCostEvaluatorBasedOnDistance (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual Costs EvaluateGivenFromToCfgs (Cfg &cfgFrom, Cfg &cfgTo)
Compute the costs for the direct and reverse path as the distance between the start and end configurations.
Public Member Functions inherited from Antipatrea::EdgeCostEvaluator
EdgeCostEvaluator (void)
virtual ~EdgeCostEvaluator (void)
virtual Costs EvaluateGivenFromToAndIntermediateCfgs (Cfg &cfgFrom, Cfg &cfgTo, std::vector< Cfg * > &intermediates)
Evaluate the direct and reverse cost of a path when given the start, end, and the sequence of intermediate configurations.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Edge cost is defined as the distance between the start and end configurations.
Author
Erion Plaku, Amarda Shehu
Remarks
This class needs access to CfgDistance in order to evaluate the distance between the start and end configurations.
Constructor & Destructor Documentation
Antipatrea::EdgeCostEvaluatorBasedOnDistance::EdgeCostEvaluatorBasedOnDistance (void) inline
virtual Antipatrea::EdgeCostEvaluatorBasedOnDistance::~EdgeCostEvaluatorBasedOnDistance (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::EdgeCostEvaluatorBasedOnDistance::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::EdgeCostEvaluatorBasedOnDistance::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual Costs Antipatrea::EdgeCostEvaluatorBasedOnDistance::EvaluateGivenFromToCfgs (Cfg & cfgFrom, Cfg & cfgTo) inline virtual
Compute the costs for the direct and reverse path as the distance between the start and end configurations.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::EdgeCostEvaluator.
References Antipatrea::ClassContainer(), Antipatrea::EdgeCostEvaluator::Costs::m_costFromTo, and Antipatrea::EdgeCostEvaluator::Costs::m_costToFrom.
The documentation for this class was generated from the following file:
EdgeCostEvaluatorBasedOnDistance.hpp