Antipatrea::CfgEnergyEvaluator Class Reference
Antipatrea::CfgEnergyEvaluator Class Reference abstract
Interface for computing the energy value of a configuration.
#include <CfgEnergyEvaluator.hpp>
Public Member Functions
CfgEnergyEvaluator (void)
virtual ~CfgEnergyEvaluator (void)
virtual double EvaluateEnergy (Cfg &cfg)=0
Computes the energy value of the configuration.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for computing the energy value of a configuration.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
Antipatrea::CfgEnergyEvaluator::CfgEnergyEvaluator (void) inline
virtual Antipatrea::CfgEnergyEvaluator::~CfgEnergyEvaluator (void) inline virtual
References Antipatrea::ClassContainer(), and EvaluateEnergy().
Member Function Documentation
virtual double Antipatrea::CfgEnergyEvaluator::EvaluateEnergy (Cfg & cfg) pure virtual
Computes the energy value of the configuration.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::CfgEnergyEvaluatorRosetta.
Referenced by ~CfgEnergyEvaluator().
The documentation for this class was generated from the following file:
CfgEnergyEvaluator.hpp