Antipatrea::Heap< Key, Compare, Equal, Hash > Class Template Reference
Antipatrea::Heap< Key, Compare, Equal, Hash > Class Template Reference
#include <Heap.hpp>
Public Member Functions
Heap (void)
virtual ~Heap (void)
virtual void SetKeyCompare (const Compare &compare)
bool IsEmpty (void) const
int GetNrKeys (void) const
bool HasKey (const Key key) const
int GetKeyPosition (const Key key) const
void Insert (const Key key)
void Update (const Key key)
void UpdateAtPosition (const int pos)
Key GetTop (void) const
Key GetKeyAtPosition (const int pos) const
Key RemoveTop (void)
void Remove (const Key key)
void RemoveAtPosition (const int pos)
void Clear (void)
void Sort (Key keys[], const int size)
bool Test (void)
void PrecolateDown (const int pos)
void PrecolateUp (const int pos)
Protected Attributes
std::unordered_map< Key, int, Hash, Equal > m_map
std::vector< Key > m_heap
Compare m_compare
Constructor & Destructor Documentation
Heap()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> Antipatrea::Heap< Key, Compare, Equal, Hash >::Heap (void) inline
~Heap()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> virtual Antipatrea::Heap< Key, Compare, Equal, Hash >::~Heap (void) inline virtual
Member Function Documentation
SetKeyCompare()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> virtual void Antipatrea::Heap< Key, Compare, Equal, Hash >::SetKeyCompare (const Compare & compare) inline virtual
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_compare.
Referenced by Antipatrea::GraphSearch< int >::AStar().
IsEmpty()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> bool Antipatrea::Heap< Key, Compare, Equal, Hash >::IsEmpty (void) const inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap.
Referenced by Antipatrea::GraphSearch< int >::AStar().
GetNrKeys()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> int Antipatrea::Heap< Key, Compare, Equal, Hash >::GetNrKeys (void) const inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap.
HasKey()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> bool Antipatrea::Heap< Key, Compare, Equal, Hash >::HasKey (const Key key) const inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map.
GetKeyPosition()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> int Antipatrea::Heap< Key, Compare, Equal, Hash >::GetKeyPosition (const Key key) const inline
References Antipatrea::Constants::ID_UNDEFINED, and Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map.
Insert()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::Insert (const Key key) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map, and Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp().
Referenced by Antipatrea::GraphSearch< int >::AStar().
Update()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::Update (const Key key) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map, and Antipatrea::Heap< Key, Compare, Equal, Hash >::UpdateAtPosition().
Referenced by Antipatrea::GraphSearch< int >::AStar().
UpdateAtPosition()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::UpdateAtPosition (const int pos) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp().
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveAtPosition(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::Update().
GetTop()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> Key Antipatrea::Heap< Key, Compare, Equal, Hash >::GetTop (void) const inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap.
GetKeyAtPosition()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> Key Antipatrea::Heap< Key, Compare, Equal, Hash >::GetKeyAtPosition (const int pos) const inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap.
RemoveTop()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> Key Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveTop (void) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, and Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveAtPosition().
Referenced by Antipatrea::GraphSearch< int >::AStar(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::Sort().
Remove()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::Remove (const Key key) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map, and Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveAtPosition().
RemoveAtPosition()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveAtPosition (const int pos) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map, and Antipatrea::Heap< Key, Compare, Equal, Hash >::UpdateAtPosition().
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::Remove(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveTop().
Clear()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::Clear (void) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, and Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map.
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::Sort().
Sort()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::Sort (Key keys[], const int size) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::Clear(), Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveTop().
Test()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> bool Antipatrea::Heap< Key, Compare, Equal, Hash >::Test (void) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_compare, Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, and Antipatrea::Logger::m_out.
PrecolateDown()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown (const int pos) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_compare, Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map, and Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp().
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::Sort(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::UpdateAtPosition().
PrecolateUp()
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> void Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp (const int pos) inline
References Antipatrea::Heap< Key, Compare, Equal, Hash >::m_compare, Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap, and Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map.
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::Insert(), Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::UpdateAtPosition().
Member Data Documentation
m_map
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> std::unordered_map<Key, int, Hash, Equal > Antipatrea::Heap< Key, Compare, Equal, Hash >::m_map protected
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::Clear(), Antipatrea::Heap< Key, Compare, Equal, Hash >::GetKeyPosition(), Antipatrea::Heap< Key, Compare, Equal, Hash >::HasKey(), Antipatrea::Heap< Key, Compare, Equal, Hash >::Insert(), Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown(), Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp(), Antipatrea::Heap< Key, Compare, Equal, Hash >::Remove(), Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveAtPosition(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::Update().
m_heap
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> std::vector<Key> Antipatrea::Heap< Key, Compare, Equal, Hash >::m_heap protected
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::Clear(), Antipatrea::Heap< Key, Compare, Equal, Hash >::GetKeyAtPosition(), Antipatrea::Heap< Key, Compare, Equal, Hash >::GetNrKeys(), Antipatrea::Heap< Key, Compare, Equal, Hash >::GetTop(), Antipatrea::Heap< Key, Compare, Equal, Hash >::Insert(), Antipatrea::Heap< Key, Compare, Equal, Hash >::IsEmpty(), Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown(), Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp(), Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveAtPosition(), Antipatrea::Heap< Key, Compare, Equal, Hash >::RemoveTop(), Antipatrea::Heap< Key, Compare, Equal, Hash >::Sort(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::Test().
m_compare
template<typename Key, typename Compare = std::less<Key>, typename Equal = std::equal_to<Key>, typename Hash = std::hash<Key>> Compare Antipatrea::Heap< Key, Compare, Equal, Hash >::m_compare protected
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateDown(), Antipatrea::Heap< Key, Compare, Equal, Hash >::PrecolateUp(), Antipatrea::Heap< Key, Compare, Equal, Hash >::SetKeyCompare(), and Antipatrea::Heap< Key, Compare, Equal, Hash >::Test().
The documentation for this class was generated from the following file:
Heap.hpp