Antipatrea::CfgAcceptorBasedOnEnergy Class Reference
Antipatrea::CfgAcceptorBasedOnEnergy Class Reference
Motion-planning component which accepts a configuration only if its energy is below a user-defined threshold.
#include <CfgAcceptorBasedOnEnergy.hpp>
Public Member Functions
CfgAcceptorBasedOnEnergy (void)
virtual ~CfgAcceptorBasedOnEnergy (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
virtual double GetEnergyThreshold (void) const
Name says it all.
virtual void SetEnergyThreshold (const double energyThreshold)
Name says it all.
virtual bool IsAcceptable (Cfg &cfg)
Returns true iff the energy of cfg is below the user-defined threshold.
Public Member Functions inherited from Antipatrea::CfgAcceptor
CfgAcceptor (void)
virtual ~CfgAcceptor (void)
virtual Cfg * GetAnAcceptableCfg (void)
When possible, return a pointer to a configuration that is acceptable.
virtual bool IsUsedAsGoalAcceptor (void) const
Get the class purpose: goal acceptor (true) or configuration acceptor (false).
virtual void UseAsGoalAcceptor (const bool use)
Set the class purpose: goal acceptor (true) or configuration acceptor (false).
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Protected Attributes
double m_energyThreshold
User-defined energy threshold.
Protected Attributes inherited from Antipatrea::CfgAcceptor
bool m_useAsGoalAcceptor
Class purpose: goal acceptor (true) or configuration acceptor (false).
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Motion-planning component which accepts a configuration only if its energy is below a user-defined threshold.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgEnergyEvaluator component in order to evaluate the energy of the configuration.
The user should also set the energy threshold.
Constructor & Destructor Documentation
Antipatrea::CfgAcceptorBasedOnEnergy::CfgAcceptorBasedOnEnergy (void) inline
References Antipatrea::CfgAcceptor::IsUsedAsGoalAcceptor(), m_energyThreshold, Antipatrea::Constants::VAL_CfgAcceptorBasedOnEnergy_EnergyThreshold, and Antipatrea::Constants::VAL_GoalAcceptorBasedOnEnergy_EnergyThreshold.
virtual Antipatrea::CfgAcceptorBasedOnEnergy::~CfgAcceptorBasedOnEnergy (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::CfgAcceptorBasedOnEnergy::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::CfgAcceptorBasedOnEnergy::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References GetEnergyThreshold(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual void Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams (Params & params) inline virtual
Set the parameter values of the component from the given parameters.
Author
Erion Plaku, Amarda Shehu
Remarks
Function first invokes CfgAcceptor::SetupFromParams(params).
It then sets the energy threshold (keyword Constants::KW_EnergyThreshold).
When used as a goal acceptor, it uses the parameter group associated with the keyword Constants::KW_GoalAcceptorBasedOnEnergy.
When used as general cfg acceptor, it uses the parameter group associated with the keyword Constants::KW_CfgAcceptorBasedOnEnergy
The parameter value can be specified in a text file as, for example, CfgAcceptorBasedOnEnergy { EnergyThreshold -12.34 } or GoalAcceptorBasedOnEnergy { EnergyThreshold -100.12 }
Reimplemented from Antipatrea::Component.
References Antipatrea::Params::GetData(), GetEnergyThreshold(), Antipatrea::CfgAcceptor::IsUsedAsGoalAcceptor(), Antipatrea::Constants::KW_CfgAcceptorBasedOnEnergy, Antipatrea::Constants::KW_EnergyThreshold, Antipatrea::Constants::KW_GoalAcceptorBasedOnEnergy, SetEnergyThreshold(), and Antipatrea::Component::SetupFromParams().
virtual double Antipatrea::CfgAcceptorBasedOnEnergy::GetEnergyThreshold (void) const inline virtual
Name says it all.
Author
Erion Plaku, Amarda Shehu
References m_energyThreshold.
Referenced by Info(), IsAcceptable(), and SetupFromParams().
virtual void Antipatrea::CfgAcceptorBasedOnEnergy::SetEnergyThreshold (const double energyThreshold) inline virtual
Name says it all.
Author
Erion Plaku, Amarda Shehu
References m_energyThreshold.
Referenced by SetupFromParams().
virtual bool Antipatrea::CfgAcceptorBasedOnEnergy::IsAcceptable (Cfg & cfg) inline virtual
Returns true iff the energy of cfg is below the user-defined threshold.
Author
Erion Plaku, Amarda Shehu
Remarks
The function will call CfgEnergyEvaluator component to evaluate the energy of cfg
It will do so, however, only if the energy of cfg has not been previously evaluated (it checks whether the energy field is undefined – if so, it computes the energy; otherwise, it accesses the energy value).
Implements Antipatrea::CfgAcceptor.
References Antipatrea::Cfg::GetEnergy(), GetEnergyThreshold(), Antipatrea::Cfg::IsEnergySet(), and Antipatrea::Cfg::SetEnergy().
Member Data Documentation
double Antipatrea::CfgAcceptorBasedOnEnergy::m_energyThreshold protected
User-defined energy threshold.
Author
Erion Plaku, Amarda Shehu
Referenced by CfgAcceptorBasedOnEnergy(), GetEnergyThreshold(), and SetEnergyThreshold().
The documentation for this class was generated from the following file:
CfgAcceptorBasedOnEnergy.hpp