Antipatrea::PlannerGraph Class Reference
Antipatrea::PlannerGraph Class Reference
Representation of the undirected graph (roadmap or tree) constructed by a sampling-based motion planner.
#include <PlannerGraph.hpp>
Public Types
typedef std::unordered_map< std::pair< int, int >, PlannerEdge *, HashStruct< std::pair< int, int > > > Edges
Define the data structure (unordered map with the vertex pair as the key) to store all the edges of the graph.
Public Member Functions
PlannerGraph (void)
virtual ~PlannerGraph (void)
virtual int GetNrVertices (void) const
Get the number of vertices.
virtual const PlannerVertex * GetVertex (const int vid) const
Get a pointer to the i-th vertex.
virtual PlannerVertex * GetVertex (const int vid)
Get a pointer to the i-th vertex.
virtual int GetVertexByCfg (const Cfg *cfg)
Get a pointer to by CFG address (yes it is ugly).
virtual int AddVertex (PlannerVertex *const v)
Add the vertex to the graph.
virtual int GetNrEdges (void) const
Get the number of edges.
virtual std::pair< int, int > GetEdgeKey (const int vidFrom, const int vidTo) const
The key is defined as (min(vidFrom, vidTo), max(vidFrom, vidTo)).
virtual PlannerEdge * FindEdge (const int vidFrom, const int vidTo) const
Return a pointer to the edge (vidFrom, vidTo).
virtual void AddEdge (PlannerEdge *const edge)
Add the edge to the graph.
virtual bool AreVerticesPathConnected (const int vidFrom, const int vidTo)
Return true iff the two vertices are connected by a path.
virtual const DisjointSet * GetComponents (void) const
Get a pointer to the disjoint-set data structure representing the connected components in the graph.
virtual DisjointSet * GetComponents (void)
Get a pointer to the disjoint-set data structure representing the connected components in the graph.
virtual const Edges * GetEdges (void) const
Get a pointer to the data structure storing all the edges of the graph.
virtual Edges * GetEdges (void)
Get a pointer to the data structure storing all the edges of the graph.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Protected Attributes
std::vector< PlannerVertex * > m_vertices
Vertices of the graph.
DisjointSet m_components
Connected components of the graph.
Edges m_edges
Edges of the graph.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Representation of the undirected graph (roadmap or tree) constructed by a sampling-based motion planner.
Author
Erion Plaku, Amarda Shehu
Remarks
The graph has the following:
a set of vertices;
a set of edges; and
a set of connected components represented as a disjoint set.
The set of edges is the union of the edges kept by each vertex. It is kept as a separate set to facilitate enumeration and searching.
It is assumed that a sampling-based motion planner will construct an undirected graph, but the edge cost from A to B could be different from the edge cost from B to A. This could happen, for example, when the edge cost is based on the energy change.
For this reason, and to facilitate the graph search, the graph maintains the edges as directed edges. In other words, when a sampling-based motion planner makes a connection from vertex A to B, it needs to add two edges to the graph, namely, the edge (A, B) with cost from A to B and the edge (B, A) with cost from B to A.
Member Typedef Documentation
Edges
typedef std::unordered_map< std::pair<int, int>, PlannerEdge*, HashStruct< std::pair<int, int> > > Antipatrea::PlannerGraph::Edges
Define the data structure (unordered map with the vertex pair as the key) to store all the edges of the graph.
Author
Erion Plaku, Amarda Shehu
Constructor & Destructor Documentation
PlannerGraph()
Antipatrea::PlannerGraph::PlannerGraph (void) inline
References ~PlannerGraph().
~PlannerGraph()
virtual Antipatrea::PlannerGraph::~PlannerGraph (void) virtual
Referenced by PlannerGraph().
Member Function Documentation
GetNrVertices()
virtual int Antipatrea::PlannerGraph::GetNrVertices (void) const inline virtual
Get the number of vertices.
Author
Erion Plaku, Amarda Shehu
References m_vertices.
Referenced by AddVertex().
GetVertex() [1/2]
virtual const PlannerVertex* Antipatrea::PlannerGraph::GetVertex (const int vid) const inline virtual
Get a pointer to the i-th vertex.
Author
Erion Plaku, Amarda Shehu
Remarks
i should be between 0 and GetNrVertices()-1
The function does not check whether i is within the proper range.
References m_vertices.
Referenced by AreVerticesPathConnected().
GetVertex() [2/2]
virtual PlannerVertex* Antipatrea::PlannerGraph::GetVertex (const int vid) inline virtual
Get a pointer to the i-th vertex.
Author
Erion Plaku, Amarda Shehu
Remarks
i should be between 0 and GetNrVertices()-1
The function does not check whether i is within the proper range.
References m_vertices.
GetVertexByCfg()
virtual int Antipatrea::PlannerGraph::GetVertexByCfg (const Cfg * cfg) inline virtual
Get a pointer to by CFG address (yes it is ugly).
Author
Erion Plaku, Amarda Shehu
References m_vertices.
AddVertex()
virtual int Antipatrea::PlannerGraph::AddVertex (PlannerVertex *const v) inline virtual
Add the vertex to the graph.
Author
Erion Plaku, Amarda Shehu
Remarks
The function also creates a new graph component with v as its only vertex.
References GetNrVertices(), m_components, m_vertices, Antipatrea::DisjointSet::Make(), and Antipatrea::PlannerVertex::SetDisjointSetElem().
GetNrEdges()
virtual int Antipatrea::PlannerGraph::GetNrEdges (void) const inline virtual
Get the number of edges.
Author
Erion Plaku, Amarda Shehu
References m_edges.
GetEdgeKey()
virtual std::pair<int, int> Antipatrea::PlannerGraph::GetEdgeKey (const int vidFrom, const int vidTo) const inline virtual
The key is defined as (min(vidFrom, vidTo), max(vidFrom, vidTo)).
Author
Erion Plaku, Amarda Shehu
Referenced by FindEdge().
FindEdge()
virtual PlannerEdge* Antipatrea::PlannerGraph::FindEdge (const int vidFrom, const int vidTo) const inline virtual
Return a pointer to the edge (vidFrom, vidTo).
Author
Erion Plaku, Amarda Shehu
Remarks
If the edge is not in the graph, the function returns NULL.
References AddEdge(), GetEdgeKey(), and m_edges.
AddEdge()
virtual void Antipatrea::PlannerGraph::AddEdge (PlannerEdge *const edge) virtual
Add the edge to the graph.
Author
Erion Plaku, Amarda Shehu
Remarks
The function does not check if the edge is already in the graph. It is the responsibility of the calling function to perform this check (using FindEdge) if indeed there may be a possibility that the same edge could be added multiple times.
The function also joins the components associated with the end vertices of the edge.
Referenced by FindEdge().
AreVerticesPathConnected()
virtual bool Antipatrea::PlannerGraph::AreVerticesPathConnected (const int vidFrom, const int vidTo) inline virtual
Return true iff the two vertices are connected by a path.
Author
Erion Plaku, Amarda Shehu
Remarks
This function uses the disjoint-set data structure, so it works correctly only if the graph is undirected, i.e., if (A, B) is an edge in the graph, then so is (B, A).
References GetVertex(), m_components, and Antipatrea::DisjointSet::Same().
GetComponents() [1/2]
virtual const DisjointSet* Antipatrea::PlannerGraph::GetComponents (void) const inline virtual
Get a pointer to the disjoint-set data structure representing the connected components in the graph.
Author
Erion Plaku, Amarda Shehu
References m_components.
GetComponents() [2/2]
virtual DisjointSet* Antipatrea::PlannerGraph::GetComponents (void) inline virtual
Get a pointer to the disjoint-set data structure representing the connected components in the graph.
Author
Erion Plaku, Amarda Shehu
References m_components.
GetEdges() [1/2]
virtual const Edges* Antipatrea::PlannerGraph::GetEdges (void) const inline virtual
Get a pointer to the data structure storing all the edges of the graph.
Author
Erion Plaku, Amarda Shehu
References m_edges.
GetEdges() [2/2]
virtual Edges* Antipatrea::PlannerGraph::GetEdges (void) inline virtual
Get a pointer to the data structure storing all the edges of the graph.
Author
Erion Plaku, Amarda Shehu
References m_edges.
Member Data Documentation
m_vertices
std::vector<PlannerVertex*> Antipatrea::PlannerGraph::m_vertices protected
Vertices of the graph.
Author
Erion Plaku, Amarda Shehu
Referenced by AddVertex(), GetNrVertices(), GetVertex(), and GetVertexByCfg().
m_components
DisjointSet Antipatrea::PlannerGraph::m_components protected
Connected components of the graph.
Author
Erion Plaku, Amarda Shehu
Referenced by AddVertex(), AreVerticesPathConnected(), and GetComponents().
m_edges
Edges Antipatrea::PlannerGraph::m_edges protected
Edges of the graph.
Author
Erion Plaku, Amarda Shehu
Referenced by FindEdge(), GetEdges(), and GetNrEdges().
The documentation for this class was generated from the following file:
PlannerGraph.hpp