Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath Class Reference
Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath Class Reference
#include <CfgOffspringGeneratorTowardTargetByPartialPath.hpp>
Public Member Functions
CfgOffspringGeneratorTowardTargetByPartialPath (void)
virtual ~CfgOffspringGeneratorTowardTargetByPartialPath (void)
virtual void Info (const char prefix[]) const
virtual bool CheckSetup (void)
virtual void GenerateOffspring (const Cfg &cfgCurr, Cfg &cfgOffspring)
Public Member Functions inherited from Antipatrea::CfgOffspringGeneratorTowardTarget
CfgOffspringGeneratorTowardTarget (void)
virtual ~CfgOffspringGeneratorTowardTarget (void)
virtual const Cfg * GetTargetCfg (void) const
virtual void SetTargetCfg (const Cfg *cfgTarget)
virtual double GetTimeStep (void) const
virtual void SetTimeStep (const double tstep)
Public Member Functions inherited from Antipatrea::CfgOffspringGenerator
CfgOffspringGenerator (void)
virtual ~CfgOffspringGenerator (void)
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Protected Attributes inherited from Antipatrea::CfgOffspringGeneratorTowardTarget
const Cfg * m_cfgTarget
double m_tstep
Constructor & Destructor Documentation
Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath::CfgOffspringGeneratorTowardTargetByPartialPath (void) inline
virtual Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath::~CfgOffspringGeneratorTowardTargetByPartialPath (void) inline virtual
Member Function Documentation
virtual void Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath::Info (const char prefix[]) const inline virtual
Reimplemented from Antipatrea::CfgOffspringGeneratorTowardTarget.
References Antipatrea::CfgOffspringGeneratorTowardTarget::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual bool Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup(), Antipatrea::ClassContainer(), and GenerateOffspring().
virtual void Antipatrea::CfgOffspringGeneratorTowardTargetByPartialPath::GenerateOffspring (const Cfg & cfgCurr, Cfg & cfgOffspring) virtual
Implements Antipatrea::CfgOffspringGenerator.
Referenced by CheckSetup().
The documentation for this class was generated from the following file:
CfgOffspringGeneratorTowardTargetByPartialPath.hpp