Antipatrea::CfgForwardKinematics Class Reference
Antipatrea::CfgForwardKinematics Class Reference abstract
Interface for computing the forward kinematics corresponding to the specified configuration values.
#include <CfgForwardKinematics.hpp>
Public Member Functions
CfgForwardKinematics (void)
virtual ~CfgForwardKinematics (void)
virtual void CopyJointValues (const double vals[])
Copy the joint values.
virtual void FK (void)
Compute the forward kinematics if FLAG_RECOMPUTE_FK has been set.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
Protected Types
enum { FLAG_RECOMPUTE_FK = 1 }
Protected Member Functions
virtual void OnValuesChanged (void)
Set FLAG_RECOMPUTE_FK when values change.
virtual void DoFK (void)=0
Implement the forward kinematics.
Protected Attributes
std::vector< double > m_joints
Joint values.
Flags m_flags
Flags to keep track of status, e.g., whether or not FK should be recomputed.
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface for computing the forward kinematics corresponding to the specified configuration values.
Author
Erion Plaku, Amarda Shehu
Remarks
This class requires access to CfgManager component in order to access the configuration dimension.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
FLAG_RECOMPUTE_FK
Constructor & Destructor Documentation
CfgForwardKinematics()
Antipatrea::CfgForwardKinematics::CfgForwardKinematics (void) inline
~CfgForwardKinematics()
virtual Antipatrea::CfgForwardKinematics::~CfgForwardKinematics (void) inline virtual
References CopyJointValues().
Member Function Documentation
CopyJointValues()
virtual void Antipatrea::CfgForwardKinematics::CopyJointValues (const double vals[]) virtual
Copy the joint values.
Author
Erion Plaku, Amarda Shehu
Remarks
The function also sets FLAG_RECOMPUTE_FK if the new values, vals, are different from the current values. If they are the same, the flag is not set to avoid recomputing the forward kinematics.
Referenced by ~CfgForwardKinematics().
FK()
virtual void Antipatrea::CfgForwardKinematics::FK (void) inline virtual
Compute the forward kinematics if FLAG_RECOMPUTE_FK has been set.
Author
Erion Plaku, Amarda Shehu
References DoFK(), FLAG_RECOMPUTE_FK, Antipatrea::HasFlag(), m_flags, and Antipatrea::RemoveFlag().
OnValuesChanged()
virtual void Antipatrea::CfgForwardKinematics::OnValuesChanged (void) inline protected virtual
Set FLAG_RECOMPUTE_FK when values change.
Author
Erion Plaku, Amarda Shehu
References Antipatrea::AddFlag(), DoFK(), FLAG_RECOMPUTE_FK, and m_flags.
DoFK()
virtual void Antipatrea::CfgForwardKinematics::DoFK (void) protected pure virtual
Implement the forward kinematics.
Author
Erion Plaku, Amarda Shehu
Remarks
This function should always compute the forward kinematics, ignoring flag values.
Implemented in Antipatrea::Chain2D, and Antipatrea::MolecularStructureRosetta.
Referenced by FK(), and OnValuesChanged().
Member Data Documentation
m_joints
std::vector<double> Antipatrea::CfgForwardKinematics::m_joints protected
Joint values.
Author
Erion Plaku, Amarda Shehu
Referenced by Antipatrea::Chain2D::GetLinkTheta(), and Antipatrea::Chain2D::GetNrJoints().
m_flags
Flags Antipatrea::CfgForwardKinematics::m_flags protected
Flags to keep track of status, e.g., whether or not FK should be recomputed.
Author
Erion Plaku, Amarda Shehu
Referenced by FK(), and OnValuesChanged().
The documentation for this class was generated from the following file:
CfgForwardKinematics.hpp