Antipatrea::PathAcceptor Class Reference
Antipatrea::PathAcceptor Class Reference abstract
Interface to test whether or not a path is valid at a given time-step resolution.
#include <PathAcceptor.hpp>
Public Member Functions
PathAcceptor (void)
virtual ~PathAcceptor (void)
virtual bool CheckSetup (void)
Check whether or not the component has been setup correctly.
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual bool IsAcceptable (PathGenerator &pathGenerator, const double tstep)=0
Test whether or not a path is valid at the given time-step resolution.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Interface to test whether or not a path is valid at a given time-step resolution.
Author
Erion Plaku, Amarda Shehu
Remarks
The path is considered valid iff every configuration along the path is acceptable.
For practical purposes, classes implementing this interface often discretize the path at a given time-step resolution into a sequence of configurations and deem the path acceptable iff every configuration in the sequence is acceptable.
The end configurations (at time = 0 and time = 1) are not checked (assumed to be acceptable).
This class requires access to CfgManager and CfgAcceptor to determine whether or not configurations along the path are acceptable.
Constructor & Destructor Documentation
Antipatrea::PathAcceptor::PathAcceptor (void) inline
virtual Antipatrea::PathAcceptor::~PathAcceptor (void) inline virtual
Member Function Documentation
virtual bool Antipatrea::PathAcceptor::CheckSetup (void) inline virtual
Check whether or not the component has been setup correctly.
Author
Erion Plaku, Amarda Shehu
Remarks
Check that parameter values and/or pointers to other components or objects have been setup correctly.
References Antipatrea::Component::CheckSetup().
virtual void Antipatrea::PathAcceptor::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::ClassContainer(), Antipatrea::Object::Info(), IsAcceptable(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
virtual bool Antipatrea::PathAcceptor::IsAcceptable (PathGenerator & pathGenerator, const double tstep) pure virtual
Test whether or not a path is valid at the given time-step resolution.
Author
Erion Plaku, Amarda Shehu
Implemented in Antipatrea::PathAcceptorBySubdivision, and Antipatrea::PathAcceptorByIncrement.
Referenced by Info().
The documentation for this class was generated from the following file:
PathAcceptor.hpp