Antipatrea::EdgeCostEvaluatorBasedOnMW Class Reference
Antipatrea::EdgeCostEvaluatorBasedOnMW Class Reference
Edge cost is defined as the min(0,change in energy between the start and end configurations).
#include <EdgeCostEvaluatorBasedOnMW.hpp>
Public Member Functions
EdgeCostEvaluatorBasedOnMW (void)
virtual ~EdgeCostEvaluatorBasedOnMW (void)
virtual bool CheckSetup (void)
virtual void Info (const char prefix[]) const
Print the paramater values and the names of the components used by this class.
virtual Costs EvaluateGivenFromToCfgs (Cfg &cfgFrom, Cfg &cfgTo)
Compute the costs for the direct and reverse edge as the change in energy between the start and end configurations.
Public Member Functions inherited from Antipatrea::EdgeCostEvaluator
EdgeCostEvaluator (void)
virtual ~EdgeCostEvaluator (void)
virtual Costs EvaluateGivenFromToAndIntermediateCfgs (Cfg &cfgFrom, Cfg &cfgTo, std::vector< Cfg *> &intermediates)
Evaluate the direct and reverse cost of a path when given the start, end, and the sequence of intermediate configurations.
Public Member Functions inherited from Antipatrea::Component
Component (void)
virtual ~Component (void)
virtual bool CheckSetup (void) const
Check whether or not the component has been setup correctly.
virtual void SetupFromParams (Params &params)
Set the parameter values of the component from the given parameters.
Public Member Functions inherited from Antipatrea::Object
Object (void)
virtual ~Object (void)
Additional Inherited Members
Static Public Member Functions inherited from Antipatrea::Object
static const char * Name (const Object *const obj)
Return the class name associated with the object.
Detailed Description
Edge cost is defined as the min(0,change in energy between the start and end configurations).
Author
Erion Plaku, Amarda Shehu
Remarks
This class needs access to CfgEnergyEvaluator in order to evaluate the configuration energy.
Constructor & Destructor Documentation
EdgeCostEvaluatorBasedOnMW()
Antipatrea::EdgeCostEvaluatorBasedOnMW::EdgeCostEvaluatorBasedOnMW (void) inline
~EdgeCostEvaluatorBasedOnMW()
virtual Antipatrea::EdgeCostEvaluatorBasedOnMW::~EdgeCostEvaluatorBasedOnMW (void) inline virtual
Member Function Documentation
CheckSetup()
virtual bool Antipatrea::EdgeCostEvaluatorBasedOnMW::CheckSetup (void) inline virtual
References Antipatrea::Component::CheckSetup().
Info()
virtual void Antipatrea::EdgeCostEvaluatorBasedOnMW::Info (const char prefix[]) const inline virtual
Print the paramater values and the names of the components used by this class.
Author
Erion Plaku, Amarda Shehu
Remarks
This function is useful for debugging purposes to see that the component has been setup as desired.
prefix is used to ensure proper alignment when printing (you can use "" for the prefix, for example).
Reimplemented from Antipatrea::Object.
References Antipatrea::ClassContainer(), EvaluateGivenFromToCfgs(), Antipatrea::Object::Info(), Antipatrea::Logger::m_out, and Antipatrea::Object::Name().
EvaluateGivenFromToCfgs()
virtual Costs Antipatrea::EdgeCostEvaluatorBasedOnMW::EvaluateGivenFromToCfgs (Cfg & cfgFrom, Cfg & cfgTo) virtual
Compute the costs for the direct and reverse edge as the change in energy between the start and end configurations.
Author
Erion Plaku, Amarda Shehu
Implements Antipatrea::EdgeCostEvaluator.
Referenced by Info().
The documentation for this class was generated from the following file:
EdgeCostEvaluatorBasedOnMW.hpp