Antipatrea::Algebra3D Namespace Reference
Antipatrea::Algebra3D Namespace Reference
Enumerations
enum {
Trans_NR_ENTRIES = 3,
Quat_NR_ENTRIES = 4,
Rot_NR_ENTRIES = 9,
AxisAngle_NR_ENTRIES = 4,
TransQuat_NR_ENTRIES = 7,
TransRot_NR_ENTRIES = 12,
TransAxisAngle_NR_ENTRIES = 7
}
Functions
static double VecDotProduct (const double v1[], const double v2[])
static void VecCrossProduct (const double v1[], const double v2[], double v[])
static void VecNormalToTriangle (const double ta[], const double tb[], const double tc[], double v[])
static double PointDistanceSquared (const double p1[], const double p2[])
static double PointDistance (const double p1[], const double p2[])
static double VecNormSquared (const double v[])
static double VecNorm (const double v[])
static void VecUnit (const double v[], double vunit[])
static void VecScale (const double v[], const double s, double vscaled[])
static void VecClampMagnitude (double v[], const double dmax)
static void VecAdd (const double v1[], const double v2[], double v[])
static void VecSubtract (const double v1[], const double v2[], double v[])
static void VecLinearInterpolation (const double v1[], const double t1, const double v2[], const double t2, double v[])
static double VecAngle (const double v1[], const double v2[])
static double VecAngleUnitArgs (const double v1[], const double v2[])
void VecNormal (const double v[], double vnormal[])
static void VecParallelProjection (const double v[], const double u[], double v_on_u[])
static void VecParallelProjectionUnitArgs (const double v[], const double u[], double v_on_u[])
static void VecOrthogonalProjection (const double v[], const double u[], double v_on_u[])
static void VecOrthogonalProjectionUnitArgs (const double v[], const double u[], double v_on_u[])
static bool VecAreNormal (const double v1[], const double v2[])
static bool VecAreParallelOrAntiParallel (const double v1[], const double v2[])
static bool VecAreParallel (const double v1[], const double v2[])
static bool VecAreAntiParallel (const double v1[], const double v2[])
static int VecAlignment (const double v1[], const double v2[])
static bool VecAreParallelOrAntiParallelUnitArgs (const double v1[], const double v2[])
static bool VecAreParallelUnitArgs (const double v1[], const double v2[])
static bool VecAreAntiParallelUnitArgs (const double v1[], const double v2[])
static int VecAlignmentUnitArgs (const double v1[], const double v2[])
static double QuatDotProduct (const double Q1[], const double Q2[])
static double QuatNormSquared (const double Q[])
static double QuatNorm (const double Q[])
static void QuatUnit (const double Q[], double Qunit[])
static void IdentityAsTrans (double T[])
static void IdentityAsQuat (double Q[])
static void IdentityAsRot (double R[])
static void IdentityAsAxisAngle (double AA[])
static void IdentityAsTransQuat (double TQ[])
static void IdentityAsTransRot (double TR[])
static void IdentityAsTransAxisAngle (double TAA[])
static bool IdentitySameAsTrans (const double T[])
static bool IdentitySameAsQuat (const double Q[])
static bool IdentitySameAsRot (const double R[])
static bool IdentitySameAsTransQuat (const double TQ[])
static bool IdentitySameAsTransRot (const double TR[])
static void TransAsTrans (const double x, const double y, const double z, double Tresult[])
static void TransAsTrans (const double T[], double Tresult[])
static void QuatAsQuat (const double Q[], double Qresult[])
static void QuatAsRot (const double Q[], double R[])
static void QuatAsAxisAngle (const double Q[], double AA[])
static void QuatAsUnitAxisAngle (const double Q[], double AA[])
void RotAsQuat (const double R[], double Q[])
static void RotAsRot (const double R[], double Rresult[])
static void RotAsAxisAngle (const double R[], double AA[])
static void RotAsUnitAxisAngle (const double R[], double AA[])
static void UnitAxisAngleAsQuat (const double AA[], double Q[])
static void AxisAngleAsQuat (const double AA[], double Q[])
static void UnitAxisAngleAsRot (const double AA[], double R[])
static void XAxisAngleAsRot (const double theta, double R[])
static void YAxisAngleAsRot (const double theta, double R[])
static void ZAxisAngleAsRot (const double theta, double R[])
static void AxisAngleAsRot (const double AA[], double R[])
static void AxisAngleAsAxisAngle (const double AA[], double AAresult[])
static void AxisAngleAsUnitAxisAngle (const double AA[], double AAresult[])
void FromToAxisAsQuat (const double Afrom[], const double Ato[], const double normProd, double Q[])
static void FromToUnitAxisAsQuat (const double Afrom[], const double Ato[], double Q[])
static void FromToAxisAsQuat (const double Afrom[], const double Ato[], double Q[])
void FromToAxisAsRot (const double Afrom[], const double Ato[], const double normProd, double R[])
static void FromToUnitAxisAsRot (const double Afrom[], const double Ato[], double R[])
static void FromToAxisAsRot (const double Afrom[], const double Ato[], double R[])
void FromToAxisAsAxisAngle (const double Afrom[], const double Ato[], const double normProd, double AA[])
static void FromToUnitAxisAsAxisAngle (const double Afrom[], const double Ato[], double AA[])
static void FromToAxisAsAxisAngle (const double Afrom[], const double Ato[], double AA[])
static void TransQuatAsTransQuat (const double TQ[], double TQresult[])
static void TransQuatAsTransRot (const double TQ[], double TR[])
static void TransQuatAsTransAxisAngle (const double TQ[], double TAA[])
static void TransQuatAsTransUnitAxisAngle (const double TQ[], double TAA[])
static void TransRotAsTransQuat (const double TR[], double TQ[])
static void TransRotAsTransRot (const double TR[], double TRresult[])
static void TransRotAsTransAxisAngle (const double TR[], double TAA[])
static void TransRotAsTransUnitAxisAngle (const double TR[], double TAA[])
static void TransAxisAngleAsTransQuat (const double TAA[], double TQ[])
static void TransAxisAngleAsTransRot (const double TAA[], double TR[])
static void TransAxisAngleAsTransAxisAngle (const double TAA[], double TAAresult[])
static void TransAxisAngleAsTransUnitAxisAngle (const double TAA[], double TAAresult[])
static void TransUnitAxisAngleAsTransQuat (const double TAA[], double TQ[])
static void TransUnitAxisAngleAsTransRot (const double TAA[], double TR[])
static void TransUnitAxisAngleAsTransAxisAngle (const double TAA[], double TAAresult[])
static void TransUnitAxisAngleAsTransUnitAxisAngle (const double TAA[], double TAAresult[])
static bool TransSameAsTrans (const double Ta[], const double Tb[])
static bool QuatSameAsQuat (const double Qa[], const double Qb[])
static bool QuatSameAsRot (const double Q[], const double R[])
static bool RotSameAsQuat (const double R[], const double Q[])
static bool RotSameAsRot (const double Ra[], const double Rb[])
static bool TransQuatSameAsTransQuat (const double TQa[], const double TQb[])
static bool TransQuatSameAsTransRot (const double TQ[], const double TR[])
static bool TransRotSameAsTransQuat (const double TR[], const double TQ[])
static bool TransRotSameAsTransRot (const double TRa[], const double TRb[])
static void TransMultPoint (const double T[], const double p[], double pnew[])
static void TransMultInvPoint (const double T[], const double p[], double pnew[])
static void InvTransMultPoint (const double T[], const double p[], double pnew[])
static void InvTransMultInvPoint (const double T[], const double p[], double pnew[])
static void QuatMultPoint (const double Q[], const double p[], double pnew[])
static void QuatMultInvPoint (const double Q[], const double p[], double pnew[])
static void InvQuatMultPoint (const double Q[], const double p[], double pnew[])
static void InvQuatMultInvPoint (const double Q[], const double p[], double pnew[])
static void QuatMultXAxis (const double Q[], double axis[])
static void QuatMultNegXAxis (const double Q[], double axis[])
static void InvQuatMultXAxis (const double Q[], double axis[])
static void QuatMultYAxis (const double Q[], double ynew[])
static void QuatMultZAxis (const double Q[], double znew[])
static void RotMultPoint (const double R[], const double p[], double pnew[])
static void RotMultInvPoint (const double R[], const double p[], double pnew[])
static void InvRotMultPoint (const double R[], const double p[], double pnew[])
static void InvRotMultInvPoint (const double R[], const double p[], double pnew[])
static void RotMultXAxis (const double R[], double xnew[])
static void RotMultYAxis (const double R[], double ynew[])
static void RotMultZAxis (const double R[], double znew[])
static void TransQuatMultPoint (const double TQ[], const double p[], double pnew[])
static void TransQuatMultInvPoint (const double TQ[], const double p[], double pnew[])
static void InvTransQuatMultPoint (const double TQ[], const double p[], double pnew[])
static void InvTransQuatMultInvPoint (const double TQ[], const double p[], double pnew[])
static void TransRotMultPoint (const double TR[], const double p[], double pnew[])
static void TransRotMultInvPoint (const double TR[], const double p[], double pnew[])
static void InvTransRotMultPoint (const double TR[], const double p[], double pnew[])
static void InvTransRotMultInvPoint (const double TR[], const double p[], double pnew[])
static void InvTransAsTrans (const double T[], double Tresult[])
static void InvQuatAsQuat (const double Q[], double Qresult[])
static void InvQuatAsRot (const double Q[], double R[])
static void InvRotAsQuat (const double R[], double Q[])
static void InvRotAsRot (const double R[], double Rresult[])
static void InvTransQuatAsTransQuat (const double TQ[], double TQresult[])
static void InvTransQuatAsTransRot (const double TQ[], double TR[])
static void InvTransRotAsTransQuat (const double TR[], double TQ[])
static void InvTransRotAsTransRot (const double TR[], double TRresult[])
static void TransMultTransAsTrans (const double Ta[], const double Tb[], double T[])
static void TransMultQuatAsTransQuat (const double T[], const double Q[], double TQ[])
static void TransMultQuatAsTransRot (const double T[], const double Q[], double TR[])
static void TransMultRotAsTransQuat (const double T[], const double R[], double TQ[])
static void TransMultRotAsTransRot (const double T[], const double R[], double TR[])
static void TransMultTransQuatAsTransQuat (const double T[], const double TQ[], double TQresult[])
static void TransMultTransQuatAsTransRot (const double T[], const double TQ[], double TR[])
static void TransMultTransRotAsTransQuat (const double T[], const double TR[], double TQ[])
static void TransMultTransRotAsTransRot (const double T[], const double TR[], double TRresult[])
static void QuatMultTransAsTransQuat (const double Q[], const double T[], double TQ[])
static void QuatMultTransAsTransRot (const double Q[], const double T[], double TR[])
static void QuatMultQuatAsQuat (const double Qa[], const double Qb[], double Q[])
static void QuatMultQuatAsRot (const double Qa[], const double Qb[], double R[])
static void QuatMultRotAsQuat (const double Q[], const double R[], double Qresult[])
void RotMultRotAsRot (const double Ra[], const double Rb[], double R[])
static void QuatMultRotAsRot (const double Q[], const double R[], double Rresult[])
static void QuatMultTransQuatAsTransQuat (const double Q[], const double TQ[], double TQresult[])
static void QuatMultTransQuatAsTransRot (const double Q[], const double TQ[], double TR[])
static void QuatMultTransRotAsTransQuat (const double Q[], const double TR[], double TQ[])
static void QuatMultTransRotAsTransRot (const double Q[], const double TR[], double TRresult[])
static void RotMultTransAsTransQuat (const double R[], const double T[], double TQ[])
static void RotMultTransAsTransRot (const double R[], const double T[], double TR[])
static void RotMultQuatAsQuat (const double R[], const double Q[], double Qresult[])
static void RotMultQuatAsRot (const double R[], const double Q[], double Rresult[])
static void RotMultRotAsQuat (const double Ra[], const double Rb[], double Q[])
static void RotMultTransQuatAsTransQuat (const double R[], const double TQ[], double TQresult[])
static void RotMultTransQuatAsTransRot (const double R[], const double TQ[], double TRresult[])
static void RotMultTransRotAsTransQuat (const double R[], const double TR[], double TQ[])
static void RotMultTransRotAsTransRot (const double R[], const double TR[], double TRresult[])
static void TransQuatMultTransAsTransQuat (const double TQ[], const double T[], double TQresult[])
static void TransQuatMultTransAsTransRot (const double TQ[], const double T[], double TR[])
static void TransQuatMultQuatAsTransQuat (const double TQ[], const double Q[], double TQresult[])
static void TransQuatMultQuatAsTransRot (const double TQ[], const double Q[], double TR[])
static void TransQuatMultRotAsTransQuat (const double TQ[], const double R[], double TQresult[])
static void TransQuatMultRotAsTransRot (const double TQ[], const double R[], double TR[])
static void TransQuatMultTransQuatAsTransQuat (const double TQa[], const double TQb[], double TQ[])
static void TransQuatMultTransQuatAsTransRot (const double TQa[], const double TQb[], double TR[])
static void TransQuatMultTransRotAsTransQuat (const double TQ[], const double TR[], double TQresult[])
static void TransQuatMultTransRotAsTransRot (const double TQ[], const double TR[], double TRresult[])
static void TransRotMultTransAsTransQuat (const double TR[], const double T[], double TQresult[])
static void TransRotMultTransAsTransRot (const double TR[], const double T[], double TRresult[])
static void TransRotMultQuatAsTransQuat (const double TR[], const double Q[], double TQresult[])
static void TransRotMultQuatAsTransRot (const double TR[], const double Q[], double TRresult[])
static void TransRotMultRotAsTransQuat (const double TR[], const double R[], double TQresult[])
static void TransRotMultRotAsTransRot (const double TR[], const double R[], double TRresult[])
static void TransRotMultTransQuatAsTransQuat (const double TR[], const double TQ[], double TQresult[])
static void TransRotMultTransQuatAsTransRot (const double TR[], const double TQ[], double TRresult[])
static void TransRotMultTransRotAsTransQuat (const double TRa[], const double TRb[], double TQ[])
static void TransRotMultTransRotAsTransRot (const double TRa[], const double TRb[], double TR[])
static void TransSampleUniform (double T[])
static void TransSampleUniform (double T[], const double bbox[])
void QuatSampleUniform_Marsaglia (double Q[])
void QuatSampleUniform_Gaussian (double Q[])
void QuatSampleUniform_Shoemake (double Q[])
static void QuatSampleUniform (double Q[])
static void RotSampleUniform (double R[])
static void TransQuatSampleUniform (double TQ[])
static void TransQuatSampleUniform (double TQ[], const double bbox[])
static void TransRotSampleUniform (double TR[])
static void TransRotSampleUniform (double TR[], const double bbox[])
static void QuatLERP (const double Q1[], const double Q2[], const double t, double Q[])
static void TransQuatLERP (const double TQ1[], const double TQ2[], const double t, double TQ[])
static void QuatSLERP (const double Q1[], const double Q2[], const double t, double Q[])
static void TransQuatSLERP (const double TQ1[], const double TQ2[], const double t, double TQ[])
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
Trans_NR_ENTRIES
Quat_NR_ENTRIES
Rot_NR_ENTRIES
AxisAngle_NR_ENTRIES
TransQuat_NR_ENTRIES
TransRot_NR_ENTRIES
TransAxisAngle_NR_ENTRIES
Function Documentation
VecDotProduct()
static double Antipatrea::Algebra3D::VecDotProduct (const double v1[], const double v2[]) inline static
Referenced by FromToAxisAsAxisAngle(), FromToAxisAsQuat(), FromToAxisAsRot(), QuatAsUnitAxisAngle(), VecAlignment(), VecAlignmentUnitArgs(), VecAngle(), VecAngleUnitArgs(), VecAreAntiParallel(), VecAreAntiParallelUnitArgs(), VecAreNormal(), VecAreParallel(), VecAreParallelOrAntiParallelUnitArgs(), VecAreParallelUnitArgs(), VecNormSquared(), VecOrthogonalProjection(), VecOrthogonalProjectionUnitArgs(), VecParallelProjection(), and VecParallelProjectionUnitArgs().
VecCrossProduct()
static void Antipatrea::Algebra3D::VecCrossProduct (const double v1[], const double v2[], double v[]) inline static
Referenced by VecNormalToTriangle().
VecNormalToTriangle()
static void Antipatrea::Algebra3D::VecNormalToTriangle (const double ta[], const double tb[], const double tc[], double v[]) inline static
References VecCrossProduct().
PointDistanceSquared()
static double Antipatrea::Algebra3D::PointDistanceSquared (const double p1[], const double p2[]) inline static
Referenced by PointDistance().
PointDistance()
static double Antipatrea::Algebra3D::PointDistance (const double p1[], const double p2[]) inline static
References PointDistanceSquared().
VecNormSquared()
static double Antipatrea::Algebra3D::VecNormSquared (const double v[]) inline static
References VecDotProduct().
Referenced by VecClampMagnitude(), and VecNorm().
VecNorm()
static double Antipatrea::Algebra3D::VecNorm (const double v[]) inline static
References VecNormSquared().
Referenced by AxisAngleAsRot(), VecAngle(), VecOrthogonalProjection(), VecParallelProjection(), and VecUnit().
VecUnit()
static void Antipatrea::Algebra3D::VecUnit (const double v[], double vunit[]) inline static
References VecNorm().
Referenced by AxisAngleAsUnitAxisAngle().
VecScale()
static void Antipatrea::Algebra3D::VecScale (const double v[], const double s, double vscaled[]) inline static
Referenced by VecClampMagnitude().
VecClampMagnitude()
static void Antipatrea::Algebra3D::VecClampMagnitude (double v[], const double dmax) inline static
References VecNormSquared(), and VecScale().
VecAdd()
static void Antipatrea::Algebra3D::VecAdd (const double v1[], const double v2[], double v[]) inline static
VecSubtract()
static void Antipatrea::Algebra3D::VecSubtract (const double v1[], const double v2[], double v[]) inline static
VecLinearInterpolation()
static void Antipatrea::Algebra3D::VecLinearInterpolation (const double v1[], const double t1, const double v2[], const double t2, double v[]) inline static
VecAngle()
static double Antipatrea::Algebra3D::VecAngle (const double v1[], const double v2[]) inline static
References VecDotProduct(), and VecNorm().
VecAngleUnitArgs()
static double Antipatrea::Algebra3D::VecAngleUnitArgs (const double v1[], const double v2[]) inline static
References VecDotProduct(), and VecNormal().
VecNormal()
void Antipatrea::Algebra3D::VecNormal (const double v[], double vnormal[])
Referenced by VecAngleUnitArgs().
VecParallelProjection()
static void Antipatrea::Algebra3D::VecParallelProjection (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), and VecNorm().
VecParallelProjectionUnitArgs()
static void Antipatrea::Algebra3D::VecParallelProjectionUnitArgs (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct().
VecOrthogonalProjection()
static void Antipatrea::Algebra3D::VecOrthogonalProjection (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), and VecNorm().
VecOrthogonalProjectionUnitArgs()
static void Antipatrea::Algebra3D::VecOrthogonalProjectionUnitArgs (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct().
VecAreNormal()
static bool Antipatrea::Algebra3D::VecAreNormal (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreParallelOrAntiParallel()
static bool Antipatrea::Algebra3D::VecAreParallelOrAntiParallel (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON_SQUARED.
Referenced by VecAlignment(), VecAreAntiParallel(), and VecAreParallel().
VecAreParallel()
static bool Antipatrea::Algebra3D::VecAreParallel (const double v1[], const double v2[]) inline static
References VecAreParallelOrAntiParallel(), and VecDotProduct().
VecAreAntiParallel()
static bool Antipatrea::Algebra3D::VecAreAntiParallel (const double v1[], const double v2[]) inline static
References VecAreParallelOrAntiParallel(), and VecDotProduct().
VecAlignment()
static int Antipatrea::Algebra3D::VecAlignment (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::ANTI_PARALLEL, Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL, Antipatrea::Constants::PARALLEL, VecAreParallelOrAntiParallel(), and VecDotProduct().
VecAreParallelOrAntiParallelUnitArgs()
static bool Antipatrea::Algebra3D::VecAreParallelOrAntiParallelUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreParallelUnitArgs()
static bool Antipatrea::Algebra3D::VecAreParallelUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreAntiParallelUnitArgs()
static bool Antipatrea::Algebra3D::VecAreAntiParallelUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAlignmentUnitArgs()
static int Antipatrea::Algebra3D::VecAlignmentUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::ANTI_PARALLEL, Antipatrea::Constants::EPSILON, Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL, Antipatrea::Constants::PARALLEL, and VecDotProduct().
QuatDotProduct()
static double Antipatrea::Algebra3D::QuatDotProduct (const double Q1[], const double Q2[]) inline static
Referenced by QuatNormSquared(), and QuatSLERP().
QuatNormSquared()
static double Antipatrea::Algebra3D::QuatNormSquared (const double Q[]) inline static
References QuatDotProduct().
Referenced by QuatNorm().
QuatNorm()
static double Antipatrea::Algebra3D::QuatNorm (const double Q[]) inline static
References QuatNormSquared().
Referenced by QuatUnit().
QuatUnit()
static void Antipatrea::Algebra3D::QuatUnit (const double Q[], double Qunit[]) inline static
References QuatNorm().
Referenced by QuatLERP().
IdentityAsTrans()
static void Antipatrea::Algebra3D::IdentityAsTrans (double T[]) inline static
IdentityAsQuat()
static void Antipatrea::Algebra3D::IdentityAsQuat (double Q[]) inline static
Referenced by AxisAngleAsQuat().
IdentityAsRot()
static void Antipatrea::Algebra3D::IdentityAsRot (double R[]) inline static
Referenced by AxisAngleAsRot().
IdentityAsAxisAngle()
static void Antipatrea::Algebra3D::IdentityAsAxisAngle (double AA[]) inline static
IdentityAsTransQuat()
static void Antipatrea::Algebra3D::IdentityAsTransQuat (double TQ[]) inline static
IdentityAsTransRot()
static void Antipatrea::Algebra3D::IdentityAsTransRot (double TR[]) inline static
IdentityAsTransAxisAngle()
static void Antipatrea::Algebra3D::IdentityAsTransAxisAngle (double TAA[]) inline static
IdentitySameAsTrans()
static bool Antipatrea::Algebra3D::IdentitySameAsTrans (const double T[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by IdentitySameAsTransQuat(), and IdentitySameAsTransRot().
IdentitySameAsQuat()
static bool Antipatrea::Algebra3D::IdentitySameAsQuat (const double Q[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by IdentitySameAsTransQuat().
IdentitySameAsRot()
static bool Antipatrea::Algebra3D::IdentitySameAsRot (const double R[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by IdentitySameAsTransRot().
IdentitySameAsTransQuat()
static bool Antipatrea::Algebra3D::IdentitySameAsTransQuat (const double TQ[]) inline static
References IdentitySameAsQuat(), and IdentitySameAsTrans().
IdentitySameAsTransRot()
static bool Antipatrea::Algebra3D::IdentitySameAsTransRot (const double TR[]) inline static
References IdentitySameAsRot(), and IdentitySameAsTrans().
TransAsTrans() [1/2]
static void Antipatrea::Algebra3D::TransAsTrans (const double x, const double y, const double z, double Tresult[]) inline static
Referenced by TransAxisAngleAsTransQuat(), TransAxisAngleAsTransRot(), TransAxisAngleAsTransUnitAxisAngle(), TransMultQuatAsTransQuat(), TransMultQuatAsTransRot(), TransMultRotAsTransQuat(), TransMultRotAsTransRot(), TransQuatAsTransAxisAngle(), TransQuatAsTransRot(), TransQuatAsTransUnitAxisAngle(), TransQuatMultQuatAsTransQuat(), TransQuatMultQuatAsTransRot(), TransQuatMultRotAsTransQuat(), TransQuatMultRotAsTransRot(), TransRotAsTransAxisAngle(), TransRotAsTransQuat(), TransRotAsTransUnitAxisAngle(), TransRotMultQuatAsTransQuat(), TransRotMultQuatAsTransRot(), TransRotMultRotAsTransQuat(), TransRotMultRotAsTransRot(), TransUnitAxisAngleAsTransQuat(), and TransUnitAxisAngleAsTransRot().
TransAsTrans() [2/2]
static void Antipatrea::Algebra3D::TransAsTrans (const double T[], double Tresult[]) inline static
QuatAsQuat()
static void Antipatrea::Algebra3D::QuatAsQuat (const double Q[], double Qresult[]) inline static
Referenced by QuatMultTransAsTransQuat(), TransMultQuatAsTransQuat(), TransMultTransQuatAsTransQuat(), and TransQuatMultTransAsTransQuat().
QuatAsRot()
static void Antipatrea::Algebra3D::QuatAsRot (const double Q[], double R[]) inline static
Referenced by QuatMultQuatAsRot(), QuatMultRotAsRot(), QuatMultTransAsTransRot(), RotMultQuatAsRot(), RotSampleUniform(), TransMultQuatAsTransRot(), TransMultTransQuatAsTransRot(), TransQuatAsTransRot(), and TransQuatMultTransAsTransRot().
QuatAsAxisAngle()
static void Antipatrea::Algebra3D::QuatAsAxisAngle (const double Q[], double AA[]) inline static
Referenced by TransQuatAsTransAxisAngle().
QuatAsUnitAxisAngle()
static void Antipatrea::Algebra3D::QuatAsUnitAxisAngle (const double Q[], double AA[]) inline static
References Antipatrea::Constants::EPSILON_SQUARED, RotAsQuat(), and VecDotProduct().
Referenced by RotAsUnitAxisAngle(), and TransQuatAsTransUnitAxisAngle().
RotAsQuat()
void Antipatrea::Algebra3D::RotAsQuat (const double R[], double Q[])
Referenced by InvRotAsQuat(), QuatAsUnitAxisAngle(), QuatMultRotAsQuat(), RotAsAxisAngle(), RotAsUnitAxisAngle(), RotMultQuatAsQuat(), RotMultRotAsQuat(), RotMultTransAsTransQuat(), TransMultRotAsTransQuat(), TransMultTransRotAsTransQuat(), TransRotAsTransQuat(), and TransRotMultTransAsTransQuat().
RotAsRot()
static void Antipatrea::Algebra3D::RotAsRot (const double R[], double Rresult[]) inline static
References Rot_NR_ENTRIES.
Referenced by RotMultTransAsTransRot(), TransMultRotAsTransRot(), TransMultTransRotAsTransRot(), and TransRotMultTransAsTransRot().
RotAsAxisAngle()
static void Antipatrea::Algebra3D::RotAsAxisAngle (const double R[], double AA[]) inline static
References RotAsQuat().
Referenced by TransRotAsTransAxisAngle().
RotAsUnitAxisAngle()
static void Antipatrea::Algebra3D::RotAsUnitAxisAngle (const double R[], double AA[]) inline static
References QuatAsUnitAxisAngle(), and RotAsQuat().
Referenced by TransRotAsTransUnitAxisAngle().
UnitAxisAngleAsQuat()
static void Antipatrea::Algebra3D::UnitAxisAngleAsQuat (const double AA[], double Q[]) inline static
Referenced by TransUnitAxisAngleAsTransQuat().
AxisAngleAsQuat()
static void Antipatrea::Algebra3D::AxisAngleAsQuat (const double AA[], double Q[]) inline static
References IdentityAsQuat().
Referenced by TransAxisAngleAsTransQuat().
UnitAxisAngleAsRot()
static void Antipatrea::Algebra3D::UnitAxisAngleAsRot (const double AA[], double R[]) inline static
Referenced by AxisAngleAsRot(), and TransUnitAxisAngleAsTransRot().
XAxisAngleAsRot()
static void Antipatrea::Algebra3D::XAxisAngleAsRot (const double theta, double R[]) inline static
YAxisAngleAsRot()
static void Antipatrea::Algebra3D::YAxisAngleAsRot (const double theta, double R[]) inline static
ZAxisAngleAsRot()
static void Antipatrea::Algebra3D::ZAxisAngleAsRot (const double theta, double R[]) inline static
AxisAngleAsRot()
static void Antipatrea::Algebra3D::AxisAngleAsRot (const double AA[], double R[]) inline static
References IdentityAsRot(), UnitAxisAngleAsRot(), and VecNorm().
Referenced by TransAxisAngleAsTransRot().
AxisAngleAsAxisAngle()
static void Antipatrea::Algebra3D::AxisAngleAsAxisAngle (const double AA[], double AAresult[]) inline static
References AxisAngle_NR_ENTRIES.
AxisAngleAsUnitAxisAngle()
static void Antipatrea::Algebra3D::AxisAngleAsUnitAxisAngle (const double AA[], double AAresult[]) inline static
References FromToAxisAsQuat(), and VecUnit().
Referenced by TransAxisAngleAsTransUnitAxisAngle().
FromToAxisAsQuat() [1/2]
void Antipatrea::Algebra3D::FromToAxisAsQuat (const double Afrom[], const double Ato[], const double normProd, double Q[])
Referenced by AxisAngleAsUnitAxisAngle(), FromToAxisAsQuat(), and FromToUnitAxisAsQuat().
FromToUnitAxisAsQuat()
static void Antipatrea::Algebra3D::FromToUnitAxisAsQuat (const double Afrom[], const double Ato[], double Q[]) inline static
References FromToAxisAsQuat().
FromToAxisAsQuat() [2/2]
static void Antipatrea::Algebra3D::FromToAxisAsQuat (const double Afrom[], const double Ato[], double Q[]) inline static
References FromToAxisAsQuat(), FromToAxisAsRot(), and VecDotProduct().
FromToAxisAsRot() [1/2]
void Antipatrea::Algebra3D::FromToAxisAsRot (const double Afrom[], const double Ato[], const double normProd, double R[])
Referenced by FromToAxisAsQuat(), FromToAxisAsRot(), and FromToUnitAxisAsRot().
FromToUnitAxisAsRot()
static void Antipatrea::Algebra3D::FromToUnitAxisAsRot (const double Afrom[], const double Ato[], double R[]) inline static
References FromToAxisAsRot().
FromToAxisAsRot() [2/2]
static void Antipatrea::Algebra3D::FromToAxisAsRot (const double Afrom[], const double Ato[], double R[]) inline static
References FromToAxisAsAxisAngle(), FromToAxisAsRot(), and VecDotProduct().
FromToAxisAsAxisAngle() [1/2]
void Antipatrea::Algebra3D::FromToAxisAsAxisAngle (const double Afrom[], const double Ato[], const double normProd, double AA[])
Referenced by FromToAxisAsAxisAngle(), FromToAxisAsRot(), and FromToUnitAxisAsAxisAngle().
FromToUnitAxisAsAxisAngle()
static void Antipatrea::Algebra3D::FromToUnitAxisAsAxisAngle (const double Afrom[], const double Ato[], double AA[]) inline static
References FromToAxisAsAxisAngle().
FromToAxisAsAxisAngle() [2/2]
static void Antipatrea::Algebra3D::FromToAxisAsAxisAngle (const double Afrom[], const double Ato[], double AA[]) inline static
References FromToAxisAsAxisAngle(), and VecDotProduct().
TransQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransQuatAsTransQuat (const double TQ[], double TQresult[]) inline static
References TransQuat_NR_ENTRIES.
TransQuatAsTransRot()
static void Antipatrea::Algebra3D::TransQuatAsTransRot (const double TQ[], double TR[]) inline static
References QuatAsRot(), and TransAsTrans().
TransQuatAsTransAxisAngle()
static void Antipatrea::Algebra3D::TransQuatAsTransAxisAngle (const double TQ[], double TAA[]) inline static
References QuatAsAxisAngle(), and TransAsTrans().
TransQuatAsTransUnitAxisAngle()
static void Antipatrea::Algebra3D::TransQuatAsTransUnitAxisAngle (const double TQ[], double TAA[]) inline static
References QuatAsUnitAxisAngle(), and TransAsTrans().
TransRotAsTransQuat()
static void Antipatrea::Algebra3D::TransRotAsTransQuat (const double TR[], double TQ[]) inline static
References RotAsQuat(), and TransAsTrans().
TransRotAsTransRot()
static void Antipatrea::Algebra3D::TransRotAsTransRot (const double TR[], double TRresult[]) inline static
References TransRot_NR_ENTRIES.
TransRotAsTransAxisAngle()
static void Antipatrea::Algebra3D::TransRotAsTransAxisAngle (const double TR[], double TAA[]) inline static
References RotAsAxisAngle(), and TransAsTrans().
TransRotAsTransUnitAxisAngle()
static void Antipatrea::Algebra3D::TransRotAsTransUnitAxisAngle (const double TR[], double TAA[]) inline static
References RotAsUnitAxisAngle(), and TransAsTrans().
TransAxisAngleAsTransQuat()
static void Antipatrea::Algebra3D::TransAxisAngleAsTransQuat (const double TAA[], double TQ[]) inline static
References AxisAngleAsQuat(), and TransAsTrans().
TransAxisAngleAsTransRot()
static void Antipatrea::Algebra3D::TransAxisAngleAsTransRot (const double TAA[], double TR[]) inline static
References AxisAngleAsRot(), and TransAsTrans().
TransAxisAngleAsTransAxisAngle()
static void Antipatrea::Algebra3D::TransAxisAngleAsTransAxisAngle (const double TAA[], double TAAresult[]) inline static
References TransAxisAngle_NR_ENTRIES.
Referenced by TransUnitAxisAngleAsTransAxisAngle(), and TransUnitAxisAngleAsTransUnitAxisAngle().
TransAxisAngleAsTransUnitAxisAngle()
static void Antipatrea::Algebra3D::TransAxisAngleAsTransUnitAxisAngle (const double TAA[], double TAAresult[]) inline static
References AxisAngleAsUnitAxisAngle(), and TransAsTrans().
TransUnitAxisAngleAsTransQuat()
static void Antipatrea::Algebra3D::TransUnitAxisAngleAsTransQuat (const double TAA[], double TQ[]) inline static
References TransAsTrans(), and UnitAxisAngleAsQuat().
TransUnitAxisAngleAsTransRot()
static void Antipatrea::Algebra3D::TransUnitAxisAngleAsTransRot (const double TAA[], double TR[]) inline static
References TransAsTrans(), and UnitAxisAngleAsRot().
TransUnitAxisAngleAsTransAxisAngle()
static void Antipatrea::Algebra3D::TransUnitAxisAngleAsTransAxisAngle (const double TAA[], double TAAresult[]) inline static
References TransAxisAngleAsTransAxisAngle().
TransUnitAxisAngleAsTransUnitAxisAngle()
static void Antipatrea::Algebra3D::TransUnitAxisAngleAsTransUnitAxisAngle (const double TAA[], double TAAresult[]) inline static
References TransAxisAngleAsTransAxisAngle().
TransSameAsTrans()
static bool Antipatrea::Algebra3D::TransSameAsTrans (const double Ta[], const double Tb[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by TransQuatSameAsTransQuat(), TransQuatSameAsTransRot(), and TransRotSameAsTransRot().
QuatSameAsQuat()
static bool Antipatrea::Algebra3D::QuatSameAsQuat (const double Qa[], const double Qb[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by TransQuatSameAsTransQuat().
QuatSameAsRot()
static bool Antipatrea::Algebra3D::QuatSameAsRot (const double Q[], const double R[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by RotSameAsQuat(), and TransQuatSameAsTransRot().
RotSameAsQuat()
static bool Antipatrea::Algebra3D::RotSameAsQuat (const double R[], const double Q[]) inline static
References QuatSameAsRot().
RotSameAsRot()
static bool Antipatrea::Algebra3D::RotSameAsRot (const double Ra[], const double Rb[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by TransRotSameAsTransRot().
TransQuatSameAsTransQuat()
static bool Antipatrea::Algebra3D::TransQuatSameAsTransQuat (const double TQa[], const double TQb[]) inline static
References QuatSameAsQuat(), and TransSameAsTrans().
TransQuatSameAsTransRot()
static bool Antipatrea::Algebra3D::TransQuatSameAsTransRot (const double TQ[], const double TR[]) inline static
References QuatSameAsRot(), and TransSameAsTrans().
Referenced by TransRotSameAsTransQuat().
TransRotSameAsTransQuat()
static bool Antipatrea::Algebra3D::TransRotSameAsTransQuat (const double TR[], const double TQ[]) inline static
References TransQuatSameAsTransRot().
TransRotSameAsTransRot()
static bool Antipatrea::Algebra3D::TransRotSameAsTransRot (const double TRa[], const double TRb[]) inline static
References RotSameAsRot(), and TransSameAsTrans().
TransMultPoint()
static void Antipatrea::Algebra3D::TransMultPoint (const double T[], const double p[], double pnew[]) inline static
Referenced by TransQuatMultInvPoint(), TransQuatMultPoint(), TransRotMultInvPoint(), and TransRotMultPoint().
TransMultInvPoint()
static void Antipatrea::Algebra3D::TransMultInvPoint (const double T[], const double p[], double pnew[]) inline static
InvTransMultPoint()
static void Antipatrea::Algebra3D::InvTransMultPoint (const double T[], const double p[], double pnew[]) inline static
Referenced by InvTransQuatMultPoint(), and InvTransRotMultPoint().
InvTransMultInvPoint()
static void Antipatrea::Algebra3D::InvTransMultInvPoint (const double T[], const double p[], double pnew[]) inline static
Referenced by InvTransQuatMultInvPoint(), and InvTransRotMultInvPoint().
QuatMultPoint()
static void Antipatrea::Algebra3D::QuatMultPoint (const double Q[], const double p[], double pnew[]) inline static
Referenced by QuatMultInvPoint(), QuatMultTransAsTransQuat(), QuatMultTransQuatAsTransQuat(), QuatMultTransQuatAsTransRot(), QuatMultTransRotAsTransQuat(), QuatMultTransRotAsTransRot(), TransQuatMultPoint(), TransQuatMultTransAsTransQuat(), TransQuatMultTransAsTransRot(), TransQuatMultTransQuatAsTransQuat(), TransQuatMultTransQuatAsTransRot(), TransQuatMultTransRotAsTransQuat(), and TransQuatMultTransRotAsTransRot().
QuatMultInvPoint()
static void Antipatrea::Algebra3D::QuatMultInvPoint (const double Q[], const double p[], double pnew[]) inline static
References QuatMultPoint().
Referenced by InvTransQuatAsTransQuat(), and TransQuatMultInvPoint().
InvQuatMultPoint()
static void Antipatrea::Algebra3D::InvQuatMultPoint (const double Q[], const double p[], double pnew[]) inline static
Referenced by InvQuatMultInvPoint(), InvTransQuatMultInvPoint(), and InvTransQuatMultPoint().
InvQuatMultInvPoint()
static void Antipatrea::Algebra3D::InvQuatMultInvPoint (const double Q[], const double p[], double pnew[]) inline static
References InvQuatMultPoint().
QuatMultXAxis()
static void Antipatrea::Algebra3D::QuatMultXAxis (const double Q[], double axis[]) inline static
QuatMultNegXAxis()
static void Antipatrea::Algebra3D::QuatMultNegXAxis (const double Q[], double axis[]) inline static
InvQuatMultXAxis()
static void Antipatrea::Algebra3D::InvQuatMultXAxis (const double Q[], double axis[]) inline static
QuatMultYAxis()
static void Antipatrea::Algebra3D::QuatMultYAxis (const double Q[], double ynew[]) inline static
QuatMultZAxis()
static void Antipatrea::Algebra3D::QuatMultZAxis (const double Q[], double znew[]) inline static
RotMultPoint()
static void Antipatrea::Algebra3D::RotMultPoint (const double R[], const double p[], double pnew[]) inline static
Referenced by QuatMultTransAsTransRot(), RotMultTransAsTransQuat(), RotMultTransAsTransRot(), RotMultTransQuatAsTransQuat(), RotMultTransQuatAsTransRot(), RotMultTransRotAsTransQuat(), RotMultTransRotAsTransRot(), TransRotMultPoint(), TransRotMultTransAsTransQuat(), TransRotMultTransAsTransRot(), TransRotMultTransQuatAsTransQuat(), TransRotMultTransQuatAsTransRot(), TransRotMultTransRotAsTransQuat(), and TransRotMultTransRotAsTransRot().
RotMultInvPoint()
static void Antipatrea::Algebra3D::RotMultInvPoint (const double R[], const double p[], double pnew[]) inline static
Referenced by InvTransQuatAsTransRot(), InvTransRotAsTransRot(), and TransRotMultInvPoint().
InvRotMultPoint()
static void Antipatrea::Algebra3D::InvRotMultPoint (const double R[], const double p[], double pnew[]) inline static
Referenced by InvTransRotMultInvPoint(), and InvTransRotMultPoint().
InvRotMultInvPoint()
static void Antipatrea::Algebra3D::InvRotMultInvPoint (const double R[], const double p[], double pnew[]) inline static
Referenced by InvTransRotAsTransQuat().
RotMultXAxis()
static void Antipatrea::Algebra3D::RotMultXAxis (const double R[], double xnew[]) inline static
RotMultYAxis()
static void Antipatrea::Algebra3D::RotMultYAxis (const double R[], double ynew[]) inline static
RotMultZAxis()
static void Antipatrea::Algebra3D::RotMultZAxis (const double R[], double znew[]) inline static
TransQuatMultPoint()
static void Antipatrea::Algebra3D::TransQuatMultPoint (const double TQ[], const double p[], double pnew[]) inline static
References QuatMultPoint(), and TransMultPoint().
TransQuatMultInvPoint()
static void Antipatrea::Algebra3D::TransQuatMultInvPoint (const double TQ[], const double p[], double pnew[]) inline static
References QuatMultInvPoint(), and TransMultPoint().
InvTransQuatMultPoint()
static void Antipatrea::Algebra3D::InvTransQuatMultPoint (const double TQ[], const double p[], double pnew[]) inline static
References InvQuatMultPoint(), and InvTransMultPoint().
InvTransQuatMultInvPoint()
static void Antipatrea::Algebra3D::InvTransQuatMultInvPoint (const double TQ[], const double p[], double pnew[]) inline static
References InvQuatMultPoint(), and InvTransMultInvPoint().
TransRotMultPoint()
static void Antipatrea::Algebra3D::TransRotMultPoint (const double TR[], const double p[], double pnew[]) inline static
References RotMultPoint(), and TransMultPoint().
TransRotMultInvPoint()
static void Antipatrea::Algebra3D::TransRotMultInvPoint (const double TR[], const double p[], double pnew[]) inline static
References RotMultInvPoint(), and TransMultPoint().
InvTransRotMultPoint()
static void Antipatrea::Algebra3D::InvTransRotMultPoint (const double TR[], const double p[], double pnew[]) inline static
References InvRotMultPoint(), and InvTransMultPoint().
InvTransRotMultInvPoint()
static void Antipatrea::Algebra3D::InvTransRotMultInvPoint (const double TR[], const double p[], double pnew[]) inline static
References InvRotMultPoint(), and InvTransMultInvPoint().
InvTransAsTrans()
static void Antipatrea::Algebra3D::InvTransAsTrans (const double T[], double Tresult[]) inline static
InvQuatAsQuat()
static void Antipatrea::Algebra3D::InvQuatAsQuat (const double Q[], double Qresult[]) inline static
Referenced by InvRotAsQuat(), and InvTransQuatAsTransQuat().
InvQuatAsRot()
static void Antipatrea::Algebra3D::InvQuatAsRot (const double Q[], double R[]) inline static
Referenced by InvTransQuatAsTransRot().
InvRotAsQuat()
static void Antipatrea::Algebra3D::InvRotAsQuat (const double R[], double Q[]) inline static
References InvQuatAsQuat(), and RotAsQuat().
Referenced by InvTransRotAsTransQuat().
InvRotAsRot()
static void Antipatrea::Algebra3D::InvRotAsRot (const double R[], double Rresult[]) inline static
Referenced by InvTransRotAsTransRot().
InvTransQuatAsTransQuat()
static void Antipatrea::Algebra3D::InvTransQuatAsTransQuat (const double TQ[], double TQresult[]) inline static
References InvQuatAsQuat(), and QuatMultInvPoint().
InvTransQuatAsTransRot()
static void Antipatrea::Algebra3D::InvTransQuatAsTransRot (const double TQ[], double TR[]) inline static
References InvQuatAsRot(), and RotMultInvPoint().
InvTransRotAsTransQuat()
static void Antipatrea::Algebra3D::InvTransRotAsTransQuat (const double TR[], double TQ[]) inline static
References InvRotAsQuat(), and InvRotMultInvPoint().
InvTransRotAsTransRot()
static void Antipatrea::Algebra3D::InvTransRotAsTransRot (const double TR[], double TRresult[]) inline static
References InvRotAsRot(), and RotMultInvPoint().
TransMultTransAsTrans()
static void Antipatrea::Algebra3D::TransMultTransAsTrans (const double Ta[], const double Tb[], double T[]) inline static
Referenced by TransMultTransQuatAsTransQuat(), TransMultTransQuatAsTransRot(), TransMultTransRotAsTransQuat(), TransMultTransRotAsTransRot(), TransQuatMultTransAsTransQuat(), TransQuatMultTransAsTransRot(), TransQuatMultTransQuatAsTransQuat(), TransQuatMultTransQuatAsTransRot(), TransQuatMultTransRotAsTransQuat(), TransQuatMultTransRotAsTransRot(), TransRotMultTransAsTransQuat(), TransRotMultTransAsTransRot(), TransRotMultTransQuatAsTransQuat(), TransRotMultTransQuatAsTransRot(), TransRotMultTransRotAsTransQuat(), and TransRotMultTransRotAsTransRot().
TransMultQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransMultQuatAsTransQuat (const double T[], const double Q[], double TQ[]) inline static
References QuatAsQuat(), and TransAsTrans().
TransMultQuatAsTransRot()
static void Antipatrea::Algebra3D::TransMultQuatAsTransRot (const double T[], const double Q[], double TR[]) inline static
References QuatAsRot(), and TransAsTrans().
TransMultRotAsTransQuat()
static void Antipatrea::Algebra3D::TransMultRotAsTransQuat (const double T[], const double R[], double TQ[]) inline static
References RotAsQuat(), and TransAsTrans().
TransMultRotAsTransRot()
static void Antipatrea::Algebra3D::TransMultRotAsTransRot (const double T[], const double R[], double TR[]) inline static
References RotAsRot(), and TransAsTrans().
TransMultTransQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransMultTransQuatAsTransQuat (const double T[], const double TQ[], double TQresult[]) inline static
References QuatAsQuat(), and TransMultTransAsTrans().
TransMultTransQuatAsTransRot()
static void Antipatrea::Algebra3D::TransMultTransQuatAsTransRot (const double T[], const double TQ[], double TR[]) inline static
References QuatAsRot(), and TransMultTransAsTrans().
TransMultTransRotAsTransQuat()
static void Antipatrea::Algebra3D::TransMultTransRotAsTransQuat (const double T[], const double TR[], double TQ[]) inline static
References RotAsQuat(), and TransMultTransAsTrans().
TransMultTransRotAsTransRot()
static void Antipatrea::Algebra3D::TransMultTransRotAsTransRot (const double T[], const double TR[], double TRresult[]) inline static
References RotAsRot(), and TransMultTransAsTrans().
QuatMultTransAsTransQuat()
static void Antipatrea::Algebra3D::QuatMultTransAsTransQuat (const double Q[], const double T[], double TQ[]) inline static
References QuatAsQuat(), and QuatMultPoint().
QuatMultTransAsTransRot()
static void Antipatrea::Algebra3D::QuatMultTransAsTransRot (const double Q[], const double T[], double TR[]) inline static
References QuatAsRot(), and RotMultPoint().
QuatMultQuatAsQuat()
static void Antipatrea::Algebra3D::QuatMultQuatAsQuat (const double Qa[], const double Qb[], double Q[]) inline static
Referenced by QuatMultQuatAsRot(), QuatMultRotAsQuat(), QuatMultTransQuatAsTransQuat(), RotMultQuatAsQuat(), TransQuatMultQuatAsTransQuat(), and TransQuatMultTransQuatAsTransQuat().
QuatMultQuatAsRot()
static void Antipatrea::Algebra3D::QuatMultQuatAsRot (const double Qa[], const double Qb[], double R[]) inline static
References Quat_NR_ENTRIES, QuatAsRot(), and QuatMultQuatAsQuat().
Referenced by QuatMultTransQuatAsTransRot(), TransQuatMultQuatAsTransRot(), and TransQuatMultTransQuatAsTransRot().
QuatMultRotAsQuat()
static void Antipatrea::Algebra3D::QuatMultRotAsQuat (const double Q[], const double R[], double Qresult[]) inline static
References Quat_NR_ENTRIES, QuatMultQuatAsQuat(), RotAsQuat(), and RotMultRotAsRot().
Referenced by QuatMultTransRotAsTransQuat(), TransQuatMultRotAsTransQuat(), and TransQuatMultTransRotAsTransQuat().
RotMultRotAsRot()
void Antipatrea::Algebra3D::RotMultRotAsRot (const double Ra[], const double Rb[], double R[])
Referenced by QuatMultRotAsQuat(), QuatMultRotAsRot(), RotMultQuatAsRot(), RotMultRotAsQuat(), RotMultTransRotAsTransRot(), TransRotMultRotAsTransRot(), and TransRotMultTransRotAsTransRot().
QuatMultRotAsRot()
static void Antipatrea::Algebra3D::QuatMultRotAsRot (const double Q[], const double R[], double Rresult[]) inline static
References QuatAsRot(), Rot_NR_ENTRIES, and RotMultRotAsRot().
Referenced by QuatMultTransRotAsTransRot(), TransQuatMultRotAsTransRot(), and TransQuatMultTransRotAsTransRot().
QuatMultTransQuatAsTransQuat()
static void Antipatrea::Algebra3D::QuatMultTransQuatAsTransQuat (const double Q[], const double TQ[], double TQresult[]) inline static
References QuatMultPoint(), and QuatMultQuatAsQuat().
QuatMultTransQuatAsTransRot()
static void Antipatrea::Algebra3D::QuatMultTransQuatAsTransRot (const double Q[], const double TQ[], double TR[]) inline static
References QuatMultPoint(), and QuatMultQuatAsRot().
QuatMultTransRotAsTransQuat()
static void Antipatrea::Algebra3D::QuatMultTransRotAsTransQuat (const double Q[], const double TR[], double TQ[]) inline static
References QuatMultPoint(), and QuatMultRotAsQuat().
QuatMultTransRotAsTransRot()
static void Antipatrea::Algebra3D::QuatMultTransRotAsTransRot (const double Q[], const double TR[], double TRresult[]) inline static
References QuatMultPoint(), and QuatMultRotAsRot().
RotMultTransAsTransQuat()
static void Antipatrea::Algebra3D::RotMultTransAsTransQuat (const double R[], const double T[], double TQ[]) inline static
References RotAsQuat(), and RotMultPoint().
RotMultTransAsTransRot()
static void Antipatrea::Algebra3D::RotMultTransAsTransRot (const double R[], const double T[], double TR[]) inline static
References RotAsRot(), and RotMultPoint().
RotMultQuatAsQuat()
static void Antipatrea::Algebra3D::RotMultQuatAsQuat (const double R[], const double Q[], double Qresult[]) inline static
References Quat_NR_ENTRIES, QuatMultQuatAsQuat(), and RotAsQuat().
Referenced by RotMultTransQuatAsTransQuat(), TransRotMultQuatAsTransQuat(), and TransRotMultTransQuatAsTransQuat().
RotMultQuatAsRot()
static void Antipatrea::Algebra3D::RotMultQuatAsRot (const double R[], const double Q[], double Rresult[]) inline static
References QuatAsRot(), Rot_NR_ENTRIES, and RotMultRotAsRot().
Referenced by RotMultTransQuatAsTransRot(), TransRotMultQuatAsTransRot(), and TransRotMultTransQuatAsTransRot().
RotMultRotAsQuat()
static void Antipatrea::Algebra3D::RotMultRotAsQuat (const double Ra[], const double Rb[], double Q[]) inline static
References Rot_NR_ENTRIES, RotAsQuat(), and RotMultRotAsRot().
Referenced by RotMultTransRotAsTransQuat(), TransRotMultRotAsTransQuat(), and TransRotMultTransRotAsTransQuat().
RotMultTransQuatAsTransQuat()
static void Antipatrea::Algebra3D::RotMultTransQuatAsTransQuat (const double R[], const double TQ[], double TQresult[]) inline static
References RotMultPoint(), and RotMultQuatAsQuat().
RotMultTransQuatAsTransRot()
static void Antipatrea::Algebra3D::RotMultTransQuatAsTransRot (const double R[], const double TQ[], double TRresult[]) inline static
References RotMultPoint(), and RotMultQuatAsRot().
RotMultTransRotAsTransQuat()
static void Antipatrea::Algebra3D::RotMultTransRotAsTransQuat (const double R[], const double TR[], double TQ[]) inline static
References RotMultPoint(), and RotMultRotAsQuat().
RotMultTransRotAsTransRot()
static void Antipatrea::Algebra3D::RotMultTransRotAsTransRot (const double R[], const double TR[], double TRresult[]) inline static
References RotMultPoint(), and RotMultRotAsRot().
TransQuatMultTransAsTransQuat()
static void Antipatrea::Algebra3D::TransQuatMultTransAsTransQuat (const double TQ[], const double T[], double TQresult[]) inline static
References QuatAsQuat(), QuatMultPoint(), and TransMultTransAsTrans().
TransQuatMultTransAsTransRot()
static void Antipatrea::Algebra3D::TransQuatMultTransAsTransRot (const double TQ[], const double T[], double TR[]) inline static
References QuatAsRot(), QuatMultPoint(), and TransMultTransAsTrans().
TransQuatMultQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransQuatMultQuatAsTransQuat (const double TQ[], const double Q[], double TQresult[]) inline static
References QuatMultQuatAsQuat(), and TransAsTrans().
TransQuatMultQuatAsTransRot()
static void Antipatrea::Algebra3D::TransQuatMultQuatAsTransRot (const double TQ[], const double Q[], double TR[]) inline static
References QuatMultQuatAsRot(), and TransAsTrans().
TransQuatMultRotAsTransQuat()
static void Antipatrea::Algebra3D::TransQuatMultRotAsTransQuat (const double TQ[], const double R[], double TQresult[]) inline static
References QuatMultRotAsQuat(), and TransAsTrans().
TransQuatMultRotAsTransRot()
static void Antipatrea::Algebra3D::TransQuatMultRotAsTransRot (const double TQ[], const double R[], double TR[]) inline static
References QuatMultRotAsRot(), and TransAsTrans().
TransQuatMultTransQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransQuatMultTransQuatAsTransQuat (const double TQa[], const double TQb[], double TQ[]) inline static
References QuatMultPoint(), QuatMultQuatAsQuat(), and TransMultTransAsTrans().
TransQuatMultTransQuatAsTransRot()
static void Antipatrea::Algebra3D::TransQuatMultTransQuatAsTransRot (const double TQa[], const double TQb[], double TR[]) inline static
References QuatMultPoint(), QuatMultQuatAsRot(), and TransMultTransAsTrans().
TransQuatMultTransRotAsTransQuat()
static void Antipatrea::Algebra3D::TransQuatMultTransRotAsTransQuat (const double TQ[], const double TR[], double TQresult[]) inline static
References QuatMultPoint(), QuatMultRotAsQuat(), and TransMultTransAsTrans().
TransQuatMultTransRotAsTransRot()
static void Antipatrea::Algebra3D::TransQuatMultTransRotAsTransRot (const double TQ[], const double TR[], double TRresult[]) inline static
References QuatMultPoint(), QuatMultRotAsRot(), and TransMultTransAsTrans().
TransRotMultTransAsTransQuat()
static void Antipatrea::Algebra3D::TransRotMultTransAsTransQuat (const double TR[], const double T[], double TQresult[]) inline static
References RotAsQuat(), RotMultPoint(), and TransMultTransAsTrans().
TransRotMultTransAsTransRot()
static void Antipatrea::Algebra3D::TransRotMultTransAsTransRot (const double TR[], const double T[], double TRresult[]) inline static
References RotAsRot(), RotMultPoint(), and TransMultTransAsTrans().
TransRotMultQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransRotMultQuatAsTransQuat (const double TR[], const double Q[], double TQresult[]) inline static
References RotMultQuatAsQuat(), and TransAsTrans().
TransRotMultQuatAsTransRot()
static void Antipatrea::Algebra3D::TransRotMultQuatAsTransRot (const double TR[], const double Q[], double TRresult[]) inline static
References RotMultQuatAsRot(), and TransAsTrans().
TransRotMultRotAsTransQuat()
static void Antipatrea::Algebra3D::TransRotMultRotAsTransQuat (const double TR[], const double R[], double TQresult[]) inline static
References RotMultRotAsQuat(), and TransAsTrans().
TransRotMultRotAsTransRot()
static void Antipatrea::Algebra3D::TransRotMultRotAsTransRot (const double TR[], const double R[], double TRresult[]) inline static
References RotMultRotAsRot(), and TransAsTrans().
TransRotMultTransQuatAsTransQuat()
static void Antipatrea::Algebra3D::TransRotMultTransQuatAsTransQuat (const double TR[], const double TQ[], double TQresult[]) inline static
References RotMultPoint(), RotMultQuatAsQuat(), and TransMultTransAsTrans().
TransRotMultTransQuatAsTransRot()
static void Antipatrea::Algebra3D::TransRotMultTransQuatAsTransRot (const double TR[], const double TQ[], double TRresult[]) inline static
References RotMultPoint(), RotMultQuatAsRot(), and TransMultTransAsTrans().
TransRotMultTransRotAsTransQuat()
static void Antipatrea::Algebra3D::TransRotMultTransRotAsTransQuat (const double TRa[], const double TRb[], double TQ[]) inline static
References RotMultPoint(), RotMultRotAsQuat(), and TransMultTransAsTrans().
TransRotMultTransRotAsTransRot()
static void Antipatrea::Algebra3D::TransRotMultTransRotAsTransRot (const double TRa[], const double TRb[], double TR[]) inline static
References RotMultPoint(), RotMultRotAsRot(), and TransMultTransAsTrans().
TransSampleUniform() [1/2]
static void Antipatrea::Algebra3D::TransSampleUniform (double T[]) inline static
References Antipatrea::RandomUniformReal().
Referenced by TransQuatSampleUniform(), and TransRotSampleUniform().
TransSampleUniform() [2/2]
static void Antipatrea::Algebra3D::TransSampleUniform (double T[], const double bbox[]) inline static
References QuatSampleUniform_Gaussian(), QuatSampleUniform_Marsaglia(), QuatSampleUniform_Shoemake(), and Antipatrea::RandomUniformReal().
QuatSampleUniform_Marsaglia()
void Antipatrea::Algebra3D::QuatSampleUniform_Marsaglia (double Q[])
Referenced by QuatSampleUniform(), and TransSampleUniform().
QuatSampleUniform_Gaussian()
void Antipatrea::Algebra3D::QuatSampleUniform_Gaussian (double Q[])
Referenced by TransSampleUniform().
QuatSampleUniform_Shoemake()
void Antipatrea::Algebra3D::QuatSampleUniform_Shoemake (double Q[])
Referenced by TransSampleUniform().
QuatSampleUniform()
static void Antipatrea::Algebra3D::QuatSampleUniform (double Q[]) inline static
References QuatSampleUniform_Marsaglia().
Referenced by RotSampleUniform(), and TransQuatSampleUniform().
RotSampleUniform()
static void Antipatrea::Algebra3D::RotSampleUniform (double R[]) inline static
References Quat_NR_ENTRIES, QuatAsRot(), and QuatSampleUniform().
Referenced by TransRotSampleUniform().
TransQuatSampleUniform() [1/2]
static void Antipatrea::Algebra3D::TransQuatSampleUniform (double TQ[]) inline static
References QuatSampleUniform(), and TransSampleUniform().
TransQuatSampleUniform() [2/2]
static void Antipatrea::Algebra3D::TransQuatSampleUniform (double TQ[], const double bbox[]) inline static
References QuatSampleUniform(), and TransSampleUniform().
TransRotSampleUniform() [1/2]
static void Antipatrea::Algebra3D::TransRotSampleUniform (double TR[]) inline static
References RotSampleUniform(), and TransSampleUniform().
TransRotSampleUniform() [2/2]
static void Antipatrea::Algebra3D::TransRotSampleUniform (double TR[], const double bbox[]) inline static
References RotSampleUniform(), and TransSampleUniform().
QuatLERP()
static void Antipatrea::Algebra3D::QuatLERP (const double Q1[], const double Q2[], const double t, double Q[]) inline static
References QuatUnit().
Referenced by QuatSLERP(), and TransQuatLERP().
TransQuatLERP()
static void Antipatrea::Algebra3D::TransQuatLERP (const double TQ1[], const double TQ2[], const double t, double TQ[]) inline static
References QuatLERP(), and Trans_NR_ENTRIES.
QuatSLERP()
static void Antipatrea::Algebra3D::QuatSLERP (const double Q1[], const double Q2[], const double t, double Q[]) inline static
References QuatDotProduct(), and QuatLERP().
Referenced by TransQuatSLERP().
TransQuatSLERP()
static void Antipatrea::Algebra3D::TransQuatSLERP (const double TQ1[], const double TQ2[], const double t, double TQ[]) inline static
References QuatSLERP(), and Trans_NR_ENTRIES.