Antipatrea::Vector3Algebra Namespace Reference
Antipatrea::Vector3Algebra Namespace Reference
Functionality to measure various metrics on vectors in 3D.
Typedefs
typedef double * Vector3_t
Data type for 3-dimensional vectors.
Functions
Dynamic memory management.
static Vector3_t Vector3Alloc (void)
Allocate memory.
static void Vector3Free (Vector3_t v)
Free memory.
Input/output functions.
static void Vector3Read (Vector3_t v, FILE *in)
Read the elements of the vector v from the file stream in.
static void Vector3Print (const Vector3_t v, FILE *out)
Print the elements of the vector v to the file stream out.
Access functions.
static double Vector3GetElem (const Vector3_t v, const int i)
Access the i-th element of the vector v.
Modify functions.
static void Vector3SetElem (Vector3_t v, const int i, const double a)
Set the i-th element of the vector v, i.e., v[i] <– a.
static void Vector3Set (Vector3_t v, const double a, const double b, const double c)
Set the vector v to (a, b, c).
static Vector3_t Vector3Zero (Vector3_t v)
Set every element of the vector v to 0.
Identity functions.
static Vector3_t Vector3AdditiveIdentity (Vector3_t v)
Set the vector v to the 3-dimensional additive identity vector.
Utility functions.
static Vector3_t Vector3Copy (Vector3_t v, const Vector3_t v1)
Copy the vector v1 into the vector v, i.e., v <– COPY(v1).
static float * Vector3GetFloat (const Vector3_t v, float *vf)
Copy the elements of the vector v cast to float into the memory block to which vf points to.
General math functions.
static Vector3_t Vector3Add (Vector3_t v, const Vector3_t v1, const Vector3_t v2)
Set the vector v to the sum of the vectors v1 and v2, i.e., v <– v1 + v2.
static Vector3_t Vector3Sub (Vector3_t v, const Vector3_t v1, const Vector3_t v2)
Set the vector v to the difference of the vectors v1 and v2, i.e., v <– v1 - v2.
static Vector3_t Vector3MultiplyScalar (Vector3_t v, const Vector3_t v1, const double d)
Set the vector v to the product of the vector v1 with the scalar d, i.e., v <– v1 * d.
static void Vector3FindNormal (Vector3_t normal, const Vector3_t from)
Find a vector that is perpendicular to from.
static Vector3_t Vector3LinearCombination (Vector3_t v, const Vector3_t v1, const double d1, const Vector3_t v2, const double d2)
Set the vector v to the linear combination of the vectors v1 and v2 with the scalars d1 and d2, i.e., v <– v1 * d1 + v2 * d2.
static Vector3_t Vector3CrossProduct (Vector3_t v, const Vector3_t v1, const Vector3_t v2)
Set the vector v to the cross product of the vectors v1 and v2, i.e., v <– CROSS(v1, v2).
static double Vector3DotProduct (const Vector3_t v1, const Vector3_t v2)
Compute the dot product of the vectors v1 and v2.
static double Vector3Norm (const Vector3_t v)
Compute the norm of the vector v.
static Vector3_t Vector3Unit (Vector3_t v)
Normalize the vector v, i.e., v <– UNIT(v).
static void Vector3Random (Vector3_t v, double min, double max)
Set every element of the vector v to random numbers between min and max.
static Vector3_t Vector3Negate (Vector3_t v, const Vector3_t v1)
Set the vector v to the negation of the vector v1, i.e., v <– NEGATE(v1).
static double Vector3Angle (const Vector3_t v1, const Vector3_t v2)
Compute the angle between the vectors v1 and v2.
static double Vector3AnglePlane (const Vector3_t v1, const Vector3_t v2, const Vector3_t v3)
Linear interpolation functions.
static Vector3_t Vector3lerp (Vector3_t v, const Vector3_t v1, const Vector3_t v2, const double t)
Set the vector v to the linear interpolation of the vectors v1 and v2.
Distance functions.
static double Vector3SquareDistance (const Vector3_t v1, const Vector3_t v2)
Compute the square of the Euclidean distance between the vectors v1 and v2.
static double Vector3Distance (const Vector3_t v1, const Vector3_t v2)
Compute the Euclidean distance between the vectors v1 and v2.
static double Vector3ParallelProjection (const Vector3_t u, const Vector3_t v)
Compute the parallel projection of the vector u unto the vector v
Detailed Description
Functionality to measure various metrics on vectors in 3D.
Author
Amarda Shehu
Typedef Documentation
Vector3_t
typedef double* Antipatrea::Vector3Algebra::Vector3_t
Data type for 3-dimensional vectors.
A 3-dimensional vector v = (a, b, c) is a 3-tuple, where a, b, and c represent the first, second, and third coordinate of v, respectively.
Function Documentation
Vector3Alloc()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Alloc (void) inline static
Allocate memory.
Returns
A contigous block of 3 elements of type double.
Vector3Free()
static void Antipatrea::Vector3Algebra::Vector3Free (Vector3_t v) inline static
Free memory.
Parameters
[in,out] v a pointer of type Vector3_t representing the memory address to be freed.
Description:
Free the memory allocated to v.
No memory is freed if v is NULL.
Vector3Read()
static void Antipatrea::Vector3Algebra::Vector3Read (Vector3_t v, FILE * in) inline static
Read the elements of the vector v from the file stream in.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be read.
[in] in a pointer to a file stream opened for reading.
Description:
Read 3 consecutive double elements, v[0], v[1], v[2], from the file stream in points to.
Vector3Print()
static void Antipatrea::Vector3Algebra::Vector3Print (const Vector3_t v, FILE * out) inline static
Print the elements of the vector v to the file stream out.
Parameters
[in] v a pointer of type Vector3_t representing the vector to be printed.
[in] out a pointer to a file stream opened for writing.
Description:
Write 3 consecutive double elements, v[0], v[1], v[2], separated by spaces to the file stream out points to.
Vector3GetElem()
static double Antipatrea::Vector3Algebra::Vector3GetElem (const Vector3_t v, const int i) inline static
Access the i-th element of the vector v.
Parameters
[in] v a pointer of type Vector3_t representing the vector to be accessed.
[in] i a int in the range 0...2 representing the index of the vector element.
Returns
The element in position i of v.
Warning
Errors may occur if the index is outside the allowed range due to the inappropriate memory access.
Vector3SetElem()
static void Antipatrea::Vector3Algebra::Vector3SetElem (Vector3_t v, const int i, const double a) inline static
Set the i-th element of the vector v, i.e., v[i] <– a.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be modified.
[in] i a int in the range 0...2 representing the index of the vector element.
[in] a a double representing the new value of the i-th vector element.
Description:
Set the value of the element in position i of v to a.
Warning
Errors may occur if the index is outside the allowed range due to the inappropriate memory access.
Vector3Set()
static void Antipatrea::Vector3Algebra::Vector3Set (Vector3_t v, const double a, const double b, const double c) inline static
Set the vector v to (a, b, c).
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be modified.
[in] a a double representing the new value of the 0-th vector element.
[in] b a double representing the new value of the 1-st vector element.
[in] c a double representing the new value of the 2-nd vector element.
Description:
Set v to (a, b, c).
Vector3Zero()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Zero (Vector3_t v) inline static
Set every element of the vector v to 0.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be modified.
Returns
Vector v defined as (0, 0, 0).
Referenced by Vector3AdditiveIdentity().
Vector3AdditiveIdentity()
static Vector3_t Antipatrea::Vector3Algebra::Vector3AdditiveIdentity (Vector3_t v) inline static
Set the vector v to the 3-dimensional additive identity vector.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be modified.
Returns
Vector v defined as v' = v + v' = v' + v, for every 3-dimensional vector v'. It follows that all entries of v are 0.
Attention
Equivalent to Vector3Zero.
References Vector3Zero().
Vector3Copy()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Copy (Vector3_t v, const Vector3_t v1) inline static
Copy the vector v1 into the vector v, i.e., v <– COPY(v1).
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to copy to.
[in] v1 a pointer of type Vector3_t representing the vector to copy from.
Returns
Vector v defined as the copy of the vector v1, i.e., v[i] = v1[i], for all i = 0, 1, 2.
Vector3GetFloat()
static float* Antipatrea::Vector3Algebra::Vector3GetFloat (const Vector3_t v, float * vf) inline static
Copy the elements of the vector v cast to float into the memory block to which vf points to.
Parameters
[in] v a pointer of type Vector3_t representing the vector to copy from.
[in,out] vf a pointer of type float * to a contigous block of 3 elements of type float.
Returns
The pointer vf defined as the copy of the vector v.
Vector3Add()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Add (Vector3_t v, const Vector3_t v1, const Vector3_t v2) inline static
Set the vector v to the sum of the vectors v1 and v2, i.e., v <– v1 + v2.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector sum.
[in] v1 a pointer of type Vector3_t representing the first operand.
[in] v2 a pointer of type Vector3_t representing the second operand.
Returns
Vector v defined as v[i] = v1[i] + v2[i], for all i = 0, 1, 2.
Vector3Sub()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Sub (Vector3_t v, const Vector3_t v1, const Vector3_t v2) inline static
Set the vector v to the difference of the vectors v1 and v2, i.e., v <– v1 - v2.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector difference.
[in] v1 a pointer of type Vector3_t representing the first operand.
[in] v2 a pointer of type Vector3_t representing the second operand.
Returns
Vector v defined as v[i] = v1[i] - v2[i], for all i = 0, 1, 2.
Vector3MultiplyScalar()
static Vector3_t Antipatrea::Vector3Algebra::Vector3MultiplyScalar (Vector3_t v, const Vector3_t v1, const double d) inline static
Set the vector v to the product of the vector v1 with the scalar d, i.e., v <– v1 * d.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector-scalar product.
[in] v1 a pointer of type Vector3_t representing the vector operand.
[in] d a double representing the scalar operand.
Returns
Vector v defined as v[i] = v1[i] * d, for all i = 0, 1, 2.
Vector3FindNormal()
static void Antipatrea::Vector3Algebra::Vector3FindNormal (Vector3_t normal, const Vector3_t from) inline static
Find a vector that is perpendicular to from.
Parameters
[out] normal a pointer of type Vector3_t .
[in] from a pointer of type Vector3_t .
Returns
The vector normal that is perpendicular to vector from
Vector3LinearCombination()
static Vector3_t Antipatrea::Vector3Algebra::Vector3LinearCombination (Vector3_t v, const Vector3_t v1, const double d1, const Vector3_t v2, const double d2) inline static
Set the vector v to the linear combination of the vectors v1 and v2 with the scalars d1 and d2, i.e., v <– v1 * d1 + v2 * d2.
Parameters
[in,out] v a pointer of type Vector3_t representing the result.
[in] v1 a pointer of type Vector3_t representing the first vector to be linearly combined.
[in] d1 a double representing the scalar factor for the first vector.
[in] v2 a pointer of type Vector3_t representing the second vector to be linearly combined.
[in] d2 a double representing the scalar factor for the second vector.
Returns
Vector v defined as v[i] = v1[i] * d1 + v2[i] * d2, for all i = 0, 1, 2.
See also
Vector3Add, Vector3MultiplyScalar.
Referenced by Vector3lerp().
Vector3CrossProduct()
static Vector3_t Antipatrea::Vector3Algebra::Vector3CrossProduct (Vector3_t v, const Vector3_t v1, const Vector3_t v2) inline static
Set the vector v to the cross product of the vectors v1 and v2, i.e., v <– CROSS(v1, v2).
Parameters
[in,out] v a pointer of type Vector3_t representing the cross product.
[in] v1 a pointer of type Vector3_t representing the first operand.
[in] v2 a pointer of type Vector3_t representing the second operand.
Returns
The cross product of the vectors v1 = (a1, b1, c1) and v2 = (a2, b2, c2) defined as v = v1 x v2 = (b1 * c2 - c1 * b2, c1 * a2 - a1 * c2, a1 * b2 - b1 * a2).
Warning
Vector cross product is not commutative.
Referenced by Vector3AnglePlane().
Vector3DotProduct()
static double Antipatrea::Vector3Algebra::Vector3DotProduct (const Vector3_t v1, const Vector3_t v2) inline static
Compute the dot product of the vectors v1 and v2.
Parameters
[in] v1 a pointer of type Vector3_t representing the first operand.
[in] v2 a pointer of type Vector3_t representing the second operand.
Returns
The dot product of the vectors v1 = (a1, b1, c1) and v2 = (a2, b2, c2) defined as a1 * a2 + b1 * b2 + c1 * c2.
Referenced by Vector3Angle(), Vector3Norm(), and Vector3ParallelProjection().
Vector3Norm()
static double Antipatrea::Vector3Algebra::Vector3Norm (const Vector3_t v) inline static
Compute the norm of the vector v.
Parameters
[in] v a pointer of type Vector3_t representing the vector to be accessed.
Returns
The norm of the vector v = (a, b, c) defined as norm(v) = sqrt(a * a + b * b + c * c).
References Vector3DotProduct().
Referenced by Vector3Unit().
Vector3Unit()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Unit (Vector3_t v) inline static
Normalize the vector v, i.e., v <– UNIT(v).
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be accessed and then modified.
Returns
The unit vector v defined as v / norm(v).
Warning
If norm(v) = 0, then v is not modified.
See also
Vector3Norm.
References Vector3Norm().
Referenced by Vector3Random().
Vector3Random()
static void Antipatrea::Vector3Algebra::Vector3Random (Vector3_t v, double min, double max) inline static
Set every element of the vector v to random numbers between min and max.
Parameters
[in,out] v a pointer of type Vector3_t representing the vector to be modified.
[in] min,real representing the beginning of interval to randomly generate elements
[in] max,real representing the end of interval to randomly generate elements
Returns
Vector v, with randomly generated elements from min to max, and normalized.
References Antipatrea::RandomUniformReal(), and Vector3Unit().
Vector3Negate()
static Vector3_t Antipatrea::Vector3Algebra::Vector3Negate (Vector3_t v, const Vector3_t v1) inline static
Set the vector v to the negation of the vector v1, i.e., v <– NEGATE(v1).
Parameters
[in,out] v a pointer of type Vector3_t representing the negated vector.
[in] v1 a pointer of type Vector3_t representing the vector to be negated.
Returns
Vector v defined as v = -v1 = (-a1, -b1, -c1), where v1 = (a1, b1, c1).
Vector3Angle()
static double Antipatrea::Vector3Algebra::Vector3Angle (const Vector3_t v1, const Vector3_t v2) inline static
Compute the angle between the vectors v1 and v2.
Parameters
[in] v1 a pointer of type Vector3_t representing the first vector.
[in] v2 a pointer of type Vector3_t representing the second vector.
Returns
The angle theta between the vectors v1 and v2 defined as theta = acos(dot(v1, v2) / (norm(v1) * norm(v2)). The computed angle theta is in the range [0, Pi].
Warning
If norm(v1) or norm(v2) is close to 0, then 0 is returned as the angle between v1 and v2.
References Vector3DotProduct().
Referenced by Vector3AnglePlane().
Vector3AnglePlane()
static double Antipatrea::Vector3Algebra::Vector3AnglePlane (const Vector3_t v1, const Vector3_t v2, const Vector3_t v3) inline static
References Vector3Angle(), Vector3CrossProduct(), and Vector3Declare.
Vector3lerp()
static Vector3_t Antipatrea::Vector3Algebra::Vector3lerp (Vector3_t v, const Vector3_t v1, const Vector3_t v2, const double t) inline static
Set the vector v to the linear interpolation of the vectors v1 and v2.
Parameters
[in,out] v a pointer of type Vector3_t representing the interpolated vector.
[in] v1 a pointer of type Vector3_t representing the source vector.
[in] v2 a pointer of type Vector3_t representing the destination vector.
[in] t a double in the interval [0, 1] representing the interpolation factor.
Returns
Vector v defined as v = v(t) = (1-t) * v1 + t * v2.
References Vector3LinearCombination().
Vector3SquareDistance()
static double Antipatrea::Vector3Algebra::Vector3SquareDistance (const Vector3_t v1, const Vector3_t v2) inline static
Compute the square of the Euclidean distance between the vectors v1 and v2.
Parameters
[in] v1 a pointer of type Vector3_t representing the first vector.
[in] v2 a pointer of type Vector3_t representing the second vector.
Returns
The square of the distance between v1 and v2 defined as dot(v1 - v2, v1 - v2).
Referenced by Vector3Distance().
Vector3Distance()
static double Antipatrea::Vector3Algebra::Vector3Distance (const Vector3_t v1, const Vector3_t v2) inline static
Compute the Euclidean distance between the vectors v1 and v2.
Parameters
[in] v1 a pointer of type Vector3_t representing the first vector.
[in] v2 a pointer of type Vector3_t representing the second vector.
Returns
The distance between v1 and v2 defined as norm(v1 - v2) = sqrt(dot(v1 - v2, v1 - v2)).
References Vector3SquareDistance().
Vector3ParallelProjection()
static double Antipatrea::Vector3Algebra::Vector3ParallelProjection (const Vector3_t u, const Vector3_t v) inline static
Compute the parallel projection of the vector u unto the vector v
Author
Amarda Shehu
Parameters
u vector
v vector
proj parallel projection of u onto v
Description:
proj <– v * dot(u, v) / dot(v, v)
References Vector3DotProduct().