Antipatrea::Algebra Namespace Reference
Antipatrea::Algebra Namespace Reference
Functions
static double VecDotProduct (const int n, const double v1[], const double v2[])
static double PointDistanceSquared (const int n, const double p1[], const double p2[])
static double PointDistance (const int n, const double p1[], const double p2[])
static double VecNormSquared (const int n, const double v[])
static double VecNorm (const int n, const double v[])
static void VecScale (const int n, const double v[], const double s, double vscaled[])
static void VecUnit (const int n, const double v[], double vunit[])
static void VecClampMagnitude (const int n, double v[], const double dmax)
static void VecClampMaxAbs (const int n, double v[], const double amax)
static double VecMaxAbsDifference (const int n, const double v1[], const double v2[])
static void VecAdd (const int n, const double v1[], const double v2[], double v[])
static void VecSubtract (const int n, const double v1[], const double v2[], double v[])
static void VecLinearInterpolation (const int n, const double v1[], const double t1, const double v2[], const double t2, double v[])
static double VecAngle (const int n, const double v1[], const double v2[])
static double VecAngleUnitArgs (const int n, const double v1[], const double v2[])
static void VecNormal (const int n, const double v[], double vnormal[])
static void VecParallelProjection (const int n, const double v[], const double u[], double v_on_u[])
static void VecParallelProjectionUnitArgs (const int n, const double v[], const double u[], double v_on_u[])
static void VecOrthogonalProjection (const int n, const double v[], const double u[], double v_on_u[])
static void VecOrthogonalProjectionUnitArgs (const int n, const double v[], const double u[], double v_on_u[])
static bool VecAreNormal (const int n, const double v1[], const double v2[])
static bool VecAreParallelOrAntiParallel (const int n, const double v1[], const double v2[])
static bool VecAreParallel (const int n, const double v1[], const double v2[])
static bool VecAreAntiParallel (const int n, const double v1[], const double v2[])
static int VecAlignment (const int n, const double v1[], const double v2[])
static bool VecAreParallelOrAntiParallelUnitArgs (const int n, const double v1[], const double v2[])
static bool VecAreParallelUnitArgs (const int n, const double v1[], const double v2[])
static bool VecAreAntiParallelUnitArgs (const int n, const double v1[], const double v2[])
static int VecAlignmentUnitArgs (const int n, const double v1[], const double v2[])
static double * MatAlloc (const int nrRows, const int nrCols)
static void MatFree (double A[])
static double MatGetEntry (const int nrRows, const int nrCols, const double A[], const int row, const int col)
static const double * MatGetRow (const int nrRows, const int nrCols, const double A[], const int row)
static void MatGetCol (const int nrRows, const int nrCols, const double A[], const int col, double colEntries[])
static void MatSetEntry (const int nrRows, const int nrCols, double A[], const int row, const int col, const double val)
static void MatSetRow (const int nrRows, const int nrCols, double A[], const int row, const double vals[])
static void MatSetCol (const int nrRows, const int nrCols, double A[], const int col, const double vals[])
static double MatRowDotVec (const int nrRows, const int nrCols, const double A[], const int row, const double v[])
static double MatColDotVec (const int nrRows, const int nrCols, const double A[], const int col, const double v[])
static double MatRowDotRow (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int row1, const int row2)
static double MatRowDotCol (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int row1, const int col2)
static double MatColDotRow (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int col1, const int row2)
static double MatColDotCol (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int col1, const int col2)
static void MatTranspose (const int nrRows, const int nrCols, const double A[], double Atransp[])
static void MatAdd (const int nrRows, const int nrCols, const double A1[], const double A2[], double A[])
static void MatSubtract (const int nrRows, const int nrCols, const double A1[], const double A2[], double A[])
static void MatScale (const int nrRows, const int nrCols, const double A[], const double s, double Ascaled[])
static void MatLinearInterpolation (const int nrRows, const int nrCols, const double A1[], const double t1, const double A2[], const double t2, double A[])
static void MatMultVec (const int nrRows, const int nrCols, const double A[], const double v[], double vnew[])
static void MatMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void TransposeOfMatMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void MatMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void TransposeOfMatMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void MatTransposeMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void TransposeOfMatTransposeMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void MatTransposeMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
static void TransposeOfMatTransposeMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[])
bool SolveLinearSystemMatMultVec (const int n, double Atransp[], double b[])
bool SVD (const int nrRowsA, const int nrColsA, double Atransp[], double Utransp[], double Sigma[], double V[])
static void PointSampleUniform (const int n, double p[], const double bbox[])
Function Documentation
VecDotProduct()
static double Antipatrea::Algebra::VecDotProduct (const int n, const double v1[], const double v2[]) inline static
Referenced by MatMultVec(), MatRowDotRow(), MatRowDotVec(), VecAlignment(), VecAlignmentUnitArgs(), VecAngle(), VecAngleUnitArgs(), VecAreAntiParallel(), VecAreAntiParallelUnitArgs(), VecAreNormal(), VecAreParallel(), VecAreParallelOrAntiParallel(), VecAreParallelOrAntiParallelUnitArgs(), VecAreParallelUnitArgs(), VecNormSquared(), VecOrthogonalProjection(), VecOrthogonalProjectionUnitArgs(), VecParallelProjection(), and VecParallelProjectionUnitArgs().
PointDistanceSquared()
static double Antipatrea::Algebra::PointDistanceSquared (const int n, const double p1[], const double p2[]) inline static
Referenced by PointDistance().
PointDistance()
static double Antipatrea::Algebra::PointDistance (const int n, const double p1[], const double p2[]) inline static
References PointDistanceSquared().
VecNormSquared()
static double Antipatrea::Algebra::VecNormSquared (const int n, const double v[]) inline static
References VecDotProduct().
Referenced by VecClampMagnitude(), and VecNorm().
VecNorm()
static double Antipatrea::Algebra::VecNorm (const int n, const double v[]) inline static
References VecNormSquared().
Referenced by VecAlignment(), VecAngle(), VecAreAntiParallel(), VecAreParallel(), VecAreParallelOrAntiParallel(), VecOrthogonalProjection(), VecParallelProjection(), and VecUnit().
VecScale()
static void Antipatrea::Algebra::VecScale (const int n, const double v[], const double s, double vscaled[]) inline static
Referenced by MatScale(), VecClampMagnitude(), VecClampMaxAbs(), VecParallelProjection(), VecParallelProjectionUnitArgs(), and VecUnit().
VecUnit()
static void Antipatrea::Algebra::VecUnit (const int n, const double v[], double vunit[]) inline static
References VecNorm(), and VecScale().
VecClampMagnitude()
static void Antipatrea::Algebra::VecClampMagnitude (const int n, double v[], const double dmax) inline static
References VecNormSquared(), and VecScale().
VecClampMaxAbs()
static void Antipatrea::Algebra::VecClampMaxAbs (const int n, double v[], const double amax) inline static
References VecScale().
VecMaxAbsDifference()
static double Antipatrea::Algebra::VecMaxAbsDifference (const int n, const double v1[], const double v2[]) inline static
VecAdd()
static void Antipatrea::Algebra::VecAdd (const int n, const double v1[], const double v2[], double v[]) inline static
Referenced by MatAdd().
VecSubtract()
static void Antipatrea::Algebra::VecSubtract (const int n, const double v1[], const double v2[], double v[]) inline static
Referenced by MatSubtract().
VecLinearInterpolation()
static void Antipatrea::Algebra::VecLinearInterpolation (const int n, const double v1[], const double t1, const double v2[], const double t2, double v[]) inline static
Referenced by MatLinearInterpolation().
VecAngle()
static double Antipatrea::Algebra::VecAngle (const int n, const double v1[], const double v2[]) inline static
References VecDotProduct(), and VecNorm().
VecAngleUnitArgs()
static double Antipatrea::Algebra::VecAngleUnitArgs (const int n, const double v1[], const double v2[]) inline static
References VecDotProduct().
VecNormal()
static void Antipatrea::Algebra::VecNormal (const int n, const double v[], double vnormal[]) inline static
References Antipatrea::Constants::EPSILON.
VecParallelProjection()
static void Antipatrea::Algebra::VecParallelProjection (const int n, const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), VecNorm(), and VecScale().
VecParallelProjectionUnitArgs()
static void Antipatrea::Algebra::VecParallelProjectionUnitArgs (const int n, const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), and VecScale().
VecOrthogonalProjection()
static void Antipatrea::Algebra::VecOrthogonalProjection (const int n, const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), and VecNorm().
VecOrthogonalProjectionUnitArgs()
static void Antipatrea::Algebra::VecOrthogonalProjectionUnitArgs (const int n, const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct().
VecAreNormal()
static bool Antipatrea::Algebra::VecAreNormal (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreParallelOrAntiParallel()
static bool Antipatrea::Algebra::VecAreParallelOrAntiParallel (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, VecDotProduct(), and VecNorm().
VecAreParallel()
static bool Antipatrea::Algebra::VecAreParallel (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, VecDotProduct(), and VecNorm().
VecAreAntiParallel()
static bool Antipatrea::Algebra::VecAreAntiParallel (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, VecDotProduct(), and VecNorm().
VecAlignment()
static int Antipatrea::Algebra::VecAlignment (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::ANTI_PARALLEL, Antipatrea::Constants::EPSILON, Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL, Antipatrea::Constants::PARALLEL, VecDotProduct(), and VecNorm().
VecAreParallelOrAntiParallelUnitArgs()
static bool Antipatrea::Algebra::VecAreParallelOrAntiParallelUnitArgs (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreParallelUnitArgs()
static bool Antipatrea::Algebra::VecAreParallelUnitArgs (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreAntiParallelUnitArgs()
static bool Antipatrea::Algebra::VecAreAntiParallelUnitArgs (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAlignmentUnitArgs()
static int Antipatrea::Algebra::VecAlignmentUnitArgs (const int n, const double v1[], const double v2[]) inline static
References Antipatrea::Constants::ANTI_PARALLEL, Antipatrea::Constants::EPSILON, Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL, Antipatrea::Constants::PARALLEL, and VecDotProduct().
MatAlloc()
static double* Antipatrea::Algebra::MatAlloc (const int nrRows, const int nrCols) inline static
MatFree()
static void Antipatrea::Algebra::MatFree (double A[]) inline static
MatGetEntry()
static double Antipatrea::Algebra::MatGetEntry (const int nrRows, const int nrCols, const double A[], const int row, const int col) inline static
MatGetRow()
static double * Antipatrea::Algebra::MatGetRow (const int nrRows, const int nrCols, const double A[], const int row) inline static
Referenced by MatRowDotCol(), MatRowDotRow(), MatRowDotVec(), and MatSetRow().
MatGetCol()
static void Antipatrea::Algebra::MatGetCol (const int nrRows, const int nrCols, const double A[], const int col, double colEntries[]) inline static
MatSetEntry()
static void Antipatrea::Algebra::MatSetEntry (const int nrRows, const int nrCols, double A[], const int row, const int col, const double val) inline static
MatSetRow()
static void Antipatrea::Algebra::MatSetRow (const int nrRows, const int nrCols, double A[], const int row, const double vals[]) inline static
References MatGetRow().
MatSetCol()
static void Antipatrea::Algebra::MatSetCol (const int nrRows, const int nrCols, double A[], const int col, const double vals[]) inline static
MatRowDotVec()
static double Antipatrea::Algebra::MatRowDotVec (const int nrRows, const int nrCols, const double A[], const int row, const double v[]) inline static
References MatGetRow(), and VecDotProduct().
MatColDotVec()
static double Antipatrea::Algebra::MatColDotVec (const int nrRows, const int nrCols, const double A[], const int col, const double v[]) inline static
MatRowDotRow()
static double Antipatrea::Algebra::MatRowDotRow (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int row1, const int row2) inline static
References MatGetRow(), and VecDotProduct().
Referenced by MatMultMatTranspose(), and TransposeOfMatMultMatTranspose().
MatRowDotCol()
static double Antipatrea::Algebra::MatRowDotCol (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int row1, const int col2) inline static
References MatGetRow().
Referenced by MatColDotRow(), MatMultMat(), and TransposeOfMatMultMat().
MatColDotRow()
static double Antipatrea::Algebra::MatColDotRow (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int col1, const int row2) inline static
References MatRowDotCol().
Referenced by MatTransposeMultMatTranspose(), and TransposeOfMatTransposeMultMatTranspose().
MatColDotCol()
static double Antipatrea::Algebra::MatColDotCol (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], const int col1, const int col2) inline static
Referenced by MatTransposeMultMat(), and TransposeOfMatTransposeMultMat().
MatTranspose()
static void Antipatrea::Algebra::MatTranspose (const int nrRows, const int nrCols, const double A[], double Atransp[]) inline static
MatAdd()
static void Antipatrea::Algebra::MatAdd (const int nrRows, const int nrCols, const double A1[], const double A2[], double A[]) inline static
References VecAdd().
MatSubtract()
static void Antipatrea::Algebra::MatSubtract (const int nrRows, const int nrCols, const double A1[], const double A2[], double A[]) inline static
References VecSubtract().
MatScale()
static void Antipatrea::Algebra::MatScale (const int nrRows, const int nrCols, const double A[], const double s, double Ascaled[]) inline static
References VecScale().
MatLinearInterpolation()
static void Antipatrea::Algebra::MatLinearInterpolation (const int nrRows, const int nrCols, const double A1[], const double t1, const double A2[], const double t2, double A[]) inline static
References VecLinearInterpolation().
MatMultVec()
static void Antipatrea::Algebra::MatMultVec (const int nrRows, const int nrCols, const double A[], const double v[], double vnew[]) inline static
References VecDotProduct().
MatMultMat()
static void Antipatrea::Algebra::MatMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatRowDotCol().
TransposeOfMatMultMat()
static void Antipatrea::Algebra::TransposeOfMatMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatRowDotCol().
MatMultMatTranspose()
static void Antipatrea::Algebra::MatMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatRowDotRow().
TransposeOfMatMultMatTranspose()
static void Antipatrea::Algebra::TransposeOfMatMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatRowDotRow().
MatTransposeMultMat()
static void Antipatrea::Algebra::MatTransposeMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatColDotCol().
TransposeOfMatTransposeMultMat()
static void Antipatrea::Algebra::TransposeOfMatTransposeMultMat (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatColDotCol().
MatTransposeMultMatTranspose()
static void Antipatrea::Algebra::MatTransposeMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatColDotRow().
TransposeOfMatTransposeMultMatTranspose()
static void Antipatrea::Algebra::TransposeOfMatTransposeMultMatTranspose (const int nrRows1, const int nrCols1, const double A1[], const int nrRows2, const int nrCols2, const double A2[], double A[]) inline static
References MatColDotRow(), SolveLinearSystemMatMultVec(), and SVD().
SolveLinearSystemMatMultVec()
bool Antipatrea::Algebra::SolveLinearSystemMatMultVec (const int n, double Atransp[], double b[])
Referenced by TransposeOfMatTransposeMultMatTranspose().
SVD()
bool Antipatrea::Algebra::SVD (const int nrRowsA, const int nrColsA, double Atransp[], double Utransp[], double Sigma[], double V[])
Referenced by TransposeOfMatTransposeMultMatTranspose().
PointSampleUniform()
static void Antipatrea::Algebra::PointSampleUniform (const int n, double p[], const double bbox[]) inline static
References Antipatrea::RandomUniformReal().