Antipatrea::Constants Namespace Reference
Antipatrea::Constants Namespace Reference
Keywords and default values.
Variables
const char KW_UseCfgManager [] = "UseCfgManager"
const char KW_CfgManager [] = "CfgManager"
const char KW_Dim [] = "Dim"
const char KW_UseCfgAcceptor [] = "UseCfgAcceptor"
const char KW_CfgAcceptor [] = "CfgAcceptor"
const char KW_CfgAcceptorBasedOnDistance [] = "CfgAcceptorBasedOnDistance"
const char KW_CfgAcceptorBasedOnEnergy [] = "CfgAcceptorBasedOnEnergy"
const char KW_EnergyThreshold [] = "EnergyThreshold"
const char KW_DistanceThreshold [] = "DistanceThreshold"
const double VAL_CfgAcceptorBasedOnEnergy_EnergyThreshold = INFINITY
const double VAL_CfgAcceptorBasedOnDistance_DistanceThreshold = 0.2
const char KW_UseGoalAcceptor [] = "UseGoalAcceptor"
const char KW_GoalAcceptor [] = "GoalAcceptor"
const char KW_GoalAcceptorBasedOnDistance [] = "GoalAcceptorBasedOnDistance"
const char KW_GoalAcceptorBasedOnEnergy [] = "GoalAcceptorBasedOnEnergy"
const double VAL_GoalAcceptorBasedOnDistance_DistanceThreshold = VAL_CfgAcceptorBasedOnDistance_DistanceThreshold
const double VAL_GoalAcceptorBasedOnEnergy_EnergyThreshold = INFINITY
const char KW_UseSignedDistanceBetweenTwoValues [] = "UseSignedDistanceBetweenTwoValues"
const char KW_SignedDistanceBetweenTwoValues [] = "SignedDistanceBetweenTwoValues"
const char KW_SignedDistanceBetweenTwoAngles [] = "SignedDistanceBetweenTwoAngles"
const char KW_SignedDistanceBetweenTwoNumbers [] = "SignedDistanceBetweenTwoNumbers"
const char KW_UseCfgDistance [] = "UseCfgDistance"
const char KW_CfgDistance [] = "CfgDistance"
const char KW_CfgDistanceLp [] = "CfgDistanceLp"
const char KW_Exponent [] = "Exponent"
const int VAL_CfgDistanceLp_Exponent = 2
const char KW_UseCfgEnergyEvaluator [] = "UseCfgEnergyEvaluator"
const char KW_CfgEnergyEvaluator [] = "CfgEnergyEvaluator"
const char KW_CfgEnergyEvaluatorInJointSpace [] = "CfgEnergyEvaluatorInJointSpace"
const char KW_UseCfgImprover [] = "UseCfgImprover"
const char KW_CfgImprover [] = "CfgImprover"
const char KW_CfgImproverDoNothing [] = "CfgImproverDoNothing"
const char KW_UseCfgOffspringGenerator [] = "UseCfgOffspringGenerator"
const char KW_CfgOffspringGenerator [] = "CfgOffspringGenerator"
const char KW_Step [] = "Step"
const char KW_CfgOffspringGeneratorTowardTarget [] = "CfgOffspringGeneratorTowardTarget"
const char KW_CfgOffspringGeneratorToTarget [] = "CfgOffspringGeneratorToTarget"
const char KW_CfgOffspringGeneratorToTargetByLinearInterpolation [] = "CfgOffspringGeneratorToTargetByLinearInterpolation"
const char KW_CfgOffspringGeneratorByGaussianPerturbation [] = "CfgOffspringGeneratorByGaussianPerturbation"
const char KW_Consecutive [] = "Consecutive"
const char KW_MinNrValuesToPerturb [] = "MinNrValuesToPerturb"
const char KW_MaxNrValuesToPerturb [] = "MaxNrValuesToPerturb"
const double VAL_CfgOffspringGenerator_Step = 0.1
const bool VAL_CfgOffspringGeneratorByGaussianPerturbation_Consecutive = false
const int VAL_CfgOffspringGeneratorByGaussianPerturbation_MinNrValuesToPerturb = 1
const int VAL_CfgOffspringGeneratorByGaussianPerturbation_MaxNrValuesToPerturb = std::numeric_limits<int>::max()
const char KW_UseCfgSampler [] = "UseCfgSampler"
const char KW_CfgSampler [] = "CfgSampler"
const char KW_CfgUniformSamplerInJointSpace [] = "CfgUniformSamplerInJointSpace"
const char KW_UseCfgForwardKinematics [] = "UseCfgForwardKinematics"
const char KW_CfgForwardKinematics [] = "CfgForwardKinematics"
const char KW_UseCfgProjector [] = "UseCfgProjector"
const char KW_CfgProjector [] = "CfgProjector"
const char KW_UseEdgeCostEvaluator [] = "UseEdgeCostEvaluator"
const char KW_EdgeCostEvaluator [] = "EdgeCostEvaluator"
const char KW_EdgeCostEvaluatorBasedOnDistance [] = "EdgeCostEvaluatorBasedOnDistance"
const char KW_EdgeCostEvaluatorBasedOnEnergy [] = "EdgeCostEvaluatorBasedOnEnergy"
const char KW_UsePlannerGraph [] = "UsePlannerGraph"
const char KW_PlannerGraph [] = "PlannerGraph"
const char KW_ReadWhenPlannerStarts [] = "ReadWhenPlannerStarts"
const char KW_PrintWhenPlannerEnds [] = "PrintWhenPlannerEnds"
const char VAL_PlannerGraphFile [] = "data/PlannerGraph.txt"
const char KW_UsePlannerProblem [] = "UsePlannerProblem"
const char KW_PlannerProblem [] = "PlannerProblem"
const char KW_UsePlannerSolution [] = "UsePlannerSolution"
const char KW_PlannerSolution [] = "PlannerSolution"
const char KW_UsePlanner [] = "UsePlanner"
const char KW_Planner [] = "Planner"
const char KW_SamplingBasedPlanner [] = "SamplingBasedPlanner"
const char KW_OneStepDistance [] = "OneStepDistance"
const double VAL_SamplingBasedPlanner_OneStepDistance = 0.1
const char KW_PRM [] = "PRM"
const char KW_NrNeighbors [] = "NrNeighbors"
const char KW_BatchSizeToGenerateVertices [] = "BatchSizeToGenerateVertices"
const char KW_ProbAllowCycles [] = "ProbAllowCycles"
const int VAL_PRM_NrNeighbors = 10
const int VAL_PRM_BatchSizeToGenerateVertices = 100
const double VAL_PRM_ProbAllowCycles = 0.0
const char KW_TreeSamplingBasedPlanner [] = "TreeSamplingBasedPlanner"
const char KW_ExtendMaxNrSteps [] = "ExtendMaxNrSteps"
const char KW_ExtendReachedTargetDistanceThreshold [] = "ExtendReachedTargetDistanceThreshold"
const char KW_GoalBias [] = "GoalBias"
const char KW_SampleValidTargetCfg [] = "SampleValidTargetCfg"
const int VAL_Tree_ExtendMaxNrSteps = 100
const double VAL_Tree_ExtendReachedTargetDistanceThreshold = 0.1
const double VAL_Tree_GoalBias = 0.05
const char KW_EST [] = "EST"
const char KW_NeighborhoodRadius [] = "NeighborhoodRadius"
const double VAL_EST_NeighborhoodRadius = 2.0
const char KW_RRT [] = "RRT"
const char KW_PGT [] = "PGT"
const char KW_RunPlanner [] = "RunPlanner"
const char KW_UseStatsFile [] = "UseStatsFile"
const char KW_MaxNrRuns [] = "MaxNrRuns"
const char KW_MaxRuntime [] = "MaxRuntime"
const char KW_MaxNrFailures [] = "MaxNrFailures"
const char KW_IntervalRuntime [] = "IntervalRuntime"
const char KW_ReadInitAndGoalCfgsFromFile [] = "ReadInitAndGoalCfgsFromFile"
const char VAL_RunPlanner_StatsFile [] = "data/planner.stats"
const int VAL_RunPlanner_MaxNrRuns = 10
const int VAL_RunPlanner_MaxNrFailures = 5
const double VAL_RunPlanner_MaxRuntime = 5.0
const double VAL_RunPlanner_IntervalRuntime = 1.0
const char KW_Runtime_PlannerSolve [] = "Runtime_PlannerSolve"
const char KW_Runtime_PlannerStart [] = "Runtime_PlannerStart"
const char KW_Runtime_PRM_GenerateVertices [] = "Runtime_PRM_GenerateVertices"
const char KW_Runtime_PRM_GenerateEdges [] = "Runtime_PRM_GenerateEdges"
const char KW_UseSetup [] = "UseSetup"
const char KW_Scene2D [] = "Scene2D"
const char VAL_SceneFile [] = "data/scene.txt"
const char KW_SetupPoint2D [] = "SetupPoint2D"
const char KW_CfgSamplerPoint2D [] = "CfgSamplerPoint2D"
const char KW_CfgAcceptorPoint2D [] = "CfgAcceptorPoint2D"
const char KW_CfgProjectorPoint2D [] = "CfgProjectorPoint2D"
const char KW_SetupChain2D [] = "SetupChain2D"
const char KW_Chain2D [] = "Chain2D"
const char KW_NrLinks [] = "NrLinks"
const char KW_LinkLength [] = "LinkLength"
const int VAL_Chain2D_NrLinks = 8
const double VAL_Chain2D_LinkLength = 1.0
const char KW_CfgAcceptorChain2D [] = "CfgAcceptorChain2D"
const char KW_CfgProjectorChain2D [] = "CfgProjectorChain2D"
const char KW_SetupRosetta [] = "SetupRosetta"
const char KW_MolecularStructureRosetta [] = "MolecularStructureRosetta"
const char KW_CfgSamplerRosetta [] = "CfgSamplerRosetta"
const char KW_CfgImproverRosetta [] = "CfgImproverRosetta"
const char KW_CfgOffspringGeneratorRosetta [] = "CfgOffspringGeneratorRosetta"
const char KW_CfgEnergyEvaluatorRosetta [] = "CfgEnergyEvaluatorRosetta"
const char KW_CfgProjectorUSR [] = "CfgProjectorUSR"
const char KW_CfgProjectorDeltaR [] = "CfgProjectorDeltaR"
const int NEITHER_PARALLEL_NOR_ANTI_PARALLEL = 0
const int PARALLEL = 1
const int ANTI_PARALLEL = 2
const double EPSILON = ldexp(1.0, -36)
const double EPSILON_SQUARED = ldexp(1.0, -72)
const double SQRT_EPSILON = ldexp(1.0, -18)
const double RAD2DEG = 180 / M_PI
const double DEG2RAD = M_PI / 180
const int ID_UNDEFINED = -1
const char KW_Grid [] = "Grid"
const char KW_GridNrDims [] = "NrDims"
const char KW_GridMin [] = "Min"
const char KW_GridMax [] = "Max"
const char KW_GridDims [] = "Dims"
const char KW_ReadFromFile [] = "ReadFromFile"
const char KW_WriteToFile [] = "WriteToFile"
const char KW_UseFile [] = "UseFile"
Detailed Description
Keywords and default values.
Author
Erion Plaku, Amarda Shehu
Variable Documentation
const char Antipatrea::Constants::KW_UseCfgManager[] = "UseCfgManager"
const char Antipatrea::Constants::KW_CfgManager[] = "CfgManager"
Referenced by Antipatrea::CfgManager::SetupFromParams().
const char Antipatrea::Constants::KW_Dim[] = "Dim"
Referenced by Antipatrea::CfgManager::SetupFromParams(), and Antipatrea::CfgProjector::SetupFromParams().
const char Antipatrea::Constants::KW_UseCfgAcceptor[] = "UseCfgAcceptor"
const char Antipatrea::Constants::KW_CfgAcceptor[] = "CfgAcceptor"
const char Antipatrea::Constants::KW_CfgAcceptorBasedOnDistance[] = "CfgAcceptorBasedOnDistance"
Referenced by Antipatrea::CfgAcceptorBasedOnDistance::SetupFromParams().
const char Antipatrea::Constants::KW_CfgAcceptorBasedOnEnergy[] = "CfgAcceptorBasedOnEnergy"
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams().
const char Antipatrea::Constants::KW_EnergyThreshold[] = "EnergyThreshold"
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams().
const char Antipatrea::Constants::KW_DistanceThreshold[] = "DistanceThreshold"
Referenced by Antipatrea::CfgAcceptorBasedOnDistance::SetupFromParams().
const double Antipatrea::Constants::VAL_CfgAcceptorBasedOnEnergy_EnergyThreshold = INFINITY
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::CfgAcceptorBasedOnEnergy().
const double Antipatrea::Constants::VAL_CfgAcceptorBasedOnDistance_DistanceThreshold = 0.2
Referenced by Antipatrea::CfgAcceptorBasedOnDistance::CfgAcceptorBasedOnDistance().
const char Antipatrea::Constants::KW_UseGoalAcceptor[] = "UseGoalAcceptor"
const char Antipatrea::Constants::KW_GoalAcceptor[] = "GoalAcceptor"
const char Antipatrea::Constants::KW_GoalAcceptorBasedOnDistance[] = "GoalAcceptorBasedOnDistance"
Referenced by Antipatrea::CfgAcceptorBasedOnDistance::SetupFromParams().
const char Antipatrea::Constants::KW_GoalAcceptorBasedOnEnergy[] = "GoalAcceptorBasedOnEnergy"
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::SetupFromParams().
const double Antipatrea::Constants::VAL_GoalAcceptorBasedOnDistance_DistanceThreshold = VAL_CfgAcceptorBasedOnDistance_DistanceThreshold
Referenced by Antipatrea::CfgAcceptorBasedOnDistance::CfgAcceptorBasedOnDistance().
const double Antipatrea::Constants::VAL_GoalAcceptorBasedOnEnergy_EnergyThreshold = INFINITY
Referenced by Antipatrea::CfgAcceptorBasedOnEnergy::CfgAcceptorBasedOnEnergy().
const char Antipatrea::Constants::KW_UseSignedDistanceBetweenTwoValues[] = "UseSignedDistanceBetweenTwoValues"
const char Antipatrea::Constants::KW_SignedDistanceBetweenTwoValues[] = "SignedDistanceBetweenTwoValues"
const char Antipatrea::Constants::KW_SignedDistanceBetweenTwoAngles[] = "SignedDistanceBetweenTwoAngles"
const char Antipatrea::Constants::KW_SignedDistanceBetweenTwoNumbers[] = "SignedDistanceBetweenTwoNumbers"
const char Antipatrea::Constants::KW_UseCfgDistance[] = "UseCfgDistance"
const char Antipatrea::Constants::KW_CfgDistance[] = "CfgDistance"
const char Antipatrea::Constants::KW_CfgDistanceLp[] = "CfgDistanceLp"
Referenced by Antipatrea::CfgDistanceLp::SetupFromParams().
const char Antipatrea::Constants::KW_Exponent[] = "Exponent"
Referenced by Antipatrea::CfgDistanceLp::SetupFromParams().
const int Antipatrea::Constants::VAL_CfgDistanceLp_Exponent = 2
const char Antipatrea::Constants::KW_UseCfgEnergyEvaluator[] = "UseCfgEnergyEvaluator"
Referenced by Antipatrea::SetupRosetta::NewCfgEnergyEvaluator().
const char Antipatrea::Constants::KW_CfgEnergyEvaluator[] = "CfgEnergyEvaluator"
const char Antipatrea::Constants::KW_CfgEnergyEvaluatorInJointSpace[] = "CfgEnergyEvaluatorInJointSpace"
const char Antipatrea::Constants::KW_UseCfgImprover[] = "UseCfgImprover"
Referenced by Antipatrea::SetupRosetta::NewCfgImprover().
const char Antipatrea::Constants::KW_CfgImprover[] = "CfgImprover"
const char Antipatrea::Constants::KW_CfgImproverDoNothing[] = "CfgImproverDoNothing"
const char Antipatrea::Constants::KW_UseCfgOffspringGenerator[] = "UseCfgOffspringGenerator"
Referenced by Antipatrea::SetupRosetta::NewCfgOffspringGenerator().
const char Antipatrea::Constants::KW_CfgOffspringGenerator[] = "CfgOffspringGenerator"
Referenced by Antipatrea::CfgOffspringGenerator::SetupFromParams().
const char Antipatrea::Constants::KW_Step[] = "Step"
Referenced by Antipatrea::CfgOffspringGenerator::SetupFromParams().
const char Antipatrea::Constants::KW_CfgOffspringGeneratorTowardTarget[] = "CfgOffspringGeneratorTowardTarget"
const char Antipatrea::Constants::KW_CfgOffspringGeneratorToTarget[] = "CfgOffspringGeneratorToTarget"
const char Antipatrea::Constants::KW_CfgOffspringGeneratorToTargetByLinearInterpolation[] = "CfgOffspringGeneratorToTargetByLinearInterpolation"
const char Antipatrea::Constants::KW_CfgOffspringGeneratorByGaussianPerturbation[] = "CfgOffspringGeneratorByGaussianPerturbation"
Referenced by Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams().
const char Antipatrea::Constants::KW_Consecutive[] = "Consecutive"
Referenced by Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams().
const char Antipatrea::Constants::KW_MinNrValuesToPerturb[] = "MinNrValuesToPerturb"
Referenced by Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams().
const char Antipatrea::Constants::KW_MaxNrValuesToPerturb[] = "MaxNrValuesToPerturb"
Referenced by Antipatrea::CfgOffspringGeneratorByGaussianPerturbation::SetupFromParams().
const double Antipatrea::Constants::VAL_CfgOffspringGenerator_Step = 0.1
const bool Antipatrea::Constants::VAL_CfgOffspringGeneratorByGaussianPerturbation_Consecutive = false
const int Antipatrea::Constants::VAL_CfgOffspringGeneratorByGaussianPerturbation_MinNrValuesToPerturb = 1
const int Antipatrea::Constants::VAL_CfgOffspringGeneratorByGaussianPerturbation_MaxNrValuesToPerturb = std::numeric_limits<int>::max()
const char Antipatrea::Constants::KW_UseCfgSampler[] = "UseCfgSampler"
Referenced by Antipatrea::SetupRosetta::NewCfgSampler().
const char Antipatrea::Constants::KW_CfgSampler[] = "CfgSampler"
const char Antipatrea::Constants::KW_CfgUniformSamplerInJointSpace[] = "CfgUniformSamplerInJointSpace"
const char Antipatrea::Constants::KW_UseCfgForwardKinematics[] = "UseCfgForwardKinematics"
Referenced by Antipatrea::SetupRosetta::NewCfgForwardKinematics().
const char Antipatrea::Constants::KW_CfgForwardKinematics[] = "CfgForwardKinematics"
const char Antipatrea::Constants::KW_UseCfgProjector[] = "UseCfgProjector"
Referenced by Antipatrea::SetupRosetta::NewCfgProjector().
const char Antipatrea::Constants::KW_CfgProjector[] = "CfgProjector"
Referenced by Antipatrea::CfgProjector::SetupFromParams().
const char Antipatrea::Constants::KW_UseEdgeCostEvaluator[] = "UseEdgeCostEvaluator"
const char Antipatrea::Constants::KW_EdgeCostEvaluator[] = "EdgeCostEvaluator"
const char Antipatrea::Constants::KW_EdgeCostEvaluatorBasedOnDistance[] = "EdgeCostEvaluatorBasedOnDistance"
const char Antipatrea::Constants::KW_EdgeCostEvaluatorBasedOnEnergy[] = "EdgeCostEvaluatorBasedOnEnergy"
const char Antipatrea::Constants::KW_UsePlannerGraph[] = "UsePlannerGraph"
const char Antipatrea::Constants::KW_PlannerGraph[] = "PlannerGraph"
const char Antipatrea::Constants::KW_ReadWhenPlannerStarts[] = "ReadWhenPlannerStarts"
const char Antipatrea::Constants::KW_PrintWhenPlannerEnds[] = "PrintWhenPlannerEnds"
const char Antipatrea::Constants::VAL_PlannerGraphFile[] = "data/PlannerGraph.txt"
const char Antipatrea::Constants::KW_UsePlannerProblem[] = "UsePlannerProblem"
const char Antipatrea::Constants::KW_PlannerProblem[] = "PlannerProblem"
const char Antipatrea::Constants::KW_UsePlannerSolution[] = "UsePlannerSolution"
const char Antipatrea::Constants::KW_PlannerSolution[] = "PlannerSolution"
const char Antipatrea::Constants::KW_UsePlanner[] = "UsePlanner"
const char Antipatrea::Constants::KW_Planner[] = "Planner"
const char Antipatrea::Constants::KW_SamplingBasedPlanner[] = "SamplingBasedPlanner"
Referenced by Antipatrea::SamplingBasedPlanner::SetupFromParams().
const char Antipatrea::Constants::KW_OneStepDistance[] = "OneStepDistance"
Referenced by Antipatrea::SamplingBasedPlanner::SetupFromParams().
const double Antipatrea::Constants::VAL_SamplingBasedPlanner_OneStepDistance = 0.1
const char Antipatrea::Constants::KW_PRM[] = "PRM"
Referenced by Antipatrea::PRM::SetupFromParams().
const char Antipatrea::Constants::KW_NrNeighbors[] = "NrNeighbors"
Referenced by Antipatrea::PRM::SetupFromParams().
const char Antipatrea::Constants::KW_BatchSizeToGenerateVertices[] = "BatchSizeToGenerateVertices"
Referenced by Antipatrea::PRM::SetupFromParams().
const char Antipatrea::Constants::KW_ProbAllowCycles[] = "ProbAllowCycles"
Referenced by Antipatrea::PRM::SetupFromParams().
const int Antipatrea::Constants::VAL_PRM_NrNeighbors = 10
const int Antipatrea::Constants::VAL_PRM_BatchSizeToGenerateVertices = 100
const double Antipatrea::Constants::VAL_PRM_ProbAllowCycles = 0.0
const char Antipatrea::Constants::KW_TreeSamplingBasedPlanner[] = "TreeSamplingBasedPlanner"
Referenced by Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
const char Antipatrea::Constants::KW_ExtendMaxNrSteps[] = "ExtendMaxNrSteps"
Referenced by Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
const char Antipatrea::Constants::KW_ExtendReachedTargetDistanceThreshold[] = "ExtendReachedTargetDistanceThreshold"
Referenced by Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
const char Antipatrea::Constants::KW_GoalBias[] = "GoalBias"
Referenced by Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
const char Antipatrea::Constants::KW_SampleValidTargetCfg[] = "SampleValidTargetCfg"
Referenced by Antipatrea::TreeSamplingBasedPlanner::SetupFromParams().
const int Antipatrea::Constants::VAL_Tree_ExtendMaxNrSteps = 100
const double Antipatrea::Constants::VAL_Tree_ExtendReachedTargetDistanceThreshold = 0.1
const double Antipatrea::Constants::VAL_Tree_GoalBias = 0.05
const char Antipatrea::Constants::KW_EST[] = "EST"
Referenced by Antipatrea::EST::SetupFromParams().
const char Antipatrea::Constants::KW_NeighborhoodRadius[] = "NeighborhoodRadius"
Referenced by Antipatrea::EST::SetupFromParams().
const double Antipatrea::Constants::VAL_EST_NeighborhoodRadius = 2.0
const char Antipatrea::Constants::KW_RRT[] = "RRT"
const char Antipatrea::Constants::KW_PGT[] = "PGT"
const char Antipatrea::Constants::KW_RunPlanner[] = "RunPlanner"
const char Antipatrea::Constants::KW_UseStatsFile[] = "UseStatsFile"
const char Antipatrea::Constants::KW_MaxNrRuns[] = "MaxNrRuns"
const char Antipatrea::Constants::KW_MaxRuntime[] = "MaxRuntime"
const char Antipatrea::Constants::KW_MaxNrFailures[] = "MaxNrFailures"
const char Antipatrea::Constants::KW_IntervalRuntime[] = "IntervalRuntime"
const char Antipatrea::Constants::KW_ReadInitAndGoalCfgsFromFile[] = "ReadInitAndGoalCfgsFromFile"
const char Antipatrea::Constants::VAL_RunPlanner_StatsFile[] = "data/planner.stats"
const int Antipatrea::Constants::VAL_RunPlanner_MaxNrRuns = 10
const int Antipatrea::Constants::VAL_RunPlanner_MaxNrFailures = 5
const double Antipatrea::Constants::VAL_RunPlanner_MaxRuntime = 5.0
const double Antipatrea::Constants::VAL_RunPlanner_IntervalRuntime = 1.0
const char Antipatrea::Constants::KW_Runtime_PlannerSolve[] = "Runtime_PlannerSolve"
const char Antipatrea::Constants::KW_Runtime_PlannerStart[] = "Runtime_PlannerStart"
const char Antipatrea::Constants::KW_Runtime_PRM_GenerateVertices[] = "Runtime_PRM_GenerateVertices"
const char Antipatrea::Constants::KW_Runtime_PRM_GenerateEdges[] = "Runtime_PRM_GenerateEdges"
const char Antipatrea::Constants::KW_UseSetup[] = "UseSetup"
const char Antipatrea::Constants::KW_Scene2D[] = "Scene2D"
const char Antipatrea::Constants::VAL_SceneFile[] = "data/scene.txt"
const char Antipatrea::Constants::KW_SetupPoint2D[] = "SetupPoint2D"
const char Antipatrea::Constants::KW_CfgSamplerPoint2D[] = "CfgSamplerPoint2D"
const char Antipatrea::Constants::KW_CfgAcceptorPoint2D[] = "CfgAcceptorPoint2D"
const char Antipatrea::Constants::KW_CfgProjectorPoint2D[] = "CfgProjectorPoint2D"
const char Antipatrea::Constants::KW_SetupChain2D[] = "SetupChain2D"
const char Antipatrea::Constants::KW_Chain2D[] = "Chain2D"
const char Antipatrea::Constants::KW_NrLinks[] = "NrLinks"
const char Antipatrea::Constants::KW_LinkLength[] = "LinkLength"
const int Antipatrea::Constants::VAL_Chain2D_NrLinks = 8
const double Antipatrea::Constants::VAL_Chain2D_LinkLength = 1.0
const char Antipatrea::Constants::KW_CfgAcceptorChain2D[] = "CfgAcceptorChain2D"
const char Antipatrea::Constants::KW_CfgProjectorChain2D[] = "CfgProjectorChain2D"
const char Antipatrea::Constants::KW_SetupRosetta[] = "SetupRosetta"
const char Antipatrea::Constants::KW_MolecularStructureRosetta[] = "MolecularStructureRosetta"
Referenced by Antipatrea::SetupRosetta::NewCfgForwardKinematics().
const char Antipatrea::Constants::KW_CfgSamplerRosetta[] = "CfgSamplerRosetta"
Referenced by Antipatrea::SetupRosetta::NewCfgSampler().
const char Antipatrea::Constants::KW_CfgImproverRosetta[] = "CfgImproverRosetta"
Referenced by Antipatrea::SetupRosetta::NewCfgImprover().
const char Antipatrea::Constants::KW_CfgOffspringGeneratorRosetta[] = "CfgOffspringGeneratorRosetta"
Referenced by Antipatrea::SetupRosetta::NewCfgOffspringGenerator().
const char Antipatrea::Constants::KW_CfgEnergyEvaluatorRosetta[] = "CfgEnergyEvaluatorRosetta"
Referenced by Antipatrea::SetupRosetta::NewCfgEnergyEvaluator().
const char Antipatrea::Constants::KW_CfgProjectorUSR[] = "CfgProjectorUSR"
Referenced by Antipatrea::SetupRosetta::NewCfgProjector().
const char Antipatrea::Constants::KW_CfgProjectorDeltaR[] = "CfgProjectorDeltaR"
Referenced by Antipatrea::SetupRosetta::NewCfgProjector().
const int Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL = 0
Referenced by Antipatrea::Algebra2D::VecAlignment(), Antipatrea::Algebra3D::VecAlignment(), Antipatrea::Algebra::VecAlignment(), Antipatrea::Algebra3D::VecAlignmentUnitArgs(), Antipatrea::Algebra2D::VecAlignmentUnitArgs(), and Antipatrea::Algebra::VecAlignmentUnitArgs().
const int Antipatrea::Constants::PARALLEL = 1
Referenced by Antipatrea::Algebra2D::VecAlignment(), Antipatrea::Algebra3D::VecAlignment(), Antipatrea::Algebra::VecAlignment(), Antipatrea::Algebra3D::VecAlignmentUnitArgs(), Antipatrea::Algebra2D::VecAlignmentUnitArgs(), and Antipatrea::Algebra::VecAlignmentUnitArgs().
const int Antipatrea::Constants::ANTI_PARALLEL = 2
Referenced by Antipatrea::Algebra2D::VecAlignment(), Antipatrea::Algebra3D::VecAlignment(), Antipatrea::Algebra::VecAlignment(), Antipatrea::Algebra3D::VecAlignmentUnitArgs(), Antipatrea::Algebra2D::VecAlignmentUnitArgs(), and Antipatrea::Algebra::VecAlignmentUnitArgs().
const double Antipatrea::Constants::EPSILON = ldexp(1.0, -36)
Referenced by Antipatrea::Algebra2D::AngleSameAsAngle(), Antipatrea::Algebra2D::AngleSameAsRot(), Antipatrea::Algebra2D::IdentitySameAsAngle(), Antipatrea::Algebra3D::IdentitySameAsQuat(), Antipatrea::Algebra3D::IdentitySameAsRot(), Antipatrea::Algebra2D::IdentitySameAsRot(), Antipatrea::Algebra3D::IdentitySameAsTrans(), Antipatrea::Algebra2D::IdentitySameAsTrans(), Antipatrea::Algebra3D::QuatSameAsQuat(), Antipatrea::Algebra3D::QuatSameAsRot(), Antipatrea::Algebra2D::RotSameAsRot(), Antipatrea::Algebra3D::RotSameAsRot(), Antipatrea::Algebra2D::TransSameAsTrans(), Antipatrea::Algebra3D::TransSameAsTrans(), Antipatrea::Algebra::VecAlignment(), Antipatrea::Algebra3D::VecAlignmentUnitArgs(), Antipatrea::Algebra::VecAlignmentUnitArgs(), Antipatrea::Algebra::VecAreAntiParallel(), Antipatrea::Algebra2D::VecAreAntiParallelUnitArgs(), Antipatrea::Algebra3D::VecAreAntiParallelUnitArgs(), Antipatrea::Algebra::VecAreAntiParallelUnitArgs(), Antipatrea::Algebra3D::VecAreNormal(), Antipatrea::Algebra2D::VecAreNormal(), Antipatrea::Algebra::VecAreNormal(), Antipatrea::Algebra::VecAreParallel(), Antipatrea::Algebra2D::VecAreParallelOrAntiParallel(), Antipatrea::Algebra::VecAreParallelOrAntiParallel(), Antipatrea::Algebra3D::VecAreParallelOrAntiParallelUnitArgs(), Antipatrea::Algebra::VecAreParallelOrAntiParallelUnitArgs(), Antipatrea::Algebra2D::VecAreParallelUnitArgs(), Antipatrea::Algebra3D::VecAreParallelUnitArgs(), Antipatrea::Algebra::VecAreParallelUnitArgs(), and Antipatrea::Algebra::VecNormal().
const double Antipatrea::Constants::EPSILON_SQUARED = ldexp(1.0, -72)
Referenced by Antipatrea::Algebra3D::QuatAsUnitAxisAngle(), and Antipatrea::Algebra3D::VecAreParallelOrAntiParallel().
const double Antipatrea::Constants::SQRT_EPSILON = ldexp(1.0, -18)
const double Antipatrea::Constants::RAD2DEG = 180 / M_PI
const double Antipatrea::Constants::DEG2RAD = M_PI / 180
const int Antipatrea::Constants::ID_UNDEFINED = -1
Referenced by Antipatrea::Heap< Key, Compare, Equal, Hash >::GetKeyPosition(), and Antipatrea::PlannerEdge::PlannerEdge().
const char Antipatrea::Constants::KW_Grid[] = "Grid"
const char Antipatrea::Constants::KW_GridNrDims[] = "NrDims"
const char Antipatrea::Constants::KW_GridMin[] = "Min"
const char Antipatrea::Constants::KW_GridMax[] = "Max"
const char Antipatrea::Constants::KW_GridDims[] = "Dims"
const char Antipatrea::Constants::KW_ReadFromFile[] = "ReadFromFile"
const char Antipatrea::Constants::KW_WriteToFile[] = "WriteToFile"
const char Antipatrea::Constants::KW_UseFile[] = "UseFile"