Antipatrea Namespace Reference
Antipatrea Namespace Reference
Namespaces
Algebra
Algebra2D
Algebra3D
BinarySearch
Binary search on a sorted array.
Constants
Keywords and default values.
DLHandler
Timer
Vector3Algebra
Functionality to measure various metrics on vectors in 3D.
Classes
class Allocator
Facilitates creating, deleting, and copying an array of values.
class Cfg
Configuration representation.
class CfgAcceptor
Interface for determining whether or not a given configuration is acceptable.
class CfgAcceptorBasedOnDistance
Motion-planning component which accepts a configuration only if it is within a user-defined distance from a target/goal configuration.
class CfgAcceptorBasedOnDistanceCompare
Used by STL priority queue implementation. The top of queue will be the cfg furthest away from the goal cfg.
class CfgAcceptorBasedOnEnergy
Motion-planning component which accepts a configuration only if its energy is below a user-defined threshold.
class CfgAcceptorBasedOnFixedMMC
Motion-planning component which accepts a configuration only if the difference in energy is below accepted based on a fixed temperature and a Metropolis test.
class CfgAcceptorBasedOnMMC
Motion-planning component which accepts a configuration only if the difference in energy is below accepted based on a temperature and a Metropolis test.
class CfgAcceptorChain2D
CfgAcceptorChain2D accepts a configuration iff the chain avoids self collisions and collisions with the obstacles in the scene.
class CfgAcceptorPoint2D
CfgAcceptorPoints2D accepts a configuration iff the point robot avoids collisions with the obstacles in the scene.
class CfgDistance
Interface for computing the distance between two configurations.
class CfgDistanceAtomRMSD
Defines the distance between two configurations as the least root mean square deviation (RMSD) between the backbone atoms.
class CfgDistanceLp
Defines the distance between two configurations as the Lp norm of the pairwise distances between configuration values.
class CfgEnergyEvaluator
Interface for computing the energy value of a configuration.
class CfgEnergyEvaluatorRosetta
Use Rosetta to evaluate the energy of the configuration.
class CfgForwardKinematics
Interface for computing the forward kinematics corresponding to the specified configuration values.
class CfgImprover
Interface for modifying a configuration to further improve it, e.g., via energy minimization.
class CfgImproverDoNothing
It does nothing; so no improvement – useful for settings where an improvement cannot be defined.
class CfgImproverRosetta
Use Rosetta to improve the energetic value of the configuration.
class CfgManager
Motion-planning component for managing configurations.
class CfgOffspringGenerator
Generate an offspring configuration near the parent configuration.
class CfgOffspringGeneratorByGaussianPerturbation
Generate an offspring configuration near the parent configuration by perturbing one or more values.
class CfgOffspringGeneratorRosetta
Use Rosetta/library to generate an offspring near the parent configuration.
class CfgOffspringGeneratorRosettaWBias
Use Rosetta/library to generate an offspring near the parent configuration.
class CfgOffspringGeneratorToTarget
Generate an offspring configuration along a path that starts at the parent configuration and reaches the specific target configuration.
class CfgOffspringGeneratorToTargetByLinearInterpolation
The offspring generator defines a path that starts at the parent configuration and reaches the target configuration by linearly interpolating the configuration values.
class CfgOffspringGeneratorTowardTarget
Interface for generating an offspring near a parent configuration and toward a target configuration.
class CfgProjector
Motion-planning component for managing and defining configuration projections.
class CfgProjectorChain2D
CfgProjectorChain2D computes the projection as the position of the end effector of the chain.
class CfgProjectorDeltaR
class CfgProjectorPoint2D
CfgProjectorPoint2D computes the projection as the position of the point robot.
class CfgProjectorUSREnergy
Use Rosetta to compute the USR projection of the configuration values.
class CfgSampler
Interface for configuration sampling.
class CfgSamplerPoint2D
Sample a point uniformly at random inside the bounding box of the scene.
class CfgSamplerRosetta
Use Rosetta to sample values for the configuration.
class CfgUniformSamplerInJointSpace
Sample a configuration by sampling each value at random from [-PI, PI].
class Chain2D
Forward kinematics for a chain in a 2D environment.
class Component
Base class for each motion-planning component.
class DeltaRRegion
class DisjointSet
class EdgeCostEvaluator
Interface for evaluating the direct and reverse cost of a path.
class EdgeCostEvaluatorBasedOnDistance
Edge cost is defined as the distance between the start and end configurations.
class EdgeCostEvaluatorBasedOnEnergy
Edge cost is defined as the change in energy between the start and end configurations.
class EdgeCostEvaluatorBasedOnMW
Edge cost is defined as the min(0,change in energy between the start and end configurations).
class EST
class ESTVertex
Vertex representation for EST.
class FELTR
Implement the FELTR algorithm. See IJRR (2010) Shehu, Olson Guiding the Search for Native-like Protein Conformations with an Ab-Initio Tree-based exploration and Olson, Molloy, Shehu In Search of the Protein Native State with a Probabilistic Sampling Approach (JBCC 2011).
class FELTRCell
Implement the FELTR algorithm. See IJRR (2010) Shehu, Olson Guiding the Search for Native-like Protein Conformations with an Ab-Initio Tree-based exploration and Olson, Molloy, Shehu In Search of the Protein Native State with a Probabilistic Sampling Approach (JBCC 2011).
class FELTRRegion
class FELTRVertex
Vertex representation for FELTR.
class Fragment
Store a single molecular fragment. A Fragment is a contiguous piece exised from an imaged protein (NMR or X-ray usually) where the represented consists of the PHI, PSI, and OMEGA backbone dihedral angles (an ideal geometry is assumed). An example use of a fragment would be to randomly perturb a known good (energetically feasible) protein by selecting a fragment from a library/db and substituting in the backbone angles and adjusting the protein (forward kinematics).
class FragmentDB
DB of Rosetta fragments for a set of a protein.
class GManagerRunPlanner2D
GUI for running a planner operating in a 2D scene.
class GManagerRunPlannerChain2D
GUI for running a planner for a chain operating in a 2D scene.
class GManagerRunPlannerPoint2D
GUI for running a planner for a point robot operating in a 2D scene.
class GraphSearch
class GraphSearchInfo
class Grid
struct HashStruct
struct HashStruct< char * >
struct HashStruct< char >
struct HashStruct< const char * >
struct HashStruct< const std::string >
struct HashStruct< int >
struct HashStruct< long >
struct HashStruct< short >
struct HashStruct< signed char >
struct HashStruct< std::pair< int, int > >
struct HashStruct< std::string >
struct HashStruct< unsigned char >
struct HashStruct< unsigned int >
struct HashStruct< unsigned long >
struct HashStruct< unsigned short >
class Heap
class Logger
class MolecularStructureRosetta
Forward kinematics for a molecular structure.
class Object
class Params
Class to facilitate setting of parameter values.
class PGT
Projection-Guided Tree (PGT).
class Planner
Interface for a planner which takes a planning problem, tries to solve it, and, if successful, provides a solution.
class PlannerEdge
Edge representation in the graph (roadmap or tree) constructed by a sampling-based motion planner.
class PlannerGraph
Representation of the undirected graph (roadmap or tree) constructed by a sampling-based motion planner.
class PlannerGraphSearchInfo
Wrapper for the planner graph so that it can be used with the graph searching alogrithms, e.g., DFS, BFS, A*, Dijkstra.
class PlannerProblem
The planning problem is defined by the initial configuration and a goal acceptor.
class PlannerSolution
Data structure to store the solution obtained by a motion planner.
class PlannerVertex
Vertex representation in the graph (roadmap or tree) constructed by a sampling-based motion planner.
class point
class PRM
Probabilistic RoadMap Method (PRM).
class Proximity
class ProximityBruteForce
class ProximityDefault
class ProximityGNAT
class ProximityQuery
class ProximityResults
class Reader
Interface for reading from an input stream.
class RosettaFragment
Store a set of Rosetta fragments (all of the same length and for the same position within the protein).
class RRT
Rapidly-exploring Random Tree (RRT).
class SamplingBasedPlanner
Interface for a sampling-based planner which explores the configuration space by sampling acceptable configurations, expanding branches, and connecting neighboring configurations.
class Scene2D
Scene2D is defined by its bounding box and the 2D obstacles it contains.
class Selector
Given items p1, p2, ..., pn with weights w1, w2, ..., wn, select item pi with probability wi / (w1 + ... + wn)
class Setup
Facilitate setting up the planning problem as well as the planner and its components.
class Setup2D
Facilitate setting up planning problems in 2D workspaces as well as the planner and its components.
class SetupChain2D
Setup the planning problem for a robot kinematic chain operating in a 2D scene as well as the planner and its components.
class SetupPoint2D
Setup the planning problem for a point robot operating in a 2D scene as well as the planner and its components.
class SetupRosetta
Setup the planning problem for a molecular structure based on Rosetta representation as well as the planner and its components.
class SignedDistanceBetweenTwoAngles
Interprets the values as angles and defines the signed distance as the signed length of the shortest arc.
class SignedDistanceBetweenTwoNumbers
Interprets the values as numbers and defines the signed distance as their difference.
class SignedDistanceBetweenTwoValues
Interface to define the signed distance between two values.
class Sprint
Implement methods to calculate motions between stable protein states. Based on work by Molloy et al (see BMC Structural Biology (2012) Molloy, Shehu, Elucidating the ensemble of functionally-relevant transitions in protein systems with a robotics-inspired method.
class SprintVertex
class Stats
class TreeSamplingBasedPlanner
Sampling-based planners that expand a tree in the configuration space.
class USRFactory
Produce the Ultrafast Shape Recognization (USR) coordinates.
class Writer
Interface for writing to an output stream.
Typedefs
typedef CfgAcceptor GoalAcceptor
Redefine CfgAcceptor as GoalAcceptor since the same class can be used for either purpose.
typedef std::pair< double, Cfg * > qObj
Object type used in a priority queue. Consists of the distance to the goal and a configuration ptr.
typedef CfgAcceptorBasedOnDistance GoalAcceptorBasedOnDistance
Redefine CfgAcceptorBasedOnDistance as GoalAcceptorBasedOnDistance since the same class can be used for either purpose.
typedef CfgAcceptorBasedOnEnergy GoalAcceptorBasedOnEnergy
Redefine CfgAcceptorBasedOnEnergy as GoalAcceptorBasedOnEnergy since the same class can be used for either purpose.
typedef Setup *(* CreateSetupFn) (void)
Pointer to function for creating a Setup instance.
typedef unsigned int Flags
Functions
ClassContainer (CfgAcceptor, m_cfgAcceptor)
Get/set methods for components that need access to CfgAcceptor.
ClassContainer (GoalAcceptor, m_goalAcceptor)
Get/set methods for components that need access to GoalAcceptor.
ClassContainer (CfgAcceptorBasedOnDistance, m_cfgAcceptorBasedOnDistance)
Get/set methods for components that need access to CfgAcceptorBasedOnDistance.
ClassContainer (GoalAcceptorBasedOnDistance, m_goalAcceptorBasedOnDistance)
Get/set methods for components that need access to GoalAcceptorBasedOnDistance.
ClassContainer (CfgAcceptorBasedOnEnergy, m_cfgAcceptorBasedOnEnergy)
Get/set methods for components that need access to CfgAcceptorBasedOnEnergy.
ClassContainer (GoalAcceptorBasedOnEnergy, m_goalAcceptorBasedOnEnergy)
Get/set methods for components that need access to GoalAcceptorBasedOnEnergy.
ClassContainer (CfgAcceptorBasedOnFixedMMC, m_cfgAcceptorBasedOnFixedMMC)
Get/set methods for components that need access to CfgAcceptorBasedOnFixedMMC.
ClassContainer (CfgAcceptorBasedOnMMC, m_cfgAcceptorBasedOnMMC)
Get/set methods for components that need access to CfgAcceptorBasedOnMMC.
ClassContainer (CfgDistance, m_cfgDistance)
Get/set methods for components that need access to CfgDistance.
ClassContainer (CfgDistanceLp, m_cfgDistanceLp)
Get/set methods for components that need access to CfgDistanceLp.
ClassContainer (SignedDistanceBetweenTwoAngles, m_signedDistanceAngle)
Get/set methods for components that need access to SignedDistanceBetweenTwoAngles.
ClassContainer (SignedDistanceBetweenTwoNumbers, m_signedDistanceNumber)
Get/set methods for components that need access to SignedDistanceBetweenTwoNumbers.
ClassContainer (SignedDistanceBetweenTwoValues, m_signedDistanceValue)
Get/set methods for components that need access to SignedDistanceBetweenTwoValues.
ClassContainer (CfgEnergyEvaluator, m_cfgEnergyEvaluator)
Get/set methods for components that need access to CfgEnergyEvaluator.
ClassContainer (CfgForwardKinematics, m_cfgForwardKinematics)
Get/set methods for components that need access to CfgForwardKinematics.
ClassContainer (CfgImprover, m_cfgImprover)
Get/set methods for components that need access to CfgImprover.
ClassContainer (CfgImproverDoNothing, m_cfgImproverDoNothing)
Get/set methods for components that need access to CfgImproverDoNothing.
ClassContainer (CfgManager, m_cfgManager)
Get/set methods for components that need access to CfgManager.
ClassContainer (CfgOffspringGenerator, m_cfgOffspringGenerator)
Get/set methods for components that need access to CfgOffspringGenerator.
ClassContainer (CfgOffspringGeneratorByGaussianPerturbation, m_cfgOffspringGeneratorByGaussianPerturbation)
Get/set methods for components that need access to CfgOffspringGeneratorByGaussianPerturbation.
ClassContainer (CfgOffspringGeneratorToTarget, m_cfgOffspringGeneratorToTarget)
Get/set methods for components that need access to CfgOffspringGeneratorToTarget.
ClassContainer (CfgOffspringGeneratorToTargetByLinearInterpolation, m_cfgOffspringGeneratorToTargetByLinearInterpolation)
Get/set methods for components that need access to CfgOffspringGeneratorToTargetByLinearInterpolation.
ClassContainer (CfgOffspringGeneratorTowardTarget, m_cfgOffspringGeneratorTowardTarget)
Get/set methods for components that need access to CfgOffspringGeneratorTowardTarget.
ClassContainer (CfgProjector, m_cfgProjector)
Get/set methods for components that need access to CfgProjector.
ClassContainer (CfgSampler, m_cfgSampler)
Get/set methods for components that need access to CfgSampler.
ClassContainer (CfgUniformSamplerInJointSpace, m_cfgUniformSamplerInJointSpace)
Get/set methods for components that need access to CfgUniformSamplerInJointSpace.
ClassContainer (EdgeCostEvaluator, m_edgeCostEvaluator)
Get/set methods for components that need access to EdgeCostEvaluator.
ClassContainer (EdgeCostEvaluatorBasedOnDistance, m_edgeCostEvaluatorBasedOnDistance)
Get/set methods for components that need access to EdgeCostEvaluatorBasedOnDistance.
ClassContainer (EdgeCostEvaluatorBasedOnEnergy, m_edgeCostEvaluatorBasedOnEnergy)
Get/set methods for components that need access to EdgeCostEvaluatorBasedOnEnergy.
ClassContainer (EdgeCostEvaluatorBasedOnMW, m_edgeCostEvaluatorBasedOnMW)
Get/set methods for components that need access to EdgeCostEvaluatorBasedOnEnergy.
ClassContainer (EST, m_est)
Get/set methods for components that need access to EST.
double get_constrained_R0 (int nres)
ClassContainer (PGT, m_pgt)
Get/set methods for components that need access to PGT.
ClassContainer (Planner, m_planner)
Get/set methods for components that need access to Planner.
ClassContainer (PlannerGraph, m_plannerGraph)
Get/set methods for components that need access to PlannerGraph.
ClassContainer (PlannerProblem, m_plannerProblem)
Get/set methods for components that need access to PlannerProblem.
ClassContainer (PlannerSolution, m_plannerSolution)
Get/set methods for components that need access to PlannerSolution.
ClassContainer (PRM, m_prm)
Get/set methods for components that need access to PRM.
ClassContainer (RRT, m_rrt)
Get/set methods for components that need access to RRT.
ClassContainer (SamplingBasedPlanner, m_samplingBasedPlanner)
Get/set methods for components that need access to SamplingBasedPlanner.
ClassContainer (TreeSamplingBasedPlanner, m_treeSamplingBasedPlanner)
Get/set methods for components that need access to TreeSamplingBasedPlanner.
ClassContainer (CfgAcceptorChain2D, m_cfgAcceptorChain2D)
Get/set methods for components that need access to CfgAcceptorChain2D.
ClassContainer (CfgAcceptorPoint2D, m_cfgAcceptorPoint2D)
Get/set methods for components that need access to CfgAcceptorPoint2D.
ClassContainer (CfgProjectorChain2D, m_cfgProjectorChain2D)
Get/set methods for components that need access to CfgProjectorChain2D.
ClassContainer (CfgProjectorPoint2D, m_cfgProjectorPoint2D)
Get/set methods for components that need access to CfgProjectorPoint2D.
ClassContainer (CfgSamplerPoint2D, m_cfgSamplerPoint2D)
Get/set methods for components that need access to CfgSamplerPoint2D.
ClassContainer (Chain2D, m_chain2D)
Get/set methods for components that need access to Chain2D.
ClassContainer (Scene2D, m_scene2D)
Get/set methods for components that need access to Scene2D.
ClassContainer (CfgDistanceAtomRMSD, m_cfgDistanceAtomRMSD)
ClassContainer (CfgEnergyEvaluatorRosetta, m_cfgEnergyEvaluatorRosetta)
Get/set methods for components that need access to CfgEnergyEvaluatorRosetta.
ClassContainer (CfgImproverRosetta, m_cfgImproverRosetta)
Get/set methods for components that need access to CfgImproverRosetta.
ClassContainer (CfgOffspringGeneratorRosetta, m_cfgOffspringGeneratorRosetta)
Get/set methods for components that need access to CfgOffspringGeneratorRosetta.
ClassContainer (CfgOffspringGeneratorRosettaWBias, m_cfgOffspringGeneratorRosettaWBias)
Get/set methods for components that need access to CfgOffspringGeneratorRosetta.
ClassContainer (CfgProjectorDeltaR, m_cfgProjectorDeltaR)
Get/set methods for components that need access to CfgProjectorDeltaR.
ClassContainer (CfgProjectorUSREnergy, m_cfgProjectorUSREnergy)
Get/set methods for components that need access to CfgProjectorUSR.
ClassContainer (CfgSamplerRosetta, m_cfgSamplerRosetta)
Get/set methods for components that need access to CfgSamplerRosetta.
ClassContainer (MolecularStructureRosetta, m_molecularStructureRosetta)
Get/set methods for components that need access to MolecularStructureRosetta.
static double usrSimilarity (const double *p1, const double *p2, const int size)
static bool HasFlag (const Flags f, const Flags b)
static Flags AddFlag (const Flags f, const Flags b)
static Flags RemoveFlag (const Flags f, const Flags b)
static Flags RemoveAndAddFlag (const Flags f, const Flags rem, const Flags add)
static Flags FlipFlag (const Flags f, const Flags b)
static void TriangleAsPolygon2D (const double tA[2], const double tB[2], const double tC[2], double poly[6])
static void AABoxAsPolygon2D (const double minx, const double miny, const double maxx, const double maxy, double poly[8])
static void AABoxAsPolygon2D (const double min[2], const double max[2], double poly[8])
static void QuadAsPolygon2D (const double qA[2], const double qB[2], const double qC[2], const double qD[2], double poly[8])
void CircleAsPolygon2D (const double cx, const double cy, const double r, const int n, double poly[])
double DistanceSquaredPointLine2D (const double p[2], const double s0[2], const double s1[2], double pmin[2])
double DistanceSquaredPointSegment2D (const double p[2], const double s0[2], const double s1[2], double pmin[2])
double DistanceSquaredPointPolygon2D (const double p[2], const int n, const double poly[], double pmin[2])
double DistanceSquaredSegments2D (const double p1[2], const double p2[2], const double p3[2], const double p4[2], double pmin1[2], double pmin2[2])
double DistanceSquaredSegmentPolygon2D (const double p1[2], const double p2[2], const int n, const double poly[], double pmin1[2], double pmin2[2])
double DistanceSquaredPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[], double pmin1[2], double pmin2[2])
bool IntersectLines2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y, double *const mua, double *const mub)
static bool IntersectLineRay2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y)
static bool IntersectLineSegment2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y)
static bool IntersectRays2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y)
static bool IntersectRaySegment2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y)
static bool IntersectSegments2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y)
static bool IntersectSegments2D (const double p1[2], const double p2[2], const double p3[2], const double p4[2], double *const p)
bool IntersectSegments2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4)
static bool IntersectSegments2D (const double p1[2], const double p2[2], const double p3[2], const double p4[2])
bool IntersectSegmentPolygon2D (const double p0[2], const double p1[2], const int n, const double poly[])
bool IntersectPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[])
int IntersectLineAABox2D (const double x1, const double y1, const double x2, const double y2, const double minx, const double miny, const double maxx, const double maxy, double *const interx1, double *const intery1, double *const interx2, double *const intery2)
static double Turn2D (const double p0[2], const double p1[2], const double p2[2])
static bool IsPointLeftOfLine2D (const double p[2], const double p0[2], const double p1[2])
static bool IsPointInsideTriangle2D (const double p[2], const double tA[2], const double tB[2], const double tC[2])
static bool IsPointInsideAABox2D (const double p[2], const double min[2], const double max[2])
bool IsPointInsideConvexPolygon2D (const double p[2], const int n, const double poly[])
bool IsPointInsidePolygon2D (const double p[2], const int n, const double poly[])
static bool IsPointInsideCircle2D (const double p[2], const double cx, const double cy, const double r)
static bool IsAABoxInsideAABox2D (const double min[2], const double max[2], const double min2[2], const double max2[2])
bool IsPolygonInsideAABox2D (const int n, const double poly[], const double min[2], const double max[2])
bool IsPolygonInsideConvexPolygon2D (const int n1, const double poly1[], const int n2, const double poly2[])
bool IsPolygonInsidePolygon2D (const int n1, const double poly1[], const int n2, const double poly2[], const bool checkIntersection=true)
bool IsPolygonInsideCircle2D (const int n, const double poly[], const double cx, const double cy, const double r)
static bool CollisionSegmentConvexPolygon2D (const double p0[2], const double p1[2], const int n, const double poly[])
static bool CollisionPolygonConvexPolygon2D (const int n1, const double poly1[], const int n2, const double poly2[])
static bool CollisionConvexPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[])
static bool CollisionSegmentPolygon2D (const double p0[2], const double p1[2], const int n, const double poly[])
static bool CollisionPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[])
static bool CollisionAABoxes2D (const double min1[2], const double max1[2], const double min2[2], const double max2[2])
double SignedAreaPolygon2D (const int n, const double poly[])
void BoundingBoxPolygon2D (const int n, const double poly[], double min[2], double max[2])
static void BoundingBoxCircle2D (const double center[2], const double r, double min[2], double max[2])
void ChangeOrientationPolygon2D (const int n, double poly[])
bool IsConvexPolygonCCW2D (const int n, const double poly[])
static bool IsPolygonCCW2D (const int n, const double poly[])
static void MakeConvexPolygonCCW2D (const int n, double poly[])
static void MakePolygonCCW2D (const int n, double poly[])
bool IsPolygonConvex2D (const int n, const double poly[])
void PolygonCentroid2D (const int n, const double poly[], double centroid[2])
int TriangulateConvexPolygon2D (const int n, const double poly[], int triangles[])
void SampleRandomPointInsideAABox2D (const double min[2], const double max[2], double p[2])
void SampleRandomPointInsideTriangle2D (const double tA[2], const double tB[2], const double tC[2], double p[2])
void SampleRandomPointInsideConvexPolygon2D (const int n, const double poly[], double p[2], const double min[2]=NULL, const double max[2]=NULL)
void SampleRandomPointInsidePolygon2D (const int n, const double poly[], double p[2], const double min[2]=NULL, const double max[2]=NULL)
void SampleRandomPointInsideCircle2D (const double center[2], const double r, double p[2])
void ApplyTransRotToPolygon2D (const double TR[], const int n, const double origPoly[], double newPoly[])
size_t StringHash (const char *s, const int n)
static void ToLower (char s[])
static void ToUpper (char s[])
static double StrToDouble (const char s[])
static long int StrToInt (const char s[])
static bool StrToBool (const char s[])
static bool StrSameContent (const char s1[], const char s2[])
template<typename Item >
static Item * AllocArray (const int n)
template<typename Item >
static void FreeArray (Item a[])
template<typename Item >
static void CopyArray (Item dest[], const int n, const Item src[])
template<typename Item >
static void DeleteItems (const int n, Item items[])
template<typename Item >
static void DeleteItems (std::vector< Item > &items)
template<typename Item >
static int FindItem (const int n, const Item items[], const Item &item)
template<typename Item >
static int FindItem (const std::vector< Item > &items, const Item &item)
template<typename Item >
static void ReverseItems (const int n, Item items[])
template<typename Item >
static void ReverseItems (std::vector< Item > &items)
template<typename Item >
static void PermuteItems (const int n, Item items[], const int r)
Generate a random subset of r out of n elements.
template<typename Item >
static void PermuteItems (std::vector< Item > &items, const int r)
Generate a random subset of r elements out of the elements in the vector items.
template<typename Type >
static bool NextPermutation (const int n, Type items[])
Generate the next permutation in the lexicographic order.
static bool NextCombination (const int n, int combo[], const int r)
static bool NextGroupCombination (const int n, int vals[], const int max[])
static void OutputFormat (std::ostream &out)
void RandomPointOnSphereSurface (const int nrDims, const double center[], const double r, double p[])
void RandomPointInsideSphere (const int nrDims, const double center[], const double r, double p[])
void RandomPointOnEllipsoidSurface (const int nrDims, const double center[], const double radii[], double p[])
void RandomPointInsideEllipsoid (const int nrDims, const double center[], const double radii[], double p[])
Seed the random number generator
void RandomSeed (const unsigned int s)
Set the seed for the random number generator.
unsigned int RandomSeed (void)
Generate and set the seed for the random number generator.
Generate real numbers uniformly at random
static double RandomUniformReal (void)
Generate a real number uniformly at random from the interval [0, 1]
static double RandomUniformReal (const double min, const double max)
Generate a real number uniformly at random from the interval [min, max]
Generate integers uniformly at random
static long RandomUniformInteger (const long min, const long max)
Generate an integer number uniformly at random from the interval [min, max]
Generate boolean values uniformly at random
static bool RandomUniformBoolean (void)
Generate either true or false uniformly at random.
Generate real values from gaussian distributions
double RandomGaussianReal (const double mean, const double stddev)
Generate a number at random from the Gaussian distribution with mean mean and standard deviation stddev
Variables
const double CA_CA_IDEAL_D =3.8
const int DELTAR_PROJDIM = 1
Compute DeltaR distance.
const point undefPoint (UNDEF_COORD, UNDEF_COORD, UNDEF_COORD)
Typedef Documentation
GoalAcceptor
typedef CfgAcceptor Antipatrea::GoalAcceptor
Redefine CfgAcceptor as GoalAcceptor since the same class can be used for either purpose.
Author
Erion Plaku, Amarda Shehu
qObj
typedef std::pair<double,Cfg *> Antipatrea::qObj
Object type used in a priority queue. Consists of the distance to the goal and a configuration ptr.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
GoalAcceptorBasedOnDistance
typedef CfgAcceptorBasedOnDistance Antipatrea::GoalAcceptorBasedOnDistance
Redefine CfgAcceptorBasedOnDistance as GoalAcceptorBasedOnDistance since the same class can be used for either purpose.
Author
Erion Plaku, Amarda Shehu
GoalAcceptorBasedOnEnergy
typedef CfgAcceptorBasedOnEnergy Antipatrea::GoalAcceptorBasedOnEnergy
Redefine CfgAcceptorBasedOnEnergy as GoalAcceptorBasedOnEnergy since the same class can be used for either purpose.
Author
Erion Plaku, Amarda Shehu
CreateSetupFn
typedef Setup*(* Antipatrea::CreateSetupFn) (void)
Pointer to function for creating a Setup instance.
Author
Erion Plaku, Amarda Shehu
Flags
typedef unsigned int Antipatrea::Flags
Function Documentation
ClassContainer() [1/56]
Antipatrea::ClassContainer (CfgAcceptor , m_cfgAcceptor)
Get/set methods for components that need access to CfgAcceptor.
Author
Erion Plaku, Amarda Shehu
Referenced by Antipatrea::CfgDistance::DistancePrint(), Antipatrea::EdgeCostEvaluatorBasedOnDistance::EvaluateGivenFromToCfgs(), Antipatrea::CfgImproverDoNothing::Improve(), Antipatrea::CfgUniformSamplerInJointSpace::Info(), Antipatrea::EdgeCostEvaluatorBasedOnMW::Info(), Antipatrea::CfgProjectorChain2D::Info(), Antipatrea::CfgSamplerRosetta::Info(), Antipatrea::CfgEnergyEvaluatorRosetta::Info(), Antipatrea::CfgImproverRosetta::Info(), Antipatrea::Planner::Info(), Antipatrea::EdgeCostEvaluatorBasedOnEnergy::Info(), Antipatrea::CfgAcceptorChain2D::Info(), Antipatrea::CfgOffspringGeneratorToTargetByLinearInterpolation::Info(), Antipatrea::CfgAcceptorPoint2D::IsAcceptable(), Antipatrea::CfgProjectorPoint2D::Project(), Antipatrea::CfgSamplerPoint2D::Sample(), Antipatrea::CfgProjector::SetupFromParams(), Antipatrea::SignedDistanceBetweenTwoNumbers::SignedDistance(), Antipatrea::SignedDistanceBetweenTwoAngles::SignedDistance(), Antipatrea::CfgEnergyEvaluator::~CfgEnergyEvaluator(), Antipatrea::CfgImprover::~CfgImprover(), Antipatrea::CfgOffspringGeneratorRosettaWBias::~CfgOffspringGeneratorRosettaWBias(), Antipatrea::CfgOffspringGeneratorToTarget::~CfgOffspringGeneratorToTarget(), Antipatrea::CfgSampler::~CfgSampler(), Antipatrea::RRT::~RRT(), and Antipatrea::SignedDistanceBetweenTwoValues::~SignedDistanceBetweenTwoValues().
ClassContainer() [2/56]
Antipatrea::ClassContainer (GoalAcceptor , m_goalAcceptor)
Get/set methods for components that need access to GoalAcceptor.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [3/56]
Antipatrea::ClassContainer (CfgAcceptorBasedOnDistance , m_cfgAcceptorBasedOnDistance)
Get/set methods for components that need access to CfgAcceptorBasedOnDistance.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [4/56]
Antipatrea::ClassContainer (GoalAcceptorBasedOnDistance , m_goalAcceptorBasedOnDistance)
Get/set methods for components that need access to GoalAcceptorBasedOnDistance.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [5/56]
Antipatrea::ClassContainer (CfgAcceptorBasedOnEnergy , m_cfgAcceptorBasedOnEnergy)
Get/set methods for components that need access to CfgAcceptorBasedOnEnergy.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [6/56]
Antipatrea::ClassContainer (GoalAcceptorBasedOnEnergy , m_goalAcceptorBasedOnEnergy)
Get/set methods for components that need access to GoalAcceptorBasedOnEnergy.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [7/56]
Antipatrea::ClassContainer (CfgAcceptorBasedOnFixedMMC , m_cfgAcceptorBasedOnFixedMMC)
Get/set methods for components that need access to CfgAcceptorBasedOnFixedMMC.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [8/56]
Antipatrea::ClassContainer (CfgAcceptorBasedOnMMC , m_cfgAcceptorBasedOnMMC)
Get/set methods for components that need access to CfgAcceptorBasedOnMMC.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [9/56]
Antipatrea::ClassContainer (CfgDistance , m_cfgDistance)
Get/set methods for components that need access to CfgDistance.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [10/56]
Antipatrea::ClassContainer (CfgDistanceLp , m_cfgDistanceLp)
Get/set methods for components that need access to CfgDistanceLp.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [11/56]
Antipatrea::ClassContainer (SignedDistanceBetweenTwoAngles , m_signedDistanceAngle)
Get/set methods for components that need access to SignedDistanceBetweenTwoAngles.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [12/56]
Antipatrea::ClassContainer (SignedDistanceBetweenTwoNumbers , m_signedDistanceNumber)
Get/set methods for components that need access to SignedDistanceBetweenTwoNumbers.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [13/56]
Antipatrea::ClassContainer (SignedDistanceBetweenTwoValues , m_signedDistanceValue)
Get/set methods for components that need access to SignedDistanceBetweenTwoValues.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [14/56]
Antipatrea::ClassContainer (CfgEnergyEvaluator , m_cfgEnergyEvaluator)
Get/set methods for components that need access to CfgEnergyEvaluator.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [15/56]
Antipatrea::ClassContainer (CfgForwardKinematics , m_cfgForwardKinematics)
Get/set methods for components that need access to CfgForwardKinematics.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [16/56]
Antipatrea::ClassContainer (CfgImprover , m_cfgImprover)
Get/set methods for components that need access to CfgImprover.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [17/56]
Antipatrea::ClassContainer (CfgImproverDoNothing , m_cfgImproverDoNothing)
Get/set methods for components that need access to CfgImproverDoNothing.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [18/56]
Antipatrea::ClassContainer (CfgManager , m_cfgManager)
Get/set methods for components that need access to CfgManager.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [19/56]
Antipatrea::ClassContainer (CfgOffspringGenerator , m_cfgOffspringGenerator)
Get/set methods for components that need access to CfgOffspringGenerator.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [20/56]
Antipatrea::ClassContainer (CfgOffspringGeneratorByGaussianPerturbation , m_cfgOffspringGeneratorByGaussianPerturbation)
Get/set methods for components that need access to CfgOffspringGeneratorByGaussianPerturbation.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [21/56]
Antipatrea::ClassContainer (CfgOffspringGeneratorToTarget , m_cfgOffspringGeneratorToTarget)
Get/set methods for components that need access to CfgOffspringGeneratorToTarget.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [22/56]
Antipatrea::ClassContainer (CfgOffspringGeneratorToTargetByLinearInterpolation , m_cfgOffspringGeneratorToTargetByLinearInterpolation)
Get/set methods for components that need access to CfgOffspringGeneratorToTargetByLinearInterpolation.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [23/56]
Antipatrea::ClassContainer (CfgOffspringGeneratorTowardTarget , m_cfgOffspringGeneratorTowardTarget)
Get/set methods for components that need access to CfgOffspringGeneratorTowardTarget.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [24/56]
Antipatrea::ClassContainer (CfgProjector , m_cfgProjector)
Get/set methods for components that need access to CfgProjector.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [25/56]
Antipatrea::ClassContainer (CfgSampler , m_cfgSampler)
Get/set methods for components that need access to CfgSampler.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [26/56]
Antipatrea::ClassContainer (CfgUniformSamplerInJointSpace , m_cfgUniformSamplerInJointSpace)
Get/set methods for components that need access to CfgUniformSamplerInJointSpace.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [27/56]
Antipatrea::ClassContainer (EdgeCostEvaluator , m_edgeCostEvaluator)
Get/set methods for components that need access to EdgeCostEvaluator.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [28/56]
Antipatrea::ClassContainer (EdgeCostEvaluatorBasedOnDistance , m_edgeCostEvaluatorBasedOnDistance)
Get/set methods for components that need access to EdgeCostEvaluatorBasedOnDistance.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [29/56]
Antipatrea::ClassContainer (EdgeCostEvaluatorBasedOnEnergy , m_edgeCostEvaluatorBasedOnEnergy)
Get/set methods for components that need access to EdgeCostEvaluatorBasedOnEnergy.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [30/56]
Antipatrea::ClassContainer (EdgeCostEvaluatorBasedOnMW , m_edgeCostEvaluatorBasedOnMW)
Get/set methods for components that need access to EdgeCostEvaluatorBasedOnEnergy.
Author
Erion Plaku, Amarda Shehu, Kevin Molloy
ClassContainer() [31/56]
Antipatrea::ClassContainer (EST , m_est)
Get/set methods for components that need access to EST.
Author
Erion Plaku, Amarda Shehu
get_constrained_R0()
double Antipatrea::get_constrained_R0 (int nres)
Referenced by Antipatrea::FELTRRegion::FELTRRegion().
ClassContainer() [32/56]
Antipatrea::ClassContainer (PGT , m_pgt)
Get/set methods for components that need access to PGT.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [33/56]
Antipatrea::ClassContainer (Planner , m_planner)
Get/set methods for components that need access to Planner.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [34/56]
Antipatrea::ClassContainer (PlannerGraph , m_plannerGraph)
Get/set methods for components that need access to PlannerGraph.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [35/56]
Antipatrea::ClassContainer (PlannerProblem , m_plannerProblem)
Get/set methods for components that need access to PlannerProblem.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [36/56]
Antipatrea::ClassContainer (PlannerSolution , m_plannerSolution)
Get/set methods for components that need access to PlannerSolution.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [37/56]
Antipatrea::ClassContainer (PRM , m_prm)
Get/set methods for components that need access to PRM.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [38/56]
Antipatrea::ClassContainer (RRT , m_rrt)
Get/set methods for components that need access to RRT.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [39/56]
Antipatrea::ClassContainer (SamplingBasedPlanner , m_samplingBasedPlanner)
Get/set methods for components that need access to SamplingBasedPlanner.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [40/56]
Antipatrea::ClassContainer (TreeSamplingBasedPlanner , m_treeSamplingBasedPlanner)
Get/set methods for components that need access to TreeSamplingBasedPlanner.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [41/56]
Antipatrea::ClassContainer (CfgAcceptorChain2D , m_cfgAcceptorChain2D)
Get/set methods for components that need access to CfgAcceptorChain2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [42/56]
Antipatrea::ClassContainer (CfgAcceptorPoint2D , m_cfgAcceptorPoint2D)
Get/set methods for components that need access to CfgAcceptorPoint2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [43/56]
Antipatrea::ClassContainer (CfgProjectorChain2D , m_cfgProjectorChain2D)
Get/set methods for components that need access to CfgProjectorChain2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [44/56]
Antipatrea::ClassContainer (CfgProjectorPoint2D , m_cfgProjectorPoint2D)
Get/set methods for components that need access to CfgProjectorPoint2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [45/56]
Antipatrea::ClassContainer (CfgSamplerPoint2D , m_cfgSamplerPoint2D)
Get/set methods for components that need access to CfgSamplerPoint2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [46/56]
Antipatrea::ClassContainer (Chain2D , m_chain2D)
Get/set methods for components that need access to Chain2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [47/56]
Antipatrea::ClassContainer (Scene2D , m_scene2D)
Get/set methods for components that need access to Scene2D.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [48/56]
Antipatrea::ClassContainer (CfgDistanceAtomRMSD , m_cfgDistanceAtomRMSD)
ClassContainer() [49/56]
Antipatrea::ClassContainer (CfgEnergyEvaluatorRosetta , m_cfgEnergyEvaluatorRosetta)
Get/set methods for components that need access to CfgEnergyEvaluatorRosetta.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [50/56]
Antipatrea::ClassContainer (CfgImproverRosetta , m_cfgImproverRosetta)
Get/set methods for components that need access to CfgImproverRosetta.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [51/56]
Antipatrea::ClassContainer (CfgOffspringGeneratorRosetta , m_cfgOffspringGeneratorRosetta)
Get/set methods for components that need access to CfgOffspringGeneratorRosetta.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [52/56]
Antipatrea::ClassContainer (CfgOffspringGeneratorRosettaWBias , m_cfgOffspringGeneratorRosettaWBias)
Get/set methods for components that need access to CfgOffspringGeneratorRosetta.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [53/56]
Antipatrea::ClassContainer (CfgProjectorDeltaR , m_cfgProjectorDeltaR)
Get/set methods for components that need access to CfgProjectorDeltaR.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [54/56]
Antipatrea::ClassContainer (CfgProjectorUSREnergy , m_cfgProjectorUSREnergy)
Get/set methods for components that need access to CfgProjectorUSR.
Author
Erion Plaku, Amarda Shehu
ClassContainer() [55/56]
Antipatrea::ClassContainer (CfgSamplerRosetta , m_cfgSamplerRosetta)
Get/set methods for components that need access to CfgSamplerRosetta.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
ClassContainer() [56/56]
Antipatrea::ClassContainer (MolecularStructureRosetta , m_molecularStructureRosetta)
Get/set methods for components that need access to MolecularStructureRosetta.
Author
Erion Plaku, Amarda Shehu
usrSimilarity()
static double Antipatrea::usrSimilarity (const double * p1, const double * p2, const int size) inline static
HasFlag()
static bool Antipatrea::HasFlag (const Flags f, const Flags b) inline static
Referenced by Antipatrea::CfgForwardKinematics::FK().
AddFlag()
static Flags Antipatrea::AddFlag (const Flags f, const Flags b) inline static
Referenced by Antipatrea::CfgForwardKinematics::OnValuesChanged().
RemoveFlag()
static Flags Antipatrea::RemoveFlag (const Flags f, const Flags b) inline static
Referenced by Antipatrea::CfgForwardKinematics::FK().
RemoveAndAddFlag()
static Flags Antipatrea::RemoveAndAddFlag (const Flags f, const Flags rem, const Flags add) inline static
FlipFlag()
static Flags Antipatrea::FlipFlag (const Flags f, const Flags b) inline static
TriangleAsPolygon2D()
static void Antipatrea::TriangleAsPolygon2D (const double tA[2], const double tB[2], const double tC[2], double poly[6]) inline static
AABoxAsPolygon2D() [1/2]
static void Antipatrea::AABoxAsPolygon2D (const double minx, const double miny, const double maxx, const double maxy, double poly[8]) inline static
AABoxAsPolygon2D() [2/2]
static void Antipatrea::AABoxAsPolygon2D (const double min[2], const double max[2], double poly[8]) inline static
QuadAsPolygon2D()
static void Antipatrea::QuadAsPolygon2D (const double qA[2], const double qB[2], const double qC[2], const double qD[2], double poly[8]) inline static
References CircleAsPolygon2D(), DistanceSquaredPointLine2D(), DistanceSquaredPointPolygon2D(), DistanceSquaredPointSegment2D(), DistanceSquaredPolygons2D(), DistanceSquaredSegmentPolygon2D(), DistanceSquaredSegments2D(), and IntersectLines2D().
CircleAsPolygon2D()
void Antipatrea::CircleAsPolygon2D (const double cx, const double cy, const double r, const int n, double poly[])
Referenced by QuadAsPolygon2D().
DistanceSquaredPointLine2D()
double Antipatrea::DistanceSquaredPointLine2D (const double p[2], const double s0[2], const double s1[2], double pmin[2])
Referenced by QuadAsPolygon2D().
DistanceSquaredPointSegment2D()
double Antipatrea::DistanceSquaredPointSegment2D (const double p[2], const double s0[2], const double s1[2], double pmin[2])
Referenced by QuadAsPolygon2D().
DistanceSquaredPointPolygon2D()
double Antipatrea::DistanceSquaredPointPolygon2D (const double p[2], const int n, const double poly[], double pmin[2])
Referenced by QuadAsPolygon2D().
DistanceSquaredSegments2D()
double Antipatrea::DistanceSquaredSegments2D (const double p1[2], const double p2[2], const double p3[2], const double p4[2], double pmin1[2], double pmin2[2])
Referenced by QuadAsPolygon2D().
DistanceSquaredSegmentPolygon2D()
double Antipatrea::DistanceSquaredSegmentPolygon2D (const double p1[2], const double p2[2], const int n, const double poly[], double pmin1[2], double pmin2[2])
Referenced by QuadAsPolygon2D().
DistanceSquaredPolygons2D()
double Antipatrea::DistanceSquaredPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[], double pmin1[2], double pmin2[2])
Referenced by QuadAsPolygon2D().
IntersectLines2D()
bool Antipatrea::IntersectLines2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y, double *const mua, double *const mub)
Referenced by IntersectLineRay2D(), IntersectLineSegment2D(), IntersectRays2D(), IntersectRaySegment2D(), IntersectSegments2D(), and QuadAsPolygon2D().
IntersectLineRay2D()
static bool Antipatrea::IntersectLineRay2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y) inline static
References IntersectLines2D().
IntersectLineSegment2D()
static bool Antipatrea::IntersectLineSegment2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y) inline static
References IntersectLines2D().
IntersectRays2D()
static bool Antipatrea::IntersectRays2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y) inline static
References IntersectLines2D().
IntersectRaySegment2D()
static bool Antipatrea::IntersectRaySegment2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y) inline static
References IntersectLines2D().
IntersectSegments2D() [1/4]
static bool Antipatrea::IntersectSegments2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4, double *const x, double *const y) inline static
References IntersectLines2D().
Referenced by IntersectSegments2D().
IntersectSegments2D() [2/4]
static bool Antipatrea::IntersectSegments2D (const double p1[2], const double p2[2], const double p3[2], const double p4[2], double *const p) inline static
References IntersectSegments2D().
IntersectSegments2D() [3/4]
bool Antipatrea::IntersectSegments2D (const double x1, const double y1, const double x2, const double y2, const double x3, const double y3, const double x4, const double y4)
IntersectSegments2D() [4/4]
static bool Antipatrea::IntersectSegments2D (const double p1[2], const double p2[2], const double p3[2], const double p4[2]) inline static
References IntersectLineAABox2D(), IntersectPolygons2D(), IntersectSegmentPolygon2D(), and IntersectSegments2D().
IntersectSegmentPolygon2D()
bool Antipatrea::IntersectSegmentPolygon2D (const double p0[2], const double p1[2], const int n, const double poly[])
Referenced by CollisionSegmentConvexPolygon2D(), CollisionSegmentPolygon2D(), and IntersectSegments2D().
IntersectPolygons2D()
bool Antipatrea::IntersectPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[])
Referenced by CollisionConvexPolygons2D(), CollisionPolygonConvexPolygon2D(), CollisionPolygons2D(), and IntersectSegments2D().
IntersectLineAABox2D()
int Antipatrea::IntersectLineAABox2D (const double x1, const double y1, const double x2, const double y2, const double minx, const double miny, const double maxx, const double maxy, double *const interx1, double *const intery1, double *const interx2, double *const intery2)
Referenced by IntersectSegments2D().
Turn2D()
static double Antipatrea::Turn2D (const double p0[2], const double p1[2], const double p2[2]) inline static
Referenced by IsPointLeftOfLine2D().
IsPointLeftOfLine2D()
static bool Antipatrea::IsPointLeftOfLine2D (const double p[2], const double p0[2], const double p1[2]) inline static
References Turn2D().
Referenced by IsPointInsideTriangle2D().
IsPointInsideTriangle2D()
static bool Antipatrea::IsPointInsideTriangle2D (const double p[2], const double tA[2], const double tB[2], const double tC[2]) inline static
References IsPointLeftOfLine2D().
IsPointInsideAABox2D()
static bool Antipatrea::IsPointInsideAABox2D (const double p[2], const double min[2], const double max[2]) inline static
References IsPointInsideConvexPolygon2D(), and IsPointInsidePolygon2D().
IsPointInsideConvexPolygon2D()
bool Antipatrea::IsPointInsideConvexPolygon2D (const double p[2], const int n, const double poly[])
Referenced by CollisionConvexPolygons2D(), CollisionPolygonConvexPolygon2D(), CollisionSegmentConvexPolygon2D(), and IsPointInsideAABox2D().
IsPointInsidePolygon2D()
bool Antipatrea::IsPointInsidePolygon2D (const double p[2], const int n, const double poly[])
Referenced by CollisionPolygonConvexPolygon2D(), CollisionPolygons2D(), CollisionSegmentPolygon2D(), and IsPointInsideAABox2D().
IsPointInsideCircle2D()
static bool Antipatrea::IsPointInsideCircle2D (const double p[2], const double cx, const double cy, const double r) inline static
IsAABoxInsideAABox2D()
static bool Antipatrea::IsAABoxInsideAABox2D (const double min[2], const double max[2], const double min2[2], const double max2[2]) inline static
References IsPolygonInsideAABox2D(), IsPolygonInsideCircle2D(), IsPolygonInsideConvexPolygon2D(), and IsPolygonInsidePolygon2D().
IsPolygonInsideAABox2D()
bool Antipatrea::IsPolygonInsideAABox2D (const int n, const double poly[], const double min[2], const double max[2])
Referenced by IsAABoxInsideAABox2D().
IsPolygonInsideConvexPolygon2D()
bool Antipatrea::IsPolygonInsideConvexPolygon2D (const int n1, const double poly1[], const int n2, const double poly2[])
Referenced by IsAABoxInsideAABox2D().
IsPolygonInsidePolygon2D()
bool Antipatrea::IsPolygonInsidePolygon2D (const int n1, const double poly1[], const int n2, const double poly2[], const bool checkIntersection = true)
Referenced by IsAABoxInsideAABox2D().
IsPolygonInsideCircle2D()
bool Antipatrea::IsPolygonInsideCircle2D (const int n, const double poly[], const double cx, const double cy, const double r)
Referenced by IsAABoxInsideAABox2D().
CollisionSegmentConvexPolygon2D()
static bool Antipatrea::CollisionSegmentConvexPolygon2D (const double p0[2], const double p1[2], const int n, const double poly[]) inline static
References IntersectSegmentPolygon2D(), and IsPointInsideConvexPolygon2D().
CollisionPolygonConvexPolygon2D()
static bool Antipatrea::CollisionPolygonConvexPolygon2D (const int n1, const double poly1[], const int n2, const double poly2[]) inline static
References IntersectPolygons2D(), IsPointInsideConvexPolygon2D(), and IsPointInsidePolygon2D().
CollisionConvexPolygons2D()
static bool Antipatrea::CollisionConvexPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[]) inline static
References IntersectPolygons2D(), and IsPointInsideConvexPolygon2D().
CollisionSegmentPolygon2D()
static bool Antipatrea::CollisionSegmentPolygon2D (const double p0[2], const double p1[2], const int n, const double poly[]) inline static
References IntersectSegmentPolygon2D(), and IsPointInsidePolygon2D().
CollisionPolygons2D()
static bool Antipatrea::CollisionPolygons2D (const int n1, const double poly1[], const int n2, const double poly2[]) inline static
References IntersectPolygons2D(), and IsPointInsidePolygon2D().
CollisionAABoxes2D()
static bool Antipatrea::CollisionAABoxes2D (const double min1[2], const double max1[2], const double min2[2], const double max2[2]) inline static
References BoundingBoxPolygon2D(), and SignedAreaPolygon2D().
SignedAreaPolygon2D()
double Antipatrea::SignedAreaPolygon2D (const int n, const double poly[])
Referenced by CollisionAABoxes2D(), and IsPolygonCCW2D().
BoundingBoxPolygon2D()
void Antipatrea::BoundingBoxPolygon2D (const int n, const double poly[], double min[2], double max[2])
Referenced by CollisionAABoxes2D().
BoundingBoxCircle2D()
static void Antipatrea::BoundingBoxCircle2D (const double center[2], const double r, double min[2], double max[2]) inline static
References ChangeOrientationPolygon2D(), and IsConvexPolygonCCW2D().
ChangeOrientationPolygon2D()
void Antipatrea::ChangeOrientationPolygon2D (const int n, double poly[])
Referenced by BoundingBoxCircle2D(), MakeConvexPolygonCCW2D(), and MakePolygonCCW2D().
IsConvexPolygonCCW2D()
bool Antipatrea::IsConvexPolygonCCW2D (const int n, const double poly[])
Referenced by BoundingBoxCircle2D(), and MakeConvexPolygonCCW2D().
IsPolygonCCW2D()
static bool Antipatrea::IsPolygonCCW2D (const int n, const double poly[]) inline static
References SignedAreaPolygon2D().
Referenced by MakePolygonCCW2D().
MakeConvexPolygonCCW2D()
static void Antipatrea::MakeConvexPolygonCCW2D (const int n, double poly[]) inline static
References ChangeOrientationPolygon2D(), and IsConvexPolygonCCW2D().
MakePolygonCCW2D()
static void Antipatrea::MakePolygonCCW2D (const int n, double poly[]) inline static
References ApplyTransRotToPolygon2D(), ChangeOrientationPolygon2D(), IsPolygonCCW2D(), IsPolygonConvex2D(), PolygonCentroid2D(), SampleRandomPointInsideAABox2D(), SampleRandomPointInsideCircle2D(), SampleRandomPointInsideConvexPolygon2D(), SampleRandomPointInsidePolygon2D(), SampleRandomPointInsideTriangle2D(), and TriangulateConvexPolygon2D().
IsPolygonConvex2D()
bool Antipatrea::IsPolygonConvex2D (const int n, const double poly[])
Referenced by MakePolygonCCW2D().
PolygonCentroid2D()
void Antipatrea::PolygonCentroid2D (const int n, const double poly[], double centroid[2])
Referenced by MakePolygonCCW2D().
TriangulateConvexPolygon2D()
int Antipatrea::TriangulateConvexPolygon2D (const int n, const double poly[], int triangles[])
Referenced by MakePolygonCCW2D().
SampleRandomPointInsideAABox2D()
void Antipatrea::SampleRandomPointInsideAABox2D (const double min[2], const double max[2], double p[2])
Referenced by MakePolygonCCW2D().
SampleRandomPointInsideTriangle2D()
void Antipatrea::SampleRandomPointInsideTriangle2D (const double tA[2], const double tB[2], const double tC[2], double p[2])
Referenced by MakePolygonCCW2D().
SampleRandomPointInsideConvexPolygon2D()
void Antipatrea::SampleRandomPointInsideConvexPolygon2D (const int n, const double poly[], double p[2], const double min[2] = NULL, const double max[2] = NULL)
Referenced by MakePolygonCCW2D().
SampleRandomPointInsidePolygon2D()
void Antipatrea::SampleRandomPointInsidePolygon2D (const int n, const double poly[], double p[2], const double min[2] = NULL, const double max[2] = NULL)
Referenced by MakePolygonCCW2D().
SampleRandomPointInsideCircle2D()
void Antipatrea::SampleRandomPointInsideCircle2D (const double center[2], const double r, double p[2])
Referenced by MakePolygonCCW2D().
ApplyTransRotToPolygon2D()
void Antipatrea::ApplyTransRotToPolygon2D (const double TR[], const int n, const double origPoly[], double newPoly[])
Referenced by MakePolygonCCW2D().
StringHash()
size_t Antipatrea::StringHash (const char * s, const int n)
Referenced by Antipatrea::HashStruct< const std::string >::operator()(), Antipatrea::HashStruct< std::string >::operator()(), Antipatrea::HashStruct< char * >::operator()(), Antipatrea::HashStruct< const char * >::operator()(), Antipatrea::HashStruct< char >::operator()(), Antipatrea::HashStruct< unsigned char >::operator()(), Antipatrea::HashStruct< signed char >::operator()(), Antipatrea::HashStruct< short >::operator()(), Antipatrea::HashStruct< unsigned short >::operator()(), Antipatrea::HashStruct< int >::operator()(), Antipatrea::HashStruct< unsigned int >::operator()(), Antipatrea::HashStruct< long >::operator()(), Antipatrea::HashStruct< unsigned long >::operator()(), and Antipatrea::HashStruct< std::pair< int, int > >::operator()().
ToLower()
static void Antipatrea::ToLower (char s[]) inline static
ToUpper()
static void Antipatrea::ToUpper (char s[]) inline static
StrToDouble()
static double Antipatrea::StrToDouble (const char s[]) inline static
Referenced by Antipatrea::Params::GetValueAsDouble().
StrToInt()
static long int Antipatrea::StrToInt (const char s[]) inline static
Referenced by Antipatrea::Params::GetValueAsInt().
StrToBool()
static bool Antipatrea::StrToBool (const char s[]) inline static
Referenced by Antipatrea::Params::GetValueAsBool().
StrSameContent()
static bool Antipatrea::StrSameContent (const char s1[], const char s2[]) inline static
Referenced by Antipatrea::SetupRosetta::NewCfgEnergyEvaluator(), Antipatrea::SetupRosetta::NewCfgForwardKinematics(), Antipatrea::SetupRosetta::NewCfgImprover(), Antipatrea::SetupRosetta::NewCfgOffspringGenerator(), Antipatrea::SetupRosetta::NewCfgProjector(), and Antipatrea::SetupRosetta::NewCfgSampler().
AllocArray()
template<typename Item > static Item* Antipatrea::AllocArray (const int n) inline static
FreeArray()
template<typename Item > static void Antipatrea::FreeArray (Item a[]) inline static
CopyArray()
template<typename Item > static void Antipatrea::CopyArray (Item dest[], const int n, const Item src[]) inline static
DeleteItems() [1/2]
template<typename Item > static void Antipatrea::DeleteItems (const int n, Item items[]) inline static
DeleteItems() [2/2]
template<typename Item > static void Antipatrea::DeleteItems (std::vector< Item > & items) inline static
FindItem() [1/2]
template<typename Item > static int Antipatrea::FindItem (const int n, const Item items[], const Item & item) inline static
FindItem() [2/2]
template<typename Item > static int Antipatrea::FindItem (const std::vector< Item > & items, const Item & item) inline static
ReverseItems() [1/2]
template<typename Item > static void Antipatrea::ReverseItems (const int n, Item items[]) inline static
ReverseItems() [2/2]
template<typename Item > static void Antipatrea::ReverseItems (std::vector< Item > & items) inline static
PermuteItems() [1/2]
template<typename Item > static void Antipatrea::PermuteItems (const int n, Item items[], const int r) static
Generate a random subset of r out of n elements.
Author
Erion Plaku, Amarda Shehu
Parameters
n number of elements in the array items
items array of elements
r number of elements in the subset
Description:
A subset of r elements out of n elements can be selected uniformly at random by selecting the i-th element, i = 0, 1, ..., r - 1, of the r-subset of p as follows:
generate uniformly at random an index j in the integer interval [i, n - 1]
swap elements p[i] and p[j]
At the end of this procedure, the elements p[0], p[1], ..., p[r - 1] correspond to an ordered r-subset selected uniformly at random from the original n-set p. The elements p[r], ..., p[n - 1] contain the original elements of p that were not selected.
The number of ways of choosing an ordered r-subset out of an n-set p is given by P(r, n) = n! / (n - r)!. For example, for r = 2 there are 4! / (4 - 2)! = 12 ordered r-subsets of p = {0, 1, 2, 3}, namely, {0, 1}, {0, 2}, {0, 3}, {1, 0}, {1, 2}, {1, 3}, {2, 0}, {2, 1}, {2, 3}, {3, 0}, {3, 1}, {3, 2}. The ordered r-subset is said to be selected uniformly at random when it is selected with probability 1 / P(r, n) out of all P(r, n) possible ordered r-subsets of the n-set p. Similarly, the number of ways of choosing an unordered r-subset out of an n-set p is given by C(r, n) = P(r, n) / r! = n! / ((n - r)! r!). For example, for r = 2 there are 4! / ((4 - 2)! 2!) = 6unordered r-subsets of p = {0, 1, 2, 3}, namely, {0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3}. The unordered r-subset is said to be selected uniformly at random when it is selected with probability 1 / C(r, n) out of all C(r, n) possible unordered r-subsets of the n-set p.
Observe that each unordered r-subset corresponds to r! ordered r-subsets obtained by generating all possible permutations of the elements of the unordered r-subset. Hence, the same procedure that selects uniformly at random an ordered r-subset of the n-set p, can be used to select uniformly at random an unordered r-subset of the n-set p. The unordered r-subset of p is selected when one of the r! corresponding ordered r-subsets is selected. Since an ordered r-subset is selected with probability 1 / P(r, n), then an unordered r-subset is selected with probability r! (1/ P(r, n)) = 1 / C(r, n).
Remarks
The values of n and r should satisfy the following constraint:
0 <= r <= n
References RandomUniformInteger().
PermuteItems() [2/2]
template<typename Item > static void Antipatrea::PermuteItems (std::vector< Item > & items, const int r) inline static
Generate a random subset of r elements out of the elements in the vector items.
Author
Erion Plaku, Amarda Shehu
Remarks
It calls PermuteItems<Item>(n, p, r) with p as the memory address of the first element in the vector items and n as the number of elements in the vector items.
NextPermutation()
template<typename Type > static bool Antipatrea::NextPermutation (const int n, Type items[]) inline static
Generate the next permutation in the lexicographic order.
Author
Erion Plaku, Amarda Shehu
Parameters
n number of elements
items array of elements
Returns
true iff items is already the largest permutation in the lexicographic order
Description:
A permutation A is said to be larger than another permutation B iff there exists an integer j such that A[0..j-1] = B[0..j-1] and A[j] > B[j], i.e., it is the same as comparing numbers where the digits of the number form the permutation.
The next permutation of A is defined as the smallest possible permutation B larger than A.
The procedure to generate the next permutation in the lexicographic order is as follows:
Starting from right to left examine the array to find the largest tail that is in descending order. Permutation looks like p[0] < ... < p[i-2] < p[i-1] < p[i] > p[i+1] > p[i+2] >... > p[n-1].
Since we are after the next largest permutation we should keep p[0], p[1],...,p[i-2] unchanged and change p[i-1] to something larger but as small as possible. Thus, we need to find p[k] > p[i-1] among the longest tail which is the smallest possible.
Swap p[k] with p[i-1].
Reverse tail p[i..n-1].
Remarks
Type must support the less-than comparison operator < .
NextCombination()
static bool Antipatrea::NextCombination (const int n, int combo[], const int r) inline static
NextGroupCombination()
static bool Antipatrea::NextGroupCombination (const int n, int vals[], const int max[]) inline static
OutputFormat()
static void Antipatrea::OutputFormat (std::ostream & out) inline static
RandomSeed() [1/2]
void Antipatrea::RandomSeed (const unsigned int s)
Set the seed for the random number generator.
Parameters
s seed value
RandomSeed() [2/2]
unsigned int Antipatrea::RandomSeed (void)
Generate and set the seed for the random number generator.
Returns
A pseudorandom number read from the file /dev/urandom, which is then used to set the seed using srandom
If file /dev/urandom does not exist, then time(NULL) is used to obtain the seed.
RandomUniformReal() [1/2]
static double Antipatrea::RandomUniformReal (void) inline static
Generate a real number uniformly at random from the interval [0, 1]
Referenced by Antipatrea::Algebra2D::AngleSampleUniform(), Antipatrea::CfgAcceptorBasedOnFixedMMC::IsAcceptable(), Antipatrea::CfgAcceptorBasedOnMMC::IsAcceptable(), Antipatrea::Algebra::PointSampleUniform(), RandomUniformBoolean(), RandomUniformInteger(), RandomUniformReal(), Antipatrea::Algebra2D::RotSampleUniform(), Antipatrea::CfgSamplerPoint2D::Sample(), Antipatrea::Selector< Antipatrea::FELTRCell *>::Select(), Antipatrea::Algebra2D::TransSampleUniform(), Antipatrea::Algebra3D::TransSampleUniform(), and Antipatrea::Vector3Algebra::Vector3Random().
RandomUniformReal() [2/2]
static double Antipatrea::RandomUniformReal (const double min, const double max) inline static
Generate a real number uniformly at random from the interval [min, max]
Parameters
min left boundary of the sampling interval
max right boundary of the sampling interval
References RandomUniformReal().
RandomUniformInteger()
static long Antipatrea::RandomUniformInteger (const long min, const long max) inline static
Generate an integer number uniformly at random from the interval [min, max]
Parameters
min left boundary of the sampling interval
max right boundary of the sampling interval
References RandomUniformReal().
Referenced by Antipatrea::ProximityGNAT< int, Antipatrea::SamplingBasedPlanner * >::KCenters(), PermuteItems(), Antipatrea::PGT::Cell::SelectVertex(), and Antipatrea::TreeSamplingBasedPlanner::SelectVertex().
RandomUniformBoolean()
static bool Antipatrea::RandomUniformBoolean (void) inline static
Generate either true or false uniformly at random.
References RandomGaussianReal(), RandomPointInsideEllipsoid(), RandomPointInsideSphere(), RandomPointOnEllipsoidSurface(), RandomPointOnSphereSurface(), and RandomUniformReal().
Referenced by Antipatrea::Algebra2D::RotSampleUniform().
RandomGaussianReal()
double Antipatrea::RandomGaussianReal (const double mean, const double stddev)
Generate a number at random from the Gaussian distribution with mean mean and standard deviation stddev
Parameters
mean mean of the Gaussian distribution.
stddev standard deviation of the Gaussian distribution.
Description:
Given , with , the normal or Gaussian probability distribution function is defined by
When and , the distribution is usually called the standard normal distribution.
The fundamental transformation law of probabilities allows for the design of a transformation function that takes as input random variables from one distribution and outputs random variables from another distribution. An important example of such transformation is the Box-Muller method for generating random samples with a Gaussian (normal) distribution using samples from a uniform distribution.
The transformation of two uniform samples x1, x2 in (0, 1) into two samples y1, y2 from a Gaussian (normal) distribution with mean 0 and standard deviation 1 is defined as
The computation can be simplified by using the polar form of the Box-Muller transform. Instead of picking x1 and x2 uniformly inside the unit square, v1 and v2 are picked as the ordinate and abscissa of a random point inside the unit circle around the origin. Then, R = v1 * v1 + v2 * v2 is a uniform sample and can be used instead of x1. Furthermore, the random angle 2PI * x2 can be replaced by the angle that the point (v1, v2) defines w.r.t. the v1 axis. In this way, the expensive calls to cos and sin can be written as v1 / sqrt(R) and v2 / sqrt(R).
A sample y from a Gaussian (normal) distribution with mean 0 and standard deviation 1 is transformed into a sample z from a Gaussian (normal) distribution with mean mean and standard deviation stddev as follows: z = y * stddev + mean
References:
Chapter 7 of Numerical Recipes in C.
G. E. P Box and M. E. Muller. ''A note on the generation of random normal deviates'', in Annals Math. Stat, V. 29, pp. 610-611, 1958.
Referenced by RandomUniformBoolean().
RandomPointOnSphereSurface()
void Antipatrea::RandomPointOnSphereSurface (const int nrDims, const double center[], const double r, double p[])
Referenced by RandomUniformBoolean().
RandomPointInsideSphere()
void Antipatrea::RandomPointInsideSphere (const int nrDims, const double center[], const double r, double p[])
Referenced by RandomUniformBoolean().
RandomPointOnEllipsoidSurface()
void Antipatrea::RandomPointOnEllipsoidSurface (const int nrDims, const double center[], const double radii[], double p[])
Referenced by RandomUniformBoolean().
RandomPointInsideEllipsoid()
void Antipatrea::RandomPointInsideEllipsoid (const int nrDims, const double center[], const double radii[], double p[])
Referenced by RandomUniformBoolean().
Variable Documentation
CA_CA_IDEAL_D
const double Antipatrea::CA_CA_IDEAL_D =3.8
DELTAR_PROJDIM
const int Antipatrea::DELTAR_PROJDIM = 1
Compute DeltaR distance.
Author
Kevin Molloy, Erion Plaku, Amarda Shehu
undefPoint
const point Antipatrea::undefPoint(UNDEF_COORD, UNDEF_COORD, UNDEF_COORD)
Referenced by Antipatrea::USRFactory::GetPointAtIndex().