Antipatrea::Algebra2D Namespace Reference
Antipatrea::Algebra2D Namespace Reference
Enumerations
enum {
Trans_NR_ENTRIES = 2,
Angle_NR_ENTRIES = 1,
Rot_NR_ENTRIES = 2,
TransAngle_NR_ENTRIES = 3,
TransRot_NR_ENTRIES = 4,
Rot_COS = 0,
Rot_SIN = 1
}
Functions
static double VecDotProduct (const double v1[], const double v2[])
static double VecCrossProduct (const double v1[], const double v2[])
static double PointDistanceSquared (const double p1[], const double p2[])
static double PointDistance (const double p1[], const double p2[])
static double VecNormSquared (const double v[])
static double VecNorm (const double v[])
static void VecUnit (const double v[], double vunit[])
static void VecScale (const double v[], const double s, double vscaled[])
static void VecClampMagnitude (double v[], const double dmax)
static void VecAdd (const double v1[], const double v2[], double v[])
static void VecSubtract (const double v1[], const double v2[], double v[])
static void VecLinearInterpolation (const double v1[], const double t1, const double v2[], const double t2, double v[])
static bool VecFromToCCW (const double v1[], const double v2[])
static double VecFromToAngleCCW (const double v1[], const double v2[])
static double VecFromToAngleCCW (const double v1[], const double v2[], const double d)
static double VecFromToAngleCCWUnitArgs (const double v1[], const double v2[])
static double VecAngle (const double v1[], const double v2[])
static double VecAngleUnitArgs (const double v1[], const double v2[])
static void VecNormal (const double v[], double vnormal[])
static void VecParallelProjection (const double v[], const double u[], double v_on_u[])
static void VecParallelProjectionUnitArgs (const double v[], const double u[], double v_on_u[])
static void VecOrthogonalProjection (const double v[], const double u[], double v_on_u[])
static void VecOrthogonalProjectionUnitArgs (const double v[], const double u[], double v_on_u[])
static bool VecAreNormal (const double v1[], const double v2[])
static bool VecAreParallelOrAntiParallel (const double v1[], const double v2[])
static bool VecAreParallel (const double v1[], const double v2[])
static bool VecAreAntiParallel (const double v1[], const double v2[])
static int VecAlignment (const double v1[], const double v2[])
static bool VecAreParallelUnitArgs (const double v1[], const double v2[])
static bool VecAreAntiParallelUnitArgs (const double v1[], const double v2[])
static bool VecAreParallelOrAntiParallelUnitArgs (const double v1[], const double v2[])
static int VecAlignmentUnitArgs (const double v1[], const double v2[])
static double DegreesToRadians (const double theta)
static double RadiansToDegrees (const double theta)
static double AngleNormalize (const double theta, const double low)
static double AngleDistance (const double theta1, const double theta2)
static double AngleSignedDistance (const double theta1, const double theta2)
static double AngleInterpolation (const double theta1, const double theta2, const double t)
static bool AngleIsInside (const double theta, const double mintheta, const double range)
static double AngleClamp (const double theta, const double mintheta, const double range)
static void IdentityAsTrans (double T[])
static double IdentityAsAngle (void)
static void IdentityAsRot (double R[])
static double IdentityAsTransAngle (double T[])
static void IdentityAsTransRot (double TR[])
static bool IdentitySameAsTrans (const double T[])
static bool IdentitySameAsAngle (const double A)
static bool IdentitySameAsRot (const double R[])
static bool IdentitySameAsTransAngle (const double T[], const double A)
static bool IdentitySameAsTransRot (const double T[], const double R[])
static void TransAsTrans (const double T[], double Tresult[])
static double AngleAsAngle (const double A)
static void AngleAsRot (const double A, double R[])
static double RotAsAngle (const double R[])
static void RotAsRot (const double R[], double Rresult[])
static void TransAngleAsTransAngle (const double TA[], double TAresult[])
static void TransAngleAsTransRot (const double TA[], double TR[])
static void TransRotAsTransAngle (const double TR[], double TA[])
static void TransRotAsTransRot (const double TR[], double TRresult[])
static bool TransSameAsTrans (const double Ta[], const double Tb[])
static bool AngleSameAsAngle (const double Aa, const double Ab)
static bool AngleSameAsRot (const double A, const double R[])
static bool RotSameAsAngle (const double R[], const double A)
static bool RotSameAsRot (const double Ra[], const double Rb[])
static bool TransAngleSameAsTransAngle (const double TAa[], const double TAb[])
static bool TransAngleSameAsTransRot (const double TA[], const double TR[])
static bool TransRotSameAsTransAngle (const double TR[], const double TA[])
static bool TransRotSameAsTransRot (const double TRa[], const double TRb[])
static void TransMultPoint (const double T[], const double p[], double pnew[])
static void TransMultInvPoint (const double T[], const double p[], double pnew[])
static void InvTransMultPoint (const double T[], const double p[], double pnew[])
static void InvTransMultInvPoint (const double T[], const double p[], double pnew[])
static void AngleMultPoint (const double A, const double p[], double pnew[])
static void AngleMultInvPoint (const double A, const double p[], double pnew[])
static void InvAngleMultPoint (const double A, const double p[], double pnew[])
static void InvAngleMultInvPoint (const double A, const double p[], double pnew[])
static void RotMultPoint (const double R[], const double p[], double pnew[])
static void RotMultInvPoint (const double R[], const double p[], double pnew[])
static void InvRotMultPoint (const double R[], const double p[], double pnew[])
static void InvRotMultInvPoint (const double R[], const double p[], double pnew[])
static void TransAngleMultPoint (const double TA[], const double p[], double pnew[])
static void TransAngleMultInvPoint (const double TA[], const double p[], double pnew[])
static void InvTransAngleMultPoint (const double TA[], const double p[], double pnew[])
static void InvTransAngleMultInvPoint (const double TA[], const double p[], double pnew[])
static void TransRotMultPoint (const double TR[], const double p[], double pnew[])
static void TransRotMultInvPoint (const double TR[], const double p[], double pnew[])
static void InvTransRotMultPoint (const double TR[], const double p[], double pnew[])
static void InvTransRotMultInvPoint (const double TR[], const double p[], double pnew[])
static void InvTransAsTrans (const double T[], double Tresult[])
static double InvAngleAsAngle (const double A)
static void InvAngleAsRot (const double A, double R[])
static double InvRotAsAngle (const double R[])
static void InvRotAsRot (const double R[], double Rresult[])
static void InvTransAngleAsTransAngle (const double TA[], double TAresult[])
static void InvTransAngleAsTransRot (const double TA[], double TR[])
static void InvTransRotAsTransAngle (const double TR[], double TA[])
static void InvTransRotAsTransRot (const double TR[], double TRresult[])
static void TransMultTransAsTrans (const double Ta[], const double Tb[], double T[])
static void TransMultAngleAsTransAngle (const double T[], const double A, double TA[])
static void TransMultAngleAsTransRot (const double T[], const double A, double TR[])
static void TransMultRotAsTransAngle (const double T[], const double R[], double TA[])
static void TransMultRotAsTransRot (const double T[], const double R[], double TR[])
static void TransMultTransAngleAsTransAngle (const double T[], const double TA[], double TAresult[])
static void TransMultTransAngleAsTransRot (const double T[], const double TA[], double TR[])
static void TransMultTransRotAsTransAngle (const double T[], const double TR[], double TA[])
static void TransMultTransRotAsTransRot (const double T[], const double TR[], double TRresult[])
static void AngleMultTransAsTransAngle (const double A, const double T[], double TA[])
static void AngleMultTransAsTransRot (const double A, const double T[], double TR[])
static double AngleMultAngleAsAngle (const double Aa, const double Ab)
static void AngleMultAngleAsRot (const double Aa, const double Ab, double R[])
static double AngleMultRotAsAngle (const double A, const double R[])
static void RotMultRotAsRot (const double Ra[], const double Rb[], double R[])
static void AngleMultRotAsRot (const double A, const double R[], double Rresult[])
static void AngleMultTransAngleAsTransAngle (const double A, const double TA[], double TAresult[])
static void AngleMultTransAngleAsTransRot (const double A, const double TA[], double TR[])
static void AngleMultTransRotAsTransAngle (const double A, const double TR[], double TA[])
static void AngleMultTransRotAsTransRot (const double A, const double TR[], double TRresult[])
static void RotMultTransAsTransAngle (const double R[], const double T[], double TA[])
static void RotMultTransAsTransRot (const double R[], const double T[], double TR[])
static double RotMultAngleAsAngle (const double R[], const double A)
static void RotMultAngleAsRot (const double R[], const double A, double Rresult[])
static double RotMultRotAsAngle (const double Ra[], const double Rb[])
static void RotMultTransAngleAsTransAngle (const double R[], const double TA[], double TAresult[])
static void RotMultTransAngleAsTransRot (const double R[], const double TA[], double TRresult[])
static void RotMultTransRotAsTransAngle (const double R[], const double TR[], double TA[])
static void RotMultTransRotAsTransRot (const double R[], const double TR[], double TRresult[])
static void TransAngleMultTransAsTransAngle (const double TA[], const double T[], double TAresult[])
static void TransAngleMultTransAsTransRot (const double TA[], const double T[], double TR[])
static void TransAngleMultAngleAsTransAngle (const double TA[], const double A, double TAresult[])
static void TransAngleMultAngleAsTransRot (const double TA[], const double A, double TR[])
static void TransAngleMultRotAsTransAngle (const double TA[], const double R[], double TAresult[])
static void TransAngleMultRotAsTransRot (const double TA[], const double R[], double TR[])
static void TransAngleMultTransAngleAsTransAngle (const double TAa[], const double TAb[], double TA[])
static void TransAngleMultTransAngleAsTransRot (const double TAa[], const double TAb[], double TR[])
static void TransAngleMultTransRotAsTransAngle (const double TA[], const double TR[], double TAresult[])
static void TransAngleMultTransRotAsTransRot (const double TA[], const double TR[], double TRresult[])
static void TransRotMultTransAsTransAngle (const double TR[], const double T[], double TAresult[])
static void TransRotMultTransAsTransRot (const double TR[], const double T[], double TRresult[])
static void TransRotMultAngleAsTransAngle (const double TR[], const double A, double TAresult[])
static void TransRotMultAngleAsTransRot (const double TR[], const double A, double TRresult[])
static void TransRotMultRotAsTransAngle (const double TR[], const double R[], double TAresult[])
static void TransRotMultRotAsTransRot (const double TR[], const double R[], double TRresult[])
static void TransRotMultTransAngleAsTransAngle (const double TR[], const double TA[], double TAresult[])
static void TransRotMultTransAngleAsTransRot (const double TR[], const double TA[], double TRresult[])
static void TransRotMultTransRotAsTransAngle (const double TRa[], const double TRb[], double TA[])
static void TransRotMultTransRotAsTransRot (const double TRa[], const double TRb[], double TR[])
static void TransSampleUniform (double T[])
static void TransSampleUniform (double T[], const double bbox[])
static double AngleSampleUniform (void)
static double AngleSampleUniform (const double bbox[])
static void RotSampleUniform (double R[])
static void RotSampleUniform (double R[], const double bbox[])
static void TransAngleSampleUniform (double TA[])
static void TransAngleSampleUniform (double TA[], const double bbox[])
static void TransRotSampleUniform (double TR[])
static void TransRotSampleUniform (double TR[], const double bbox[])
static void RotateAroundPointAsTransRot (const double theta, const double p[2], double TR[])
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
Trans_NR_ENTRIES
Angle_NR_ENTRIES
Rot_NR_ENTRIES
TransAngle_NR_ENTRIES
TransRot_NR_ENTRIES
Rot_COS
Rot_SIN
Function Documentation
VecDotProduct()
static double Antipatrea::Algebra2D::VecDotProduct (const double v1[], const double v2[]) inline static
Referenced by VecAlignment(), VecAngle(), VecAngleUnitArgs(), VecAreAntiParallel(), VecAreNormal(), VecAreParallel(), VecFromToAngleCCW(), VecFromToAngleCCWUnitArgs(), VecNormSquared(), VecOrthogonalProjection(), VecOrthogonalProjectionUnitArgs(), VecParallelProjection(), and VecParallelProjectionUnitArgs().
VecCrossProduct()
static double Antipatrea::Algebra2D::VecCrossProduct (const double v1[], const double v2[]) inline static
Referenced by VecAreParallelOrAntiParallel(), VecFromToAngleCCW(), VecFromToAngleCCWUnitArgs(), and VecFromToCCW().
PointDistanceSquared()
static double Antipatrea::Algebra2D::PointDistanceSquared (const double p1[], const double p2[]) inline static
Referenced by PointDistance().
PointDistance()
static double Antipatrea::Algebra2D::PointDistance (const double p1[], const double p2[]) inline static
References PointDistanceSquared().
VecNormSquared()
static double Antipatrea::Algebra2D::VecNormSquared (const double v[]) inline static
References VecDotProduct().
Referenced by VecClampMagnitude(), and VecNorm().
VecNorm()
static double Antipatrea::Algebra2D::VecNorm (const double v[]) inline static
References VecNormSquared().
Referenced by VecAngle(), VecFromToAngleCCW(), VecOrthogonalProjection(), VecParallelProjection(), and VecUnit().
VecUnit()
static void Antipatrea::Algebra2D::VecUnit (const double v[], double vunit[]) inline static
References VecNorm().
VecScale()
static void Antipatrea::Algebra2D::VecScale (const double v[], const double s, double vscaled[]) inline static
Referenced by VecClampMagnitude().
VecClampMagnitude()
static void Antipatrea::Algebra2D::VecClampMagnitude (double v[], const double dmax) inline static
References VecNormSquared(), and VecScale().
VecAdd()
static void Antipatrea::Algebra2D::VecAdd (const double v1[], const double v2[], double v[]) inline static
VecSubtract()
static void Antipatrea::Algebra2D::VecSubtract (const double v1[], const double v2[], double v[]) inline static
VecLinearInterpolation()
static void Antipatrea::Algebra2D::VecLinearInterpolation (const double v1[], const double t1, const double v2[], const double t2, double v[]) inline static
VecFromToCCW()
static bool Antipatrea::Algebra2D::VecFromToCCW (const double v1[], const double v2[]) inline static
References VecCrossProduct().
VecFromToAngleCCW() [1/2]
static double Antipatrea::Algebra2D::VecFromToAngleCCW (const double v1[], const double v2[]) inline static
References VecCrossProduct(), VecDotProduct(), and VecNorm().
VecFromToAngleCCW() [2/2]
static double Antipatrea::Algebra2D::VecFromToAngleCCW (const double v1[], const double v2[], const double d) inline static
References VecCrossProduct(), and VecDotProduct().
VecFromToAngleCCWUnitArgs()
static double Antipatrea::Algebra2D::VecFromToAngleCCWUnitArgs (const double v1[], const double v2[]) inline static
References VecCrossProduct(), and VecDotProduct().
VecAngle()
static double Antipatrea::Algebra2D::VecAngle (const double v1[], const double v2[]) inline static
References VecDotProduct(), and VecNorm().
VecAngleUnitArgs()
static double Antipatrea::Algebra2D::VecAngleUnitArgs (const double v1[], const double v2[]) inline static
References VecDotProduct().
VecNormal()
static void Antipatrea::Algebra2D::VecNormal (const double v[], double vnormal[]) inline static
VecParallelProjection()
static void Antipatrea::Algebra2D::VecParallelProjection (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), and VecNorm().
VecParallelProjectionUnitArgs()
static void Antipatrea::Algebra2D::VecParallelProjectionUnitArgs (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct().
VecOrthogonalProjection()
static void Antipatrea::Algebra2D::VecOrthogonalProjection (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct(), and VecNorm().
VecOrthogonalProjectionUnitArgs()
static void Antipatrea::Algebra2D::VecOrthogonalProjectionUnitArgs (const double v[], const double u[], double v_on_u[]) inline static
References VecDotProduct().
VecAreNormal()
static bool Antipatrea::Algebra2D::VecAreNormal (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecDotProduct().
VecAreParallelOrAntiParallel()
static bool Antipatrea::Algebra2D::VecAreParallelOrAntiParallel (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON, and VecCrossProduct().
Referenced by VecAlignment(), VecAreAntiParallel(), and VecAreParallel().
VecAreParallel()
static bool Antipatrea::Algebra2D::VecAreParallel (const double v1[], const double v2[]) inline static
References VecAreParallelOrAntiParallel(), and VecDotProduct().
VecAreAntiParallel()
static bool Antipatrea::Algebra2D::VecAreAntiParallel (const double v1[], const double v2[]) inline static
References VecAreParallelOrAntiParallel(), and VecDotProduct().
VecAlignment()
static int Antipatrea::Algebra2D::VecAlignment (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::ANTI_PARALLEL, Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL, Antipatrea::Constants::PARALLEL, VecAreParallelOrAntiParallel(), and VecDotProduct().
VecAreParallelUnitArgs()
static bool Antipatrea::Algebra2D::VecAreParallelUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by VecAlignmentUnitArgs(), and VecAreParallelOrAntiParallelUnitArgs().
VecAreAntiParallelUnitArgs()
static bool Antipatrea::Algebra2D::VecAreAntiParallelUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by VecAlignmentUnitArgs(), and VecAreParallelOrAntiParallelUnitArgs().
VecAreParallelOrAntiParallelUnitArgs()
static bool Antipatrea::Algebra2D::VecAreParallelOrAntiParallelUnitArgs (const double v1[], const double v2[]) inline static
References VecAreAntiParallelUnitArgs(), and VecAreParallelUnitArgs().
VecAlignmentUnitArgs()
static int Antipatrea::Algebra2D::VecAlignmentUnitArgs (const double v1[], const double v2[]) inline static
References Antipatrea::Constants::ANTI_PARALLEL, Antipatrea::Constants::NEITHER_PARALLEL_NOR_ANTI_PARALLEL, Antipatrea::Constants::PARALLEL, VecAreAntiParallelUnitArgs(), and VecAreParallelUnitArgs().
DegreesToRadians()
static double Antipatrea::Algebra2D::DegreesToRadians (const double theta) inline static
RadiansToDegrees()
static double Antipatrea::Algebra2D::RadiansToDegrees (const double theta) inline static
AngleNormalize()
static double Antipatrea::Algebra2D::AngleNormalize (const double theta, const double low) inline static
Referenced by AngleDistance(), AngleIsInside(), AngleSameAsAngle(), AngleSignedDistance(), and IdentitySameAsAngle().
AngleDistance()
static double Antipatrea::Algebra2D::AngleDistance (const double theta1, const double theta2) inline static
References AngleNormalize().
Referenced by AngleClamp().
AngleSignedDistance()
static double Antipatrea::Algebra2D::AngleSignedDistance (const double theta1, const double theta2) inline static
References AngleNormalize().
Referenced by AngleInterpolation(), and Antipatrea::SignedDistanceBetweenTwoAngles::SignedDistance().
AngleInterpolation()
static double Antipatrea::Algebra2D::AngleInterpolation (const double theta1, const double theta2, const double t) inline static
References AngleSignedDistance().
AngleIsInside()
static bool Antipatrea::Algebra2D::AngleIsInside (const double theta, const double mintheta, const double range) inline static
References AngleNormalize().
Referenced by AngleClamp().
AngleClamp()
static double Antipatrea::Algebra2D::AngleClamp (const double theta, const double mintheta, const double range) inline static
References AngleDistance(), and AngleIsInside().
IdentityAsTrans()
static void Antipatrea::Algebra2D::IdentityAsTrans (double T[]) inline static
Referenced by IdentityAsTransAngle(), and IdentityAsTransRot().
IdentityAsAngle()
static double Antipatrea::Algebra2D::IdentityAsAngle (void) inline static
Referenced by IdentityAsTransAngle().
IdentityAsRot()
static void Antipatrea::Algebra2D::IdentityAsRot (double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by IdentityAsTransRot().
IdentityAsTransAngle()
static double Antipatrea::Algebra2D::IdentityAsTransAngle (double T[]) inline static
References IdentityAsAngle(), and IdentityAsTrans().
IdentityAsTransRot()
static void Antipatrea::Algebra2D::IdentityAsTransRot (double TR[]) inline static
References IdentityAsRot(), IdentityAsTrans(), and Trans_NR_ENTRIES.
IdentitySameAsTrans()
static bool Antipatrea::Algebra2D::IdentitySameAsTrans (const double T[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by IdentitySameAsTransAngle(), and IdentitySameAsTransRot().
IdentitySameAsAngle()
static bool Antipatrea::Algebra2D::IdentitySameAsAngle (const double A) inline static
References AngleNormalize(), and Antipatrea::Constants::EPSILON.
Referenced by IdentitySameAsTransAngle().
IdentitySameAsRot()
static bool Antipatrea::Algebra2D::IdentitySameAsRot (const double R[]) inline static
References Antipatrea::Constants::EPSILON, Rot_COS, and Rot_SIN.
Referenced by IdentitySameAsTransRot().
IdentitySameAsTransAngle()
static bool Antipatrea::Algebra2D::IdentitySameAsTransAngle (const double T[], const double A) inline static
References IdentitySameAsAngle(), and IdentitySameAsTrans().
IdentitySameAsTransRot()
static bool Antipatrea::Algebra2D::IdentitySameAsTransRot (const double T[], const double R[]) inline static
References IdentitySameAsRot(), and IdentitySameAsTrans().
TransAsTrans()
static void Antipatrea::Algebra2D::TransAsTrans (const double T[], double Tresult[]) inline static
Referenced by TransAngleAsTransRot(), TransAngleMultAngleAsTransAngle(), TransAngleMultAngleAsTransRot(), TransAngleMultRotAsTransAngle(), TransAngleMultRotAsTransRot(), TransAngleMultTransAngleAsTransAngle(), TransAngleMultTransAngleAsTransRot(), TransAngleMultTransRotAsTransAngle(), TransAngleMultTransRotAsTransRot(), TransMultAngleAsTransAngle(), TransMultAngleAsTransRot(), TransMultRotAsTransAngle(), TransMultRotAsTransRot(), TransRotAsTransAngle(), TransRotMultAngleAsTransAngle(), TransRotMultAngleAsTransRot(), TransRotMultRotAsTransAngle(), TransRotMultRotAsTransRot(), TransRotMultTransAngleAsTransAngle(), TransRotMultTransAngleAsTransRot(), TransRotMultTransRotAsTransAngle(), and TransRotMultTransRotAsTransRot().
AngleAsAngle()
static double Antipatrea::Algebra2D::AngleAsAngle (const double A) inline static
Referenced by AngleMultTransAsTransAngle(), TransAngleMultTransAsTransAngle(), TransMultAngleAsTransAngle(), and TransMultTransAngleAsTransAngle().
AngleAsRot()
static void Antipatrea::Algebra2D::AngleAsRot (const double A, double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by AngleMultRotAsRot(), AngleMultTransAsTransRot(), AngleMultTransRotAsTransRot(), RotateAroundPointAsTransRot(), RotMultAngleAsRot(), TransAngleAsTransRot(), TransAngleMultTransAsTransRot(), TransMultAngleAsTransRot(), and TransMultTransAngleAsTransRot().
RotAsAngle()
static double Antipatrea::Algebra2D::RotAsAngle (const double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by AngleMultRotAsAngle(), RotMultAngleAsAngle(), RotMultRotAsAngle(), RotMultTransAsTransAngle(), TransMultRotAsTransAngle(), TransMultTransRotAsTransAngle(), TransRotAsTransAngle(), and TransRotMultTransAsTransAngle().
RotAsRot()
static void Antipatrea::Algebra2D::RotAsRot (const double R[], double Rresult[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by RotMultTransAsTransRot(), TransMultRotAsTransRot(), TransMultTransRotAsTransRot(), and TransRotMultTransAsTransRot().
TransAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransAngleAsTransAngle (const double TA[], double TAresult[]) inline static
TransAngleAsTransRot()
static void Antipatrea::Algebra2D::TransAngleAsTransRot (const double TA[], double TR[]) inline static
References AngleAsRot(), and TransAsTrans().
TransRotAsTransAngle()
static void Antipatrea::Algebra2D::TransRotAsTransAngle (const double TR[], double TA[]) inline static
References RotAsAngle(), and TransAsTrans().
TransRotAsTransRot()
static void Antipatrea::Algebra2D::TransRotAsTransRot (const double TR[], double TRresult[]) inline static
References TransRot_NR_ENTRIES.
TransSameAsTrans()
static bool Antipatrea::Algebra2D::TransSameAsTrans (const double Ta[], const double Tb[]) inline static
References Antipatrea::Constants::EPSILON.
Referenced by TransAngleSameAsTransAngle(), TransAngleSameAsTransRot(), and TransRotSameAsTransRot().
AngleSameAsAngle()
static bool Antipatrea::Algebra2D::AngleSameAsAngle (const double Aa, const double Ab) inline static
References AngleNormalize(), and Antipatrea::Constants::EPSILON.
Referenced by TransAngleSameAsTransAngle().
AngleSameAsRot()
static bool Antipatrea::Algebra2D::AngleSameAsRot (const double A, const double R[]) inline static
References Antipatrea::Constants::EPSILON, Rot_COS, and Rot_SIN.
Referenced by RotSameAsAngle(), and TransAngleSameAsTransRot().
RotSameAsAngle()
static bool Antipatrea::Algebra2D::RotSameAsAngle (const double R[], const double A) inline static
References AngleSameAsRot().
RotSameAsRot()
static bool Antipatrea::Algebra2D::RotSameAsRot (const double Ra[], const double Rb[]) inline static
References Antipatrea::Constants::EPSILON, Rot_COS, and Rot_SIN.
Referenced by TransRotSameAsTransRot().
TransAngleSameAsTransAngle()
static bool Antipatrea::Algebra2D::TransAngleSameAsTransAngle (const double TAa[], const double TAb[]) inline static
References AngleSameAsAngle(), and TransSameAsTrans().
TransAngleSameAsTransRot()
static bool Antipatrea::Algebra2D::TransAngleSameAsTransRot (const double TA[], const double TR[]) inline static
References AngleSameAsRot(), and TransSameAsTrans().
Referenced by TransRotSameAsTransAngle().
TransRotSameAsTransAngle()
static bool Antipatrea::Algebra2D::TransRotSameAsTransAngle (const double TR[], const double TA[]) inline static
References TransAngleSameAsTransRot().
TransRotSameAsTransRot()
static bool Antipatrea::Algebra2D::TransRotSameAsTransRot (const double TRa[], const double TRb[]) inline static
References RotSameAsRot(), and TransSameAsTrans().
TransMultPoint()
static void Antipatrea::Algebra2D::TransMultPoint (const double T[], const double p[], double pnew[]) inline static
Referenced by TransAngleMultInvPoint(), TransAngleMultPoint(), TransRotMultInvPoint(), and TransRotMultPoint().
TransMultInvPoint()
static void Antipatrea::Algebra2D::TransMultInvPoint (const double T[], const double p[], double pnew[]) inline static
InvTransMultPoint()
static void Antipatrea::Algebra2D::InvTransMultPoint (const double T[], const double p[], double pnew[]) inline static
Referenced by InvTransAngleMultPoint(), and InvTransRotMultPoint().
InvTransMultInvPoint()
static void Antipatrea::Algebra2D::InvTransMultInvPoint (const double T[], const double p[], double pnew[]) inline static
Referenced by InvTransAngleMultInvPoint(), and InvTransRotMultInvPoint().
AngleMultPoint()
static void Antipatrea::Algebra2D::AngleMultPoint (const double A, const double p[], double pnew[]) inline static
Referenced by AngleMultTransAngleAsTransAngle(), AngleMultTransAngleAsTransRot(), AngleMultTransAsTransAngle(), AngleMultTransRotAsTransAngle(), TransAngleMultPoint(), TransAngleMultTransAsTransAngle(), and TransAngleMultTransAsTransRot().
AngleMultInvPoint()
static void Antipatrea::Algebra2D::AngleMultInvPoint (const double A, const double p[], double pnew[]) inline static
Referenced by InvTransAngleAsTransAngle(), and TransAngleMultInvPoint().
InvAngleMultPoint()
static void Antipatrea::Algebra2D::InvAngleMultPoint (const double A, const double p[], double pnew[]) inline static
Referenced by InvTransAngleMultInvPoint(), and InvTransAngleMultPoint().
InvAngleMultInvPoint()
static void Antipatrea::Algebra2D::InvAngleMultInvPoint (const double A, const double p[], double pnew[]) inline static
RotMultPoint()
static void Antipatrea::Algebra2D::RotMultPoint (const double R[], const double p[], double pnew[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by AngleMultTransAsTransRot(), AngleMultTransRotAsTransRot(), RotMultTransAngleAsTransAngle(), RotMultTransAngleAsTransRot(), RotMultTransAsTransAngle(), RotMultTransAsTransRot(), RotMultTransRotAsTransAngle(), RotMultTransRotAsTransRot(), TransRotMultPoint(), TransRotMultTransAsTransAngle(), and TransRotMultTransAsTransRot().
RotMultInvPoint()
static void Antipatrea::Algebra2D::RotMultInvPoint (const double R[], const double p[], double pnew[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by InvTransAngleAsTransRot(), InvTransRotAsTransRot(), and TransRotMultInvPoint().
InvRotMultPoint()
static void Antipatrea::Algebra2D::InvRotMultPoint (const double R[], const double p[], double pnew[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by InvTransRotMultInvPoint(), and InvTransRotMultPoint().
InvRotMultInvPoint()
static void Antipatrea::Algebra2D::InvRotMultInvPoint (const double R[], const double p[], double pnew[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by InvTransRotAsTransAngle().
TransAngleMultPoint()
static void Antipatrea::Algebra2D::TransAngleMultPoint (const double TA[], const double p[], double pnew[]) inline static
References AngleMultPoint(), and TransMultPoint().
TransAngleMultInvPoint()
static void Antipatrea::Algebra2D::TransAngleMultInvPoint (const double TA[], const double p[], double pnew[]) inline static
References AngleMultInvPoint(), and TransMultPoint().
InvTransAngleMultPoint()
static void Antipatrea::Algebra2D::InvTransAngleMultPoint (const double TA[], const double p[], double pnew[]) inline static
References InvAngleMultPoint(), and InvTransMultPoint().
InvTransAngleMultInvPoint()
static void Antipatrea::Algebra2D::InvTransAngleMultInvPoint (const double TA[], const double p[], double pnew[]) inline static
References InvAngleMultPoint(), and InvTransMultInvPoint().
TransRotMultPoint()
static void Antipatrea::Algebra2D::TransRotMultPoint (const double TR[], const double p[], double pnew[]) inline static
References RotMultPoint(), and TransMultPoint().
TransRotMultInvPoint()
static void Antipatrea::Algebra2D::TransRotMultInvPoint (const double TR[], const double p[], double pnew[]) inline static
References RotMultInvPoint(), and TransMultPoint().
InvTransRotMultPoint()
static void Antipatrea::Algebra2D::InvTransRotMultPoint (const double TR[], const double p[], double pnew[]) inline static
References InvRotMultPoint(), and InvTransMultPoint().
InvTransRotMultInvPoint()
static void Antipatrea::Algebra2D::InvTransRotMultInvPoint (const double TR[], const double p[], double pnew[]) inline static
References InvRotMultPoint(), and InvTransMultInvPoint().
InvTransAsTrans()
static void Antipatrea::Algebra2D::InvTransAsTrans (const double T[], double Tresult[]) inline static
InvAngleAsAngle()
static double Antipatrea::Algebra2D::InvAngleAsAngle (const double A) inline static
Referenced by InvTransAngleAsTransAngle().
InvAngleAsRot()
static void Antipatrea::Algebra2D::InvAngleAsRot (const double A, double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by InvTransAngleAsTransRot().
InvRotAsAngle()
static double Antipatrea::Algebra2D::InvRotAsAngle (const double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by InvTransRotAsTransAngle().
InvRotAsRot()
static void Antipatrea::Algebra2D::InvRotAsRot (const double R[], double Rresult[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by InvTransRotAsTransRot().
InvTransAngleAsTransAngle()
static void Antipatrea::Algebra2D::InvTransAngleAsTransAngle (const double TA[], double TAresult[]) inline static
References AngleMultInvPoint(), and InvAngleAsAngle().
InvTransAngleAsTransRot()
static void Antipatrea::Algebra2D::InvTransAngleAsTransRot (const double TA[], double TR[]) inline static
References InvAngleAsRot(), and RotMultInvPoint().
InvTransRotAsTransAngle()
static void Antipatrea::Algebra2D::InvTransRotAsTransAngle (const double TR[], double TA[]) inline static
References InvRotAsAngle(), and InvRotMultInvPoint().
InvTransRotAsTransRot()
static void Antipatrea::Algebra2D::InvTransRotAsTransRot (const double TR[], double TRresult[]) inline static
References InvRotAsRot(), and RotMultInvPoint().
TransMultTransAsTrans()
static void Antipatrea::Algebra2D::TransMultTransAsTrans (const double Ta[], const double Tb[], double T[]) inline static
Referenced by TransAngleMultTransAngleAsTransAngle(), TransAngleMultTransAngleAsTransRot(), TransAngleMultTransAsTransAngle(), TransAngleMultTransAsTransRot(), TransAngleMultTransRotAsTransAngle(), TransAngleMultTransRotAsTransRot(), TransMultTransAngleAsTransAngle(), TransMultTransAngleAsTransRot(), TransMultTransRotAsTransAngle(), TransMultTransRotAsTransRot(), TransRotMultTransAngleAsTransAngle(), TransRotMultTransAngleAsTransRot(), TransRotMultTransAsTransAngle(), TransRotMultTransAsTransRot(), TransRotMultTransRotAsTransAngle(), and TransRotMultTransRotAsTransRot().
TransMultAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransMultAngleAsTransAngle (const double T[], const double A, double TA[]) inline static
References AngleAsAngle(), and TransAsTrans().
TransMultAngleAsTransRot()
static void Antipatrea::Algebra2D::TransMultAngleAsTransRot (const double T[], const double A, double TR[]) inline static
References AngleAsRot(), and TransAsTrans().
TransMultRotAsTransAngle()
static void Antipatrea::Algebra2D::TransMultRotAsTransAngle (const double T[], const double R[], double TA[]) inline static
References RotAsAngle(), and TransAsTrans().
TransMultRotAsTransRot()
static void Antipatrea::Algebra2D::TransMultRotAsTransRot (const double T[], const double R[], double TR[]) inline static
References RotAsRot(), and TransAsTrans().
TransMultTransAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransMultTransAngleAsTransAngle (const double T[], const double TA[], double TAresult[]) inline static
References AngleAsAngle(), and TransMultTransAsTrans().
TransMultTransAngleAsTransRot()
static void Antipatrea::Algebra2D::TransMultTransAngleAsTransRot (const double T[], const double TA[], double TR[]) inline static
References AngleAsRot(), and TransMultTransAsTrans().
TransMultTransRotAsTransAngle()
static void Antipatrea::Algebra2D::TransMultTransRotAsTransAngle (const double T[], const double TR[], double TA[]) inline static
References RotAsAngle(), and TransMultTransAsTrans().
TransMultTransRotAsTransRot()
static void Antipatrea::Algebra2D::TransMultTransRotAsTransRot (const double T[], const double TR[], double TRresult[]) inline static
References RotAsRot(), and TransMultTransAsTrans().
AngleMultTransAsTransAngle()
static void Antipatrea::Algebra2D::AngleMultTransAsTransAngle (const double A, const double T[], double TA[]) inline static
References AngleAsAngle(), and AngleMultPoint().
AngleMultTransAsTransRot()
static void Antipatrea::Algebra2D::AngleMultTransAsTransRot (const double A, const double T[], double TR[]) inline static
References AngleAsRot(), and RotMultPoint().
AngleMultAngleAsAngle()
static double Antipatrea::Algebra2D::AngleMultAngleAsAngle (const double Aa, const double Ab) inline static
Referenced by AngleMultTransAngleAsTransAngle(), and TransAngleMultAngleAsTransAngle().
AngleMultAngleAsRot()
static void Antipatrea::Algebra2D::AngleMultAngleAsRot (const double Aa, const double Ab, double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by AngleMultTransAngleAsTransRot(), and TransAngleMultAngleAsTransRot().
AngleMultRotAsAngle()
static double Antipatrea::Algebra2D::AngleMultRotAsAngle (const double A, const double R[]) inline static
References RotAsAngle().
Referenced by AngleMultTransRotAsTransAngle(), and TransAngleMultRotAsTransAngle().
RotMultRotAsRot()
static void Antipatrea::Algebra2D::RotMultRotAsRot (const double Ra[], const double Rb[], double R[]) inline static
References Rot_COS, and Rot_SIN.
Referenced by AngleMultRotAsRot(), AngleMultTransRotAsTransRot(), RotMultAngleAsRot(), RotMultRotAsAngle(), RotMultTransRotAsTransRot(), and TransRotMultRotAsTransRot().
AngleMultRotAsRot()
static void Antipatrea::Algebra2D::AngleMultRotAsRot (const double A, const double R[], double Rresult[]) inline static
References AngleAsRot(), Rot_NR_ENTRIES, and RotMultRotAsRot().
Referenced by TransAngleMultRotAsTransRot().
AngleMultTransAngleAsTransAngle()
static void Antipatrea::Algebra2D::AngleMultTransAngleAsTransAngle (const double A, const double TA[], double TAresult[]) inline static
References AngleMultAngleAsAngle(), and AngleMultPoint().
Referenced by TransAngleMultTransAngleAsTransAngle().
AngleMultTransAngleAsTransRot()
static void Antipatrea::Algebra2D::AngleMultTransAngleAsTransRot (const double A, const double TA[], double TR[]) inline static
References AngleMultAngleAsRot(), and AngleMultPoint().
Referenced by TransAngleMultTransAngleAsTransRot().
AngleMultTransRotAsTransAngle()
static void Antipatrea::Algebra2D::AngleMultTransRotAsTransAngle (const double A, const double TR[], double TA[]) inline static
References AngleMultPoint(), and AngleMultRotAsAngle().
Referenced by TransAngleMultTransRotAsTransAngle().
AngleMultTransRotAsTransRot()
static void Antipatrea::Algebra2D::AngleMultTransRotAsTransRot (const double A, const double TR[], double TRresult[]) inline static
References AngleAsRot(), Rot_NR_ENTRIES, RotMultPoint(), and RotMultRotAsRot().
Referenced by TransAngleMultTransRotAsTransRot().
RotMultTransAsTransAngle()
static void Antipatrea::Algebra2D::RotMultTransAsTransAngle (const double R[], const double T[], double TA[]) inline static
References RotAsAngle(), and RotMultPoint().
RotMultTransAsTransRot()
static void Antipatrea::Algebra2D::RotMultTransAsTransRot (const double R[], const double T[], double TR[]) inline static
References RotAsRot(), and RotMultPoint().
RotMultAngleAsAngle()
static double Antipatrea::Algebra2D::RotMultAngleAsAngle (const double R[], const double A) inline static
References RotAsAngle().
Referenced by RotMultTransAngleAsTransAngle(), and TransRotMultAngleAsTransAngle().
RotMultAngleAsRot()
static void Antipatrea::Algebra2D::RotMultAngleAsRot (const double R[], const double A, double Rresult[]) inline static
References AngleAsRot(), Rot_NR_ENTRIES, and RotMultRotAsRot().
Referenced by RotMultTransAngleAsTransRot(), and TransRotMultAngleAsTransRot().
RotMultRotAsAngle()
static double Antipatrea::Algebra2D::RotMultRotAsAngle (const double Ra[], const double Rb[]) inline static
References Rot_NR_ENTRIES, RotAsAngle(), and RotMultRotAsRot().
Referenced by RotMultTransRotAsTransAngle(), and TransRotMultRotAsTransAngle().
RotMultTransAngleAsTransAngle()
static void Antipatrea::Algebra2D::RotMultTransAngleAsTransAngle (const double R[], const double TA[], double TAresult[]) inline static
References RotMultAngleAsAngle(), and RotMultPoint().
Referenced by TransRotMultTransAngleAsTransAngle().
RotMultTransAngleAsTransRot()
static void Antipatrea::Algebra2D::RotMultTransAngleAsTransRot (const double R[], const double TA[], double TRresult[]) inline static
References RotMultAngleAsRot(), and RotMultPoint().
Referenced by TransRotMultTransAngleAsTransRot().
RotMultTransRotAsTransAngle()
static void Antipatrea::Algebra2D::RotMultTransRotAsTransAngle (const double R[], const double TR[], double TA[]) inline static
References RotMultPoint(), and RotMultRotAsAngle().
Referenced by TransRotMultTransRotAsTransAngle().
RotMultTransRotAsTransRot()
static void Antipatrea::Algebra2D::RotMultTransRotAsTransRot (const double R[], const double TR[], double TRresult[]) inline static
References RotMultPoint(), and RotMultRotAsRot().
Referenced by TransRotMultTransRotAsTransRot().
TransAngleMultTransAsTransAngle()
static void Antipatrea::Algebra2D::TransAngleMultTransAsTransAngle (const double TA[], const double T[], double TAresult[]) inline static
References AngleAsAngle(), AngleMultPoint(), and TransMultTransAsTrans().
TransAngleMultTransAsTransRot()
static void Antipatrea::Algebra2D::TransAngleMultTransAsTransRot (const double TA[], const double T[], double TR[]) inline static
References AngleAsRot(), AngleMultPoint(), and TransMultTransAsTrans().
TransAngleMultAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransAngleMultAngleAsTransAngle (const double TA[], const double A, double TAresult[]) inline static
References AngleMultAngleAsAngle(), and TransAsTrans().
TransAngleMultAngleAsTransRot()
static void Antipatrea::Algebra2D::TransAngleMultAngleAsTransRot (const double TA[], const double A, double TR[]) inline static
References AngleMultAngleAsRot(), and TransAsTrans().
TransAngleMultRotAsTransAngle()
static void Antipatrea::Algebra2D::TransAngleMultRotAsTransAngle (const double TA[], const double R[], double TAresult[]) inline static
References AngleMultRotAsAngle(), and TransAsTrans().
TransAngleMultRotAsTransRot()
static void Antipatrea::Algebra2D::TransAngleMultRotAsTransRot (const double TA[], const double R[], double TR[]) inline static
References AngleMultRotAsRot(), and TransAsTrans().
TransAngleMultTransAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransAngleMultTransAngleAsTransAngle (const double TAa[], const double TAb[], double TA[]) inline static
References AngleMultTransAngleAsTransAngle(), TransAsTrans(), and TransMultTransAsTrans().
TransAngleMultTransAngleAsTransRot()
static void Antipatrea::Algebra2D::TransAngleMultTransAngleAsTransRot (const double TAa[], const double TAb[], double TR[]) inline static
References AngleMultTransAngleAsTransRot(), TransAsTrans(), and TransMultTransAsTrans().
TransAngleMultTransRotAsTransAngle()
static void Antipatrea::Algebra2D::TransAngleMultTransRotAsTransAngle (const double TA[], const double TR[], double TAresult[]) inline static
References AngleMultTransRotAsTransAngle(), TransAsTrans(), and TransMultTransAsTrans().
TransAngleMultTransRotAsTransRot()
static void Antipatrea::Algebra2D::TransAngleMultTransRotAsTransRot (const double TA[], const double TR[], double TRresult[]) inline static
References AngleMultTransRotAsTransRot(), TransAsTrans(), and TransMultTransAsTrans().
TransRotMultTransAsTransAngle()
static void Antipatrea::Algebra2D::TransRotMultTransAsTransAngle (const double TR[], const double T[], double TAresult[]) inline static
References RotAsAngle(), RotMultPoint(), and TransMultTransAsTrans().
TransRotMultTransAsTransRot()
static void Antipatrea::Algebra2D::TransRotMultTransAsTransRot (const double TR[], const double T[], double TRresult[]) inline static
References RotAsRot(), RotMultPoint(), and TransMultTransAsTrans().
TransRotMultAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransRotMultAngleAsTransAngle (const double TR[], const double A, double TAresult[]) inline static
References RotMultAngleAsAngle(), and TransAsTrans().
TransRotMultAngleAsTransRot()
static void Antipatrea::Algebra2D::TransRotMultAngleAsTransRot (const double TR[], const double A, double TRresult[]) inline static
References RotMultAngleAsRot(), and TransAsTrans().
TransRotMultRotAsTransAngle()
static void Antipatrea::Algebra2D::TransRotMultRotAsTransAngle (const double TR[], const double R[], double TAresult[]) inline static
References RotMultRotAsAngle(), and TransAsTrans().
TransRotMultRotAsTransRot()
static void Antipatrea::Algebra2D::TransRotMultRotAsTransRot (const double TR[], const double R[], double TRresult[]) inline static
References RotMultRotAsRot(), and TransAsTrans().
TransRotMultTransAngleAsTransAngle()
static void Antipatrea::Algebra2D::TransRotMultTransAngleAsTransAngle (const double TR[], const double TA[], double TAresult[]) inline static
References RotMultTransAngleAsTransAngle(), TransAsTrans(), and TransMultTransAsTrans().
TransRotMultTransAngleAsTransRot()
static void Antipatrea::Algebra2D::TransRotMultTransAngleAsTransRot (const double TR[], const double TA[], double TRresult[]) inline static
References RotMultTransAngleAsTransRot(), TransAsTrans(), and TransMultTransAsTrans().
TransRotMultTransRotAsTransAngle()
static void Antipatrea::Algebra2D::TransRotMultTransRotAsTransAngle (const double TRa[], const double TRb[], double TA[]) inline static
References RotMultTransRotAsTransAngle(), TransAsTrans(), and TransMultTransAsTrans().
TransRotMultTransRotAsTransRot()
static void Antipatrea::Algebra2D::TransRotMultTransRotAsTransRot (const double TRa[], const double TRb[], double TR[]) inline static
References RotMultTransRotAsTransRot(), TransAsTrans(), and TransMultTransAsTrans().
TransSampleUniform() [1/2]
static void Antipatrea::Algebra2D::TransSampleUniform (double T[]) inline static
References Antipatrea::RandomUniformReal().
Referenced by TransAngleSampleUniform(), and TransRotSampleUniform().
TransSampleUniform() [2/2]
static void Antipatrea::Algebra2D::TransSampleUniform (double T[], const double bbox[]) inline static
References Antipatrea::RandomUniformReal().
AngleSampleUniform() [1/2]
static double Antipatrea::Algebra2D::AngleSampleUniform (void) inline static
References Antipatrea::RandomUniformReal().
Referenced by TransAngleSampleUniform().
AngleSampleUniform() [2/2]
static double Antipatrea::Algebra2D::AngleSampleUniform (const double bbox[]) inline static
References Antipatrea::RandomUniformReal().
RotSampleUniform() [1/2]
static void Antipatrea::Algebra2D::RotSampleUniform (double R[]) inline static
References Antipatrea::RandomUniformBoolean(), Antipatrea::RandomUniformReal(), Rot_COS, and Rot_SIN.
Referenced by TransRotSampleUniform().
RotSampleUniform() [2/2]
static void Antipatrea::Algebra2D::RotSampleUniform (double R[], const double bbox[]) inline static
References Antipatrea::RandomUniformReal(), Rot_COS, and Rot_SIN.
TransAngleSampleUniform() [1/2]
static void Antipatrea::Algebra2D::TransAngleSampleUniform (double TA[]) inline static
References AngleSampleUniform(), and TransSampleUniform().
TransAngleSampleUniform() [2/2]
static void Antipatrea::Algebra2D::TransAngleSampleUniform (double TA[], const double bbox[]) inline static
References AngleSampleUniform(), and TransSampleUniform().
TransRotSampleUniform() [1/2]
static void Antipatrea::Algebra2D::TransRotSampleUniform (double TR[]) inline static
References RotSampleUniform(), and TransSampleUniform().
TransRotSampleUniform() [2/2]
static void Antipatrea::Algebra2D::TransRotSampleUniform (double TR[], const double bbox[]) inline static
References RotSampleUniform(), and TransSampleUniform().
RotateAroundPointAsTransRot()
static void Antipatrea::Algebra2D::RotateAroundPointAsTransRot (const double theta, const double p[2], double TR[]) inline static
References AngleAsRot(), Rot_COS, Rot_SIN, and Trans_NR_ENTRIES.