Antipatrea::HashStruct< unsigned short > Struct Template Reference
Antipatrea::HashStruct< unsigned short > Struct Template Reference
#include <HashFn.hpp>
Public Member Functions
size_t operator() (unsigned short x) const
Member Function Documentation
size_t Antipatrea::HashStruct< unsigned short >::operator() (unsigned short x) const inline
References operator()(), and Antipatrea::StringHash().
Referenced by operator()().
The documentation for this struct was generated from the following file:
HashFn.hpp