Antipatrea::HashStruct< char > Struct Template Reference
Antipatrea::HashStruct< char > Struct Template Reference
#include <HashFn.hpp>
Public Member Functions
size_t operator() (char x) const
Member Function Documentation
operator()()
size_t Antipatrea::HashStruct< char >::operator() (char x) const inline
References operator()(), and Antipatrea::StringHash().
Referenced by operator()().
The documentation for this struct was generated from the following file:
HashFn.hpp